### ISSUE TITLE
hip_throw fails to output runtime_error string

### ISSUE THREAD

**Issue by aaronenyeshi** [ROCm-Developer-Tools/HIP#1008]
Using syntax like: `hip_throw(std::runtime_error{"Metadata parsing failed."});` inside of HIP header files fails to output the correct exception message. 
Using HIP branch roc-2.2.x, the correct exception message is thrown.

**Actual Output:**
```
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
```
**Expected Output:**
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Metadata parsing failed.
```
Steps to reproduce:
- Write `hip_throw(std::runtime_error{"Metadata parsing failed."});` in `HIP/include/hip/hcc_detail/program_state.hpp` function `read_kernarg_metadata`
- Compile and build any test, then run the test

**Comment by fkruggel** [comment]
Hi there,

I found this annoying, too. I changed all occurrences of hip_throw(XX) to throw XX in 
files hip/hcc_detail/*.hpp.

Best, Frithjof

**Comment by SarbojitAMD** [comment]
Latest source has the fix hence closing the issue
