### ISSUE TITLE
Software built on ROCm 2.2 fails to run on ROCm 2.3 

### ISSUE THREAD

**Issue by skeelyamd** [ROCm-Developer-Tools/HIP#1026]
"All failing tests give symbol lookup error: undefined symbol: _ZN8hip_impl14function_namesB5cxx11Eb. It seems that something was removed, which makes 2.2 and 2.3 not binary compatible." - VincentSC

Moved from ROCr bug report.

**Comment by skeelyamd** [comment]
@VincentSC

**Comment by gargrahul** [comment]
Please try with rebuilding application/library/framework on top of 2.3 HIP/HCC.

**Comment by gargrahul** [comment]
There is NO binary compatibility between 2.2 and 2.3. Every HIP application has to be rebuilt after switching to 2.3.
