### ISSUE TITLE
[HIPIFY] Unable to convert cudnnSetFilter4dDescriptor 

### ISSUE THREAD

**Issue by rohanmahapatra** [ROCm-Developer-Tools/HIP#1037]
Hello,

Hipify-clang is unable to convert convolutional_layer.c file(https://github.com/pjreddie/darknet/blob/61c9d02ec461e30d55762ec7669d6a1d3c356fb2/src/convolutional_layer.c#L125)

Could you please help?

Error message:  

tmp/convolutional_layer.c-276d1c.hip:132:5: warning: CUDA identifier is unsupported in HIP.
   cudnnSetFilter4dDescriptor(l->dweightDesc, CUDNN_DATA_FLOAT, CUDNN_TENSOR_NCHW, l->n, l->c/l->groups, l->size, l->size);
   ^
/tmp/convolutional_layer.c-276d1c.hip:133:5: warning: CUDA identifier is unsupported in HIP.
   cudnnSetFilter4dDescriptor(l->weightDesc, CUDNN_DATA_FLOAT, CUDNN_TENSOR_NCHW, l->n, l->c/l->groups, l->size, l->size);
   ^
2 warnings generated when compiling for host.

Thank you,
Rohan

**Comment by emankov** [comment]
`cudnnSetFilter4dDescriptor` and `cudnnGetFilter4dDescriptor` methods are not yet supported by [hipDNN](https://github.com/ROCmSoftwarePlatform/hipDNN).
The above are the warnings, not errors; thus your CUDA source should be hipified despite these warnings; `cudnnSetFilter4dDescriptor` will stay nonhipified in the output HIP file.

Please refer [Supported CUDA APIs](https://github.com/ROCm-Developer-Tools/HIP/tree/master/hipify-clang#-supported-cuda-apis) to check whether particular CUDA method or data type is supported by HIP or not.

I may advise you 2 things here:
1. Try to rewrite the source or an output code based on `(cu)hipdnnSetFilterNdDescriptor`.
2. Open a ticket in [hipDNN](https://github.com/ROCmSoftwarePlatform/hipDNN) for supporting `cudnnSetFilter4dDescriptor` in  it.
