### ISSUE TITLE
Minor bug in header hip_runtime_api.h

### ISSUE THREAD

**Issue by fkruggel** [ROCm-Developer-Tools/HIP#1038]
Hi there,

in file hip/nvcc_detail/hip_runtime_api.h, line 850, the function definition:
inline static hipError_t hipPointerGetAttributes(hipPointerAttribute_t* attributes, void* ptr) 
should be replaced by:
inline static hipError_t hipPointerGetAttributes(hipPointerAttribute_t* attributes, const void* ptr)
to match the documentation and definition in the hcc branch.

Thanks - and keep up the good work, Frithjof

**Comment by gargrahul** [comment]
Thanks. #1039 should fix this.
