### ISSUE TITLE
[Question] Whether dim3(32, 2) work well with wrapSize = 64 for ROCm?

### ISSUE THREAD

**Issue by ghostplant** [ROCm-Developer-Tools/HIP#1041]
I saw the wrapSize of most AMD devices is 64, so if I want to fully utilize the per-block resources, I am supposed to launch a kernel whose number of threads per block should be the integer-time of 64, right?

If so, for this case `kernel<<<.., dim3(32, 2), >>>`, I wonder whether the threads per block are executed by 2 different wraps, or within a same wrap?

**Comment by bensander** [comment]
One warp , size 64

**Comment by ghostplant** [comment]
@bensander Great, thanks! Another relative question is whether the following 2 cases have similar performance, or not?

```sh
Case-1) kernel<<<(N + 63) / 64, 64>>>(...)
Case-2) kernel<<<(N + 1023) / 1024, 1024>>>(...)
```
Ignoring other factors like shared memory, I just wonder when both 2 cases following the warpSize requirement, whether Case-1 has larger overhead than Case-2? (as it uses less threads per block compared with Case-2)

**Comment by ghostplant** [comment]
Hi @bensander, can one CU schedule 10 work groups together? (each work group has exactly 256 work items)
