### ISSUE TITLE
Error with hipMemcpyToSymbol only when targetting nvcc

### ISSUE THREAD

**Issue by JMadgwick** [ROCm-Developer-Tools/HIP#1078]
I have found a problem with hipMemcpyToSymbol running hipcc **when targetting nvcc**.
It should be reproducible with this simple program:
```cpp
#include <iostream>
#include <hip/hip_runtime.h>
#include <hip/hip_runtime_api.h>

__constant__ int dim;

__global__ void test(int *gpu_Num){
    *gpu_Num = dim;
}

int main(int argc, char* argv[])
{
    int num = 25;
    hipMemcpyToSymbol(HIP_SYMBOL(dim),&num,sizeof(int),0,hipMemcpyHostToDevice);
    
    int *gpu_Num;
    hipMalloc(&gpu_Num,sizeof(int));

    hipLaunchKernelGGL(test,dim3(1),dim3(1),0,0,gpu_Num);

    int hostResult;
    hipMemcpy(&hostResult,gpu_Num,sizeof(int),hipMemcpyDefault);
    
    printf("Result: %i\n",hostResult);
}
```
The hipcc output when targetting nvcc (HIPCC_VERBOSE enabled) is:
```
james@Ryzen:~/Documents$ hipcc HIP_Bug.cpp -o bug
Use of uninitialized value $HIP_RUNTIME in string eq at /opt/rocm/bin/hipcc line 109.
Use of uninitialized value $HIP_COMPILER in string eq at /opt/rocm/bin/hipcc line 131.
hipcc-cmd: /usr/local/cuda/bin/nvcc  -Wno-deprecated-gpu-targets  -isystem /usr/local/cuda/include -isystem /opt/rocm/include -DHIP_VERSION_MAJOR=1 -DHIP_VERSION_MINOR=5 -DHIP_VERSION_PATCH=19123 -x cu  -Wno-deprecated-gpu-targets -lcuda -lcudart -L/usr/local/cuda/lib64  HIP_Bug.cpp -o bug
HIP_Bug.cpp(14): error: argument of type "int" is incompatible with parameter of type "const void *"

1 error detected in the compilation of "/tmp/tmpxft_00000939_00000000-8_HIP_Bug.cpp1.ii".
```
The equivilent program in CUDA is this:
```cpp
#include <iostream>
#include <cuda.h>
#include <cuda_runtime.h>

__constant__ int dim;

__global__ void test(int *gpu_Num){
    *gpu_Num = dim;
}

int main(int argc, char* argv[])
{
    int num = 25;
    cudaMemcpyToSymbol(dim,&num,sizeof(int),0,cudaMemcpyHostToDevice);
    
    int *gpu_Num;
    cudaMalloc(&gpu_Num,sizeof(int));

    test<<<1,1>>>(gpu_Num);

    int hostResult;
    cudaMemcpy(&hostResult,gpu_Num,sizeof(int),cudaMemcpyDefault);
    
    printf("Result: %i\n",hostResult);
}
```
Which compiles and runs as expected:
```
james@Ryzen:~/Documents$ nvcc HIP_Bug.cu -o bug
james@Ryzen:~/Documents$ ./bug
Result: 25
```

It would seem that `__constant__ int dim` is the problem, HIP does not appear to manage `__constant__` which is not a pointer. This works for AMD GPUs so presumably the problem is in the conversion between HIP and CUDA that is sent to nvcc. Using -keep, I had a look at the temp file but nothing struck me as wrong it seemed to contain the expected mappings from HIP to CUDA.
If the program is changed to this:
```cpp
<snip>
__constant__ int dim[1];

__global__ void test(int *gpu_Num){
    *gpu_Num = *dim;
}

int main(int argc, char* argv[])
{
    int num = 25;
    hipMemcpyToSymbol(HIP_SYMBOL(dim),&num,sizeof(int),0,hipMemcpyHostToDevice);
    
    int *gpu_Num;
    hipMalloc(&gpu_Num,sizeof(int));

    hipLaunchKernelGGL(test,dim3(1),dim3(1),0,0,gpu_Num);

    int hostResult;
    hipMemcpy(&hostResult,gpu_Num,sizeof(int),hipMemcpyDefault);
    
    printf("Result: %i\n",hostResult);
}
```
then it compiles and runs, giving the expected result. This indicates the problem is only with `__constant__`s which are not pointers.

_Hopefully this should be an easy fix._

**Also** I noticed [that it says here "symbol name needs to be encased in the HIP_SYMBOL macro"](https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md#memcpytosymbol). Except that it can in fact be omitted and appears to have no effect. Also HIP_SYMBOL [is not mentioned in the API reference at all](https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/HIP_API/Memory-Management.html#hipmemcpytosymbol)? Whether or not it is used has no effect on the bug I have described.

**Comment by gargrahul** [comment]
Thanks for reporting this. Please confirm if #1082 resolves this.

**Comment by JMadgwick** [comment]
@gargrahul Can confirm that #1082 fixes the problem the HIP_SYMBOL() macro, programs now compiles and works as expected.
**However, only when the HIP_SYMBOL() macro is used.** When HIP_SYMBOL() is not used the error is unchanged. This behaviour when it isn't used is bad because it is inconsistent. The porting guide states to use the macro but it is not mentioned in the [API reference](https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/HIP_API/Memory-Management.html#hipmemcpytosymbol).
If the macro is not used, pointer values still work without it, if the macro is required they should not work or at least there should be some warning the the macro should be used. This is for the most part a documentation issue and I might reopen it there.
