### ISSUE TITLE
HIP make fails on roc-2.3.x branch

### ISSUE THREAD

**Issue by prateeksahu** [ROCm-Developer-Tools/HIP#1079]
Checked out the roc-2.3.x branch of HIP source code since I am developing on the roc-2.3.x ROCK-Kernel. 
Steps followed:
mkdir build; mkdir hip
cd build
cmake -DHSA_PATH=/path/to/hsa -DHCC_HOME=/path/to/hcc -CMAKE_INSTALL_PREFIX=../hip -DCMAKE_BUILD_TYPE=Release ..
make

cmake output:
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HIP Platform: hcc
-- HIP Compiler: hcc
-- Looking for HCC in: /opt/rocm/hcc. Found version: 1.2.18354-ec91fed-e2b51bf-009cb63
-- Looking for HSA runtime in: /opt/rocm/hsa
-- HIP will be installed in: /home/prateeks/HIP/hip
-- Generating profiling promitives: /home/prateeks/HIP/include/hip/hcc_detail/hip_prof_str.h
/home/prateeks/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyToSymbolAsync
/home/prateeks/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyFromSymbolAsync
/home/prateeks/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyFromSymbol
/home/prateeks/HIP/hip_prof_gen.py Warning: implementation not found: hipModuleGetGlobal
/home/prateeks/HIP/hip_prof_gen.py Warning: implementation not found: hipGetSymbolAddress
/home/prateeks/HIP/hip_prof_gen.py Warning: implementation not found: hipGetSymbolSize
/home/prateeks/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyToSymbol
/home/prateeks/HIP/hip_prof_gen.py Warning: 7 API calls missing in interception layer
-- Found HIP: /home/prateeks/HIP/hip (found version "1.5.19123") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/prateeks/HIP/build

make output:
Scanning dependencies of target hip_hcc_static
[  0%] Building CXX object CMakeFiles/hip_hcc_static.dir/src/code_object_bundle.cpp.o
[  0%] Building CXX object CMakeFiles/hip_hcc_static.dir/src/hip_clang.cpp.o
[  9%] Building CXX object CMakeFiles/hip_hcc_static.dir/src/hip_hcc.cpp.o
/home/prateeks/HIP/src/hip_hcc.cpp:2175:19: error: no member named 'copy2d_ext' in 'hc::accelerator_view'
        crit->_av.copy2d_ext(src, dst, width, height, srcPitch, dstPitch, hcCopyDir, srcPtrInfo, dstPtrInfo,
        ~~~~~~~~~ ^
/home/prateeks/HIP/src/hip_hcc.cpp:2398:28: error: no member named 'copy2d_ext' in 'hc::accelerator_view'
                 crit->_av.copy2d_ext(src, dst, width, height, srcPitch, dstPitch, hcCopyDir, srcPtrInfo, dstPtrInfo,
                 ~~~~~~~~~ ^
/home/prateeks/HIP/src/hip_hcc.cpp:2404:49: error: no member named 'copy2d_async_ext' in 'hc::accelerator_view'
                 const auto& future = crit->_av.copy2d_async_ext(src, dst, width, height, srcPitch, dstPitch, hcCopyDir, srcPtrInfo, dstPtrInfo,
                                      ~~~~~~~~~ ^
/home/prateeks/HIP/src/hip_hcc.cpp:2432:20: error: no member named 'copy2d_ext' in 'hc::accelerator_view'
         crit->_av.copy2d_ext(src, dst, width, height, srcPitch, dstPitch, hcCopyDir, srcPtrInfo, dstPtrInfo,
         ~~~~~~~~~ ^
4 errors generated.
/home/prateeks/HIP/src/hip_hcc.cpp:2175:19: error: no member named 'copy2d_ext' in 'hc::accelerator_view'
        crit->_av.copy2d_ext(src, dst, width, height, srcPitch, dstPitch, hcCopyDir, srcPtrInfo, dstPtrInfo,
        ~~~~~~~~~ ^
/home/prateeks/HIP/src/hip_hcc.cpp:2398:28: error: no member named 'copy2d_ext' in 'hc::accelerator_view'
                 crit->_av.copy2d_ext(src, dst, width, height, srcPitch, dstPitch, hcCopyDir, srcPtrInfo, dstPtrInfo,
                 ~~~~~~~~~ ^
/home/prateeks/HIP/src/hip_hcc.cpp:2404:49: error: no member named 'copy2d_async_ext' in 'hc::accelerator_view'
                 const auto& future = crit->_av.copy2d_async_ext(src, dst, width, height, srcPitch, dstPitch, hcCopyDir, srcPtrInfo, dstPtrInfo,
                                      ~~~~~~~~~ ^
/home/prateeks/HIP/src/hip_hcc.cpp:2432:20: error: no member named 'copy2d_ext' in 'hc::accelerator_view'
         crit->_av.copy2d_ext(src, dst, width, height, srcPitch, dstPitch, hcCopyDir, srcPtrInfo, dstPtrInfo,
         ~~~~~~~~~ ^
4 errors generated.
CMakeFiles/hip_hcc_static.dir/build.make:110: recipe for target 'CMakeFiles/hip_hcc_static.dir/src/hip_hcc.cpp.o' failed
make[2]: *** [CMakeFiles/hip_hcc_static.dir/src/hip_hcc.cpp.o] Error 1
CMakeFiles/Makefile2:1822: recipe for target 'CMakeFiles/hip_hcc_static.dir/all' failed
make[1]: *** [CMakeFiles/hip_hcc_static.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

the rock libraries, like hcc, hsa are on the latest versions -- hcc (1.2.18354), hip_hcc (1.5.18353), hsa-rocr-dev (1.1.9-8-g51c00c2), hsa-ext-rocr-dev (1.1.9-8-g51c00c2).

Any help will be appreciated.

**Comment by gargrahul** [comment]
Looks like you are not using recent HCC. copy2d_ext is defined here https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/include/hc.hpp#L379

Can you try by building latest hcc or using ROCm 2.3 released HCC packages?

**Comment by prateeksahu** [comment]
Hi Rahul, can you please tell me if the apt packages for hcc not on the latest versions (ROCm 2.3)? I did think that the hcc version dependencies could have been an issue and updated my apt packages.
I did try to build hcc from the source as well and my make failed with an error as described by this GitHub issue (https://github.com/RadeonOpenCompute/hcc/issues/960).

**Comment by gargrahul** [comment]
Your ROCm stack looks quite old. You need to upgrade to the latest ROCm stack- including ROCr. Just building latest HCC may not be enough.  Please refer https://github.com/RadeonOpenCompute/ROCm#current-rocm-version-23 
RadeonOpenCompute/hcc#960 would be resolved once you upgrade to the latest ROCr.
