### ISSUE TITLE
[Question][HIPIFY][QUDA] I'm a developer on an open source CUDA based project called QUDA. Does anybody know of any previous activity to `hipify` QUDA by AMD?

### ISSUE THREAD

**Issue by cpviolator** [ROCm-Developer-Tools/HIP#1086]
The repo is here: https://github.com/lattice/quda

I am obviously curious as to how this library can be made to run on the new Frontier machine at Oak Ridge. I'm not an NVIDIA employee, but I have extensive knowledge of QUDA and CUDA. If no efforts have been made so far to make QUDA work on AMD architecture, I will start the project as soon as possible. For the next few days, I'm simply trying to gather as much information as possible so time is not wasted going over old ground.

Thank you!

**Comment by whchung** [comment]
@cpviolator you might want to check an early port made some time ago at: https://bitbucket.org/multicoreware/quda-port

**Comment by cpviolator** [comment]
Hi Jack, Thanks for the link. Unfortunately I'm getting and 'Access Denied` from Bitbucket. Can you give me a contact for the repo owners?

**Comment by whchung** [comment]
@cpviolator I didn't work on the project myself so I'm not sure who the repo owners are.

adding @bensander as he should have the contacts to the team working on the HIP-QUDA project.

**Comment by bensander** [comment]
@cpviolator  Dean - thanks for reaching out.  I will check on the status of the previous port.  But might be easier to start afresh with a new project and perhaps pick-and-choose from the older project as needed.

**Comment by cpviolator** [comment]
@bensander Thank you very much. Any head start we can gain from previous work on this would be phenomenal. I found this https://indico4.twgrid.org/indico/event/8/session/23/contribution/2/material/slides/0.pdf with a cursory search, which isn't promising. I'm sure we can get a working port with the main features up and running on AMD with some thought and effort.

**Comment by bensander** [comment]
@cpviolator  - quick review of the repot suggests best path would be to start fresh.  Likely better in the long run - a lot has changed (improved!) since that port was attempted.

**Comment by cpviolator** [comment]
@bensander Thanks for getting back on this. QUDA currently is undergoing a rehaul in that as much of the algorithmic content as possible can be isolated from the back end implementation. We make use of jitify extensively, and we can hipify the code using the same paradigm. This will be after some further clean up to homogenise the library to make the hipify solution clear.

Thanks again to @bensander and @whchung for your help. I'll get back to you when we're ready for HIP!

**Comment by cpviolator** [comment]
Thanks for the info Ben.

I strongly suspect that we will go ahead with attempting QUDA port using HIP in the near future and I will likely be on point for this. I will study the guide and attempt to port the QUDA 0.9.0 master branch.

I see that your master branch is very active. Can you recommend a stable(ish) HIP branch to work from? Also, if I encounter specific issues is there a Slack channel or other line of communication I can use?

**Comment by gargrahul** [comment]
Thanks @cpviolator 
Recommended latest stable HIP code is https://github.com/ROCm-Developer-Tools/HIP/tree/roc-2.4.x. 
If you need any latest changes then the master branch should be used.
For issues, please log github issue and we will get in touch with you.
