### ISSUE TITLE
How to compile device-only HIP source to HSACO efficiently?

### ISSUE THREAD

**Issue by ghostplant** [ROCm-Developer-Tools/HIP#1098]
Here is an example of a device-only HIP source code (with always only 1 device function set):
```sh
extern "C" __global__ void device_func_main(float *x, float *y) {
   ..
}
```
I think some working ways are like using `KMDUMPISA=1` when compiling this code by `hipcc`, or using `extactkernel` for the generated target binary. However, I don't think generator target binary is a must which definitely slows down the HSACO object I want to get. So is there other better way to compile this device-only HIP source code efficiently? (maybe I need something like `clang-9 device-code.hip.cc --device-only --emit-xxx ...`)

**Comment by mangupta** [comment]
See the [module_api sample](https://github.com/ROCm-Developer-Tools/HIP/blob/master/samples/0_Intro/module_api). ```hipcc --genco``` is the option you are looking for.

**Comment by ghostplant** [comment]
@mangupta Thanks, but I got some warnings or some unexpected errors:
``sh
$ hipcc --genco currentKrnl.cc
clang-9: warning: -amdgpu-target argument 'gfx801' is not recognized; using gfx803 instead [-Winvalid-command-line-argument]
clang-9: warning: -amdgpu-target argument 'gfx802' is not recognized; using gfx803 instead [-Winvalid-command-line-argument]

$ hipcc --genco currentKrnl.cc --amdgpu-target=gfx906
Unrecognised token: --amdgpu-target
Died at /opt/rocm/bin/hipcc line 345.
```

The rocm-dev version is lastest 2.4

**Comment by mangupta** [comment]
```hipcc --genco``` tries to compile the kernel for all possible GCN ISA as listed in https://www.llvm.org/docs/AMDGPUUsage.html#processors. Some of which the compiler may not be supporting/removed support for. Hence the warnings. It is safe to ignore the warnings right now.

```hipcc --genco``` internally uses another executable namely lpl for generation of code objects. This binary currently does not accept targets using ```--amdgpu-target```. Instead it recognizes the ```--targets``` option.
So using something like ```hipcc --genco --targets gfx906 currentKrnl.c``` should work.

**Comment by ghostplant** [comment]
@mangupta Thanks, it works, so does `lpl` command.

**Comment by leofang** [comment]
Hi @mangupta, I found `hipcc --genco --targets gfx906 ...` no longer works (tested on ROCm 3.5/3.8). It complains "--targets" is not recognized. Is something changed? Also, the public documentation is apparently outdated: it uses `--target-isa` instead of `--targets` (and it doesn't work either):  
https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-GUIDE.html?#kernel-compilation
