### ISSUE TITLE
CUDA-style parameter filling is not working for ROCm 2.4

### ISSUE THREAD

**Issue by ghostplant** [ROCm-Developer-Tools/HIP#1099]
Reference example: https://github.com/ROCm-Developer-Tools/HIP/blob/master/samples/0_Intro/module_api/defaultDriver.cpp#L68

If setting `kernelParams` argument instead of setting `extra` argument, the kernel function doesn't  get the expected argument value.

**Comment by gargrahul** [comment]
#1091 Fixes this.

**Comment by ghostplant** [comment]
Thanks, waiting for the next release.
