### ISSUE TITLE
Getting Pointer to constant memory fails

### ISSUE THREAD

**Issue by davidrohr** [ROCm-Developer-Tools/HIP#1107]
For me, hipGetSymbolAddress() always fails with an error code 500 / hipErrorNotFound.
Tried with HIP 2.2 / 2.3 / 2.4 on different OS.

Testcase attached below.
Compile command used: hipcc --amdgpu-target=gfx906 -o test  test.hip.cpp

[test.hip.cpp.gz](https://github.com/ROCm-Developer-Tools/HIP/files/3182844/test.hip.cpp.gz)

**Comment by gargrahul** [comment]
@davidrohr Could you please try following ? I have added a dummy kernel to use constant memory and the symbol name needs to be encased in the HIP_SYMBOL macro as described in https://github.com/ROCm-Developer-Tools/HIP/blob/roc-2.4.x/docs/markdown/hip_porting_guide.md#memcpytosymbol.

#include "hip/hip_runtime.h"
#include <cstdio>

 __constant__ uint4 gGPUConstantMemBuffer[1024];

#define GPUFailedMsgI(x) GPUFailedMsgAI(x, __FILE__, __LINE__)

__global__ void Assign(uint4* Out) {
    int tid = threadIdx.x + blockIdx.x * blockDim.x;
    Out[tid] = gGPUConstantMemBuffer[tid];
}


static int GPUFailedMsgAI(const long long int error, const char* file, int line)
{
  // Check for HIP Error and in the case of an error display the corresponding error string
  if (error == hipSuccess) {
    return (0);
  }
  printf("HIP Error: %lld / %s (%s:%d)\n", error, hipGetErrorString((hipError_t)error), file, line);
  return 1;
}

int main(int, char**)
{
    void* devPtrConstantMem;
    if (GPUFailedMsgI(hipGetSymbolAddress(&devPtrConstantMem, HIP_SYMBOL(gGPUConstantMemBuffer)))) {
        printf("Error getting ptr to constant memory\n");
        return 1;
    }
    printf("Ptr %p\n", devPtrConstantMem);

    return 0;
}

**Comment by davidrohr** [comment]
@gargrahul : Thx, that works. And it needs the dummy kernel. Could this be fixed?
Also, is it safe to use the ptr obtained via hipGetSymbolAddress in a kerne, which does not explicitly use gGPUConstantMemBuffer?

Thx
David

**Comment by zjin-lcf** [comment]
Could AMD developers please comment on the David's question ?

ptr obtained via hipGetSymbolAddress in a kernel, which does not explicitly use gGPUConstantMemBuffer?  

Is the dummy kernel required ? 

Thanks
