### ISSUE TITLE
Where is hipify binary file

### ISSUE THREAD

**Issue by syifan** [ROCm-Developer-Tools/HIP#112]
In newer versions of HIP release, I cannot find hipify executable file in the bin folder. Is it replaced by hipify-clang, and users have to build from source to use it?

**Comment by bensander** [comment]
Hi Yifan – we support both “hipify-perl” (for fast conversions and analysis) and “hipify-clang” (for more extensive conversions with actual code parsing).  Hipify-perl is in the bin directory while hipify-clang is built from source.

**Comment by syifan** [comment]
Thank you very much. Good to know that hipify-perl is actually the old hipify. And I have also compiled the hipify-clang from source. The compilation process takes a while.
