### ISSUE TITLE
Getting ptr to constant memory fails when GCC is used as linker

### ISSUE THREAD

**Issue by davidrohr** [ROCm-Developer-Tools/HIP#1126]
This is a follow up to #1107 :
hipGetSymbolAddress fails when I compile the hip.cpp file with hipcc but then use GCC for linking. Everything works well when I use hipcc for both compilation and linking. From the documentation I understand that it should in principle be possible to a different linker.

**Comment by davidrohr** [comment]
After playing around a bit, I found out that hipcc takes very long during the linking phase.
This looks to me like it does the GPU compilation somehow during the linking? Perhaps there is something missing when I perform the linking with GCC.

**Comment by SarbojitAMD** [comment]
@davidrohr,
You are correct, hipcc during compile only emits LLVM IR and later during linking it generates ISA
hence linking using GCC is not possible. But you can always compile HOST code using GCC and device code using hipcc and later you can use hipcc for linking those object codes.

I am closing the ticket now. Feel free to create new ticket in case you have any further query.
