### ISSUE TITLE
Support using type `int8` without inline assembly code in HIP kernel?

### ISSUE THREAD

**Issue by ghostplant** [ROCm-Developer-Tools/HIP#1145]
Is it able to use type `int8` for dot4 without inline assembly code in HIP kernel?

In addition, where can I find the reference of the argument usage of `v_dot4_i32_i8 %out, %x, %y, %b`? Thanks!

**Comment by ex-rzr** [comment]
https://github.com/ROCm-Developer-Tools/HIP/blob/b93666bdde1b490ae2370d7864674800f7c52455/include/hip/hcc_detail/math_functions.h#L137

**Comment by ghostplant** [comment]
@ex-rzr  Thanks!

**Comment by ghostplant** [comment]
@ex-rzr Does it calculate for `ret = a * b + c`, what does saturate mean here?

**Comment by ex-rzr** [comment]
I've never used it, but you can look at its software (for older GPUs) implementation:
https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/ockl/src/dots.cl#L95
