### ISSUE TITLE
question about FindHIP cmake file

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#118]
Is there a cmake variable that is set when HIP is found ? I would like to generate a define
in my code to specify whether HIP was found or not.

For OpenCL, there is the OPENCL_FOUND cmake variable.

**Comment by boxerab** [comment]
I would recommend HIP_FOUND, if there isn't already a variable being set.

**Comment by boxerab** [comment]
For now, I will use HIP_VERSION

**Comment by mangupta** [comment]
Could you share how you are trying to use FindHIP? FindHIP uses FindPackageHandleStandardArgs which should automatically set HIP_FOUND to TRUE. Attached is a sample [cmake](https://github.com/ROCm-Developer-Tools/HIP/files/1182111/CMakeLists.txt) that uses FindHIP. I was able to successfully run it using cmake 3.6.1. In fact running cmake with --trace-expand shows
```.../share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake(262):  set(HIP_FOUND TRUE )```

**Comment by boxerab** [comment]
You are right! Thanks - closing this.
