### ISSUE TITLE
Use of uninitialized value $HIP_RUNTIME when compiling with hipcc

### ISSUE THREAD

**Issue by Alkeryn** [ROCm-Developer-Tools/HIP#1186]
Whenever i compile using hipcc it throw me these errors:
![image](https://user-images.githubusercontent.com/11599075/60055874-52a61400-96df-11e9-902e-c0b5e228d7e0.png)
Tho it successfully compile and the executable successfully runs

**Comment by SarbojitAMD** [comment]
Thanks for pointing it out raised PR https://github.com/ROCm-Developer-Tools/HIP/pull/1343

**Comment by cederikhoefs** [comment]
(Sorry to open this old thread up again, but I get a
`Use of uninitialized value $HIP_COMPILER in string ne at /opt/rocm/hip/bin//hipcc line 657.`
at each invocation of `hipcc`. `nvcc` is being used as the back end.
