### ISSUE TITLE
hipFuncGetAttributes is not working as expected. 

### ISSUE THREAD

**Issue by Kaveh01** [ROCm-Developer-Tools/HIP#1193]
```
cudaFuncGetAttributes(&kernel_attrs, kernel_func);
printf("%d  \n", kernel_attrs.sharedSizeBytes);
```
works fine with expected output.
```
hipFuncGetAttributes(&kernel_attrs, HIP_SYMBOL(kernel_func));
printf("%d  \n", kernel_attrs.sharedSizeBytes);
```
 returns a random integer like an uninitialized variable.

**Comment by gargrahul** [comment]
Could you please try with https://github.com/ROCm-Developer-Tools/HIP/blob/roc-2.6.x/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp ?

**Comment by Kaveh01** [comment]
> Could you please try with https://github.com/ROCm-Developer-Tools/HIP/blob/roc-2.6.x/tests/src/runtimeApi/module/hipFuncGetAttributes.cpp ?

Thanks, it worked with "reinterpret_cast".
