### ISSUE TITLE
HIP_ADD_EXECUTABLE does not work with target_link_libraries

### ISSUE THREAD

**Issue by syifan** [ROCm-Developer-Tools/HIP#120]
In the linking script generate by CMake, libraries are not present. So the compiler complains undefined reference.

**Comment by mangupta** [comment]
Thanks! Also merged your PR #121 that fixes this issue.

**Comment by syifan** [comment]
Thank you very much for merging the pull request. 

I just realized that PR #121 just partially solves the problem. When working on ROCm platform, it works fine. It also works fine on CUDA platform when there is no dynamic link. But if I try to link with third-party libraries, there is an error. The solution to this problem is beyond my ability. 

In my particular project, I use OpenCV library to be linked dynamically to the executable. So I wrote the following in my CMakeLists.txt. 

```cmake
hip_add_executable(${FOLDER_NAME} ${HEADER_FILES} ${SRC_FILES})           
target_link_libraries(${FOLDER_NAME} be time_measurement command_line_option benchmark ${OpenCV_LIBS})
``` 

All the libraries that are directly used are static libraries. So there is no error with them. The ${OpenCV_LIBS} causes nvcc to issue the following problem.

```
nvcc fatal   : Don't know what to do with '/usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4.8'
```

And here is the command that is generated by CMake. In ROCm machine, there is no problem even the same command is generated. 
```bash
/opt/rocm/bin/hipcc_cmake_linker_helper /opt/rocm/hcc    CMakeFiles/be_hip.dir/main.cc.o CMakeFiles/be_hip.dir/be_hip_generated_be_hip_benchmark.cu.o -o be_hip  -L/usr/lib/gcc/x86_64-linux-gnu/4.8  ../libbe.a ../../common/time_measurement/libtime_measurement.a ../../common/command_line_option/libcommand_line_option.a ../../common/benchmark/libbenchmark.a /usr/lib/x86_64-linux-gnu/libopencv_videostab.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_ts.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_superres.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_stitching.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_ocl.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_gpu.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_contrib.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_photo.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_legacy.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_video.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_ml.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_calib3d.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_features2d.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_flann.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4.8 -lstdc++ -lm -lc
```

**Comment by mangupta** [comment]
Just to understand this issue you are now seeing correctly.

* On HIP/ROCm platform with the PR #121 applied you do not face any issues with linking additional libraries (static or dynamic)
* On HIP/CUDA platform with the PR #121 applied you do not face any issues when linking additional static libraries, but get an error when linking dynamic libraries.

If so, do you happen to know what happens when using Native CUDA + FindCUDA? In any case I will investigate this further myself. Just trying to understand if this is an nvcc or FindHIP issue.

**Comment by syifan** [comment]
Yes, I think the points are correct. There is no error if I use native CUDA + FindCUDA. In my case, I have 3 files involved, a .cu file, a .h file for the .cu file, and a .cc file for the main program. FindCUDA uses nvcc to compile the .cu file, but it uses c++ to do the linking. So the corresponding command that is generated by FindCUDA is 

```bash
/usr/bin/c++    -Wall -Werror -Wno-unused-command-line-argument -pthread -g   CMakeFiles/be_cuda.dir/main.cc.o CMakeFiles/be_cuda.dir/be_cuda_generated_be_cuda_benchmark.cu.o
  -o be_cuda -rdynamic /usr/local/cuda/lib64/libcudart.so ../libbe.a ../../common/time_measurement/libtime_measurement.a ../../common/command_line_option/libcommand_line_option.a ../../common/benchmark/libbenchmark.a /usr/lib/x86_64-linux-gnu/libopencv_videostab.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_ts.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_superres.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_stitching.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_ocl.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_gpu.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_contrib.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_photo.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_legacy.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_video.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_ml.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_calib3d.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_features2d.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_flann.so.2.4.8 /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4.8 -Wl,-rpath,/usr/local/cuda/lib64
```

If you want to recreate the error I am having, you can clone this branch [https://github.com/NUCAR-DEV/Hetero-Mark/tree/rocm1.4](https://github.com/NUCAR-DEV/Hetero-Mark/tree/rocm1.4). The command to compile CUDA is 
```bash
mkdir build-cuda
cd build-cuda
cmake -DCOMPILE_CUDA=On ..
make
```
and the command to compile HIP is
```bash
mkdir build-hip
cd build-hip
cmake -DCOMPILE_HIP=On ..
make
```

**Comment by theZiz** [comment]
I still have a similar problem. While compiling with CMake, it generates a dependency file with `hipcc -M`. We are using `HIP_ADD_EXECUTABLE` or `CUDA_ADD_EXECUTABLE` in our project depending on a CMake Variable. However with CUDA all flags and includes are added to the dependency generation command, but with HIP there are missing. If I set them by hand in `HIP_NVCC_FLAGS` everything works fine.

**Comment by Ulfgard** [comment]
This issue still exists.

**Comment by armeenm** [comment]
This issue still exists. I'm on HIP v1.5.19253 and I'm trying to link to OpenCV with nvcc.

**Comment by atabish** [comment]
Has anyone come out with a solution/work around for this issue?
