### ISSUE TITLE
[HIPIFY] Unknown regexp modifier error in hipify-perl

### ISSUE THREAD

**Issue by shunxu-cas** [ROCm-Developer-Tools/HIP#1221]
I try to run hipify-perl  on a CUDA file and get error messages like below. The hipify-perl used was updated by replacement maps exported by hipify-clang with '-perl' option.
```
Unknown regexp modifier "/t" at ../hipify-perl line 782, near "+= "
Unknown regexp modifier "/h" at ../hipify-perl line 782, near "+= "
Unknown regexp modifier "/_" at ../hipify-perl line 782, near "+= "
Unknown regexp modifier "/n" at ../hipify-perl line 782, near "+= "
Unknown regexp modifier "/_" at ../hipify-perl line 782, near "+= "
...
```
Then I check the replacement maps in hipify-perl-map, some look like 
```
$ft{'include'} += s/\bcaffe2/core/common_cudnn.h\b/caffe2/core/hip/common_miopen.h/g;
$ft{'include'} += s/\bcaffe2/operators/spatial_batch_norm_op.h\b/caffe2/operators/hip/spatial_batch_norm_op_miopen.hip/g;
$ft{'include'} += s/\bchannel_descriptor.h\b/hip/channel_descriptor.h/g;
...
```
Obviously, they are used in wrong way when path separator '/' used in regular expression. I suggest the separator of replacement regular expression uses '|' instead.
**The solution** is to fix the bug at line 135 in hipify-clang/src/main.cpp.

**Comment by emankov** [comment]
Please, verify.

**Comment by shunxu-cas** [comment]
It works well after fixing.
