### ISSUE TITLE
Change hipLaunchKernel to hipLaunchKernelGGL in samples and documentation

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#123]
hipLaunchKernelGGL makes HIP kernels look even more like CUDA kernels, so this usage should be promoted ( I realize this feature just dropped ).

**Comment by bensander** [comment]
We mentioned it a bit here : http://gpuopen.com/whats-new-hip-hcc-rocm-1-6/
But you are right this is a very useful simplification to the language and deserves some attention.

**Comment by boxerab** [comment]
Great, thanks.

**Comment by gargrahul** [comment]
Closing this issue since required changes were already merged in HIP and are available in the latest code.
