### ISSUE TITLE
Operator overloading for vector types?

### ISSUE THREAD

**Issue by taintur** [ROCm-Developer-Tools/HIP#124]
I'd like to do some complex number arithmetic and for that types float2 and double2 are perfect regarding performance. However, when compiling with hcc, the operators between vector types are already overloaded with element-wise products in "HIP/include/hip/hcc_detail/hip_vector_types.h". Is there a way to circumvent this?

**Comment by taintur** [comment]
Apparently it's possible to redefine the operators using a wrapper struct:
`struct cmplx : float2{};`
and defining operators for type cmplx. This fixes the problem for me. Nevertheless, the functionality of vector type operators differ between nvcc (no existing overloads) and hcc (element-wise operations), so I'd consider the issue still open.

**Comment by adityaatluri** [comment]
Operator overloading is requested by library team, hence we add it to HIP even though it is not supported by CUDA. If you don't want operator overloading, you can create your own datatypes and do not include the header.

**Comment by taintur** [comment]
I see, thanks for clarification.
