### ISSUE TITLE
HIP, HCC, cmake and Eclipse CDT

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#126]
I am using Eclipse CDT as my IDE for HIP development.
Is there a way of setting HCC as the compiler when creating build files with cmake?

**Comment by boxerab** [comment]
Perhaps you could add a sample showing how to run a cmake project that uses HIP.

**Comment by boxerab** [comment]
Any updates on this ?

**Comment by bensander** [comment]
We use CMAKE for many projects including the HIP tests (HIP/tests/src).   I am not familiar with details of eclipse but expect there would be a standard way to change the compiler?

**Comment by mangupta** [comment]
Closing the issue since the PR is merged.
