### ISSUE TITLE
Question regarding HIP-CLang dependencies

### ISSUE THREAD

**Issue by justxi** [ROCm-Developer-Tools/HIP#1273]
Hi, according to the [Installation notes](https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md) the amd-common branches of llvm/clang/lld should be used to build hip in the future. Currently for llvm/lld there are roc-hcc-2.y and roc-ocl-2.y, for clang only roc-2.y.x. Due to the fact hcc is deprecated... will there be an additional branch for HIP-Clang or is it the roc-ocl branch in the future? I ask because I help packaging (@candrews, @davidrohr) ROCm for Gentoo Linux and want to plan which compiler is needed in the future.

**Comment by Lucretia** [comment]
How long does it take for AMD to answer these questions? @davidrohr @candrews ??

**Comment by candrews** [comment]
> How long does it take for AMD to answer these questions?

I'm not an AMD person... I'm just a user and a Gentoo developer.

I'm frustrated with waiting just like you are :(

**Comment by yxsamliu** [comment]
sorry for the delay. For build and installation of HIP-Clang pls check the updated documentation https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md#hip-clang

**Comment by justxi** [comment]
@yxsamliu Do I see it right that building HIP according to that documentation, it does not depend on HCC anymore?

**Comment by yxsamliu** [comment]
Building HIP runtime still needs HCC. After it is built, when you use HIP-Clang and HIP runtime to build HIP apps, you do not need HCC.

**Comment by justxi** [comment]
Due to the fact that there is now a version of HIP which builds without "hcc", I close this.
