### ISSUE TITLE
HIP default stream ?

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#129]
Is there a concept of a default stream in HIP?

**Comment by gargrahul** [comment]
Yes. ihipInit creates ihipDevice_t for each visible device, which creates
_primaryCtx. _primaryCtx creates _defaultStream.

**Comment by bensander** [comment]
Yes.  Stream 0 is default stream and imposes special synchronization – all commands submitted to default stream wait for older commands in any non-blocking queue to complete.  Also command sent to any non-blocking queue will wait for the oldest command in default stream to complete.
There have been some recent bug fixes and optimizations in this area so please pull latest code.

**Comment by boxerab** [comment]
Thanks.
