### ISSUE TITLE
clang build fails when llvm is installed locally

### ISSUE THREAD

**Issue by malcolmroberts** [ROCm-Developer-Tools/HIP#1301]
The clang build fails when compiling Diagnostic.cpp; this may be due to having installed llvm locally.

Step 1: install llvm to ${HOME}/llvm-amd:

git clone git@github.com:RadeonOpenCompute/llvm.git
cd llvm
git checkout amd-common (actually, already done!)
mkdir build
cd build
cmake  -DCMAKE_INSTALL_PREFIX=${HOME}/llvm-amd ..
make && make install
export CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:${HOME}/lib/cmake

step 2: compile clang:
git clone git@github.com:RadeonOpenCompute/clang.git clang-amd
cd clang-amd
mkdir build && cd build
cmake  -DCMAKE_INSTALL_PREFIX=${HOME}/clang-amd ..
make

This fails with 

[ 19%] Built target clang-tablegen-targets
[ 19%] Building CXX object lib/Basic/CMakeFiles/obj.clangBasic.dir/Diagnostic.cpp.o
/home/marobert/repo/clang-amd/lib/Basic/Diagnostic.cpp: In member function ‘clang::DiagnosticsEngine::DiagState* clang::DiagnosticsEngine::DiagStateMap::File::lookup(unsigned int) const’:
/home/marobert/repo/clang-amd/lib/Basic/Diagnostic.cpp:209:7: error: ‘partition_point’ is not a member of ‘llvm’
       llvm::partition_point(StateTransitions, [=](const DiagStatePoint &P) {
       ^
/home/marobert/repo/clang-amd/lib/Basic/Diagnostic.cpp:209:7: note: suggested alternative:
In file included from /usr/include/c++/5/algorithm:62:0,
                 from /home/marobert/clang/include/llvm/Support/MathExtras.h:18,
                 from /home/marobert/clang/include/llvm/ADT/SmallVector.h:19,
                 from /home/marobert/clang/include/llvm/ADT/STLExtras.h:20,
                 from /home/marobert/clang/include/llvm/ADT/StringRef.h:12,
                 from /home/marobert/repo/clang-amd/include/clang/Basic/DiagnosticIDs.h:19,
                 from /home/marobert/repo/clang-amd/include/clang/Basic/Diagnostic.h:17,
                 from /home/marobert/repo/clang-amd/lib/Basic/Diagnostic.cpp:13:
/usr/include/c++/5/bits/stl_algo.h:600:5: note:   ‘std::partition_point’
     partition_point(_ForwardIterator __first, _ForwardIterator __last,
     ^
lib/Basic/CMakeFiles/obj.clangBasic.dir/build.make:187: recipe for target 'lib/Basic/CMakeFiles/obj.clangBasic.dir/Diagnostic.cpp.o' failed
make[2]: *** [lib/Basic/CMakeFiles/obj.clangBasic.dir/Diagnostic.cpp.o] Error 1
CMakeFiles/Makefile2:2370: recipe for target 'lib/Basic/CMakeFiles/obj.clangBasic.dir/all' failed
make[1]: *** [lib/Basic/CMakeFiles/obj.clangBasic.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I understand that it is recommended to install to /opt/rocm/llvm, but this is a multi-user machine and I don't want to replace everyone else's toolset with my own installation.  This is also important for users who wish to use hip-clang but who do not have root access.

**Comment by justxi** [comment]
Maybe I am wrong, but why do you build llvm first and then clang?
I would checkout llvm, and then checkout clang as subdirectoriy llvm/tools/clang, and lld to llvm/tools/lld and then run cmake followed by make and make install.

**Comment by emankov** [comment]
> I would checkout llvm, and then checkout clang as subdirectoriy llvm/tools/clang, and lld to llvm/tools/lld and then run cmake followed by make and make install.

As for the separate building of llvm and dependent tools, it is possible (but what for?). And @justxi is quite right that all llvm dependent tools should be cloned into tools subfolder. The reported error is exactly because of it.
