### ISSUE TITLE
[HCC] Program crash with missing constructor

### ISSUE THREAD

**Issue by davidrohr** [ROCm-Developer-Tools/HIP#1314]
The program below crashes during hipLaunchKernelGGL instead of giving a failure at compile time, that the constructor for a is defined but not implemented:

```
#include <hip/hip_runtime.h>

class a
{
public:
    __device__ a();
    int x = 0;
};

__global__ void run_printf()
{
    a aa;
}

int main() {
    hipLaunchKernelGGL(HIP_KERNEL_NAME(run_printf), dim3(1), dim3(1), 0, 0);
    hipDeviceSynchronize();
}
```
Compiler simply via: `hipcc -o test test.hip.cpp` with ROCM 2.6 and a Radeon7 GPU.

**Comment by emankov** [comment]
Good catch! Going to check with CUDA (nvcc and clang) and with hip-clang (clang -x hip). Anyway, the issue is related to [HCC](https://github.com/RadeonOpenCompute/hcc-clang-upgrade) compiler rather than HIP.

**Comment by davidrohr** [comment]
This may be, but I never used hcc standalone, so I don't have an example for hcc only, so I thought it is better to open a bug report here. Do you want me to open an issue for HCC as well?

**Comment by emankov** [comment]
hipcc goes through HCC compiler, clang -x hip goes through HIP compiler resided in clang.

> Do you want me to open an issue for HCC as well?

I think maybe later. We need to compare between compilers. I've marked the bug as HCC here.

**Comment by davidrohr** [comment]
I tried this with HIP_COMPILER=clang, and in that case it correctly identifies the missing symbol during compilation: 'lld: error: undefined hidden symbol: a::a()`
So, this problem appears only with HCC.

**Comment by emankov** [comment]
Yes, the problem is only HCC specific. CUDA through nvcc and through clang reports the analogous linking error. Could you please file this issue in HCC?
