### ISSUE TITLE
Building HIP from source, but hipcc can't find hipMemcpy2DAsync symbol

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#132]
Error message is:

     undefined reference to `hipMemcpy2DAsync'

I have built the latest source from master.

**Comment by boxerab** [comment]
Here is my code:



	#define HEIGHT 2
	int height = HEIGHT;
	float h_buffer[12] = {1,2,3,4,5,6,7,8,9,10,11,12};
	float* d_buffer;
	size_t pitch=0;
	hipMallocPitch(&d_buffer, &pitch, sizeof(float)*width, height);
	hipMemcpy2DAsync(d_buffer, pitch, &h_buffer, sizeof(float)*width, sizeof(float)*width, height, hipMemcpyHostToDevice, 0);
	printf("pitch = %d \n", pitch);

	//CUDA 5 texture objects: https://developer.nvidia.com/content/cuda-pro-tip-kepler-texture-objects-improve-performance-and-flexibility
	hipResourceDesc resDesc;
	memset(&resDesc, 0, sizeof(resDesc));
	resDesc.resType = hipResourceTypePitch2D;
	resDesc.res.pitch2D.devPtr = d_buffer;
	resDesc.res.pitch2D.pitchInBytes =  pitch;
	resDesc.res.pitch2D.width = width;
	resDesc.res.pitch2D.height = height;
	resDesc.res.pitch2D.desc.f = hipChannelFormatKindFloat;
	resDesc.res.pitch2D.desc.x = 32; // bits per channel
	resDesc.res.pitch2D.desc.y = 32;
	hipTextureDesc texDesc;
	memset(&texDesc, 0, sizeof(texDesc));
	texDesc.readMode = hipReadModeElementType;
	hipTextureObject_t tex;
	hipCreateTextureObject(&tex, &resDesc, &texDesc, NULL);

**Comment by boxerab** [comment]
This is strange: some new API methds work, but not hipMemcpy2DAsync :


       size_t width = 2;
       size_t height = 6;
	float h_buffer[12] = {1,2,3,4,5,6,7,8,9,10,11,12};
	float* d_buffer;
	size_t pitch=0;

	// this line compiles
	hipMallocPitch((void**)&d_buffer, &pitch, sizeof(float)*width, height);

	// this line compiles
	hipMemcpyAsync(d_buffer, h_buffer,sizeof(float)*width*height,hipMemcpyHostToDevice);

	// !! this line does not compile
	hipMemcpy2DAsync(d_buffer, pitch, h_buffer, sizeof(float)*width, sizeof(float)*width, height, hipMemcpyHostToDevice);

**Comment by boxerab** [comment]
Searching the source code, I don't see an implementation for hipMemcpy2DAsync.

**Comment by gargrahul** [comment]
Thanks for pointing this.Pull request #134
<https://github.com/ROCm-Developer-Tools/HIP/pull/134> should resolve this.

**Comment by gargrahul** [comment]
Please try with PR #134
<https://github.com/ROCm-Developer-Tools/HIP/pull/134>

**Comment by boxerab** [comment]
Thanks, this is working now.
