### ISSUE TITLE
Support CUDA surfaces

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#133]

**Comment by boxerab** [comment]
Textures are read only, but surfaces are writable

**Comment by boxerab** [comment]
Looks like these are not supported yet, from looking into code.

**Comment by bensander** [comment]
Not currently supported, will leave this open as we mature the HIP Texture support.  Can you share more on your use case?

**Comment by boxerab** [comment]
Thanks. So, use case is porting an OpenCL image compression program to HIP. I need a HIP equivalent
of an OpenCL image that can be either read from or written to.  So, I would need a HIP surface to do this.

My OpenCL program makes heavy use of OpenCL images, to improve caching performance.

**Comment by boxerab** [comment]
When may we expect support for surfaces ?  It's quite important for image processing applications.

**Comment by boxerab** [comment]
So, I can now use full OpenCL image features on ROCm.  It is working really well with latest release.
We need an equivalent feature for HIP, i.e. surfaces.

**Comment by boxerab** [comment]
@bensander I see a lot of commit activity relating to textures. Are you able to give us an update on when you guys will tackle surfaces ?

Thanks so much,
Aaron

**Comment by bensander** [comment]
We are getting closer!  @gargrahul is scoping this feature now.

**Comment by boxerab** [comment]
Great! Thanks for the update.

**Comment by boxerab** [comment]
it looks like this is now supported :) closing
