### ISSUE TITLE
Equivalent of cudaFuncGetAttributes

### ISSUE THREAD

**Issue by schwendp** [ROCm-Developer-Tools/HIP#1396]
I am working porting cuda code to hip, but still using nvidia compilers. The kernels are auto-tuned dependent on the maximum allowed block-size which is obtained using cudaFuncGetAttributes. There does not seem to be a hip equivalent to this function yet. How are the maximum block sizes handled on AMD hardware? Is it always the device maximum?

**Comment by gargrahul** [comment]
@schwendp Could you try with hipFuncGetAttributes ? Please refer https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/nvcc_detail/hip_runtime_api.h#L1262

**Comment by schwendp** [comment]
@gargrahul Thanks, that seemed to work.
