### ISSUE TITLE
[HIPIFY] hipify-clang and hipify-perl fails to add HIP_KERNEL_NAME (aka round brackets)

### ISSUE THREAD

**Issue by Kaveh01** [ROCm-Developer-Tools/HIP#1400]
Both hipify-clang and hipify-perl translate kernel lunch line like this:

`sort<512, 8><<<1, 512>>>(d_gpu, result_gpu);`
to
` hipLaunchKernelGGL(sort<512, 8>, dim3(1), dim3(512), 0, 0, d_gpu, result_gpu);`
which leads to folowing error:
```
.hip.cpp(49): error: expected an expression
hip.cpp(49): error: expression must have a constant value
hip.cpp(49): error: expression must have a constant value
hip.cpp(49): error: expression preceding parentheses of apparent call must have (pointer-to-) function type
hip.cpp(49): error: expected a ">"
```
the working translation should be like this:
` hipLaunchKernelGGL(HIP_KERNEL_NAME(sort<512, 8>), dim3(1), dim3(512), 0, 0, d_gpu, result_gpu);`

**Comment by Kaveh01** [comment]
Thanks!

**Comment by emankov** [comment]
Have you double-checked?

**Comment by Kaveh01** [comment]
Yes, it worked smoothly.
