### ISSUE TITLE
[HIPIFY] A valid CUDA code cannot be hipified with hipify-clang.  

### ISSUE THREAD

**Issue by Kaveh01** [ROCm-Developer-Tools/HIP#1427]
I am not sure if I should call this an nvcc issue or a hipify-clang problem. 
A valid CUDA code cannot be hipified with hipify-clang due to an error in the semantic analysis step:

```
$ cat test.cpp
int a()
{
  int b = min (2,3);
  return b*10;
}
```
```
$ nvcc -c test.cu
$ ls
test.cu  test.o
```

```
$ hipify-clang test.cu -- -x cuda --cuda-path=$CUDA_PATH 
/tmp/test.cu-4d2dd9.hip:3:11: error: no matching function for call to 'min'
  int b = min (2,3);
          ^~~
/home/k/software/cuda/9.0//include/device_functions.hpp:434:38: note: candidate function not viable: call to
      __device__ function from __host__ function
__DEVICE_FUNCTIONS_STATIC_DECL__ int min(int x, int y)
```

**Comment by emankov** [comment]
AFAIK, that is a known problem in clang, which "supports" only __device__ functions, whereas CUDA has its own __host__ functions implementation. I'm not sure whether to escalate this discrepancy in clang community or to implement in hipify-clang a conversion to STL analogues, for instance.
