### ISSUE TITLE
tccDriver is missing in hipDeviceProp_t

### ISSUE THREAD

**Issue by Kaveh01** [ROCm-Developer-Tools/HIP#1433]
tccDriver is missing in hipDeviceProp_t. It is obviously important only on Nvidia machines and I can use cudaDeviceProp instead with conditional compilation but it would be better if we had that in hipDeviceProp_t.

```
#include <hip/hip_runtime.h>
#include<stdio.h>
int main()
{
	hipDeviceProp_t deviceProp;
	hipGetDeviceProperties(&deviceProp, 0);
	int a = deviceProp.tccDriver;
	printf ("%d\n",a);
return 0;
}
```
The error: 
```
$ hipcc test.c
test.c(7): error: class "hipDeviceProp_t" has no member "tccDriver"

1 error detected in the compilation of "/tmp/tmpxft_00007587_00000000-8_test.cpp1.ii".
```

**Comment by SarbojitAMD** [comment]
Raised PR https://github.com/ROCm-Developer-Tools/HIP/pull/1434/files
