### ISSUE TITLE
[HIPIFY] hipify-clang and hipify-perl are not adding "reinterpret_cast" for hipFuncSetCacheConfig.

### ISSUE THREAD

**Issue by Kaveh01** [ROCm-Developer-Tools/HIP#1439]
hipify-clang and hipify-perl are not adding "reinterpret_cast" for hipFuncSetCacheConfig.
Original CUDA code:

```
#include <cuda.h>
__global__ void myKernel()
{
int a=0;
}
int main()
{
         cudaFuncSetCacheConfig(myKernel,cudaFuncCachePreferEqual);
return 0;
}
```
Hipified code:
```
#include <hip/hip_runtime.h>
__global__ void myKernel()
{
int a=0;
}

int main()
{

         hipFuncSetCacheConfig( myKernel,hipFuncCachePreferEqual);
return 0;
}
```
Working code:
#include <hip/hip_runtime.h>
__global__ void myKernel()
{
int a=0;
}

int main()
{
         hipFuncSetCacheConfig(reinterpret_cast<const void*>(myKernel), hipFuncCachePreferEqual);
return 0;
}

**Comment by Kaveh01** [comment]
I guess we have the same problem for hipFuncGetAttributes.

**Comment by emankov** [comment]
Implemented in hipify-clang, please check on your side.

**Comment by Kaveh01** [comment]
It works smoothly. Thanks.

**Comment by emankov** [comment]
Implemented in hipify-perl too, please check on your side.

**Comment by Kaveh01** [comment]
Thanks. It works well.
