### ISSUE TITLE
[HIP] cudaMemcpy2DFromArray implementation [question]

### ISSUE THREAD

**Issue by natowi** [ROCm-Developer-Tools/HIP#1466]
We have tried HIP one year ago to port the alicevision cuda code (for photogrammetry), but at the time, numerous functions were not supported (https://github.com/alicevision/AliceVision/issues/439#issuecomment-417422887). 

Now only _cudaMemcpy2DFromArray_ is not supported. (Good work!)

Can we expect _hipMemcpy2DFromArray_ support in the near future? This would be awesome, as a cuda alternative is highly anticipated by [Alicevision/Meshroom](https://alicevision.org/#meshroom) users.

**Comment by natowi** [comment]
@emankov?

**Comment by emankov** [comment]
@bensander, @mangupta, `cudaMemcpy2DToArray` has been implemented a long ago, what keeps us apart from implementing the rest of Memcpy2D functions for arrays, including `cudaMemcpy2DFromArray`, which is asked from time to time?

**Comment by gargrahul** [comment]
hipMemcpy2DFromArray are getting supported with #1510. hipMemcpy2DToArray needs some fixes too- will be done in a separate PR.

**Comment by natowi** [comment]
Thanks for merging PR1510, however hipconvertinplace-perl.sh still says "warning: unconverted cudaMemcpy2DFromArray : 2" - am I missing something?

**Comment by emankov** [comment]
@natowi, I'll sync hipify-clang and hipify-perl accordingly.

**Comment by natowi** [comment]
Thanks a lot.

**Comment by emankov** [comment]
@natowi and all, hipify-clang and hipify-perl are synced (#1599).
