### ISSUE TITLE
Metal backend for iOS ?

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#150]
Is there interest in using HIP to cross-compile CUDA to metal on iOS ?

This sort of thing was done last year by Otoy:

https://vrworld.com/2016/03/11/otoy-ported-cuda-non-nvidia-hardware/

**Comment by adityaatluri** [comment]
If Metal is single source language (just like CUDA), it would have been feasible. But, it uses similar model to Vulkan and OpenCL.

**Comment by boxerab** [comment]
If metal code was put in its own file, would it then be possible to do this  with HIP ?

**Comment by bensander** [comment]
Unfortunately not currently possible.  We have looked at supporting HIP on other OS including MacOS but no concrete plans.

**Comment by boxerab** [comment]
Thanks. I guess I will close this.

**Comment by rfbird** [comment]
Any update on this?

**Comment by trsh** [comment]
HIP would be a killer, if added macos support
