### ISSUE TITLE
3DTexture not work correctely

### ISSUE THREAD

**Issue by geostartongxl** [ROCm-Developer-Tools/HIP#1505]
I have try to port some cuda code to hip. When I port 3DTexuter code, tex3d fentch function not work correctly.
  here is example code:
  
#include "hip/hip_runtime.h"
#define hutilSafeCall(err)           __checkhipErrors (err, __FILE__, __LINE__)

#define HIPCHECK(error)                                                                            \
    if (error != hipSuccess) {                                                                     \
        printf("%serror: '%s'(%d) at %s:%d%s\n", KRED, hipGetErrorString(error), error, __FILE__,  \
               __LINE__, KNRM);                                                                    \
        failed("API returned error code.");                                                        \
    }
inline void __checkhipErrors(hipError_t err, const char *file, const int line)
{
        if (hipSuccess != err)
        {
                fprintf(stdout, "%s(%i) : hip Runtime API error %d: %s.\n",
                file, line, (int)err, hipGetErrorString(err));
                exit(-1);
        }
}
typedef struct {
float v;
float x;
float y;
float z;
} velst;

__global__ void
veldump (float *wot, int ntabs, int nouts,velst *vst);
texture < float, 3, hipReadModeElementType > vel_tex;
int main(int argc,char **argv)
{
int nz,nx,ny;
int iy,ix,iz;
nz=10,nx=10,ny=10;
float *vels,*hipvels;
velst *vst,*hipvst;

hipArray *vel_array;
vels=(float*)malloc(sizeof(float)*nx*nx*ny);
vst=(velst*)malloc(sizeof(velst)*nx*nx*ny);
hipMalloc((void **) &hipvst, sizeof (float) * nx*ny*nz);
hipMalloc((void **) &hipvels, sizeof (velst) * nx*ny*nz);

//fill vels
for(iz=0;iz<nz;iz++)
for(ix=0;ix<nx;ix++)
for(iy=0;iy<ny;iy++)
{
//vels[iy*nx*nz+ix*nz+iz]=ix*10+iz;
vels[iz*nx*ny+ix*ny+iy]=ix*10+iy;
}
 hipExtent vel_volumeSize = make_hipExtent (nz, nx, ny); 
          hipChannelFormatDesc channelDesc =
               hipCreateChannelDesc < float >();
/*HIP_ARRAY3D_DESCRIPTOR desc;
	desc.Format=HIP_AD_FORMAT_FLOAT;
	desc.NumChannels=1;
	desc.Width=nz;
	desc.Height=nx;
	desc.Depth=ny;
 hipArray3DCreate(&vel_array, &desc);*/
          hutilSafeCall (hipMalloc3DArray
                          (&vel_array, &channelDesc, vel_volumeSize,hipArrayDefault));
    vel_tex.normalized=false;
          vel_tex.filterMode = hipFilterModeLinear;
          vel_tex.addressMode[0] = hipAddressModeClamp;
          vel_tex.addressMode[1] = hipAddressModeClamp;
          vel_tex.addressMode[2] = hipAddressModeClamp;
          //vel_tex.addressMode[0] = hipAddressModeWrap;
          //vel_tex.addressMode[1] = hipAddressModeWrap;
         // vel_tex.addressMode[2] = hipAddressModeWrap;
        vel_tex.channelDesc.x=32;
//copy vel data to 3d Array
          hipMemcpy3DParms copyParams = {
            0
          };
         copyParams.extent = vel_volumeSize;
          copyParams.kind = hipMemcpyHostToDevice;
//vels
int nn1=10,nn2=10,nn3=10;
          copyParams.srcPtr =
            make_hipPitchedPtr ((void *) vels, nz*sizeof(float) , nz,
                                 nx);
          copyParams.dstArray = vel_array;
          hutilSafeCall (hipMemcpy3D (&copyParams));
    hutilSafeCall (hipBindTextureToArray
                          (vel_tex, vel_array, channelDesc));
dim3 ngrid = nx;
              ngrid.y = ny;
              dim3 nblk = 128;
hipLaunchKernelGGL(veldump,ngrid,nblk,0,0,hipvels,nz,nz,hipvst);
//hipMemcpy (vels, hipvels, nx*ny*nz * sizeof (float),
 //                 hipMemcpyDeviceToHost);
hipMemcpy (vst, hipvst, nx*ny*nz * sizeof (velst),
                  hipMemcpyDeviceToHost);

free(vels);
free(vst);
hipFree(hipvels);
free(vst);
hipFreeArray(vel_array);
return 0;
}
__global__ void
veldump (float *wot, int ntabs, int nouts,velst *vst)
{
  int count1;
  const int thid = hipThreadIdx_x;
  const int blkidx = hipBlockIdx_x;
  const int blkidy = hipBlockIdx_y;
  const int blkidg = hipBlockIdx_y * hipGridDim_x + hipBlockIdx_x;
  for (count1 = thid; count1 < nouts; count1 = count1 + hipBlockDim_x)
    {

          float cv = (float) (count1) / (float) nouts * float (ntabs);
          wot[blkidg * nouts + count1 ] =
              tex3D (vel_tex, cv+0.5, (float) blkidx+0.5, (float) blkidy+0.5);
          vst[blkidg * nouts + count1 ].v = wot[blkidg * nouts + count1];
          vst[blkidg * nouts + count1 ].z = cv+0.5;
          vst[blkidg * nouts + count1 ].x = blkidx+0.5;
          vst[blkidg * nouts + count1 ].y = blkidy+0.5;
    }

}

only first 10 from vst[0]-vst[9] work correctly. vst[10].v become 32, should be 10. this code 
works fine on cuda. I hade exime rocm source code , check Memcpy3D and tex3d function
is there any thing wrong with __ockl_image_sample_3d?

**Comment by gargrahul** [comment]
@geostartongxl Could you try with #1415 ?

**Comment by geostartongxl** [comment]
> @geostartongxl Could you try with #1415 ?

i already update to leatest version rocm 2.9 ,still not work.

**Comment by gargrahul** [comment]
> 
> 
> > @geostartongxl Could you try with #1415 ?
> 
> i already update to leatest version rocm 2.9 ,still not work.

#1415 is not merged yet and it is not part of ROCm 2.9. You will need to build it locally to test it.

**Comment by geostartongxl** [comment]
> > > @geostartongxl Could you try with #1415 ?
> > 
> > 
> > i already update to leatest version rocm 2.9 ,still not work.
> 
> #1415 is not merged yet and it is not part of ROCm 2.9. You will need to build it locally to test it.

Thank ill try

**Comment by geostartongxl** [comment]
> > > @geostartongxl Could you try with #1415 ?
> > 
> > 
> > i already update to leatest version rocm 2.9 ,still not work.
Thanks alot ,this PR work well
There still another when i add hipUnbindTexure statement
clang-10: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
/tmp/tex3d-0bf7a4.o: In function `hipError_t hipUnbindTexture<float, 3, (hipTextureReadMode)0>(texture<float, 3, (hipTextureReadMode)0>&)':
/opt/rocm/include/hip/hcc_detail/hip_runtime_api.h:3241: undefined reference to `ihipUnbindTextureImpl(__hip_texture* const&)'
it's looks like the ihipUnbindTextureImpl function should be modified to make this work correctly
> 
> #1415 is not merged yet and it is not part of ROCm 2.9. You will need to build it locally to test it.

**Comment by ansurya** [comment]
Fixed as part of PR #1415 .
