### ISSUE TITLE
hipUbindTexture can't link correctly when link

### ISSUE THREAD

**Issue by geostartongxl** [ROCm-Developer-Tools/HIP#1506]
When call function hipUnbindTexture, hcc complain about 
/tmp/tex3d-f8e3d0.o: In function `hipError_t hipUnbindTexture<float, 3, (hipTextureReadMode)0>(texture<float, 3, (hipTextureReadMode)0>&)':
/usr/local/include/hip/hcc_detail/hip_runtime_api.h:3273: undefined reference to `ihipUnbindTextureImpl(__hip_texture* const&)'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
it seemed ihipUnbindTextureImpl should be modified to match declaration in include fle of hip_runtime_api.h?
any fix?

**Comment by geostartongxl** [comment]
fixed by change function in src/hip_tex.cpp
hipError_t ihipUnbindTextureImpl(const hipTextureObject_t& textureObject) {
    hipError_t hip_status = hipSuccess;
TlsData* tls=tls_get_ptr();
    auto ctx = ihipGetTlsDefaultCtx();
    if (ctx) {
        hc::accelerator acc = ctx->getDevice()->_acc;
        auto device = ctx->getWriteableDevice();

        hsa_agent_t* agent = static_cast<hsa_agent_t*>(acc.get_hsa_agent());

        hipTexture* pTexture = textureHash[textureObject];
        if (pTexture != nullptr) {
            hsa_ext_image_destroy(*agent, pTexture->image);
            hsa_ext_sampler_destroy(*agent, pTexture->sampler);
            free(pTexture);
            textureHash.erase(textureObject);
        }
    }

    return hip_status;
}

**Comment by gargrahul** [comment]
Fixed via #1515.
