### ISSUE TITLE
Does HIP support MPI

### ISSUE THREAD

**Issue by merlinzone** [ROCm-Developer-Tools/HIP#151]
Does HIP support MPI or hip-aware-mpi?
https://devblogs.nvidia.com/parallelforall/introduction-cuda-aware-mpi/

**Comment by gargrahul** [comment]
@merlinzone Yes, it should. Please share further details if you are seeing any issues.

**Comment by andrewcorrigan** [comment]
Is there an API available to detect support?   With CUDA, I have a check like the following to detect CUDA-aware MPI.    What would the equivalent be for detecting HIP-aware MPI?
```
#if defined(MPIX_CUDA_AWARE_SUPPORT) && MPIX_CUDA_AWARE_SUPPORT
    if(MPIX_Query_cuda_support() == 1)
    {
        std::cout << "Detected CUDA-Aware MPI" << std::endl;
    }
    else
#endif
    {
        std::cout << "CUDA-Aware MPI is not supported" << std::endl;
    }
```

Sorry if this is obvious,[ I see extensive documentation on how to do this for CUDA](https://www.open-mpi.org/faq/?category=runcuda), but am struggling to find information for HIP.

**Comment by andrewcorrigan** [comment]
Just checking in if there is any API available for detecting HIP-aware MPI?
