### ISSUE TITLE
Build issue with cmake 3.15.4

### ISSUE THREAD

**Issue by malcolmroberts** [ROCm-Developer-Tools/HIP#1521]
When I try to compile rocFFT with cmake 3.5.14 I get the following error:
```
cmake -DCMAKE_CXX_COMPILER=hcc  ..
-- The CXX compiler identification is Clang 10.0.0
-- Check for working CXX compiler: /opt/rocm/hcc/bin/hcc
-- Check for working CXX compiler: /opt/rocm/hcc/bin/hcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HCC compiler set; ROCm backend selected [ CXX=/opt/rocm/bin/hcc cmake ... ]
-- Building with ROCm tools
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at /opt/rocm/hcc/lib/cmake/hcc/hcc-config.cmake:41 (add_library):
  add_library cannot create imported target "hsa-runtime64" because another
  target with the same name already exists.
Call Stack (most recent call first):
  /home/<USERNAME>/cmake/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/rocm/hip/lib/cmake/hip/hip-config.cmake:77 (find_dependency)
  CMakeLists.txt:151 (find_package)


-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring incomplete, errors occurred!
See also "/home/<USERNAME>/repo/rocfft/d/CMakeFiles/CMakeOutput.log".
```
Using the system cmake (3.10.2), there's no issue.

**Comment by acowley** [comment]
I had the same problem when updating [nixos-rocm](https://github.com/nixos-rocm/nixos-rocm) for ROCm 2.9, so in [this commit](https://github.com/acowley/nixos-rocm/commit/eaf98cf7976dcd5dce55b45c1d6301dc6a8a7293) I added a [patch](https://github.com/acowley/nixos-rocm/blob/eaf98cf7976dcd5dce55b45c1d6301dc6a8a7293/pkgs/development/compilers/hcc/hcc-config-hsa.patch) to guard the creation of the target. It seems to be doing the trick. I can open a PR, but they're usually ignored so if you have a way of incorporating a patch yourself that would be the quickest path forward.

**Comment by malcolmroberts** [comment]
@acowley ; you don't have a minimal working example, by chance?

**Comment by acowley** [comment]
@malcolmroberts I'm not sure which part to expand upon. If you apply the linked patch to the `hcc` sources when building that, you won't see the error you pasted when building `rocFFT`.

**Comment by malcolmroberts** [comment]
Sorry, are you saying that you have a patch for rocFFT, or for HIP?

**Comment by malcolmroberts** [comment]
Either way; please submit a PR!

**Comment by acowley** [comment]
@malcolmroberts It's an issue with `hcc`, which the current/legacy `HIP` uses as a back-end compiler. I've opened the PR.

**Comment by gargrahul** [comment]
Not a HIP issue. Required PRs have been submitted in HCC.
