### ISSUE TITLE
[HIPIFY] hipify-clang and hipify-perl translate "warpSize" to hipWarpSize

### ISSUE THREAD

**Issue by Kaveh01** [ROCm-Developer-Tools/HIP#1569]
hipify-clang and hipify-perl translate "warpSize" to "hipWarpSize":

```
$ cat test.cu 
#include <stdio.h>
#include <cuda.h>
int test()
{
	int a=warpSize;
	return a;
}
```
but hipcc cannot compile the hipified code:
```
$ cat test.c 
#include <stdio.h>
#include <hip/hip_runtime.h>
int test()
{
	int a=hipWarpSize;
	return a;
}
hipcc -c test.c 
test.c(5): error: identifier "hipWarpSize" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00003dbe_00000000-6_test.cpp1.ii".

```
worth to mention, "WarpSize" works on both Nvidia and AMD machines.

**Comment by Kaveh01** [comment]
After the last commit "76c84064498523a8faf2708a428b7e38562a8180"  hipify-clang goes to $HIP_ROOT instead of $HIP_ROOT/bin when I install that.

**Comment by Kaveh01** [comment]
It actually works like this since commit  f19e7c29dfcef3d0c941c977ce6d1448ad4e288a

**Comment by emankov** [comment]
> After the last commit "76c84064498523a8faf2708a428b7e38562a8180" hipify-clang goes to $HIP_ROOT instead of $HIP_ROOT/bin when I install that.

1. It is another unrelated issue, right?
2. Do you need previous behaviour (when CMAKE_INSTALL_PREFIX is undefined)? Could you, please, open a new ticket?

**Comment by emankov** [comment]
Yet another question.

Why `$HIP_ROOT`? Are you building hipify-clang as a part of HIP?

**Comment by Kaveh01** [comment]
The issue fixed for hipify-perl but hipify-clang terminates with this error:

```
$ ~/software/hip/hipify-clang test.cu -- -x cuda --cuda-path=$CUDA_PATH
In file included from <built-in>:1:
In file included from /home/kaveh/software/hip/include/__clang_cuda_runtime_wrapper.h:36:
/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cmath:537:3: error: constexpr function 'fpclassify' without __host__ or __device__ attributes cannot overload __device__ function with same signature.  Add a __host__ attribute, or build with -fno-cuda-host-device-constexpr.
  fpclassify(float __x)
```

**Comment by Kaveh01** [comment]
> Yet another question.
> 
> Why `$HIP_ROOT`? Are you building hipify-clang as a part of HIP?

Yes, I build that as a part of HIP. $HIP_ROOT is just env to specify the installation path.  I am going to open another issue for this.

**Comment by emankov** [comment]
> The issue fixed for hipify-perl but hipify-clang terminates with this error:

It looks like a different issue. It is no related to warpSize.

**Comment by Kaveh01** [comment]
> > The issue fixed for hipify-perl but hipify-clang terminates with this error:
> 
> It looks like a different issue. It is no related to warpSize.

Correct
