### ISSUE TITLE
nvtx api port question 

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#1638]
Could you please advise on porting NVTX API functions(e.g., nvtxRangeStartA) to HIP ? An example is the CUDA miniFE application.

Thanks

**Comment by gargrahul** [comment]
Please check https://github.com/ROCm-Developer-Tools/roctracer for more details on rocTX (equivalent to NVTX). 

https://github.com/ROCm-Developer-Tools/roctracer/blob/amd-master/test/MatrixTranspose_test/MatrixTranspose.cpp#L127
