### ISSUE TITLE
[HIPIFY] File extension '.C' recognition

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#1649]
It seems that the file extension '.C' is not recognized by the hip toolchain to examine the CUDA APIs.

**Comment by emankov** [comment]
Do you mean `hipify-clang -examine` or what?

**Comment by zjin-lcf** [comment]
I tried hipexamine-perf.sh

**Comment by emankov** [comment]
Both `hipexamine-perl` and `hipexamine` supports `*.c` extension. Could you please be more concrete: provide your usecase.

**Comment by emankov** [comment]
Ping

**Comment by emankov** [comment]
Closing it as "not a bug" after double-checking.
