### ISSUE TITLE
hipGetDeviceCount returns 0 (no device)

### ISSUE THREAD

**Issue by G-Ragghianti** [ROCm-Developer-Tools/HIP#1721]
I have a short test of hipGetDeviceCount() that returns zero devices with error 1038:

#include <iostream>
#include <hip/hip_runtime.h>

int main(){
  int ndevs = 0;
  int code = hipGetDeviceCount(&ndevs);
  printf("%i %i\n", code, ndevs);
  return 2;
}

This system has an Radeon Instinct MI25 and it is reported by rocm-smi:

ROCm System Management Interface
GPU  Temp   AvgPwr  SCLK     MCLK    Fan   Perf  PwrCap  VRAM%  GPU%  
1    28.0c  7.0W    1269Mhz  167Mhz  0.0%  auto  220.0W    0%   0%    
2    38.0c  10.0W   1269Mhz  945Mhz  0.0%  auto  220.0W    0%   0%    

Where should I look for possible reasons that hipGetDeviceCount() doesn't see these devices?

**Comment by gargrahul** [comment]
@G-Ragghianti Could you try running rocminfo and see if there is any GPU device listed in output ?

**Comment by G-Ragghianti** [comment]
OK, I'm making progress.  I realized that I needed to either be in the video group or root.  Once I did that, the system now reboots when I run rocminfo or the above code.

**Comment by SarbojitAMD** [comment]
@G-Ragghianti, do you still see the issue? Please update the issue and close if it is no longer seen

**Comment by G-Ragghianti** [comment]
The issue is resolved.  It was a hardware problem. Thanks.

**Comment by jsboer** [comment]
> The issue is resolved. It was a hardware problem. Thanks.

HI, I meet the same error. What is the hardware problem?
