### ISSUE TITLE
[Hipcc bug] Wrong target code generation from a correct source

### ISSUE THREAD

**Issue by ghostplant** [ROCm-Developer-Tools/HIP#1745]
[my_kernel.cu.txt](https://github.com/ROCm-Developer-Tools/HIP/files/3971217/my_kernel.cu.txt)

The attachment contains a very basic example, which is correctly executed on CUDA, but get wrong results on ROCM 2.10. Please check it.

**Comment by SarbojitAMD** [comment]
@ghostplant, Currently hcc compiler assumes optimal block size is 256 and it does code optimization with the same assumption which may result in different output in some cases especially where the block size is greater than 256. Assuming a higher number (>256) will create a resource crunch which will impact performance hence it is suggested to the programmers to set __launch_bounds__(<max_block_size>) if (s)he knows that block size is going to be greater than 256.
E.g. In this case if you set I could see the expected output.
extern "C" __global__ **__launch_bounds__(1024)** void template_op_kernel0( float* __restrict__ output.......)
  {
}

Closing the issue now feel free to open in case it does not help at your end.
