### ISSUE TITLE
[HIPIFY] Support for cuBLAS -> hipBLAS/rocBLAS

### ISSUE THREAD

**Issue by VincentSC** [ROCm-Developer-Tools/HIP#1752]
When will there be support for cuBLAS -> hipBLAS?

**Comment by VincentSC** [comment]
Seems there is partial support. The hipify reporting gave supported for cublasCreate, cublasDasum, cublasDaxpy, cublasDcopy, cublasDdot, cublasDestroy, cublasDgemm, cublasDgemv, cublasDger, cublasDiagType_t, cublasDnrm2, cublasDscal, cublasDtrsm, cublasFillMode_t, cublasGetMatrix, cublasGetVector, cublasHandle_t, cublasIdamax, cublasIsamax, cublasOperation_t1, cublasSasum, cublasSaxpy, cublasScopy, cublasSdot, cublasSetMatrix, cublasSetVector19, cublasSgemm, cublasSgemv, cublasSger, cublasSideMode_t, cublasSnrm2, cublasSscal, cublasStatus, cublasStatus_t and cublasStrsm.

We got "unsupported" in the hipify-report for at least these functions: cublasAlloc, cublasCaxpy, cublasCcopy, cublasCdotc, cublasCdotu, cublasCgbmv, cublasCgemm, cublasCgemv, cublasCgerc, cublasCgeru, cublasChbmv, cublasChemm, cublasChemv, cublasCher, cublasCher2, cublasCher2k, cublasCherk, cublasChpmv, cublasChpr, cublasChpr2, cublasCrot, cublasCrotg, cublasCscal, cublasCsrot, cublasCsscal, cublasCswap, cublasCsymm, cublasCsyr2k, cublasCsyrk, cublasCtbmv, cublasCtbsv, cublasCtpmv, cublasCtpsv, cublasCtrmm, cublasCtrmv, cublasCtrsm, cublasCtrsv, cublasDgbmv, cublasDrot, cublasDrotg, cublasDrotm, cublasDrotmg, cublasDsbmv, cublasDspmv, cublasDspr, cublasDspr2, cublasDswap, cublasDsymm, cublasDsymv, cublasDsyr, cublasDsyr2, cublasDsyr2k, cublasDsyrk, cublasDtbmv, cublasDtbsv, cublasDtpmv, cublasDtpsv, cublasDtrmm, cublasDtrmv, cublasDtrsv, cublasDzasum, cublasDznrm2, cublasFree, cublasGetError, cublasIcamax, cublasIcamin, cublasIdamin, cublasInit, cublasIsamin, cublasIzamax, cublasIzamin, cublasScasum, cublasScnrm2, cublasSgbmv, cublasShutdown, cublasSrot, cublasSrotg, cublasSrotm, cublasSrotmg, cublasSsbmv, cublasSspmv, cublasSspr, cublasSspr2, cublasSswap, cublasSsymm, cublasSsymv, cublasSsyr, cublasSsyr2, cublasSsyr2k, cublasSsyrk, cublasStbmv, cublasStbsv, cublasStpmv, cublasStpsv, cublasStrmm, cublasStrmv, cublasStrsv, cublasXerbla, cublasZaxpy, cublasZcopy, cublasZdotc, cublasZdotu, cublasZdrot, cublasZdscal, cublasZgbmv, cublasZgemm, cublasZgemv, cublasZgerc, cublasZgeru, cublasZhbmv, cublasZhemm, cublasZhemv, cublasZher, cublasZher2, cublasZher2k, cublasZherk, cublasZhpmv, cublasZhpr, cublasZhpr2, cublasZrot, cublasZrotg, cublasZscal, cublasZswap, cublasZsymm, cublasZsyr2k, cublasZsyrk, cublasZtbmv, cublasZtbsv, cublasZtpmv, cublasZtpsv, cublasZtrmm, cublasZtrmv, cublasZtrsm and cublasZtrsv. If I look at https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/CUBLAS_API_supported_by_HIP.md then I see there actually is support for a part of this list. so there might be another problem, like the reporting not being correct.

**Comment by emankov** [comment]
Hi @VincentSC, 

What you mean by "there might be another problem, like the reporting not being correct."?

**Comment by emankov** [comment]
Do you use the latest hipify-clang (hipify-perl)? A couple of weeks ago there was sync between hipify/hipBLAS/roc_blas and markdown docs ([1736](https://github.com/ROCm-Developer-Tools/HIP/pull/1736)). 

Btw, docs are always synced with hipify.

**Comment by emankov** [comment]
Ping!
