### ISSUE TITLE
building HIP with HIP_PLATFORM set to nvcc will not build anything

### ISSUE THREAD

**Issue by alexschroeter** [ROCm-Developer-Tools/HIP#1760]
Hello everybody,

I noticed that building HIP with HIP_PLATFORM=nvcc doesn't build anything. If there is a reason for this I fail to see it but than at least some warning or error message should appear. Currently cmake builds successfully and make does nothing with HIP_PLATFORM=nvcc.

**Current behavior:**
_$:~/HIP/build$ HIP_PLATFORM=nvcc_
_$:~/HIP/build$ cmake .._
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HIP Platform: **nvcc**
-- HIP Compiler: hcc
-- HIP will be installed in: /opt/rocm/hip
-- Generating profiling promitives: /home/aschroeter/HIP/include/hip/hcc_detail/hip_prof_str.h
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyToSymbolAsync
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyFromSymbolAsync
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyFromSymbol
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: __hipPushCallConfiguration
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipGetSymbolAddress
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipGetSymbolSize
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipExtLaunchMultiKernelMultiDevice
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyToSymbol
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: __hipPopCallConfiguration
/home/aschroeter/HIP/hip_prof_gen.py Warning: 9 API calls missing in interception layer
CMake Deprecation Warning at CMakeLists.txt:492 (cmake_policy):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Testing targets will not be available. To enable them please ensure that the HIP installation directory is writeable. Use -DCMAKE_INSTALL_PREFIX to specify a suitable location
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aschroeter/HIP/build

_$:~/HIP/build$ make_ 
make does nothing 

**Expected behavior:**
no matter which value HIP_PLATFORM is set to HIP should build.

_$:~/HIP/build$ HIP_PLATFORM=hcc_

_$:~/HIP/build$ cmake .._
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HIP Platform: **hcc**
-- HIP Compiler: hcc
-- Looking for HCC in: /opt/rocm/hcc. Found version: 2.10.19446-7ffdb8b-ff0b0f5-6c4a046
-- Looking for HSA runtime in: /opt/rocm/hsa
-- HIP will be installed in: /opt/rocm/hip
-- Generating profiling promitives: /home/aschroeter/HIP/include/hip/hcc_detail/hip_prof_str.h
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyToSymbolAsync
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyFromSymbolAsync
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyFromSymbol
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: __hipPushCallConfiguration
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipGetSymbolAddress
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipGetSymbolSize
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipExtLaunchMultiKernelMultiDevice
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: hipMemcpyToSymbol
/home/aschroeter/HIP/hip_prof_gen.py Warning: implementation not found: __hipPopCallConfiguration
/home/aschroeter/HIP/hip_prof_gen.py Warning: 9 API calls missing in interception layer
-- Code Object Manager found at /opt/rocm/lib/cmake/amd_comgr.
CMake Deprecation Warning at CMakeLists.txt:492 (cmake_policy):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Testing targets will not be available. To enable them please ensure that the HIP installation directory is writeable. Use -DCMAKE_INSTALL_PREFIX to specify a suitable location
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aschroeter/HIP/build

_$:~/HIP/build$ make_ 
make builds as expected

Happy Holidays

**Comment by SarbojitAMD** [comment]
For nvcc, HIP does not need to get built as all CUDA codes are in the header file hence 'make' not doing anything for HIP_PLATFORM=nvcc is justified. 
I would happy to help if you see any issue on nvcc platform hence expected HIP to be built on irrespective of HIP/NVCC.

**Comment by SarbojitAMD** [comment]
@alexschroeter,
Did not hear back anything from you. Let me know if you see any issue with nvcc hence expected 'make' to build hip source.

**Comment by SarbojitAMD** [comment]
@alexschroeter, I am closing this ticket as I don't think anything needs to be done here until you mention if you see any error. Feel free to reopen it in case you any further help

**Comment by alexschroeter** [comment]
@SarbojitAMD Sorry for the long delay I had very much work to do after the break. I now understand why you don't want it to build for nvcc. I still think a message why nothing is happening would be beneficial for users but I also think this post can be found and will provide the answers.

Thank you
