### ISSUE TITLE
[HIP] CUDA identifier is unsupported in HIP.

### ISSUE THREAD

**Issue by NAThompson** [ROCm-Developer-Tools/HIP#1783]
I don't know whether this should be a github issue or not, but what is the policy on unimplemented CUDA identifiers in HIP?

Here are a few which I've encountered:

```
 warning: CUDA identifier is unsupported in HIP:
   cudaMemoryTypeManaged,
   cudaMemAdvise,
   cudaMemAdviseSetAccessedBy,
   cudaCpuDeviceId,
   cudaMemPrefetchAsync,
   cudaStreamPerThread,
   cudaLimitStackSize
```

Are these on the roadmap?

Also, if these do not make it into `hipify-clang`, do they have a natural translation into hip?

**Comment by emankov** [comment]
`cudaMemoryTypeManaged` is of CUDA 10.0; thus, I believe it is not of the first priority.

@mangupta, @gargrahul, 
what about the rest, which all are of CUDA 8.0 or even older? 

I'm also interested in the functions `cudaMemAdvise` / `cuMemAdvise` with the corresponding data types `cudaMemoryAdvise` / `CUmem_advise`.

**Comment by SarbojitAMD** [comment]
Closing this ticket as all mentioned unsupported cuda identifiers are implemented in HIP now.
