### ISSUE TITLE
Every link in 6_dynamic_shared/Readme.md is broken

### ISSUE THREAD

**Issue by JonChesterfield** [ROCm-Developer-Tools/HIP#1822]
Specifically, HIP/samples/2_Cookbook/6_dynamic_shared/Readme.md
All links under more info return 'not found'

A brief random walk suggests most, but not quite all, links under samples are broken. One at the top level resolves successfully to http://rocm-developer-tools.github.io/HIP

**Comment by gargrahul** [comment]
@JonChesterfield Thanks for reporting. #1824 should fix the links for now.

**Comment by JonChesterfield** [comment]
The patch has fixed two of the eight links on that example. I haven't checked any others.

**Comment by SarbojitAMD** [comment]
This is fixed hence closing the ticket.
