### ISSUE TITLE
hipMemcpyToSymbol is giving hipErrorInvalidSymbol error.

### ISSUE THREAD

**Issue by chinchoretej** [ROCm-Developer-Tools/HIP#1837]
Hi,
I'm trying to hipify app. At the time of running the app I'm getting following error:

 **hip-api pid:23545 tid:1.13 hipMemcpyToSymbol  ret=701 (hipErrorInvalidSymbol)>> +11350 ns**

Steps to Reproduce:
**1. test.cpp**

```
#include <iostream>
#include "hip/hip_runtime.h"
__constant__ int Sd[10];
int main(){
    float Sd[100];
    hipError_t e;
    int S[10]={1,2,3,4,5,6,7,8,9,0};
    e = hipMemcpyToSymbol(HIP_SYMBOL(Sd),S,10*sizeof(int),0, hipMemcpyHostToDevice);
    return 0;
}
```

**2. hipcc test.cpp -o test**
**3. HIP_TRACE_API=1 ./test**

Thanks.

**Comment by SarbojitAMD** [comment]
@chinchoretej 
I think couple of things are missing here 
1. "__constant__ int Sd[10];" should be "**__device__** __constant__ int Sd[10];" 
    Remember API would look for device symbols which needs to be mentioned else compiler would not know 'Sd' would be on device.

2. As part of optimization if compiler will see global device variable is not used anywhere it would delete it hence adding one simple kernel e.g. 
__global__ void kernel()
{
   Sd[0] = 12;
}
forced compiler not to remove the variable and test ran without any error. 

Closing it as not bug open if you disagree :). Feel free to reach out in case of any further help.

**Comment by chinchoretej** [comment]
@SarbojitAMD  Thanks, It's working fine. I have created dummy kernel in that file.

**Comment by reguly** [comment]
@SarbojitAMD I would like to raise this again - I do believe this is a bug, the compiler should not optimize such a variable away, after all using it in hipMemcpyToSymbol still qualifies as using it (though I understand the difficulty of the compiler recognising this). At the very least an error or warning should be raised.
I have run into such cases, and that is how I found this issue - in our larger codebase it can easily happen that some global constant variables are not used in  particular compilation scenario.
