### ISSUE TITLE
hipModuleLoad is not threadsafe

### ISSUE THREAD

**Issue by jungwonkim** [ROCm-Developer-Tools/HIP#1846]
When more then one thread call hipModuleLoad() in parallel, it terminates with a segmentation fault.

**Comment by nwolfey21** [comment]
Hi @jungwonkim, do you have a simple reproducer you can share?

**Comment by pfultz2** [comment]
PR #1851 might fix this issue. It fixes a thread-safety issue in the `load_code_object_and_freeze_executable` function which the `hipModuleLoad` function uses as well.

**Comment by mangupta** [comment]
Fixed via #1851
