### ISSUE TITLE
Linking issue with mallocMC

### ISSUE THREAD

**Issue by saipavankalyan** [ROCm-Developer-Tools/HIP#1849]
I'm porting mallocMC (https://github.com/ComputationalRadiationPhysics/mallocMC) to ROCm.
Here is the attachment of  ported directory as a tar file [mallocMC.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/4165688/mallocMC.tar.gz)

**Steps followed for porting:**
Made appropriate changes in CMakeLists.txt to set correct paths and some minor changes in the actual code
mkdir build/
cd build/
cmake ..
Build files have been successfully generated
export HIP_PLATFORM=hipcc
cd ../examples
On compiling the example with this **command**
 hipcc mallocMC_example01.cpp -o mallocMC_example01 -I../src/include -I./ 
we are getting linking issue.

Below is the error log 
`/tmp/mallocMC_example01-3070fa.o: In function `run()':
mallocMC_example01.cpp:(.text+0x2dca): undefined reference to `mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> >::Allocator(mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> > const&)'
mallocMC_example01.cpp:(.text+0x2e95): undefined reference to `mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> >::Allocator(mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> > const&)'
mallocMC_example01.cpp:(.text+0x3136): undefined reference to `mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> >::Allocator(mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> > const&)'
mallocMC_example01.cpp:(.text+0x31ba): undefined reference to `mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> >::Allocator(mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> > const&)'
/tmp/mallocMC_example01-3070fa.o: In function `std::_Head_base<2ul, mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> >, false>::_Head_base<mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> > >(mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> >&&)':
mallocMC_example01.cpp:(.text+0x7bec): undefined reference to `mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> >::Allocator(mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> > const&)'
/tmp/mallocMC_example01-3070fa.o:mallocMC_example01.cpp:(.text+0xa27c): more undefined references to `mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> >::Allocator(mallocMC::Allocator<mallocMC::CreationPolicies::Scatter<ScatterHeapConfig, ScatterHashConfig>, mallocMC::DistributionPolicies::XMallocSIMD<XMallocConfig>, mallocMC::OOMPolicies::ReturnNull, mallocMC::ReservePoolPolicies::SimpleCudaMalloc, mallocMC::AlignmentPolicies::Shrink<ShrinkConfig> > const&)' follow
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Specifications:**
OS: Ubuntu 18.04.2
ROCm version: 3.0.6
HIP version: 3.0.19493-36529b1
HCC clang version 10.0.0 
cmake version 3.10.2

**Comment by psychocoderHPC** [comment]
@saipavankalyan  I ported mallocMC for PIConGPU already to HIP-clang. https://github.com/psychocoderHPC/picongpu/tree/topic-hip-amd-benachmark/thirdParty/mallocMC
I added all changes directly to our subtree.
My idea is not to ship a separate version for HIP instead I will use [cupla](https://github.com/ComputationalRadiationPhysics/cupla) so that we will support mallocMC for HIP/CUDA and CPU.

The mallocMC port I pointed to has no HIP search path in the cmake file because we are doing searching HIP already in the [alpaka camke](https://github.com/ComputationalRadiationPhysics/alpaka/blob/284eef5113c9518ee2be9c88696fe2cc2185e41b/alpakaConfig.cmake#L688-L879)

**Comment by psychocoderHPC** [comment]
@saipavankalyan I pushed my HIP port https://github.com/psychocoderHPC/mallocMC/tree/topic-hip-port and added your example changes. The command you showed worked with HIP-clang without linker issues. I used HIP-3.1 (self compiled) for my tests and did a runtime test on a Radeon VII.

**Comment by saipavankalyan** [comment]
@psychocoderHPC Thanks for the reply. Yes, when I compile using HIP-clang its working. Is it because of an issue with HIP-hcc that previously it was not working?

Can you please elaborate on how we can use alpaka instead of HIP to build mallocMC?

**Comment by psychocoderHPC** [comment]
I will try to fix my cmake for mallocMC next week first. Alpaka is currently not required for mallocMC but has already the cmake changes to setup cmake so that HIP will be found. IMO this will help you more. If you not use alpaka in your project than it will introduce a necessary dependency.

If you like to learn more about alpka please open an issue there and we can help you if needed.

Note: HIP-hcc is deprecated so you should IMO not waist time into optimizing the hcc code path. Use HIp-clang and/or HIP-nvcc.

**Comment by saipavankalyan** [comment]
Thanks for the help @psychocoderHPC!

**Comment by psychocoderHPC** [comment]
@saipavankalyan I updated https://github.com/psychocoderHPC/mallocMC/tree/topic-hip-port and added support for HIP-hcc. For HIP-hcc there is a workaround in that the heap will not be freed when the heap mallocMC heap object is destructed. Best is not to use HIP-hcc but I added support so that you can test mallocMC with the old compiler.

- HIP-nvcc
```
cmake ../mallocMC/ -D mallocMC_HIP_PLATFORM=nvcc
make -j examples
```

- HIP-clang
```
cmake ../mallocMC/ -D mallocMC_HIP_PLATFORM=clang
make -j examples
```

- HIP-hcc
```
cmake ../mallocMC/ -D mallocMC_HIP_PLATFORM=hcc
make -j examples
```

**Comment by saipavankalyan** [comment]
Yes @psychocoderHPC, now it is supporting all the backends. But the third example 'mallocMC_Example03' is failing as memory access fault both with HIP-clang and HIP-hcc.

Here is the error log for the same
Memory access fault by GPU node-2 (Agent handle: 0x72e100) on address 0x100000000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)

**Comment by psychocoderHPC** [comment]
@saipavankalyan Thanks for reporting. It could be that it is the function `x = mMC.getAvailableSlots(1);` which could create this issue. I would currently not investigate this bug deeper. 
If you have any problems in you real world application please open an issue in the [mallocMC repo](https://github.com/ComputationalRadiationPhysics/mallocMC) (even for HIP)

**Comment by psychocoderHPC** [comment]
Since the linker issue is solved you should close this issue and open a new issue for each topic.

**Comment by saipavankalyan** [comment]
Ok @psychocoderHPC . I will raise an issue there. Thank you 👍
