### ISSUE TITLE
questions on hipcc

### ISSUE THREAD

**Issue by guohaoqiang** [ROCm-Developer-Tools/HIP#190]
1、For a specific kernel, how can I get its .s file (assembly code)? And how can I convert the .s file into an executable file?
2、When I set environment variable KMDUMPISA, I got a .isa file (using hipcc complier). I found there is no correspond assembly code of clock() when I put the built-in function in a loop,
            for(...){
                    start = clock();
                           ...
                    end = clock();
            }

while I can get the assembly code of clock() if I put clock() out of a loop.
          start = clock();
          for(...){
                  ...
          }
end = clock();
Is this a bug of hipcc?

**Comment by guohaoqiang** [comment]
@bensander

**Comment by sunway513** [comment]
Hi Haoqiang,
To generate HSACO file that contains the assembly code:
$(HIPCC) --genco fool.cpp -o fool.hsaco
 
To load the hsaco file, you’ll need HIP module load APIs, see the following sample for referece:
https://github.com/ROCm-Developer-Tools/HIP/tree/dbe049937e727faf62b39ea5752b68ff8ff7f721/samples/0_Intro/module_api
 
To extract the ISA out of the hsaco file, you’ll need to:
/opt/rocm/bin/extractkernel -i fool.hsaco
The assembly code will be stored in fool-gfxXXX.isa file.
 
I don't think we support GPU kernel, can you use HIP event APIs or CPU wall time instead?

**Comment by masahi** [comment]
Hi @sunway513 ,
I was also looking to generate assembly code for HIP kernel.

When I do this,
$/opt/rocm/bin/hipcc --genco bit_extract.cpp bit_extract.hsaco

I got a lot of errors from the compiler, something like:
-------------------------------------------------------------------------------------------
In file included from bit_extract.cpp.kernel.tmp.cpp:27:
In file included from /opt/rocm/hcc/include/hc.hpp:22:
/opt/rocm/hcc/include/kalmar_math.h:364:15: error: declaration conflicts with target of using declaration already in scope
        float acosf(float x) { return __hc_acos(x); }
              ^
/opt/rocm/include/hip/hcc_detail/math_functions.h:30:18: note: target of using declaration
__device__ float acosf(float x);
                 ^
/opt/rocm/hcc/include/kalmar_math.h:300:17: note: using declaration
        using ::acosf;
--------------------------------------------------------------------------------------------

Simply passing -DGENERIC_GRID_LAUNCH=0 to the usual compile command also gives the same compiler error.
$ /opt/rocm/bin/hipcc -DGENERIC_GRID_LAUNCH=0  bit_extract.cpp -o bit_extract // same error messages above

Am I doing something wrong?

**Comment by masahi** [comment]
Oh, I was able to generate .hsaco file by moving the kernel code into its own .cpp file and then invoking hipcc --genco on it.

Ref: https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_kernel_language.md#kernel-compilation

Thanks!

**Comment by sunway513** [comment]
Thanks for the updates, and yes, you can only use `--genco` to generate hsaco object file for kernel codes.
