### ISSUE TITLE
question about the __sad function

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#1930]
In CUDA: __device__​ unsigned int __sad ( int  x, int  y, unsigned int  z )
In HIP:     __device__​ unsigned int __sad ( int  x, int  y, int  z )

Does the type of z matter ?

Thanks

**Comment by SarbojitAMD** [comment]
PR#1936 should fix the issue

**Comment by jinz2014** [comment]
In addition, I am afraid that the __usad implementation is not right on an AMD GPU. Please give a test again. 

Thanks

**Comment by SarbojitAMD** [comment]
@jinz2014 , do you have any specific example where you see it is not meeting your expectation? I tired few calculations all passed.

**Comment by jinz2014** [comment]
__global__ void usad(const unsigned *x, const unsigned *y, const unsigned *z, unsigned *r)
{
  size_t i = hipBlockDim_x * hipBlockIdx_x + hipThreadIdx_x;
  r[i] = __usad(x[i], y[i], z[i]);
}


for the above kernel, what is the output value when 

  for (int i = 0; i < n; i++) {
    x[i] = 2; 
    y[i] = -3; 
    z[i] = 1; 
    r[i] = 0;
  }
