### ISSUE TITLE
abort() can't be combined with printf()

### ISSUE THREAD

**Issue by masterleinad** [ROCm-Developer-Tools/HIP#1959]
Trying to emulate aborting with an error message in device code, combining `abort()` with `printf()` seems to be a natural idea.
However, calling `abort()` or `__assertfail` makes all output that would normally be generated by `printf` disappear. Thus, for an assert, one currently has to decide between either aborting or printing the error.
There doesn't seem to be a way to flush the buffer and print to `stdout` (or preferably `stderr`) before.
Also, see https://github.com/kokkos/kokkos/pull/2894.

On a related note, it would be helpful if `printf` wouldn't require setting any environment variables.

**Comment by SarbojitAMD** [comment]
Close this ticket as the latest HIP has device-side printf and assert support available. Let us know if you have any issues while using them.
