### ISSUE TITLE
HIP_vector_type unary arithmetic operators - and ~ are missing const

### ISSUE THREAD

**Issue by jpola** [ROCm-Developer-Tools/HIP#1960]
Hi,
as it appeared in my code I see that the `HIP_vector_type` arithmetic operators are missing const.

- [HIP_vector_type operator-() noexcept](https://github.com/ROCm-Developer-Tools/HIP/blob/28db1e4383878db51afbb614e6b6451983a157a4/include/hip/hcc_detail/hip_vector_types.h#L693)
- [HIP_vector_type operator~() noexcept](https://github.com/ROCm-Developer-Tools/HIP/blob/28db1e4383878db51afbb614e6b6451983a157a4/include/hip/hcc_detail/hip_vector_types.h#L708)

With current version of the template hipcc reports:
`error: invalid argument type 'const float4' (aka 'const HIP_vector_type<float, 4>') to unary expression`
for a following snippet
```
const float4 x = make_float4(1,1,1,1);
auto y = -x;
```
The correct version should be most likely
```
HIP_vector_type operator-() const noexcept
HIP_vector_type operator~() const noexcept
```

**Comment by benjaminrsherman** [comment]
This issue can be closed since it was resolved by PR #1965.
