### ISSUE TITLE
BUG: hipMemset2d/hipMemset3D broken

### ISSUE THREAD

**Issue by psychocoderHPC** [ROCm-Developer-Tools/HIP#1982]
`hipMemset2d`/`hipMemset3D` are broken both functions falling in the implementation back to `hipMemset` and using the wrong pitch.

## example:

```C++

#include <stdio.h>
#include <hip/hip_runtime.h>

// apply unique index to each element
__global__ void Fill(int* ptr, size_t pitch, const int numElements)
{
    for(int z = 0; z < numElements; ++z)
    {
        for(int y = 0; y < numElements; ++y)
        {
            for(int x = 0; x < numElements; ++x)
            {
                int idx = z * numElements * numElements + y * numElements + x;
                ((int*)((char*)ptr + z * numElements * pitch + y * pitch))[x] = idx;
            }
        }
    }
}

int main(int argc, char *argv[])
{
    hipPitchedPtr dPtr;
    auto extent = make_hipExtent(4 * sizeof(int),4,4);
    hipMalloc3D(&dPtr, extent);
    int* hPtr;
    hipMallocHost((void**)&hPtr, sizeof(int)*4*4*4);

    for(int i = 0; i < 4 * 4 * 4; ++i)
    {
        hPtr[i] = 133;
    }
    hipLaunchKernelGGL(HIP_KERNEL_NAME(Fill),1,1,0,0,(int*)dPtr.ptr,dPtr.pitch, 4);

    auto srcColumn2 = make_hipPitchedPtr(
        (char*)dPtr.ptr,
        dPtr.pitch,
        4,
        4
    );
    auto dstColumn2 = make_hipPitchedPtr(
        hPtr,
        4 * sizeof(int),
        4,
        4
    );

    // set 2 elements in X, 3 rows and 4 plains to zero
    auto setExtent = make_hipExtent(3*sizeof(int),3,4);
    hipMemset3D(dPtr, 0, setExtent);


    // copy all data to the host
    auto copyExtent2 = make_hipExtent(4*sizeof(int),4,4);

    hipMemcpy3DParms window2;
    window2.srcArray = nullptr;
    window2.dstArray = nullptr;

    window2.srcPtr = srcColumn2;
    window2.srcPos = make_hipPos(0,0,0);
    window2.dstPtr = dstColumn2;
    window2.dstPos = make_hipPos(0,0,0);
    window2.extent = copyExtent2;
    window2.kind = hipMemcpyDeviceToHost;

    hipMemcpy3D(
        &window2
    );
    // print data on host
    for(int z = 0; z < 4; ++z)
    {
        for(int y = 0; y < 4; ++y)
        {
            for(int x = 0; x < 4; ++x)
            {
                int idx = z * 4 * 4 + y * 4 + x;

                printf("%i ", hPtr[idx]);
            }
            printf("\n");
        }
        printf("\n");
        printf("\n");
    }
    return 0;
}
```

output:

```
0 0 0 0 
0 0 0 0 
0 0 0 0 
0 0 0 0 


0 0 0 0 
0 0 0 0 
0 0 0 0 
0 0 0 0 


0 0 0 0 
0 0 0 0 
0 0 0 0 
0 0 0 0 


48 49 50 51 
52 53 54 55 
56 57 58 59 
60 61 62 63
```

but should be:

```
0 0 2 3 
0 0 6 7 
0 0 10 11 
12 13 14 15 


0 0 18 19 
0 0 22 23 
0 0 26 27 
28 29 30 31 


0 0 34 35 
0 0 38 39 
0 0 42 43 
44 45 46 47 


0 0 50 51 
0 0 54 55 
0 0 58 59 
60 61 62 63
```

The bug is independent of https://github.com/ROCm-Developer-Tools/HIP/pull/1897

## Where is the bug in the hip code?

https://github.com/ROCm-Developer-Tools/HIP/blob/753277422a0637ff2bf541c7b43dfaaa2b12c9f6/src/hip_memory.cpp#L2238
and
https://github.com/ROCm-Developer-Tools/HIP/blob/753277422a0637ff2bf541c7b43dfaaa2b12c9f6/src/hip_memory.cpp#L2201

The 2D and 3D implementation using the pitch of the original buffer instead of using for 2D the width (byte) and for 3D the `extent.pitch` to define how many columns (bytes) must be set to the value.
Instead the original buffer pitch is multiplied with the `height` and `depth` and than forwarded to the 1D memset. This is wrong because both memset (2D/3D) working on a **view/window to the buffer** described by the pointer+pitch or for 3D encapsulated in `pitchedDevPtr`

**Comment by psychocoderHPC** [comment]
Tested with HIP 3.1.1

**Comment by gargrahul** [comment]
Thanks for reporting the issue. I think the output for above code should be:
0 0 0 3
0 0 0 7
0 0 0 11
12 13 14 15

0 0 0 19
0 0 0 23
0 0 0 27
28 29 30 31

0 0 0 35
0 0 0 39
0 0 0 43
44 45 46 47

0 0 0 51
0 0 0 55
0 0 0 59
60 61 62 63

For below output, we need to set auto setExtent = make_hipExtent(2*sizeof(int),3,4);:

0 0 2 3 
0 0 6 7 
0 0 10 11 
12 13 14 15 


0 0 18 19 
0 0 22 23 
0 0 26 27 
28 29 30 31 


0 0 34 35 
0 0 38 39 
0 0 42 43 
44 45 46 47 


0 0 50 51 
0 0 54 55 
0 0 58 59 
60 61 62 63

**Comment by psychocoderHPC** [comment]
@gargrahul Yes you are right my comment and the code to define the view/window are not identical. The example sets the view size to 3x3x4 elements.

**Comment by gargrahul** [comment]
#1987 should fix this. We will be testing it further.
