### ISSUE TITLE
[HIPIFY] hipify-clang yields some header-specific warnings

### ISSUE THREAD

**Issue by ChrisKitching** [ROCm-Developer-Tools/HIP#204]
`hipify-clang` processes each of its input files as a "main" file using the clang API. This changes the behaviour of clang's warning system, yielding output like this when processing header files:

```
example.hip.h:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
#pragma once
        ^
1 warning generated.
```

To reproduce, create any random header file with `#pragma once` and feed it to `hipify-clang`.

I _think_ the solution here is to tell the API that _no_ files are the main file - since the notion of a main file makes no sense for this application anyway. I haven't tested if this failure exists when using compilation-database mode.

**Comment by gargrahul** [comment]
@emankov Can we close this issue?

**Comment by emankov** [comment]
No, it's not fixed yet.
