### ISSUE TITLE
Invalid check for `dim` in hip_texture.cpp

### ISSUE THREAD

**Issue by Artem-B** [ROCm-Developer-Tools/HIP#2048]
https://github.com/ROCm-Developer-Tools/HIP/blob/ac79618a3c5e180b6a1f8d1e74d49927a4a05298/vdi/hip_texture.cpp#L715

This condition is always true. I believe it should've been `&&`.
It would be easier to read if it was rewritten as `if (!(dim == 0 || dim == 1))`

**Comment by chrispaquot** [comment]
Thanks! Good catch!

**Comment by Artem-B** [comment]
It may be useful to compile things with -Wall. This was one of the things reported by clang. There are quite a few unused variables and ignored return values.

**Comment by pfultz2** [comment]
HIP should use this [EnableCompilerWarnings.cmake](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/cmake/EnableCompilerWarnings.cmake) module to enable warnings.

**Comment by SarbojitAMD** [comment]
Fixed has been upstream hence closing the ticket.
