### ISSUE TITLE
meta data for kernel argument issue

### ISSUE THREAD

**Issue by joye** [ROCm-Developer-Tools/HIP#2072]
I write a kernel, which has these arguments;
`__global__ void gemm_kernel_nn(const float* A,
    int lda,
    int stride_a,
    const float* B,
    int ldb,
    int stride_b,
    float alpha,
    float beta,
    float* C,
    int ldc,
    int stride_c,
    int m,
    int n,
    int k) {
     ...}`

and I launch this kernel with
 `hipLaunchKernelGGL(gemm_kernel_nn, dim3(gridDim), dim3(blockDim), 0, 0, A + i * stride_a, lda, stride_a, B + i * stride_b, ldb, stride_b, *alpha, *beta, C+i* stride_c, ldc, stride_c, m, n, k);`

in runtime reported below problem;  terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _Z14gemm_kernel_nnPKfiiS0_iiffPfiiiii

The same code works well in nvcc.

**Comment by jglaser** [comment]
It could be that you're not indicating the GPU architecture on your `hipcc` command line, and it is not autodetected because the system you're compiling on has no GPU built in.

Such as
```
hipcc -o test --amdgpu-target=gfx906 test.cpp
```

**Comment by joye** [comment]
Thanks for the feedback, I solved this problem as your suggested.
