### ISSUE TITLE
3.5 __host__ __device__ regression

### ISSUE THREAD

**Issue by Dekken** [ROCm-Developer-Tools/HIP#2095]
Since the updated deb files pushed to the repo, I seem to have to start declaring "\_\_device__" on functions where before "it just worked"?

Is there some justification for this?

**Comment by Dekken** [comment]
The example from https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-GUIDE.html#hip-guide

```
// Example showing device function, __device__ __host__
// <- compile for both device and host
float PlusOne(float x)
{
   return x + 1.0;
}

__global__
void
MyKernel (const float *a, const float *b, float *c, unsigned N)
{
   unsigned gid = hipThreadIdx_x; // <- coordinate index function
   if (gid < N) {
       c[gid] = a[gid] + PlusOne(b[gid]);
   }
}
void callMyKernel()
{
   float *a, *b, *c; // initialization not shown...
   unsigned N = 1000000;
   const unsigned blockSize = 256;
   hipLaunchKernelGGL(MyKernel,
 (N/blockSize), dim3(blockSize), 0, 0,  a,b,c,N);
}
```

no longer compiles.

```
gpu.cpp:14:27: error: no matching function for call to 'PlusOne'
        c[gid] = a[gid] + PlusOne(b[gid]);
                          ^~~~~~~
gpu.cpp:4:7: note: candidate function not viable: call to __host__ function from __global__ function
float PlusOne(float x)

```

**Comment by Dekken** [comment]
Compilation appears broken in general.

New changes are not picked up but some artifact cached somewhere is used.

**Comment by Dekken** [comment]
This is demonstratable in the rocm-terminal docker container quite easily

```
rocm-user@f03f43bc7060:~$ hipcc gpu.cpp 
sh: 1: lsmod: not found
gpu.cpp:15:27: error: no matching function for call to 'PlusOne'
        c[gid] = a[gid] + PlusOne(b[gid]);
                          ^~~~~~~
gpu.cpp:5:7: note: candidate function not viable: call to __host__ function from __global__ function
float PlusOne(float x)
      ^
1 error generated when compiling for gfx803.
```

**Comment by yxsamliu** [comment]
The document needs update.

float PlusOne(float x) should be defined as either `__device__` or `__host__ __device__` function.

kernel can only call device or host device function. By default a function is host function. This matches CUDA language rule.

**Comment by Dekken** [comment]
Why is this not "opt-in" considering that it's a minor change but is also a breaking change?

**Comment by arghdos** [comment]
@Dekken -- the ROCm 3.5 release is a large departure, as it deprecates the older HCC compiler and run-time, replacing it with the new HIP-Clang compiler (which is much closer to upstream LLVM).  

Long story short, ROCm 3.5 and later will follow the same sort of semantics that CUDA-Clang does.  A useful resource (though primarily aimed at NVCC vs CUDA-Clang), is [this document](https://llvm.org/docs/CompileCudaWithLLVM.html#dialect-differences-between-clang-and-nvcc).

**Comment by Dekken** [comment]
I really don't get why you have something, that works, and is less invasive. And remove it.

You have no obligation to match CUDA, the addition of function decorators could be considered a restriction, and not a requirement.

**Comment by arghdos** [comment]
@Dekken -- the change was not to be in line with what CUDA or NVCC do, but is a consequence of being in alignment with how upstream Clang treats the `__host__` and `__device__` keywords.  These are now function attributes, that is:

```__host__ foo()```

cannot override

```virtual void foo() = 0;```

because the function signature is not the same.

>I really don't get why you have something, that works, and is less invasive. And remove it.

I get the frustration, really I do.  It's particularly... vexing, that we can't even update our simplest example documentation to match or explain the new semantics.  I will (as the very least) direct our documentation folks to fix that example.

**Comment by Dekken** [comment]
I appreciate it Nick, your example may be valid, but I find it insufficient.

If the signature is exactly the same, with no additional modifiers (static/virtual)
Why not default to both __device__ and __host__ ?
It seems needless to require it, and just forces people to go modify code that wouldn't otherwise need it.

**Comment by arghdos** [comment]
The difficulty with defaulting to `__device__` is that e.g., many STL library features (think `std::vector`) do not have implementations in device code.  Hence if functions were `__device__` by default, you would run into issues where many other codes wouldn't compile for different reasons :)

I realize it can be a bit of a bear, working on getting better guidance for the new compiler out there.

**Comment by Dekken** [comment]
Thanks Nick, I realise this may be more in LLVMs hands now than AMDs
