### ISSUE TITLE
hipBindTexture return error

### ISSUE THREAD

**Issue by joye** [ROCm-Developer-Tools/HIP#2100]
Is there some upper limit in hipBindTexture usage for the last parameter size setting? I find when I set the last parameter to 131072 * sizeof(float),  this api will return hipErrorRuntimeOther.

**Comment by SarbojitAMD** [comment]
@joye , 

Short answer to your question 'Yes, there is size limit'. 

More details:
Number of valid texture element size is depend on values used to create hipChannelFormatDesc. Calculation goes like 'x- value/4 * (number of channels set)' e.g. hipChannelFormatDesc chanDesc = hipCreateChannelDesc(32, 0, 0, 0, hipChannelFormatKindFloat); // x=32, #channels=1, element size  = 32 / 4 * 1 = 8;

In this case total size in bytes  = 131072 * sizeof(float) = 524288 bytes
No. of texture elements = total size / element size = 524288 / 8 = 65536

You can query max supported number of 1D texture elements as below: 
 hipDeviceGetAttribute(&outData, hipDeviceAttributeMaxTexture1DWidth, dev_id); on successful run you will get max number of elements in outData. 

Limit check : Your input memory size should not end up having greater than or equal to max number of elements supported. In your case it is happening hence the failure.

Note: Max limit can’t be mentioned as it is all in texture element size which can be calculated based on user input.

**Comment by SarbojitAMD** [comment]
Closed the bug for now let me know if you have any query regarding the same.
