### ISSUE TITLE
Incorrect device pointer returned by hipPointerGetAttributes()

### ISSUE THREAD

**Issue by AdhocMan** [ROCm-Developer-Tools/HIP#2137]
When calling `hipPointerGetAttributes`, the returned device pointer has any offset from the start of the allocated memory removed. This behavior is different from CUDA and caused an issue with the device pointer detection of an application I'm working on.
Tested with ROCm 3.5.1, HIP version 3.5.20231-93097e03.

A basic example to showcase the issue:
```
#include <iostream>
#include <cstddef>
#include <hip/hip_runtime_api.h>

int main () {
  const std::size_t size = 1024;

  double * ptr;
  hipMalloc(reinterpret_cast<void**>(&ptr), size * sizeof(double));
  double * ptr_offset = ptr + 123;

  hipPointerAttribute_t attr;
  hipPointerAttribute_t attr_offset;

  hipPointerGetAttributes(&attr, ptr);
  hipPointerGetAttributes(&attr_offset, ptr_offset);

  std::cout << "Original pointer: " << ptr << std::endl;
  std::cout << "Attribute device pointer: " << attr.devicePointer << std::endl;

  // Both pointers should be equal
  std::cout << "Original pointer with offset: " << ptr_offset << std::endl;
  std::cout << "Attribute device pointer with offset: " << attr_offset.devicePointer << std::endl;

  hipFree(ptr);

  return 0;
}
```

**Comment by leofang** [comment]
Another related issue that we observed when extending CuPy's support for ROCm (https://github.com/cupy/cupy/pull/3823): On ROCm 3.5.0, if I fetch a constant memory's address via `hipModuleGetGlobal`, and then pass it to `hipPointerGetAttributes` to look up the pointer attributes, I get `hipErrorInvalidDevice`. CUDA has no problem doing this.

**Comment by SarbojitAMD** [comment]
Fixed in rocm3.10 hence closing the ticket.
