### ISSUE TITLE
Does HIP compiler have a standard env flags comparable to `CC` or `CXX`

### ISSUE THREAD

**Issue by robertmaynard** [ROCm-Developer-Tools/HIP#2153]
Does HIP have a recommend environment flag that points to the explicit HIP compiler that a build systems should use?

**Comment by yxsamliu** [comment]
If find_package(hip, config) is used, -DHIP_CXX_COMPILER=xxx can be used to specify HIP compiler. However it is not supported through env var.

**Comment by robertmaynard** [comment]
The question was more about does the HIP project have an opinion on what environment variable build-systems should prefer to check when determining the desired HIP compiler.

For example a common pattern for `cmake` or `makefiles` is to set the `CXX` env variable to control which specific C++ compiler to use. This consistency across build-systems is great for users as it make it easier to compose large projects that might use multiple build-systems.

**Comment by yxsamliu** [comment]
No. Maybe we should use HIPCXX, like CUDACXX.

**Comment by robertmaynard** [comment]
`HIPCXX` sounds great to me. I will make sure CMake uses that.
