### ISSUE TITLE
HIP separable compilation linking fails when passed archives 

### ISSUE THREAD

**Issue by robertmaynard** [ROCm-Developer-Tools/HIP#2154]
Found while working on implementing HIP support in CMake
Tested with compilers provided with ROCm 3.5 and 3.7

Given the following CMake:
```cmake
cmake_minimum_required(VERSION 3.18)

project(static-lib-rdc HIP)

set(CMAKE_HIP_FLAGS "-fgpu-rdc")
set(CMAKE_HIP_ARCHITECTURES gfx908)

add_library(static-lib file1.cxx file2.hip.cxx file3.hip.cpp file4.hip file5.cu)

add_executable(verify main.cu)
target_link_libraries(verify PUBLIC static-lib)
set_source_files_properties(
    file1.cxx file2.hip.cxx file3.hip.cpp file4.hip file5.cu main.cu
  PROPERTIES
    LANGUAGE "HIP"
)
```

We get the following error when trying to link the `verify` executable
```
/opt/rocm/bin/hipcc -fgpu-rdc --amdgpu-target=gfx908 CMakeFiles/verify.dir/main.cu.o -o verify  libstatic-lib.a 
clang-11: error: no such file or directory: '/tmp/hipcc0wDdnRUU/file1.cxx.o /tmp/hipcc0wDdnRUU/file2.hip.cxx.o /tmp/hipcc0wDdnRUU/file3.hip.cpp.o /tmp/hipcc0wDdnRUU/file4.hip.o /tmp/hipcc0wDdnRUU/file5.cu.o'
```

It looks something is going wrong and the clang-offload-bundler files are not being placed in the correct location or being removed before linking.

**Comment by aaronenyeshi** [comment]
How did you build the static-lib? If it contains HIP code, please build using clang++ with flags `-fgpu-rdc --emit-static-lib -o libstatic-lib.a`. 
Then when linking with it, please link with these flags in target_link_libraries, `-lstatic-lib -L/path/to/libstatic-lib.a`.

**Comment by robertmaynard** [comment]
It looks like switching the link line to the following does work:

```
hipcc -fgpu-rdc --amdgpu-target=gfx908 CMakeFiles/verify.dir/main.cu.o -o verify -lstatic-lib -L.
```

Unfortunately this isn't a solution that is acceptable for CMake.

Link lines like these are ambiguous espescially when linking to multiple numerous libraries in different locations. Since we haven't given explicit paths to any of the libraries we could errantly pick up the wrong `static-lib` when given multiple link directories. CMake transforms link lines to use explicit paths whenever to possible to avoid such ambiguities.

**Comment by pfultz2** [comment]
Shouldn't cmake use clang directly and not hipcc since hipcc doesn't understand the cmake build environment?

> If it contains HIP code, please build using clang++ with flags

What if the user is using `-fno-gpu-rdc`? Is that only possible with shared libraries?

> Then when linking with it, please link with these flags in target_link_libraries

Is the `-l` flag necessary, or can the path to the static lib be passed directly to the compiler?

**Comment by robertmaynard** [comment]
> Shouldn't cmake use clang directly and not hipcc since hipcc doesn't understand the cmake build environment?

I am working on getting CMake to understand two things:

1. HIP as a compilation language
2. hipcc / hipclang as a unique compiler compared to upstream clang.


> Is the -l flag necessary, or can the path to the static lib be passed directly to the compiler?

The original bug report is that the link lines CMake is currently generating for my work to get HIP language support currently don't work with HIPClang. All build-systems are effect by this issue.

**Comment by aaronenyeshi** [comment]
> Shouldn't cmake use clang directly and not hipcc since hipcc doesn't understand the cmake build environment?
> 
> > If it contains HIP code, please build using clang++ with flags
> 
> What if the user is using `-fno-gpu-rdc`? Is that only possible with shared libraries?
> 

If the user is using `-fno-gpu-rdc`, then they can compile all their source objects normally using `-fno-gpu-rdc -c -o source.cpp.o`. Then archive them using cmake's ar, `ar rcsD list.cpp.o of.cpp.o sources.cpp.o`, I think cmake already has this functionality if you add `option(BUILD_SHARED_LIBS "Build as a shared library" OFF)` to the project.

> > Then when linking with it, please link with these flags in target_link_libraries
> 
> Is the `-l` flag necessary, or can the path to the static lib be passed directly to the compiler?

The clang++ compiler will accept these two flags. However just passing the path to static lib is not enough, I think you have to also have `-l` too.

**Comment by aaronenyeshi** [comment]
> The original bug report is that the link lines CMake is currently generating for my work to get HIP language support currently don't work with HIPClang. All build-systems are effect by this issue.

As a workaround, you may try this:
```
add_dependencies(verify static-lib)
target_link_libraries(verify PRIVATE -lstatic -L${CMAKE_CURRENT_BINARY_DIR})
```
I will discuss with my team about consuming the libstatic-lib.a as an input.

**Comment by robertmaynard** [comment]
> The clang++ compiler will accept these two flags. However just passing the path to static lib is not enough, I think you have to also have -l too.

upstream clang and hipclang both consider the line `/opt/rocm/bin/hipcc -fgpu-rdc --amdgpu-target=gfx908 CMakeFiles/verify.dir/main.cu.o -o verify  libstatic-lib.a ` to be entirely valid when `gpu-rdc` is disabled.

**Comment by pfultz2** [comment]
> The clang++ compiler will accept these two flags. However just passing the path to static lib is not enough, I think you have to also have -l too.

Are you sure? We already are building with static libs in MIOpen, rocBLAS, etc using cmake, so the explicit path should be working?

**Comment by aaronenyeshi** [comment]
> > The clang++ compiler will accept these two flags. However just passing the path to static lib is not enough, I think you have to also have -l too.
> 
> Are you sure? We already are building with static libs in MIOpen, rocBLAS, etc using cmake, so the explicit path should be working?

Sorry, you're right, when gpu-rdc is disabled, giving the path to static lib works fine.

**Comment by pfultz2** [comment]
> hipcc / hipclang as a unique compiler compared to upstream clang.

Well there is no hipclang driver, its just `clang++`(from rocm or upstream) with `-x hip`. For cmake, `clang++` with the `hip::device` cmake target should be preferred over `hipcc`. hipcc is mainly for non-cmake users, and has lots of limitations(requires a lot custom env variables to find its dependencies, and doesnt work with upstream static libs).

**Comment by robertmaynard** [comment]
@pfultz2 As far as I am aware the `clang++` provided by `rocm` is not equivalent to upstream `clang++` as it contains modifications that have not yet been accepted upstream. Therefore the ROCM provided clang compiler must be identified with a unique id and version number since it diverges from upstream.

> Well there is no hipclang driver, its just clang++(from rocm or upstream) with -x hip. 

It would be great to have Rocm provide `clang++` or some other alias inside the rocm/bin folder as currently the only easily discoverable compiler is `hipcc`.

> For cmake, clang++ with the hip::device cmake target should be preferred over hipcc

Yes long term would be to have CMake understand the following:
- upstream Clang aka COMPILER_ID Clang supports the HIP language ( -x hip )
- rocm Clang aka COMPILER_ID HIPClang ( subject to change ) supports the HIP language

Due to how CMake's internal compiler detection works, we simply can't rely on the existence of `hip::device` target as compiler detection can occur before any `find` queries. The approach for upstream `Clang` support most likely will follow how CMake added support for `Clang` as a CUDA compiler in 3.18.


> hipcc doesnt work with upstream static libs 

Can you elaborate or point me towards more information on this?

**Comment by pfultz2** [comment]
> As far as I am aware the clang++ provided by rocm is not equivalent to upstream clang++ as it contains modifications that have not yet been accepted upstream. Therefore the ROCM provided clang compiler must be identified with a unique id and version number since it diverges from upstream.

Yes, unfortunately we don't have a distinguished version, but we should.

> It would be great to have Rocm provide clang++ or some other alias inside the rocm/bin folder as currently the only easily discoverable compiler is hipcc.

I think we want to install everything into /opt/rocm, and drop these subdirectories(ie /opt/rocm/llvm, /opt/rocm/hip, /opt/rocm/miopen, etc). 

> rocm Clang aka COMPILER_ID HIPClang ( subject to change ) supports the HIP language

How would you tell if its rocm clang? Because right now, the version is the same as upstream clang.

> Due to how CMake's internal compiler detection works, we simply can't rely on the existence of hip::device target as compiler detection can occur before any find queries.

Why would the compiler detection need `hip::device`? I assume this would be used by the user as the compiler and the runtime are seperate components. I assume the detection would just check if `--cuda-host-only -x hip` are valid compilation flags.

**Comment by robertmaynard** [comment]
> Yes, unfortunately we don't have a distinguished version, but we should.

I agree, see: https://github.com/ROCm-Developer-Tools/HIP/issues/2150

> How would you tell if its rocm clang? Because right now, the version is the same as upstream clang.

No matter the language the `__HIP__` define is specified. When that is detected we know we are 'HIPClang' and normally would extract the version from the pre-processor. Currently we will extract that information by calling the compiler again with `--version` and extracting the ROCm toolkit version and using that as the compiler version.

will answer last question later.

**Comment by pfultz2** [comment]
> When that is detected we know we are 'HIPClang' 

But having`__HIP__` defined doesn't mean we aren't using upstream clang? In fact, clang-10 shows it defined:

```
$ echo | clang++-10 -x hip --cuda-host-only -dM -E - | grep -i hip
#define __HIPCC__ 1
#define __HIP__ 1
```

> Currently we will extract that information by calling the compiler again with --version and extracting the ROCm toolkit version and using that as the compiler version.

But clang doesn't show the rocm version? Furthermore, the rocm version may not be available if its built from source.

**Comment by robertmaynard** [comment]
>  In fact, clang-10 shows it defined

Well dang, that is really problematic. 

CMake needs a way to uniquely identify the clang compiler shipped as part of the ROCm toolkit.  


> But clang doesn't show the rocm version?

upstream clang compiler version information is extracted via the pre-processor. 

The root issue here is that the ROCm derivation of clang has zero identifiable pre-processor defines. We shouldn't identify it with compiler vendor of `clang` and the related clang version as that will cause downstream projects that have specific `clang` checks to potentially break.

> Furthermore, the rocm version may not be available if its built from source.

To be honest, this is the least of our worries if we can't fix the above issues.

**Comment by robertmaynard** [comment]
> Why would the compiler detection need hip::device? I assume this would be used by the user as the compiler and the runtime ? are seperate components. I assume the detection would just check if --cuda-host-only -x hip are valid compilation flags.

For compiler detection we can explicitly pass `--cuda-host-only` and extract the required information. 

The question will be how do we solve ( or can we? ) the following example project where the user tries to compile and run a block of HIP code that needs the HIP runtime.

```cmake
cmake_minimum_required(VERSION 3.19)
project(try_hip HIP)

try_run( ...  srcfile.hip ...)
```

**Comment by pfultz2** [comment]
> The root issue here is that the ROCm derivation of clang has zero identifiable pre-processor defines.

The goal of hip-clang is to have everything upstreamed so users can build from the HEAD of llvm. However, our fork many times has features that our still in the review queue of upstream llvm, so we should have a unique way of identifying our fork. Either we provide a `__rocm__` define or say `rocm-clang version:` in the output of `--version`. Perhaps @yxsamliu or @aaronenyeshi can comment on that feasibility.

**Comment by pfultz2** [comment]
> For compiler detection we can explicitly pass --cuda-host-only and extract the required information.

Thats good, because using `--cuda-device-only` requires finding rocm device libs, which needs cmake search paths.

> The question will be how do we solve ( or can we? ) the following example project where the user tries to compile and run a block of HIP code that needs the HIP runtime.

Is this because `try_run` cannot implicitly link the `hip::device` target?

**Comment by robertmaynard** [comment]
> Is this because try_run cannot implicitly link the hip::device target?

Was thinking about this more, and will report back after I have done some exploration.

**Comment by robertmaynard** [comment]
Closing this as passing static libraries explicitly on the link line when using RDC now works ( verified with 3.9 )

**Comment by ax3l** [comment]
> Closing this as passing static libraries explicitly on the link line when using RDC now works ( verified with 3.9 )

Tried again with 4.1.1 and this seems to fail again

Unfortunately for C/C++/Fortran CMake projects, the `hip::device` target that is recommended to be used also assumes that the Fortran compiler is from LLVM (aka the shipped `flang`?), even if it does not contain HIP code. Probably some of the flags should be guarded to C/C++ code in `hip::device`? #2158
I am not sure `flang` is yet ready for prime time. Besides general user code base compatibility with `flang` & code gen. progress of the `flang` project, it looks like the `flang` shipped with rocm is not even recognized by the shipped CMake modules (`The Fortran compiler identification is unknown`).

Update: opened as separate issue in #2275
