### ISSUE TITLE
[HIPIFY] Fails (unnecessarily) on language features above C++11

### ISSUE THREAD

**Issue by ChrisKitching** [ROCm-Developer-Tools/HIP#216]
Hipify ought to be able to cope with whatever version of C++ is supported by the clang it was compiled against. Unfortunately, if you do something like:

```
hipify-clang concurentKernels.cu -- -x cuda --cuda-path=/opt/cuda --cuda-gpu-arch=sm_30 -isystem /opt/cuda/samples/common/inc -std=c++17
```
... you get compile errors if you use any C++17 features, since hipify is [explicitly](https://github.com/ROCm-Developer-Tools/HIP/blob/7ee8e2d51b2167de7d24f0e64f21a063d874570d/hipify-clang/src/Cuda2Hip.cpp#L4282) adding `-std=c++11` internally. We probably want to make this conditional (only add `-std=c++11` if the user hasn't provided their own `-std` option)

Hopefully a fairly easy fix once we find the right API for querying existing args...

**Comment by emankov** [comment]
https://github.com/ROCm-Developer-Tools/HIP/issues/207:
> change option -std=c++11 to -std=c++17 in hipify-clang's cmake;

or try to remove it.

**Comment by ChrisKitching** [comment]
> change option -std=c++11 to -std=c++17 in hipify-clang's cmake;
> or try to remove it.

Oh, you misunderstand (or maybe I do?).

This isn't to do with the version of C++ used to compile hipify-clang, this is to do with the C++ version the _user_ is using in their CUDA files - as input to hipify-clang. This also applies to C++14.

The practical effect is the _user's_ code cannot contain C++14/17 features. Even if they invoke hipify-clang with `-std=c++14` (or 17).

For instance, try hipifying this trivial file
```c++
template<class T>
constexpr T pi = T(3.1415926535897932385);
```

You'll get warnings (or errors) about use of a C++14 variable template. Even if you pass `-std=c++14`!

This is because hipify-clang is adding `-std=c++11` to the end of the effective arg-list, which overrides any user-provided value. An issue I resolve in #217 .

**Comment by emankov** [comment]
Fixed with https://github.com/ROCm-Developer-Tools/HIP/pull/217
