### ISSUE TITLE
References to VDI (old, amd-internal name) in code.

### ISSUE THREAD

**Issue by rwvo** [ROCm-Developer-Tools/HIP#2161]
hip-config.cmake.in (and possibly, other files as well) have several references to VDI. E.g.:

https://github.com/ROCm-Developer-Tools/HIP/blob/master/hip-config.cmake.in#L114

Since VDI is an old/internal name for what is publicly known as ROCCLR, this is confusing for users. I would strongly suggest to bring the names in the code up-to-date with the public name for the runtime.

**Comment by gargrahul** [comment]
@rwvo github/master branch is not being updated. Please refer to rocm-3.7.x branch.
