### ISSUE TITLE
Twice as many VGPR allocated to int128 as necessary

### ISSUE THREAD

**Issue by zgu153522** [ROCm-Developer-Tools/HIP#2170]
I have a kernel using the __int128 type and reference these variables in inline asm statements (global_load_dwordx4 and global_store_dwordx4).  The compiler seems to allocate 8 VGPR to each __int128, and then never use the last 4.  This causes far more VGPR to be used for the kernel compared with the equivalent code compiled with HCC from earlier ROCm versions.

**Comment by cjatin** [comment]
Can you share a bit more details on this.
Sample kernel, your gpu arch, rocm version and command to compile.

**Comment by zgu153522** [comment]
@cjatin I am using gfx906, ROCm 3.7, and command is hipcc -save-temps file.cpp -o file.o
Sample code below:
`
__global__ void inline_asm_copy(uint32_t* __restrict__ srcptr, uint32_t* __restrict__ dstptr)
{
    unsigned localOffset = hipThreadIdx_x * 4;
    unsigned __int128 buf[5];
#pragma unroll
    for (unsigned i = 0; i < 25; i++) {
	asm volatile("global_load_dwordx4 %0, %1, off"
		     : "=v"(buf[0])
		     : "v"(srcptr + localOffset + i * 256 * 4 * 5));
	asm volatile(
	    "global_load_dwordx4 %0, %1, off"
	    : "=v"(buf[1])
	    : "v"(srcptr + localOffset + 256 * 4 * 1 + i * 256 * 4 * 5));
	asm volatile(
	    "global_load_dwordx4 %0, %1, off"
	    : "=v"(buf[2])
	    : "v"(srcptr + localOffset + 256 * 4 * 2 + i * 256 * 4 * 5));
	asm volatile(
	    "global_load_dwordx4 %0, %1, off"
	    : "=v"(buf[3])
	    : "v"(srcptr + localOffset + 256 * 4 * 3 + i * 256 * 4 * 5));
	asm volatile(
	    "global_load_dwordx4 %0, %1, off"
	    : "=v"(buf[4])
	    : "v"(srcptr + localOffset + 256 * 4 * 4 + i * 256 * 4 * 5));
	asm volatile("s_waitcnt vmcnt(0)\n\ts_barrier\n\tglobal_store_dwordx4 "
		     "%0, %1, off"
		     :
		     : "v"(dstptr + localOffset + i * 256 * 4 * 5),
		       "v"(buf[0]));
	asm volatile(
	    "global_store_dwordx4 %0, %1, off"
	    :
	    : "v"(dstptr + localOffset + 256 * 4 * 1 + i * 256 * 4 * 5),
	      "v"(buf[1]));
	asm volatile(
	    "global_store_dwordx4 %0, %1, off"
	    :
	    : "v"(dstptr + localOffset + 256 * 4 * 2 + i * 256 * 4 * 5),
	      "v"(buf[2]));
	asm volatile(
	    "global_store_dwordx4 %0, %1, off"
	    :
	    : "v"(dstptr + localOffset + 256 * 4 * 3 + i * 256 * 4 * 5),
	      "v"(buf[3]));
	asm volatile(
	    "global_store_dwordx4 %0, %1, off"
	    :
	    : "v"(dstptr + localOffset + 256 * 4 * 4 + i * 256 * 4 * 5),
	      "v"(buf[4]));
    }
}

int main(int argc, char *argv[])
{
    uint32_t *dstptr;
    uint32_t *srcptr;
    hipMalloc((void**)&srcptr, 1600 * 2560 / 32);
    hipMalloc((void**)&dstptr, 1600 * 2560 / 32);

    inline_asm_copy<<<dim3(256), dim3(256), 0, 0>>> (srcptr, dstptr);
}
`

**Comment by zgu153522** [comment]
@cjatin  would like to ask if you are able to reproduce the issue?

**Comment by cjatin** [comment]
Will share this with some compiler folks and let you know if they think its a bug.
Will keep this open till then

**Comment by zgu153522** [comment]
Hi @cjatin I would like to check on the status of this issue.

**Comment by zgu153522** [comment]
Alternatively, is there some other way to correctly reference 4 VGPR in the dwordx4 instructions?

**Comment by cjatin** [comment]
@yxsamliu can you help with this? is there any possible workaround if using inline assembly?

**Comment by yxsamliu** [comment]
@arsenm @rampitec

**Comment by zgu153522** [comment]
@cjatin @yxsamliu @arsenm @rampitec just want to check for updates.  is this something that can be fixed for a future release?

**Comment by arsenm** [comment]
First I strongly recommend not using inline asm (particularly asm volatile), especially for trivial stuff like this. You would be better off just writing natural code.

The problem seems to be the inline asm handling tries to treat i128 as legal, even though it's not. The DAG inline asm code ends up thinking it needs 2 i64 registers, but uses the 128-bit class, so the inline asm machine instruction has a phantom dead def.

**Comment by arsenm** [comment]
https://reviews.llvm.org/D95904 but I really advise against using inline asm, especially for this

**Comment by arsenm** [comment]
This should be closed, this was fixed in https://reviews.llvm.org/rGaf2cbe8effcade9913c0f2cff295f664f185df54
