### ISSUE TITLE
indirect function calls (function pointer)

### ISSUE THREAD

**Issue by psychocoderHPC** [ROCm-Developer-Tools/HIP#2186]
hip-clang (tested with HIP 3.8 and 3.9) is currently not allowing to use indirect function calls.

```
$ hipcc -std=c++14 main.cpp 
main.cpp:17:17: error: unsupported indirect call to function <unknown>
__global__ void vadd_hip(/*hipLaunchParm lp,*/ const float *a, const float *b, float *c, int N
```
There is already an issue https://github.com/RadeonOpenCompute/hcc/issues/621 for `hcc` available but since HIP is not longer using `hcc` I opened this explicit for HIP. 

# Example

```
#include "hip/hip_runtime.h"
#include <tuple>

__device__ float identity(const float a){
    return a;
}

__device__ float relu(const float a){
    return (a>0.0f?a:0.0f);
}

__device__ float (*array[]) (const float) = {&identity, &relu};

__global__ void vadd_hip(/*hipLaunchParm lp,*/ const float *a, const float *b, float *c, int N){

  *c = array[N](*a);
}

int main(int argc, char *argv[])
{
  return 0;
}
```

# Compile

```
hipcc -std=c++14 main.cpp
```

**Comment by leofang** [comment]
It'd be nice to have this capability indeed. Lack of this is blocking our code from being runnable on HIP (https://github.com/cupy/cupy/pull/4177).

**Comment by psychocoderHPC** [comment]
I extended the example a little bit to test dynamic manipulation of the function pointer array too:

```C++
#include "hip/hip_runtime.h"

__device__ void A(const float a){
    printf("A called: %f\n", a);
}

__device__ void B(const float b){
    printf("B called: %f\n", b);
}

__device__ void C(const float c){
    printf("C called: %f\n", c);
}

__device__ void (*fn_array[]) (const float) = {&A, &B, &B};

__global__ void load_fn_ptr(float* v)
{
    for(int i = 0; i < 3; ++i)
        v[i] = i;
    fn_array[2] = &C;
}

__global__ void call_fn(const float *v){

  for(int i = 0; i < 3; ++i)
      fn_array[i](v[i]);
}

int main(int argc, char *argv[])
{
    float* v = nullptr;
    hipMalloc(&v,sizeof(float) * 3u);
    hipLaunchKernelGGL(load_fn_ptr, 1, 1, 0 ,0 , v);
    hipLaunchKernelGGL(call_fn, 1, 1, 0 ,0 , v);
    hipDeviceSynchronize();
    return 0;
}
```

**Comment by psychocoderHPC** [comment]
A second example would be using virtual:

```C++
#include "hip/hip_runtime.h"
#include <tuple>

struct Interface
{
   __device__ virtual void fn(float v) = 0;
};

struct Foo : public Interface
{
   __device__ void fn(float v) final
   {
       printf("call Foo\n");
   }
};

struct Bar : public Interface
{
   __device__ void fn(float v) final
   {
       printf("call Bar\n");
   }
};

__device__ Bar global_bar;
__device__ Foo global_foo;
__device__ Interface* interface_storage[2];

__global__ void load_interface(float* v)
{
    for(int i = 0; i < 2; ++i)
        v[i] = i;
    interface_storage[0] = &global_bar;
    interface_storage[1] = &global_foo;
}

__global__ void call_interface_class(const float *v){

  for(int i = 0; i < 2; ++i)
      interface_storage[i]->fn(v[i]);
}

int main(int argc, char *argv[])
{
    float* v = nullptr;
    hipMalloc(&v,sizeof(float) * 2u);
    hipLaunchKernelGGL(load_interface, 1, 1, 0 ,0, v);
    hipLaunchKernelGGL(call_interface_class, 1, 1, 0, 0, v);
    hipDeviceSynchronize();
    return 0;
}
```

**Comment by krishoza** [comment]
@psychocoderHPC in the above example I have few queries as below. 
1. interface_storage is declared but is never allocated memory on the device
2. how are we able to initialize interface_storage inside kernel without declaring the memory.

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC in the above example I have few queries as below.
> 
> 1. interface_storage is declared but is never allocated memory on the device

The memory in this example is a device global variable and should be automatically allocated by the driver after the device is selected. This is the default behavior of CUDA and HIP independent of the topic "indirect function calls".

> 2. how are we able to initialize interface_storage inside kernel without declaring the memory.

As written above, the memory is allocated by the driver/runtime environment of HIP and initialized in the function `load_interface`.

Memory defined as `__device__` can be initialized from the host with `hipMemcpyToSymbolAsync` but in this case, we need the address of the function, therefore we need to do the initialization from a kernel.

**Comment by psychocoderHPC** [comment]
Thanks for solving this issue. The provided example code is now running with HIP 4.3+.
