### ISSUE TITLE
hipHostRegister doesn't work correctly

### ISSUE THREAD

**Issue by ye-luo** [ROCm-Developer-Tools/HIP#2189]
Checked on 3.9.1
[reproducer](https://github.com/ROCm-Developer-Tools/aomp/blob/amd-stg-openmp/test/smoke/hip_host_register/hip_host_register.hip)

hipHostMalloc case worked.
hipHostRegister case failed in the kernel execution. 
Memory access fault by GPU node-1 (Agent handle: 0x23fc930) on address 0x247b000. Reason: Page not present or supervisor privilege.

**Comment by SarbojitAMD** [comment]
@ye-luo, I think test code needs minor correction, after calling hipHostRegister use the ptr to get device pointer which should be used for any device operations such as kernel : "write_kernel" in this case.
  
For more details on how to use hipHostRegister refer : https://rocm-developer-tools.github.io/HIP/group__Memory.html#gab8258f051e1a1f7385f794a15300e674

**Comment by ye-luo** [comment]
"Applications must use the device pointer in device code, and the host pointer in device code."
What is the correct sentence?

So what is the way to registered aligned memory to GPU and use a single ptr on both host and device? I mean match hipHostMalloc experience.

With CUDA, aligned_alloc + cudaHostRegister = cudaHostAlloc with memory aligned.

**Comment by ye-luo** [comment]
Is the hipHostRegister way to engage "Faster HostToDevice and DeviceToHost Data Transfers" with pre-allocated host memory?

**Comment by SarbojitAMD** [comment]
There is a typo it should be "Applications must use the device pointer in device code, and the host pointer in **host code**."

So what is the way to registered aligned memory to GPU and use a single ptr on both host and device? I mean match hipHostMalloc experience.
>>>HIP does not support single pointer behavior similar to CUDA.

**Comment by ye-luo** [comment]
Thanks. I will live with the limitation.
