### ISSUE TITLE
Unable to compile the output of the pre-processor when using HIP 

### ISSUE THREAD

**Issue by robertmaynard** [ROCm-Developer-Tools/HIP#2199]
Given the following file:

```cxx
int main() { return 0; }
```

I was expecting that the following commands would allow me to generate the pre-processor output, and subsequently compile it:

```
/opt/rocm/llvm/bin/clang++ -D__HIP_ROCclr__=1 -std=c++14 -o /tmp/reproducer.E.cxx -x hip -c /workspaces/test.hip  -E
/opt/rocm/llvm/bin/clang++ -D__HIP_ROCclr__=1 -std=c++14 -x hip-cpp-output -c /tmp/reproducer.E.cxx -o /tmp/reproducer.o
```

But when I try to use `hip-cpp-output` I get redefintion erors such as:
```
In file included from /workspaces/test.hip:1:
In file included from <built-in>:1:
In file included from /opt/rocm-3.9.0/llvm/lib/clang/12.0.0/include/__clang_hip_runtime_wrapper.h:21:
In file included from /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/cmath:42:
/usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/cpp_type_traits.h:73:10: error: redefinition of '__true_type'
  struct __true_type { };
         ^
```
It looks like the implicit built-in includes are being re-inserted for `hip-cpp-output` which shouldn't happen as it can safely presume they are part of input file ( as `-E` includes them in the output).

**Comment by pfultz2** [comment]
@yxsamliu is this an issue in clang?

**Comment by yxsamliu** [comment]
I am taking a look

**Comment by yxsamliu** [comment]
it is a clang driver bug. I will fix it. Thanks for reporting.

**Comment by robertmaynard** [comment]
Thanks for the prompt investigation! Should I close the issue?

**Comment by yxsamliu** [comment]
You can either keep it open until the fix is released, or close it now. Up to you :-)
