### ISSUE TITLE
undefined reference to `__hip_fatbin`

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#2203]
After compiling each source file using the -fgpu-rdc option into an object file, linking these object files produces the message "undefined reference to `__hip_fatbin`".  Which HIP library should I link ? 

Thanks

**Comment by yxsamliu** [comment]
you need to specify -fgpu-rdc and  --hip-link when you link these object files.

**Comment by zjin-lcf** [comment]
Thank you for the instruction

**Comment by krishoza** [comment]
I was also facing the similar error and tried the above solution but even after that I get the below error.

lld: error: undefined hidden symbol: deviceFunction()
>>> referenced by lto.tmp:(testKernel())
>>> referenced by lto.tmp:(testKernel())
clang-13: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)

**Comment by yxsamliu** [comment]
do you have a simple test to demonstrate this issue? thanks.

**Comment by krishoza** [comment]
@yxsamliu was able to resolve the issue by generating all object files using `-fgpu-rdc` and finally generating executable using `-fgpu-rdc --hip-link`.
