### ISSUE TITLE
RelWithDebInfo builds are prevented

### ISSUE THREAD

**Issue by yalue** [ROCm-Developer-Tools/HIP#2220]
Currently, HIP can only be built using `Debug` or `Release` cmake build types.  This restriction appears to be arbitrary, resulting only from a check in `CMakeLists.txt` in order to set a different default installation path for each build type.  For those of us experimenting with HIP modifications, a RelWithDebInfo build is quite useful for quickly obtaining stack trace information should a HIP application crash, while otherwise allowing the experimental build to replace the pre-built HIP installed to `/opt/rocm*`.

Modifying CMakeLists.txt to set the `RelWithDebInfo` install path to the same location as `Release` builds allows cmake to complete and HIP to install with no apparent problems.

**Comment by satyanveshd** [comment]
HIP can be built using RelWithDebInfo cmake build type and can be installed properly with the recent builds.  This can be verified with Rel 4.1 onwards.
