### ISSUE TITLE
-finstrument-functions-after-inlining linking errors with hipcc from RocM 4.0.1

### ISSUE THREAD

**Issue by wrwilliams** [ROCm-Developer-Tools/HIP#2243]
The ICE from #2178 has been fixed, so thanks for that--but there's a new bug I've discovered in trying to use this feature.

However, there's a new and interesting failure mode I've discovered, again reproducible with the Quicksilver CORAL benchmark (and almost certainly also with a trivial test case). We've known in the Score-P group for some time that hipcc attempts to add compiler instrumentation via `-finstrument-functions` to both host and device side functions, which leads to errors on the step that links host and device code from a single CU together unless empty device side functions are provided. We work around this by specifying a "-include <stubfile>" in a compiler wrapper that provides those empty device side instrumentation functions. However, if we switch to `-finstrument-functions-after-inlining` with RocM 4.0.1, we nevertheless get a linker error:
```
lld: error: undefined symbol: __cyg_profile_func_enter
>>> referenced by hipFunctions.cc:28 (/home/h4/wwilliam/Quicksilver/src/hipFunctions.cc:28)
>>>               /tmp/hipFunctions-gfx906-d1454b.o:(testname::WarmUpKernel(int))
>>> referenced by hipFunctions.cc:28 (/home/h4/wwilliam/Quicksilver/src/hipFunctions.cc:28)
>>>               /tmp/hipFunctions-gfx906-d1454b.o:(testname::WarmUpKernel(int))

lld: error: undefined symbol: __cyg_profile_func_exit
>>> referenced by hipFunctions.cc:33 (/home/h4/wwilliam/Quicksilver/src/hipFunctions.cc:33)
>>>               /tmp/hipFunctions-gfx906-d1454b.o:(testname::WarmUpKernel(int))
>>> referenced by hipFunctions.cc:33 (/home/h4/wwilliam/Quicksilver/src/hipFunctions.cc:33)
>>>               /tmp/hipFunctions-gfx906-d1454b.o:(testname::WarmUpKernel(int))
clang-12: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
[Score-P] ERROR: Execution failed: hipcc `/home/wwilliam/sw/scorep/TUD_rocm/bin/scorep-config --thread=none --mpp=none --io=none --nocuda --noonline-access --noopencl --noopenacc --nomemory --nokokkos --hip --cxxflags`   -DHAVE_HIP="1" -DMaxIt="15" -I/opt/rocm-4.0.1/include/ -g -c  -c /home/h4/wwilliam/Quicksilver/src/hipFunctions.cc -o hipFunctions.o
make: *** [hipFunctions.o] Error 1
bash-4.2$ /home/wwilliam/sw/scorep/TUD_rocm/bin/scorep-config --thread=none --mpp=none --io=none --nocuda --noonline-access --noopencl --noopenacc --nomemory --nokokkos --hip --cxxflags
 -g -finstrument-functions-after-inlining -include /home/wwilliam/sw/scorep/TUD_rocm/share/scorep/scorep_compiler_hip.inc -I/home/wwilliam/sw/scorep/TUD_rocm/include -I/home/wwilliam/sw/scorep/TUD_rocm/include/scorep
```
Note that `-finstrument-functions` continues to work fine with the same `-include /home/wwilliam/sw/scorep/TUD_rocm/share/scorep/scorep_compiler_hip.inc` workaround.

Tagging @eshcherb per his request.

**Comment by yxsamliu** [comment]
If you only need to instrument host functions, you can use -Xarch_host -finstrument-functions or -Xarch_host -finstrument-functions-after-inlining, then device code will not be instrumented.

**Comment by wrwilliams** [comment]
> If you only need to instrument host functions, you can use -Xarch_host -finstrument-functions or -Xarch_host -finstrument-functions-after-inlining, then device code will not be instrumented.

@yxsamliu This does give a good bit of progress; -Xarch_host -finstrument-functions-after-inlining compiles fine, and it appears that the inlining in instrumented builds matches the inlining in uninstrumented builds. Some of the inlining choices look questionable but that becomes a general optimization question (and I haven't yet investigated whether this is a deviation from mainline Clang).

I would still very much like instrumentation support that allows the host and device code both to use an instrumentation library at (executable/library scope) link time for simplicity's sake, but `-Xarch_host` is at least a reasonable interim solution.

**Comment by yxsamliu** [comment]
If you need device code instrumentation, you can try option --gpu-instrument-lib=x, where x is a bitcode file containing definition of __cyg_profile_func_enter/exit.

**Comment by ROCmSupport** [comment]
Hi @wrwilliams 
I request you to close this ticket if you do not have any more questions.
Feel free to open a new issue, if you get any.
Thank you.
