### ISSUE TITLE
`hiprtcCompileProgram` does not recognize the `-D` option

### ISSUE THREAD

**Issue by leofang** [ROCm-Developer-Tools/HIP#2248]
This is likely an accompanying issue of #2182, in which the compiler option `-I` is reported not working.

I am a CuPy developer reporting an hipRTC bug that we discovered. The original issue is cupy/cupy#4997. There we found hipRTC does not recognize any macros defined by appending `-D...` to the list compiler options, leading to failures in several new features that we added and will work on. CUDA's nvrtc does not have any of these issues. 

We verified this happens all the way from ROCm 3.5.0 to **the latest ROCm 4.1.0**. 

Oddly, we found that in the HIP codebase the `-D` option is used: 
https://github.com/ROCm-Developer-Tools/HIP/blob/bc102bb6dbbc7b94218a73e14f6ca9de198069e9/rocclr/hip_rtc.cpp#L222-L223
and I can verify that those two macros are defined correctly, but not any of the user-supplied ones.

Below is a C++-only reproducer, in case you need one (it's very easy to reproduce):
```c++
// test_hiprtc_macro_define.cpp
// compile with: hipcc --std=c++11 test_hiprtc_macro_define.cpp -o test_hiprtc_macro_define
#include <cassert>
#include <iostream>
#include <vector>
#include <hip/hip_runtime.h>
#include <hip/hiprtc.h>

static constexpr auto macro{
R"(
#include <hip/hip_runtime.h>
extern "C" __global__ void xyz(float* a) {
    float x = 0;
    #ifdef CUPY_JIT_MODE
    x = 1;
    #else
    x = -1;
    #endif
    a[threadIdx.x] = x;
}
)"};

int main() {
    hiprtcProgram prog;
    hiprtcCreateProgram(&prog,      // prog
                        macro,      // buffer
                        "macro.cu", // name
                        0,          // numHeaders
                        nullptr,    // headers
                        nullptr);   // includeNames
    hipDeviceProp_t props;
    int device = 0;
    hipGetDeviceProperties(&props, device);
    std::string sarg = "-DCUPY_JIT_MODE";

    const int num_options = 1;
    const char* options[1];
    options[0] = sarg.c_str();
    for (int i = 0; i < num_options; ++i)
        printf("option %d is %s\n", i, options[i]);
    hiprtcResult compileResult = hiprtcCompileProgram(prog, num_options, options);
    assert (compileResult == 0);

    size_t logSize;
    hiprtcGetProgramLogSize(prog, &logSize);

    if (logSize) {
        std::string log(logSize, '\0');
        hiprtcGetProgramLog(prog, &log[0]);
        std::cout << log << '\n';
    }

    size_t codeSize;
    hiprtcGetCodeSize(prog, &codeSize);

    std::vector<char> code(codeSize);
    hiprtcGetCode(prog, code.data());

    hiprtcDestroyProgram(&prog);

    hipModule_t module;
    hipFunction_t kernel;
    hipModuleLoadData(&module, code.data());
    hipModuleGetFunction(&kernel, module, "xyz");

    float* x;
    assert (hipMalloc(&x, 32*sizeof(*x)) == 0);
    float* x_h = new float[32];
    void* args[] = {x,};
    auto size = sizeof(args);
    void* config[] = {HIP_LAUNCH_PARAM_BUFFER_POINTER, &args,
                      HIP_LAUNCH_PARAM_BUFFER_SIZE, &size,
                      HIP_LAUNCH_PARAM_END};

    int NUM_BLOCKS = 1;
    int NUM_THREADS = 32;
    assert (0 == hipModuleLaunchKernel(
        kernel, NUM_BLOCKS, 1, 1, NUM_THREADS, 1, 1,
        0, nullptr, nullptr, config));

    hipMemcpyDtoH(x_h, x, 32*sizeof(*x));
    for (int i = 0; i < 32; i++) {
        std::cout << i << ": " << x_h[i] << std::endl;
    }

    assert (hipFree(x) == 0);
    delete[] x_h;
    std::cout << "done" << std::endl;
    return 0;
}
```
The expected output is 1 for all i, but I got -1 instead.

cc: @takagi @ROCmSupport for vis

**Comment by leofang** [comment]
Ping @cjatin (since you replied in the accompanying issue #2182)

**Comment by leofang** [comment]
> Oddly, we found that in the HIP codebase the `-D` option is used:
> 
> https://github.com/ROCm-Developer-Tools/HIP/blob/bc102bb6dbbc7b94218a73e14f6ca9de198069e9/rocclr/hip_rtc.cpp#L222-L223
> 
> 
> and I can verify that those two macros are defined correctly, but not any of the user-supplied ones.

I spoke too fast. These two macros have different values (ex: I got (3, 5) for ROCm 3.5.0, not (9, 0) as indicated in the code), so actually it's set elsewhere and `-D` is not working in the HIP codebase either...

**Comment by cjatin** [comment]
Thanks for reporting this issue and bringing it to our attention.
The issue here was that hiprtc compile command was not appending options to the compiler call.
We have fixed this in our internal build and should be available in next release.

**Comment by leofang** [comment]
Thank you for prompt reply, @cjatin! Glad to know it's noticed and fixed by the team. I have 2 more follow-up questions:
1. Does #2182 (for `-I`) have the same root cause and will also be fixed by the same patch?
2. Which "next release" did you refer to? ROCm 4.1.1 or 4.2.0? Trying to get some coordination and hot patches done.

Thanks again!

**Comment by cjatin** [comment]
1) Yes and Yes
2) It should be 4.2

**Comment by leofang** [comment]
Thanks, @cjatin! Looking forward to it. Will leave this issue open and check if it's fixed by then.

**Comment by leofang** [comment]
Hi @cjatin I confirm that like #2182 for `-I`, `-D` is also accepted by hipRTC on ROCm 4.2.0. Thanks for fixing it! I am closing this issue 🙂
