### ISSUE TITLE
[FEA] Request: Support `cuFuncSetAttribute` in HIP (to use together with hipRTC)

### ISSUE THREAD

**Issue by leofang** [ROCm-Developer-Tools/HIP#2251]
Currently there is `hipFuncSetAttribute` in the runtime API (wrapping `cudaFuncSetAttribute` in CUDA), but not in the driver API (wrapping `cuFuncSetAttribute`):
https://github.com/ROCm-Developer-Tools/HIP/blob/2080cc113a2d767352b512b9d24c0620b6dee790/docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md#L1062
This imposes a significant challenge to hipRTC, because the configs of the JIT-compiled kernels cannot be set by the runtime API, at least it is the case on CUDA: nvRTC-compiled kernels are loaded by the driver API as `CUFunction`, not as `cudaFunction_t`. The former's config can be set by the driver API `cuFuncSetAttribute`, and the latter's by the runtime API `cudaFuncSetAttribute`; they cannot be mixed and matched. 

I just tested locally with HIP and it seems to be the case too. (Sorry, no simple reproducers this time, as I'm using CuPy's C API wrappers to test this, and expect to expose such a capability to CuPy.)

**Comment by leofang** [comment]
cc: @ROCmSupport

**Comment by leofang** [comment]
cc: @emcastillo (for vis)

**Comment by leofang** [comment]
cc: @amathews-amd (for vis)

**Comment by ppanchad-amd** [comment]
@leofang , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.

**Comment by ppanchad-amd** [comment]
@leofang Closing ticket. Please re-open if you still require assistance. Thanks!
