### ISSUE TITLE
Question: Does HIP support `-ftz=true`?

### ISSUE THREAD

**Issue by leofang** [ROCm-Developer-Tools/HIP#2252]
As title. `-ftz=true` sets the rounding mode for floating-point operations to flush to zero (hence "ftz"). In CUDA we enable this compiler flag by default, but it is unclear from either the HIP documentation or behavior of actual codes generated by hipcc/hiprtc if this is possible at all. Thanks.

**Comment by leofang** [comment]
cc: @ROCmSupport

**Comment by b-sumner** [comment]
Can you comment on why you want to do this flushing?  I believe -fcuda-flush-denormals-to-zero will do what you want.

**Comment by leofang** [comment]
To test and ensure consistent behavior across CUDA and AMD GPUs. For NVIDIA GPUs, we can pass this flag to both nvcc and nvrtc, but for AMD GPUs it seems neither hipcc nor hiprtc supports this. @b-sumner My guess is that the flag (`-fcuda-flush-denormals-to-zero`) you referred to is only valid when compiling HIP codes for NVIDIA GPUs?

**Comment by yxsamliu** [comment]
-fcuda-flush-denormals-to-zero works for compiling HIP code for AMD GPUs.

**Comment by leofang** [comment]
Thank you for confirming, @yxsamliu. It's very informative because it's not documented (and it should be!). One last question: Does hiprtc (which is even less documented...) respect this flag?

**Comment by yxsamliu** [comment]
It is documented in https://clang.llvm.org/docs/ClangCommandLineReference.html

hiprtc repsects it, assuming the bug of hipRTC for not passing user specified options has been fixed.

**Comment by leofang** [comment]
Thanks a ton, @yxsamliu. I read https://rocmdocs.amd.com/en/latest/ thoroughly (well, except for the hardware specs) and it would not be possible for me to think about checking clang's documentation. I even checked LLVM's doc at https://llvm.org/docs/AMDGPUUsage.html to see if flushing denormals is possible. ROCm's docs is not developer friendly at all...
> assuming the bug of hipRTC for not passing user specified options has been fixed

I assume you are referring to `-D` (#2248) and `-I` (#2182). Good point. So this issue is actually a bug report depending on them being resolved. Let me keep this issue open until they are confirmed fixed.

**Comment by leofang** [comment]
A separate question is why not calling it `-fhip-flush-denormals-to-zero` or, following other options, `-fgpu-flush-denormals-to-zero`. This is another confusing point that a developer would not know by just reading the docs (assuming it can be found), but perhaps this should be discussed elsewhere (where?)

**Comment by yxsamliu** [comment]
> A separate question is why not calling it `-fhip-flush-denormals-to-zero` or, following other options, `-fgpu-flush-denormals-to-zero`. This is another confusing point that a developer would not know by just reading the docs (assuming it can be found), but perhaps this should be discussed elsewhere (where?)

Good point. I will try renaming it as -fgpu-flush-denormals-to-zero. Thanks.

**Comment by leofang** [comment]
> Good point. I will try renaming it as -fgpu-flush-denormals-to-zero. Thanks.

@yxsamliu Thanks! I see that it landed in https://reviews.llvm.org/D99688, any estimation for the earliest availability in official ROCm releases?

**Comment by yxsamliu** [comment]
won't take too long

**Comment by leofang** [comment]
@yxsamliu Just curious, is there a programmatic way or tool that we can use to examine the compiled hsaco binary and see if ftz is correctly set?

**Comment by yxsamliu** [comment]
denorm flush mode is part of kernel descriptor. To dump kernel descriptor

/opt/rocm/llvm/bin/llvm-objdump --disassemble-symbols=<kerne-name>.kd <codeobject-name>

kernel descriptor is documented at https://llvm.org/docs/AMDGPUUsage.html#amdhsa-kernel-directives-table

To check denorm flush mode, check amdhsa_float_denorm_mode_32 and amdhsa_float_denorm_mode_16_64 in kernel descriptor. If they are not there, their default value is off.

I don't know there is a way to check this programmatically.

**Comment by leofang** [comment]
Thanks a lot for help @yxsamliu! For some reason `--disassemble-symbols=.kd` didn't work; I had to do `-d --section=.rodata` instead.

Below is my finding with Radeon VII (gfx906). My question is half/double precision seems unaffected, is it expected?
- On ROCm 4.2:
  - `-fcuda-flush-denormals-to-zero`: 
    - `amdhsa_float_denorm_mode_32`: 0
    - `amdhsa_float_denorm_mode_16_64`: 3
  - `-fno-cuda-flush-denormals-to-zero`:
    - `amdhsa_float_denorm_mode_32`: 3    `(<-- this changed)`
    - `amdhsa_float_denorm_mode_16_64`: 3
  - `-fgpu-flush-denormals-to-zero`: does not work (compiler error)
  - `-fno-gpu-flush-denormals-to-zero`: does not work (compiler error)
- On ROCm 4.3: Nothing works so far, as `llvm-objdump` complained the generated hsaco file is not a valid object file. @amathews-amd is helping me figure out the issue.

**Comment by ppanchad-amd** [comment]
@leofang , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
