### ISSUE TITLE
Bug: HIP kernels with array size >= 2^32 do not behave correctly

### ISSUE THREAD

**Issue by leofang** [ROCm-Developer-Tools/HIP#2253]
I am reporting another bug that @emcastillo from CuPy discovered. To save some bandwidth, please see the original bug report https://github.com/cupy/cupy/pull/4461 for reproducers in both CuPy and pure C++. There the expected output is
```
23  23
```
but the actual output is not. We tested that this bug is reproducible up to the latest ROCm 4.1.0, on both MI50 and MI100.

cc: @ROCmSupport

**Comment by gandryey** [comment]
There is a limit in HW/ucode 
https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/77589727ecc4bc715ff3f6d76dcd59f4c455b8db/src/inc/hsa.h#L2931
The app could launch multidimensional grid to cover over 2^32.

**Comment by leofang** [comment]
My apology, @gandryey and @emcastillo. Apparently I am a poor messenger. The grid and block sizes given in the referenced reproducers are set to 2^32/256 and 256, respectively, so in particular the grid size does not exceed the hardware limit of 2**31-1 imposed by both NVIDIA and AMD GPUs (or the kernel launch would fail). I have changed the issue title to reflect this.

@gandryey Could you kindly take another look at the linked C++ reproducer? 🙂 Thanks.

**Comment by gandryey** [comment]
Nevertheless I believe my answer is still correct:-) AMD HW doesn't take workgroup size(well to be more precise that mode isn't supported with AQL), Hence the value will be multiplied by 256 and will have overflow after write into the packet/register. I think the latest runtime should have a check for that and return an error earlier.

**Comment by leofang** [comment]
Thank you for confirming the behavior on AMD HW, @gandryey. It sounds like a no-fix to me :-| Well that's a bummer. We have a lot of kernel templates that are used for runtime code generation, and they've been thoroughly tested on CUDA. To adopt N-D grids may require significant rewrite that we didn't anticipate...But at least we confirm it is an issue now.

**Comment by gandryey** [comment]
I'm not entirely sure why your app uses such big workloads, because even if you read a DWORD with every thread, that would address a 16GB buffer and I wouldn't suggest 1 byte access in 4GB buffer, like you have in the example: my_add(char* y)
I think 8 bytes data read/write will be the most optimal, but use at least 1 dword. Thus rewrite your kernels and probably you will find even better performance on Cuda also.

**Comment by leofang** [comment]
@gandryey I do not really understand what you mean. That example was meant to be a minimal reproducer for a failing sanity check that we routinely perform in our extensive test suite.

Think about this real-world use case: for a massive array of 32-bit integers, 2^32 elements only take 16GB (as you pointed out), so it’s already within reach for modern GPU architectures (NVIDIA or AMD) and we already see people pushing toward the limit and beyond. Now, it is just such a common idiom to launch a kernel with grid size `(2^32+256-1)/256` and block size `256`, but this is failing only on AMD hardware and is reproduced by our example. 

Another thing is we from CuPy do not determine the workload size, our users do. We are following NumPy and provide all kinds of array operations that can be done in NumPy to GPU users, and Python is a dynamical programming language that it is hard to hardwire something to prevent users from doing odd things. Moreover, even the reproducer itself is a legitimate use case and a valid code in the CUDA pogromming model, and as such it should return correct result and should not fail silently.

I'd argue that the failure is a result of the HIP programming model being either not clearly standardized or not correctly implemented on the AMD hardware. Again, both the grid and block sizes are within the limit (`hipDeviceAttributeMaxGridDimX` etc), so they are legal.

**Comment by amathews-amd** [comment]
@leofang , Is there a reason you are using this blocks and threads directly, instead of something like this: 
```
__global__ void largeKernel(..., n_block, n_total) {
  ....
  for (int i1 = blockIdx.y; i1 < n_total; i1 += gridDim.y) {

	  for (int i = threadIdx.x + threadIdx.y * blockDim.x; i < n_block; i += blockDim.x * blockDim.y) {
	  
			sum += input[i1*n_block + i];
			
	  }
  }
  ...
}
```
n_block is data processed by a block 
n_total is total data processed

See https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/contrib_ops/cuda/layer_norm_impl.cu#L323 for an example.

**Comment by leofang** [comment]
Hi @amathews-amd, sorry I dropped the ball here.
> Is there a reason you are using this blocks and threads directly, instead of something like this:

Let me say this upfront since we've been having a very smooth communication lately. Nothing personal here, but seriously, you guys are not making sense throughout the discussion. 

The whole point of AMD creating the HIP layer, IIUC, is to prevent developers from having to rewrite their codebase in order to port to AMD GPUs. I believe --- correct me if I am wrong --- that your business goal has been set up such that "whatever runs on NVIDIA GPUs should also run on AMD GPUs". But this issue proves that it's not the case. 

There are a ton of code --- not just from CuPy but also from other HPC/ML applications that I know of --- relying on a simple 1D grid-block being able to handle > 2^32 elements. What you're suggesting simply means a total breakdown of this assumption and a complete rewrite of these codes. It requires not only changes in the device/kernel code but also the host kernel-launch logics. Why do I have to use a 2D block when 1D blocks can express my algorithms and logics natively? You're putting the burden on your customers.

I would suggest you to prioritize on resolving this issue, because there are serious user needs that have been surging on the CUDA side. Look at Thrust/CUB, in a future version they will fully support 64-bit indexing (https://github.com/NVIDIA/cub/issues/212) for those that need to process excessive workloads. If you don't take it seriously now, I can assure you that rocThrust/rocPRIM will run into a ton of troubles when the CUDA folks make it up and running.

**Comment by amathews-amd** [comment]
Internal ticket: https://ontrack-internal.amd.com/browse/SWDEV-297185

**Comment by ppanchad-amd** [comment]
It won't be implemented. HIP relies on the HW/HSA spec, which doesn't support those grids. Closing ticket.
