### ISSUE TITLE
Unable to run square example generated by HIP on gfx902

### ISSUE THREAD

**Issue by mbozdogansw** [ROCm-Developer-Tools/HIP#2254]
I am trying to convert a simple CUDA code to HIP to be able to run it on V1000. I can compile and run cl code on the CPU&GPU. Actually GPU is not recognised since the GPU is embedded, but I can see the difference(with or without GPU support) when I use benchmark tests on it. I tried to compile it via ROCM 4.1, the gfx902 is not even in the supported device list(gputable.txt). So, I could generate HIP code but I could not compile it. I tried different versions of ROCM. I could generate executable via version 2.6, but I got the error below. I do not know what I am doing wrong. Thank you for your advice.

**Device Info :**
===============
https://www.ibase.com.tw/english/download/Embedded_Computing/Disk-Size_SBCs/IB918_Datasheet.pdf
AMD Ryzen Embedded V1000
AMD Raden Vega integrated
Device name: pthread-AMD Ryzen Embedded V1605B with Radeon Vega Gfx

**ERROR**
===============
**$ ./square.out** 
GPU device 0 doesn't not exist
Aborted (core dumped)

 Info
===============
**$ /opt/rocm/bin/rocm_agent_enumerator** 
gfx000

**sudo dmesg | grep gfx**
[    5.872901] [drm] add ip block number 4 <gfx_v9_0>

**$ /opt/rocm/bin/rocminfo**
ROCk module is loaded
user is member of video group
  
HSA System Attributes    

Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

HSA Agents               
   
Agent 1            
   
  Name:                    AMD Ryzen Embedded V1605B with Radeon Vega Gfx
  Marketing Name:          AMD Ryzen Embedded V1605B with Radeon Vega Gfx
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2000                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            8                                  
  SIMDs per CU:            4                                  
  Shader Engines:          1                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    16776832(0xfffe80) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16776832(0xfffe80) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
  ISA Info:                
    N/A                      
*** Done ***

**Comment by mysoreanoop** [comment]
Did you figure out what was wrong?

**Comment by ppanchad-amd** [comment]
@mbozdogan-SwissVault , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
