### ISSUE TITLE
HIP_ROCCLR_HOME potentially used incorrectly in hipcc

### ISSUE THREAD

**Issue by haampie** [ROCm-Developer-Tools/HIP#2256]
The 4.1.0 release changed how env / config variables are set, which is related to #2224.

Currently `HIP_ROCCLR_HOME` is used in `hipcc` to compute:

- `DEVICE_LIBPATH` -- this is overridden a few lines later with `$ROCM_PATH/amdgcn/bitcode`
- `HIP_INCLUDE_PATH` -- this is overridden with `$HIP_PATH/include`
- `HIP_LIB_PATH` -- this is *not* overridden and defaults `$HIP_ROCCLR_HOME/lib`

`HIP_LIB_PATH` is used to set the `-L ...` flag, which is used so that linking `-lamdhip64` works by default.

The problem is that `HIP_LIB_PATH` currently points to `$HIP_ROCCLR_HOME/lib` if not set as an environment variable:

```perl
if (!defined $HIP_LIB_PATH) {
    $HIP_LIB_PATH = "$HIP_ROCCLR_HOME/lib";
}
```

which is incorrect, because that folder does not have `libamdhip64.so`:

```console
path/to/hip-rocclr-4.1.0-u6jg27pd6e2foenlqjte3julsuex2r3a/lib $ ls
cmake  libamdrocclr_static.a
```

It should point to `$HIP_PATH/lib`

```console
path/to/hip-4.1.0-upqzah3svncjsrexw766rzklimzl7uj2/lib $ ls
cmake  hip_prof_str.h  libamdhip64.so  libamdhip64.so.4  libamdhip64.so.4.1.0
```

Of course I can work around this by setting the `HIP_LIB_PATH` variable... but this begs the question what the point of all Perl scripts is if I ultimately have to set all environment variables myself?

Could you potentially make a spack install part of your new release testing? It's a good way to figure out if the ROCm packages work when all subprojects are installed into separate directories instead of sharing a particular prefix `/opt/rocm-x.y.z`, and it would be a great way to test whether paths are correctly "computed" or whether they rely on everything being installed in the same prefix folder.

**Comment by haampie** [comment]
Hm, and it seems `HIP_ROCCLR_HOME` is used to locate `.hipInfo`, but that file is installed as part of this repository, not https://github.com/ROCm-Developer-Tools/ROCclr/search?q=hipInfo? At least that's the case on my rocm installation.

```
if (defined $HIP_ROCCLR_HOME) {
    $HIP_INFO_PATH= "$HIP_ROCCLR_HOME/lib/.hipInfo";
} else {
    $HIP_INFO_PATH= "$HIP_PATH/lib/.hipInfo"; # use actual file
}
```

Is that a bug?

**Comment by louisespellacy-arm** [comment]
The use of `$HIP_ROCCLR_HOME` also causes a warning in the `$HIP_PLATFORM=nvidia` case as this variable is not defined but is used without being checked:
```
Use of uninitialized value $HIP_ROCCLR_HOME in concatenation (.) or string at /opt/rocm-4.1.0/hip/bin/hipcc line 120.
Use of uninitialized value $HIP_ROCCLR_HOME in concatenation (.) or string at /opt/rocm-4.1.0/hip/bin/hipcc line 123.
Use of uninitialized value $HIP_ROCCLR_HOME in concatenation (.) or string at /opt/rocm-4.1.0/hip/bin/hipcc line 125.
```

**Comment by cjatin** [comment]
@haampie 

> The problem is that HIP_LIB_PATH currently points to $HIP_ROCCLR_HOME/lib if not set as an environment variable:

HIP_ROCCLR_HOME should point to hip installation path, not the rocclr's, I guess the name is confusing.

`if (-e "$hipvars_dir/../lib/bitcode") {
    $HIP_ROCCLR_HOME = Cwd::abs_path($hipvars_dir . "/..");
} else {
    $HIP_ROCCLR_HOME = $HIP_PATH; # use HIP_PATH
}`
HIP_ROCCLR_HOME should point in the end towards HIP_PATH and it should find .hipInfo there.

We do have some cases of unused if conditions in hipcc script which should be removed.

@louisespellacy-arm 
Thats an issue and it will be added under a condition (HIP_PLATFORM == amd) to fix that.
