### ISSUE TITLE
WCG OpenPandemics Covid-19: GPU errors on Centos 7/ROCm 4/Radeon Instinct Mi50

### ISSUE THREAD

**Issue by valtercv** [ROCm-Developer-Tools/HIP#2258]
Hi there, recently World Community Grid have released a GPU application for their OpenPandemics project, I just tried to run it on a server (Centos 7/ROCm 4/Radeon Instinct Mi50), got the following error (other projects/applications work smoothly)

<message>
process exited with code 193 (0xc1, -63)</message>
<stderr_txt>
../../projects/www.worldcommunitygrid.org/wcgrid_opng_autodockgpu_7.28_x86_64-pc-linux-gnu__opencl_ati_102 -jobs OPNG_0000385_00351.job -input OPNG_0000385_00351.zip -seed 893067284 -wcgruns 1500 -wcgdpf 30
INFO: Using gpu device from app init data 4
INFO:[10:21:25] Start AutoGrid...

autogrid4: Successful Completion.
INFO:[10:21:28] End AutoGrid...
INFO:[10:21:29] Start AutoDock for ZINC000423302842_1-ACR2.8_RX1--fr2266benz_001--CYS114.dpf(Job #0)...
OpenCL device: gfx906
Memory access fault by GPU node-5 (Agent handle: 0x64a7b10) on address 0x7f954e5f0000. Reason: Page not present or supervisor privilege.
SIGABRT: abort called
Stack trace (9 frames):
../../projects/www.worldcommunitygrid.org/wcgrid_opng_autodockgpu_7.28_x86_64-pc-linux-gnu__opencl_ati_102[0x4532b2]
/lib64/libpthread.so.0(+0xf630)[0x7f996ca1b630]
/lib64/libc.so.6(gsignal+0x37)[0x7f996c674387]
/lib64/libc.so.6(abort+0x148)[0x7f996c675a78]
/opt/rocm/lib/../opencl/lib/../../lib/libhsa-runtime64.so.1(+0x63776)[0x7f99652e8776]
/opt/rocm/lib/../opencl/lib/../../lib/libhsa-runtime64.so.1(+0x6569b)[0x7f99652ea69b]
/opt/rocm/lib/../opencl/lib/../../lib/libhsa-runtime64.so.1(+0x166c7)[0x7f996529b6c7]
/lib64/libpthread.so.0(+0x7ea5)[0x7f996ca13ea5]
/lib64/libc.so.6(clone+0x6d)[0x7f996c73c8dd]

Exiting...

</stderr_txt>

**Comment by ppanchad-amd** [comment]
@valtercv , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
