### ISSUE TITLE
HIP + ELFIO (in rocclr, in HIP and upstream) = a bit of a mess.

### ISSUE THREAD

**Issue by Artem-B** [ROCm-Developer-Tools/HIP#2259]
AMD has recentrly introduced a lot of new ELF flags.

These flags made it into:
- ROCclr's copy or ELFIO: https://github.com/ROCm-Developer-Tools/ROCclr/commit/ce9f696cfe038ed6d923838c5ed344c91a0d3194
- upstream LLVM: https://github.com/llvm/llvm-project/commit/f4ace6373747a661ebdae7a14f9e510c7adfea4e

Eventually HIP's own code started using them: https://github.com/ROCm-Developer-Tools/HIP/commit/c4beefe00b1dfa0100f02a9e99d4ea4fb52873da#diff-a5d22ac1ef5d8869cdff986cfeb4d69f3bfe99ce4ff57469df6f8684de3137fa

The problem is that HIP's own copy of elfio does *not* have these constants: https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-4.1.x/include/hip/hcc_detail/elfio/elf_types.hpp I guess the only reason HIP builds now is that it picks up ROCclr's copy of ELFIO headers. If that's intentional, then it's not clear why the old copy of elfio still hangs around in HIP.

Nor did these constants make it into upstream ELFIO: https://github.com/serge1/ELFIO/blob/master/elfio/elf_types.hpp

It would be great to have these new ELF constants upstreamed to https://github.com/serge1/ELFIO/ and just use it as an external dependency. Compiling code using multiple different versions of the same library is a pretty good way to buy fair amount of trouble (ODR violations are never fun to troubleshoot). Using a private copy of a public library is double so as that would cause trouble for the end users who may need to use the upstream version of the ELFIO library.

**Comment by ppanchad-amd** [comment]
@Artem-B , Sorry for the lack of response. Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.

**Comment by Artem-B** [comment]
ROCclr is gone, so I guess the issue is obsolete now.

**Comment by b-sumner** [comment]
ROCclr is now part of this repo: https://github.com/ROCm/clr
