### ISSUE TITLE
Does hip support culinkcreate, cuLinkAddFile,cuLinkAddData,cuLinkComplete,cuLinkDestroy in Cuda?

### ISSUE THREAD

**Issue by SomnusMistletoe** [ROCm-Developer-Tools/HIP#2263]
@rocmamd 
Does hip support culinkcreate, cuLinkAddFile,cuLinkAddData,cuLinkComplete,cuLinkDestroy in Cuda?
Thank you.

**Comment by leofang** [comment]
I don't think so: https://rocmdocs.amd.com/en/latest/Programming_Guides/CUDAAPIHIP.html#module-management

**Comment by SomnusMistletoe** [comment]
hello @leofang ,
I know the existence of hiprtc and how to use the related functions of hipmodule. However, according to this picture and the test program I wrote on hip4.1.1, hip does not support linking the generated code with the static library and loading it into the moudle, in which process, link related functions will be used, as CUDA provides: culinkcreate, culinkaddfile, culinkadddata, cuLinkComplete,cuLinkDestroy. I don't know if I'm right. 
![image](https://user-images.githubusercontent.com/45657731/118914116-3fe4fa00-b95d-11eb-8df8-50f5fe7e516a.png)
Thank you.
Best Regards.
