### ISSUE TITLE
Using hipcc with self build LLVM: hipErrorNoBinaryForGpu

### ISSUE THREAD

**Issue by brad-mengchi** [ROCm-Developer-Tools/HIP#2268]
Hi all,

I tried to build LLVM and link hipcc to use my self-built LLVM for vectorAdd example in HIP-Examples but got an error during execution vectorAdd_hip.exe on a Vega gfx600 GPU:

/src/external/hip-on-vdi/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")
Makefile:30: recipe for target 'test' failed
make: *** [test] Aborted (core dumped)

I use ROCm 4.0.0 with ubuntu.
My LLVM is from https://github.com/RadeonOpenCompute/llvm-project amd-stg-open branch.
I tried to compile LLVM with the command:

cd build && cmake    -DCMAKE_BUILD_TYPE=Release    -DCMAKE_INSTALL_PREFIX=<installpath>     -DLLVM_ENABLE_PROJECTS="clang;old;compiler-rt"    -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86;NVPTX" -DLLVM_ENABLE_ASSERTIONS=On    ../llvm && make

Then I configure export HIP_CLANG_PATH=<installpath>\bin.

Then I compile the vectorAdd in https://github.com/ROCm-Developer-Tools/HIP-Examples and got the error when running the vectorAdd_hip.exe.

I also found that in https://github.com/ROCm-Developer-Tools/HIP/issues/2166, @passingglance found that the target device name is wrong "-gfx900" instead of "gfx900". But I do not find a solution to solve this.

I also noticed the same thing with the bundle file generated from extractkernel:
Using my LLVM, the bundle file shows arch as hipv4-amdgcn-amd-amdhsa--gfx900
Using ubuntu installed ROCm/llvm in /opt/rocm/llvm/bin, the bundle file shows arch as hip-amdgcn-amd-amdhsa-gfx900.

Does anyone know this is a compiler bug or misconfiguration(more possible since I am a newbie to LLVM)?

**Comment by yxsamliu** [comment]
You need release/rocm-rel-4.0 branch to work with ROCm 4.0 runtime.

**Comment by brad-mengchi** [comment]
Hi @yxsamliu, thanks for your answer, but do you mean rocm-4.0.0 branch?
I do not find release/rocm-rel-4.0 branch in https://github.com/RadeonOpenCompute/llvm-project.

Thanks!

**Comment by yxsamliu** [comment]
rocm-4.0.0 branch should be fine

**Comment by brad-mengchi** [comment]
Thanks, @yxsamliu, rocm-4.0.0 works fine for me.
