### ISSUE TITLE
Causes of hipErrorSharedObjectInitFailed during hipModuleLoadData

### ISSUE THREAD

**Issue by raikonenfnu** [ROCm-Developer-Tools/HIP#2269]
Hey guys,

I have been trying to generate hsaco code from MLIR inspired from https://github.com/ROCmSoftwarePlatform/llvm-project-mlir, I have been able to successfully generate "some" hsaco code. 

But for some reason when I try loading it with hipModuleLoadData, it keeps on throwing error 303(hipErrorSharedObjectInitFailed). I was just wondering what are all the possible causes/root problems for this specific error? 

Thanks in advance! :)

**Comment by yxsamliu** [comment]
It would be helpful if you could run with env var AMD_LOG_LEVEL=3 and paste the output

**Comment by raikonenfnu** [comment]
@yxsamliu Hey Sam, thanks for the quick reply. I tried doing that, but even after AMD_LOG_LEVEL=3, it doesn't seem to output anything extra 🤔

**Comment by raikonenfnu** [comment]
@yxsamliu If it helps this is the ISA I am converting to hsaco code from:
[add_gcn.s.zip](https://github.com/ROCm-Developer-Tools/HIP/files/6430609/add_gcn.s.zip)

I am trying to get it to run on gfx908
