### ISSUE TITLE
Compile C++ code and extern to "C" shared libraries for python

### ISSUE THREAD

**Issue by ahadji05** [ROCm-Developer-Tools/HIP#2273]
Hi,

What are the recommended flags to use for creating a shared library for python, using the HIPCC compiler?
I use technologies like rocFFT, rocThrust, and HIP.

In the past, I did the same using NVCC for an equivalent C++/CUDA code.
Then, I had to use the flags:
-shared
-fPIC
-Xcompiler

Is there an equivalent to -Xcompiler flag for HIPCC?

Also, my GPU is a Radeon RX 570, do I need to use a specific flag to target this architecture?

For example, for my NVIDIA k5200 GPU I had to use -arch=sm_35

Thank u in advance,
Andreas

**Comment by yxsamliu** [comment]
You need will need -shared -fPIC. hipcc does not need -Xcompiler. For any options passed through -Xcompiler, usually you can pass directly to hipcc.

hipcc use --offload-arch= to specify GPU arch. If you compile on the machine with AMD GPU, hipcc is supposed to identify your GPU arch by executing /opt/rocm/bin/rocm_agent_enumerator and sets proper --offload-arch automatically.

According to https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support , ROCm is enabled for RX570 but full support is not guaranteed.

**Comment by ahadji05** [comment]
@yxsamliu Thank you, that was thorough!
