### ISSUE TITLE
[DOC] Request: Document hipRTC

### ISSUE THREAD

**Issue by leofang** [ROCm-Developer-Tools/HIP#2276]
Currently hipRTC works out of box on AMD GPUs, and CuPy relies on it as it is so much faster than calling `hipcc` via subprocesses. It is a critical component for Python GPU libraries to provide reasonable JIT performance. 

However, currently it is an undocumented, "hidden" HIP feature, in the sense that it's not mentioned anywhere in the ROCm or HIP related repos, nor on the official website https://rocmdocs.amd.com/. Only those adventurous enough (like me) who are willing to dig into the source code would discover it. 

As a result, I am writing to kindly ask the team to add documentation for hipRTC. The main purpose is 3-fold:
1. To signal its existence to both experienced and new developers. 
2. Following the excellent [NVRTC documentation](https://docs.nvidia.com/cuda/nvrtc/index.html) to lay out clearly what's supported (compiler options, archs, limitations such as #268, etc) and what's not, and give example codes. This also helps stabilize the API (and potentially ABI, which CUDA took several iterations to settle on).
3. This shows a long-term commitment to maintain its support, so that more downstream projects are willing to depend on it without worrying any lifetime issues.

cc: @ROCmSupport @amathews-amd (for vis)

**Comment by cjatin** [comment]
https://rocm.docs.amd.com/projects/HIP/en/latest/user_guide/hip_rtc.html
