### ISSUE TITLE
How to get the ID of current CU?

### ISSUE THREAD

**Issue by zz-Malfurion** [ROCm-Developer-Tools/HIP#2279]
CUDA can use
```
asm volatile("mov.u32 %0, %%smid;" : "=r"(smid));    
```
to get the unique ID of the SM which is executing this command.

Does HIP have an API like that to get the ID of the current CU?

BTW, I'm using a Vega 7nm GPU.

**Comment by b-sumner** [comment]
@zz-Malfurion are you aware that dispatches can be preempted and restored to different compute units?   Thus the HW IDs cannot be assumed constant for the lifetime of the wavefront or block/work-group.  If that is a requirement, then you will need some other kind if ID.

FWIW, if you are programming in HIP, an __smid() function is available but must be considered a snapshot.

**Comment by zz-Malfurion** [comment]
@b-sumner  Thanks for your reply. `__smid()` is exactly what I'm looking for.

Since you have mentioned the dispatches can be preempted, are there any documents about the preemption mechanism?
