### ISSUE TITLE
[HIPIFY] No option to disable building hipify

### ISSUE THREAD

**Issue by ChrisKitching** [ROCm-Developer-Tools/HIP#228]
Some people presumably don't care about hipify, and it has several dependenceis (llvm, FileCheck, etc.). There's probably value in having a cmake option to turn the whole thing off.

**Comment by emankov** [comment]
hipify-clang is not built with HIP by default, -DHIPIFY_CLANG_LLVM_DIR should be set to build it. The define is necessary of course for building hipify-clang standalone.

**Comment by mangupta** [comment]
I think #225 fixes this.
