### ISSUE TITLE
each sample code can be compiled but  none of them can run

### ISSUE THREAD

**Issue by jimurk** [ROCm-Developer-Tools/HIP#2281]
I downloaded the code, tried the samples, each of them can be compiled, but none of them can run. what's wrong with my operation? Can anyone give some suggestion or tip? Here are my hipcc and the output of two samples' compilation&execution.

[xxx build]$ hipcc --version
HIP version: 4.0.21112-7433ef47
clang version 12.0.0 (http://10.0.100.3/dcutoolkit/driverruntime/llvm-project.git f816f1d344d7e4e0e21fc9d134c1b82e12e972f5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/dtk-21.04/llvm/bin

1 HIP-main/samples/1_Utils/hipInfo/:
[xxx build]$ cmake ..
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jianliheng/HIP-main/samples/1_Utils/hipInfo/build
[xxx build]$ make
Scanning dependencies of target hipInfo
[ 50%] Building CXX object CMakeFiles/hipInfo.dir/hipInfo.cpp.o
[100%] Linking CXX executable hipInfo
[100%] Built target hipInfo
[xxx build]$ ./hipInfo 
error: 'hipErrorNoDevice'(100) at /home/jianliheng/HIP-main/samples/1_Utils/hipInfo/hipInfo.cpp:206
error: API returned error code.
error: TEST FAILED

2 HIP-main/samples/1_Utils/hipBusBandwidth
[xxx build]$ cmake ..
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jianliheng/HIP-main/samples/1_Utils/hipBusBandwidth/build
[xxx build]$ make
Scanning dependencies of target hipBusBandwidth
[ 33%] Building CXX object CMakeFiles/hipBusBandwidth.dir/hipBusBandwidth.cpp.o
[ 66%] Building CXX object CMakeFiles/hipBusBandwidth.dir/ResultDatabase.cpp.o
[100%] Linking CXX executable hipBusBandwidth
[100%] Built target hipBusBandwidth
[xxx build]$ ./hipBusBandwidth 
 Mem=0.0GB #CUs=0 Freq=197Mhz  MallocMode=pinned
Segmentation fault (core dumped)

**Comment by xuhuisheng** [comment]
There is an error hipErrorNoDevice.
Make sure you have already an AMD gpu, like vega56,64,radeon7.
try /opt/rocm/bin/rocminfo to get more info.

**Comment by cjatin** [comment]
can you share the rocminfo output.

**Comment by jimurk** [comment]
The following is rocminfo output:
ROCk module is loaded
Able to open /dev/kfd read-write
hsa api call failure at: /data/jenkins_workspace/workspace/rocminfo_21.04_DCU2/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

**Comment by xuhuisheng** [comment]
I guess you may use an unsupport GPU.
You could `dmesg | grep kfd` to see if there is any error info.

**Comment by jimurk** [comment]
it is a problem of user&file access permission.
thanks, @xuhuisheng @cjatin
