### ISSUE TITLE
Error defining a global device variable in one object file and using it in another

### ISSUE THREAD

**Issue by colleeneb** [ROCm-Developer-Tools/HIP#2282]
# Issue
I see an error when I define a global device variable in one object file and then use it in another. A simple version of the code that showed the issue is https://github.com/colleeneb/linking_issue .  The code and compilation work with CUDA but not HIP. Is this expected to work or not?

# More details about the example
In the example (https://github.com/colleeneb/linking_issue ), there's a global device variable `inv_scal_fact`, but after compiling, it looks like the symbol is local (from using `nm`--the varibale is marked "b" and not "B"), and when it's linked to another file that uses `inv_scal_fact`, it fails to link since `inv_scal_fact` cannot be found.

```
> hipcc -c -fgpu-rdc GPU_HGP_kernels.cpp
> hipcc -c -fgpu-rdc scf.cpp
> hipcc -fgpu-rdc scf.o GPU_HGP_kernels.o
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /tmp/scf-a5dde1.o: in function `main':
scf.cpp:(.text+0x5): undefined reference to `genfock::CUDA_GPU::inv_scal_fact'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```
The version of HIP I'm using is 
```
> hipcc --version
HIP version: 4.2.21155-37cb3a34
clang version 12.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.2.0 21161 b204d7f0cae65b6cd4446eec50fc1fb675d582af)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-4.2.0/llvm/bin
```

**Comment by yxsamliu** [comment]
This is a known issue about shadow variable linkage which has been fixed by https://reviews.llvm.org/D95901

The fix should be available in a future release of ROCm.

**Comment by colleeneb** [comment]
Thanks!

**Comment by ppanchad-amd** [comment]
@colleeneb, Please try latest ROCm 6.0.2 (HIP 6.0.32831) to see if your issue still exists? If resolved, please close the ticket. Thanks.
