### ISSUE TITLE
Extremely long compilation time and huge memory usage

### ISSUE THREAD

**Issue by lahwaacz** [ROCm-Developer-Tools/HIP#2285]
We have a code which hipcc cannot compile reasonably fast: the compilation takes several __days__, memory usage quickly grows over __24 GB__ and the final binary has over __1 GB__. For comparison, an equivalent unit test for CUDA is compiled by nvcc in the order of minutes, memory usage is only several GBs and the final binary has less than 100 MB.

The code is a unit test for [expression templates](https://en.wikipedia.org/wiki/Expression_templates) for vectors on a GPU implemented in the [TNL library](https://mmg-gitlab.fjfi.cvut.cz/gitlab/tnl/tnl-dev). The library is fully functional with CUDA and adding HIP support is a work in progress, but we cannot proceed due to this issue. A case for reproducing the issue is described below (other unit tests are currently disabled in the cmake configuration to minimize the problem):

1. Start a [docker container](https://github.com/RadeonOpenCompute/ROCm-docker):

       sudo docker pull rocm/rocm-terminal
       sudo docker run -it --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video rocm/rocm-terminal

2. Install a newer version of cmake in the container:

       curl -LO https://github.com/Kitware/CMake/releases/download/v3.20.3/cmake-3.20.3-linux-x86_64.sh
       chmod +x cmake-3.20.3-linux-x86_64.sh
       sudo ./cmake-3.20.3-linux-x86_64.sh --skip-license --prefix=/usr

3. Clone and build TNL:

       git clone --branch=TO/Hip https://mmg-gitlab.fjfi.cvut.cz/gitlab/tnl/tnl-dev.git
       cd tnl-dev
       ./install --no-release --with-mpi=no --with-cuda=no --with-hip=yes --with-hip-platform=hcc tests

Let us know if we are doing something evidently wrong, otherwise please confirm that hipcc needs to be optimized.

**Comment by yxsamliu** [comment]
The excessive compilation time was due to hipcc by default inline all functions for device code for performance. We plan to turn this off in the future. Before that happens, you can pass option --hipcc-func-supp to hipcc to turn off inline all.

**Comment by lahwaacz** [comment]
Thanks, that helps: compilation dropped to the order of minutes with `--hipcc-func-supp`. Is the flag documented somewhere? Also please let us know when the default behaviour is changed.

I'm also wondering about the performance impact of  `--hipcc-func-supp`. I assume it does not mean "inline nothing at all", or does it?

**Comment by yxsamliu** [comment]
It is not documented. Will document it.

--hipcc-func-supp uses default inline threshold of llvm.
