### ISSUE TITLE
Outdated documentation in this repository

### ISSUE THREAD

**Issue by lahwaacz** [ROCm-Developer-Tools/HIP#2287]
It should be noted that [documentation provided in this repository](https://github.com/ROCm-Developer-Tools/HIP/tree/main/docs) is outdated and does not correspond to the [rocmdocs.amd.com](https://rocmdocs.amd.com/en/latest/index.html) website, which is built from https://github.com/RadeonOpenCompute/ROCm_Documentation. Preferably, the outdated documents should be removed and users should be clearly pointed out to the valid guides.

**Comment by ppanchad-amd** [comment]
@lahwaacz, Sorry for the lack of response.  An internal ticket has been created to address this issue. Thanks!

**Comment by ppanchad-amd** [comment]
@lahwaacz Last commit in the branch https://github.com/ROCm/HIP/tree/main is 3 years old. It is a stale branch. 
The default HIP branch is now https://github.com/ROCm/HIP/tree/develop
