### ISSUE TITLE
Can not stop program when using hipcc as compiler for "non-void function does not return a value"

### ISSUE THREAD

**Issue by genshen** [ROCm-Developer-Tools/HIP#2288]
I use hipcc as compiler to compile a small piece of code, its behavior is strange.  
In the code, I declared a function with return type `int`, but I does not give a return value in its implementation.

The compiling progress works fine but a warning message.
But when I run the program, the system will run the program again an again.  
Note, the  behavior does not exists under clang or gcc compiler.  
Maybe the hipcc compiler show give user a compiling error,  or show "Illegal instruction" when running it (just like clang).

compiles version:
```log
$ hipcc --version
/usr/bin/env: python3: No such file or directory
HIP version: 4.1.21072-c3eb5ccc
clang version 12.0.0 (/src/external/llvm-project/clang 91c055b1c52a830317cae78986d0d74e433864c6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /public/software/compiler/rocm/rocm-4.1.0/llvm/bin

$ clang --version
clang version 12.0.0 (/src/external/llvm-project/clang 91c055b1c52a830317cae78986d0d74e433864c6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /public/software/compiler/rocm/rocm-4.1.0/llvm/bin

$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

m.cpp
```cpp
#include <iostream>

#include <stdio.h>

int rand_num() {
  int rand_ = rand();
  printf("rand: %d\n", rand_);
// return 0; // I forget return a value.
}

int main() {
  rand_num();
return 0;
}
```

1. When I compile and run with g++, it works ok.
   ```bash
   $ g++ ./m.cpp 
   $ ./a.out 
   rand: 1804289383
   ```
2.  with clang:
    ```bash
    $ clang++ m.cpp 
    m.cpp:9:1: warning: non-void function does not return a value [-Wreturn-type]
    }
    ^
    1 warning generated.
    $ ./a.out 
    rand: 1804289383
    Illegal instruction
    ```
3. hipcc
    ```log
    $ hipcc m.cpp
    m.cpp:9:1: warning: non-void function does not return a value [-Wreturn-type]
    }
    ^
    1 warning generated when compiling for gfx803.
    m.cpp:9:1: warning: non-void function does not return a value [-Wreturn-type]
    }
    ^
    1 warning generated when compiling for host.

    $ ./a.out > log.log
    ls -al log.log  -h
    -rw-rw-r-- 1 genshen genshen 81M Jun  9 23:51 log.log
    $ head log.log 
    rand: 1804289383
    rand: 846930886
    rand: 1681692777
    rand: 1714636915
    rand: 1957747793
    rand: 424238335
    rand: 719885386
    rand: 1649760492
    rand: 596516649
    rand: 1189641421
    ```

**Comment by yxsamliu** [comment]
hipcc by default uses -O3 to match nvcc behavior. clang by default uses -O0. If you use clang++ -O3, the program may behave similarly.

**Comment by ex-rzr** [comment]
As far as I remember this is undefined behavior.
So all three compilers can do whatever they want :)
It could be a coincidence that clang++ and hipcc behave differently as hipcc calls clang. I guess it can be caused by different options passed to clang by hipcc.

**Comment by genshen** [comment]
> hipcc by default uses -O3 to match nvcc behavior. clang by default uses -O0. If you use clang++ -O3, the program may behave similarly.

Thanks for your nice reply. The difference is  -O3/-O0 optimization option (It has the same results when I use `clang++ -O3`).
