### ISSUE TITLE
weird error about blockIdx.x & gridDim.x

### ISSUE THREAD

**Issue by jimurk** [ROCm-Developer-Tools/HIP#2299]
I am porting some cuda functions, which works well on nvidia gpu+cuda, to hip. I have a kernel with a small snippet of code as following. When i tested with a configuration of thread grid(1, 1) and thread block(16, 16), the right execution should be running into the code block of if 5 after if 1/2/3/4 testing (just testing the condition, not running into their blocks), but the real execution ran into code block of if 3. I debugged and retyped this code snippet to eliminate the effecting of text coding, then found that the problem was condition testting of if 2. If the condition test of if 2 is removed or a printf() is added in block of if 2 althrough code of if 2 won't be executed, then everything is all right. printf() shows that blockIdx.y is 0 and gridDim.y is 1, there is no signs of error. Can anyone give some clues to this weird problem?

code:
  if (blockIdx.x < gridDim.x - 1) {  // if 1
    ...
  }
  if (blockIdx.y < gridDim.y - 1) {  // if 2
    ...
  }

  if (blockIdx.y < gridDim.y - 1) {  // if 3 
    ...
  }
  else if (blockIdx.x < gridDim.x - 1) {  // if 4
    ...
  }
  else {  // if 5
    ...
  }

**Comment by cjatin** [comment]
Hello,
Can you post the full sample with launch config as well.

**Comment by jimurk** [comment]
The launch configuration is  thread grid(1, 1) and thread block(16, 16), the full execution logic of my kernel is as following:
 
![Screenshot from 2021-07-19 10-13-09](https://user-images.githubusercontent.com/12459403/126093134-90b60fcf-7ec4-4d06-9220-7f8c630bfcad.png)

**Comment by ppanchad-amd** [comment]
@jimurk Is this still an issue for you? If resolved, please close ticket. Thanks!
