### ISSUE TITLE
HIPCC support ccache to accelerate compiling

### ISSUE THREAD

**Issue by qili93** [ROCm-Developer-Tools/HIP#2300]
NVCC supports ccache and using 

```CUDA_NVCC_EXECUTABLE="/usr/local/bin/ccache /usr/local/cuda/bin/nvcc"```

Does HIPCC supports using ccache as well, such as setting 

```set(HIP_HIPCC_EXECUTABLE "/usr/local/bin/ccache ${HIP_HIPCC_EXECUTABLE}")```

While seems cmake error thrown after the above change to HIP_HIPCC_EXECUTABLE.

**Comment by ppanchad-amd** [comment]
@qili93 Sorry for the lack of response.  At the moment, this is not supported.  Thanks!
