### ISSUE TITLE
How do I add HIP support to existing cmake project ?

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#231]
I have cmake project - would like to add some HIP files to it. So, I guess the compiler needs
to change for the project ? What is the best way of doing this ?

**Comment by bensander** [comment]
Easiest approach would be to change the compiler to "hipcc" - this will automatically detect the plaform and use the right compiler/includes/define for either ROCm or CUDA.  With this approach,  code will be compiled with HIPCC.   Another approach sometimes used for large projects is to partition the files which define or call GPU kernels and compile only those files with hipcc, and the rest with a different host compiler such as g++.

**Comment by boxerab** [comment]
Thanks, will give that a try.

**Comment by boxerab** [comment]
Solution from cmake user group is:

   `find_package(hcc PATHS /opt/rocm/hcc)`
and then
   CXX=hcc

Perhaps this can be added to the documentation somewhere ?

**Comment by pfultz2** [comment]
> Solution from cmake user group is to include a find_package for hcc, because it doesn't lie on a default path:

Thats just for the hcc runtime. You can do `find_package(hip PATHS /opt/rocm)` for the HIP runtime, but its only supported for hcc right now. If you want to support both cuda and hcc, you can just set the compiler to the `hipcc` wrapper with:

```
CXX=/opt/rocm/bin/hipcc cmake ..
```

**Comment by ragerdl** [comment]
Personally, it'd be nice to see a section in https://rocm-documentation.readthedocs.io/en/latest/Programming_Guides/HIP-porting-guide.html on how to port a CUDA-oriented CMakeLists.txt to be HCC-centric.  Of course, many things would be nice....

**Comment by gargrahul** [comment]
@ragerdl please check https://github.com/ROCm-Developer-Tools/HIP/tree/master/samples/2_Cookbook/12_cmake_hip_add_executable 

We can refer this from porting guide.
