### ISSUE TITLE
initialization is not supported for __shared__ variables

### ISSUE THREAD

**Issue by jiajunc516** [ROCm-Developer-Tools/HIP#2315]
Let's say I have a struct `myST` that I defined a `__host__ __device__ myST()` default constructor so that I can use both on host and device. As I also want to use it in shared memory, for example `__shared__ myST share_objs[10]`, on Nvidia platform I used a `__CUDA_ARCH__` macro to separate host and device initialization since default constructor is not available in shared memory.
```
struct myST {
    int a;

    __host__ __device__ myST() {
#ifndef __CUDA_ARCH__
        a = 10;
#endif
    }
};

__global__ void test() {
    __shared__ share_objs[10]
    // do sth
}
```
When moving to AMD platform, followed Porting Guide, I replace `__CUDA_ARCH__` with `__HIP_DEVICE_COMPILE__` like below.
```
    __host__ __device__ myST() {
#ifndef __HIP_DEVICE_COMPILE__
        a = 10;
#endif
    }
```
And then compiling reports `error: initialization is not supported for __shared__ variables.`
I also tried this which doesn't work either.
```
    __host__ __device__ myST() {
#if __HIP_DEVICE_COMPILE__
#else
        a = 10;
#endif
    }
```
Explicitly defining two constructors works for me though.
```
    __host__ myST() {
        a = 10;
    }

    __device__ myST() {
    }
```
**So why doesn't `__HIP_DEVICE_COMPILE__` work here? Is it what HIP expected?**

*My hipconfig outputs*
```
HIP version  : 4.3.21300-5bbc51d8

== hipconfig
HIP_PATH     : /opt/rocm-4.3.0/hip
ROCM_PATH    : /opt/rocm-4.3.0
HIP_COMPILER : clang
HIP_PLATFORM : amd
HIP_RUNTIME  : rocclr
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I"/opt/rocm-4.3.0/hip/include" -I"/opt/rocm-4.3.0/llvm/bin/../lib/clang/13.0.0" -I/opt/rocm-4.3.0/hsa/include

== hip-clang
HSA_PATH         : /opt/rocm-4.3.0/hsa
HIP_CLANG_PATH   : /opt/rocm-4.3.0/llvm/bin
clang version 13.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.3.0 21295 f2943f684437d2c1143a56e418d29fc6b3314072)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-4.3.0/llvm/bin
LLVM (http://llvm.org/):
  LLVM version 13.0.0git
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake-avx512

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
hip-clang-cxxflags :  -std=c++11 -isystem "/opt/rocm-4.3.0/llvm/lib/clang/13.0.0/include/.." -isystem /opt/rocm-4.3.0/hsa/include -isystem "/opt/rocm-4.3.0/hip/include" -O3
hip-clang-ldflags  : --driver-mode=g++ -L"/opt/rocm-4.3.0/hip/lib" -O3 -lgcc_s -lgcc -lpthread -lm -lrt

=== Environment Variables
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/rocm/bin:/opt/rocm/rocprofiler/bin:/opt/rocm/opencl/bin

== Linux Kernel
Hostname     : amd-164
Linux amd-164 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

**Comment by Artem-B** [comment]
Clang is correct here: https://godbolt.org/z/drqKeP1n6
Your struct does have a constructor with a body and that's not allowed. It has nothing to do with whether you actually use `a` in it.
The error is triggered by ` __shared__ share_objs[10]` in the kernel.
`__shared__` variables are implicitly static and when you have a nondefault constructor something/somewhere must call it and there's just no good palce to do it on the GPU side.

What you want is something like this:
```
   __host__ myST() {
       // do something;
    }
    __device__ myST() = default;
```
Maybe, combined with a member function to explicitly initialize it, because with the default constructor C++ will not do nothing with that shared array and your kernel will end up using uninitialized data unless it inits it explicitly.
