### ISSUE TITLE
Typo in enum hipSurfaceBoundaryMode

### ISSUE THREAD

**Issue by emankov** [ROCm-Developer-Tools/HIP#2319]
`hipBoundaryModeTrap` in `enum hipSurfaceBoundaryMode` should be equal 2, and `hipBoundaryModeClamp` should be equal 1 in [hip_surface_types.h](https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-4.3.x/include/hip/amd_detail/hip_surface_types.h) like in CUDA's `surface_types.h`.

**Comment by ppanchad-amd** [comment]
@emankov Apologies for the lack of response. Can you please check latest ROCm 6.0.2 (HIP 6.0.32831? If resolved, please close ticket. Thanks!
