### ISSUE TITLE
/opt/rocm-4.0.0/include/hip/hcc_detail/hip_vector_types.h:32:2: error: ("This version of HIP requires a newer version of HCC."); #error("This version of HIP requires a newer version of HCC.");

### ISSUE THREAD

**Issue by jianlongf** [ROCm-Developer-Tools/HIP#2320]
I build simple vectoradd_hip.cpp in docker and meeted this error. Accroding to error message, should I to upgrade hipcc ? What caused this problem?

**docker environment:**
> Package: rocm-libs
> Version: 4.0.0.40000-23
> Priority: optional
> Section: devel
> Maintainer: Advanced Micro Devices, Inc.
> Installed-Size: 13.3 kB
> Depends: hipblas, hipcub, hipsparse, miopen-hip, rocalution, rocblas, rocfft, rocprim, rocrand, rocsolver, rocsparse, rocthrust
> Homepage: https://github.com/RadeonOpenCompute/ROCm
> Download-Size: 826 B
> APT-Manual-Installed: yes
> APT-Sources: http://repo.radeon.com/rocm/apt/4.0 xenial/main amd64 Packages
> Description: Radeon Open Compute (ROCm) Runtime software stack

**$/opt/rocm/bin/hipcc --version**
> HIP version: 4.0.20496-4f163c68
> clang version 12.0.0 (/src/external/llvm-project/clang dac2bfceaa8d4a90257dc8a6d58f268e172ce00e)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /opt/rocm-4.0.0/llvm/bin

**Comment by ppanchad-amd** [comment]
@jianlongf,  Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!
