### ISSUE TITLE
How does HIP support Half Compute

### ISSUE THREAD

**Issue by jianlongf** [ROCm-Developer-Tools/HIP#2322]
I wanna compute Half operation by AMD GPU. So I try to write hip program. But my datatype is half. So the first question is no half type in [HIP programming guide](https://raw.githubusercontent.com/RadeonOpenCompute/ROCm/master/AMD_HIP_Programming_Guide_v4.3.pdf). And then, Should I send data(from cpu to gpu) by uint16_t* , and compute it by uint16_t* in HIP kernel(I found this way in rocBLAS). And I couldn't find related examples in HIP-Examples repo. Please anyone could give me some details about half process, thanks a lot in advance.

**Comment by jianlongf** [comment]
After experient, I found Clang _Float16 is the answer.

**Comment by mangupta** [comment]
HIP does support half. You need to include [include/hip/hip_fp16.h](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/include/hip/hip_fp16.h). On AMD platform this include would end up including https://github.com/ROCm-Developer-Tools/hipamd/blob/develop/include/hip/amd_detail/amd_hip_fp16.h which provides ```half``` and ```half2```.
