### ISSUE TITLE
#define abort() {asm("trap;");} leads to "illegal instruction" error

### ISSUE THREAD

**Issue by theZiz** [ROCm-Developer-Tools/HIP#233]
The commit https://github.com/ROCm-Developer-Tools/HIP/commit/e6e4fe613c89fc0b3ae0d4fd0b23f59a4e69a042 defined `abort` as `asm("trap;");`.
In an example application, which uses an abstraction layer for cuda or hip, this definition let's the application crash with an `illegal instruction` error when using the cuda back end of hip.

I could trace down the only difference between the directly cuda created kernel ptx code and the hip created ptx code to an added
```
	// inline asm
	trap;
	// inline asm
```
If remove the definition of `abort()` everything works as intended. The problem is, I don't even know, why the definition of `abort()` was added in the first place.

I tried to create a test application, which does not use the mentioned abstraction layer, but some `#ifdef`, but were not able to reproduce the problem there.

**Comment by gargrahul** [comment]
We have used this to implement abort() support on device for HIP/NVCC path.
Let me know if you are able to use __trap() inside kernel without
application crash with abstraction layer.

On Thu, Oct 26, 2017 at 7:07 PM, Alexander Matthes <notifications@github.com

**Comment by theZiz** [comment]
I tried `__trap()` and it also crashes the whole program with an illegal instruction error. I wonder, whether `trap` is even, what someone would expect from `abort()`. Should abort not only stop the __current__ thread? `trap` will end all threads of a kernel (and the whole program as side effect for me...).

**Comment by gargrahul** [comment]
@theZiz As I understand from your message , without "abstraction layer", abort() works for you on HIP/NVCC  path. Could you please share more details about "abstraction layer" ? 

We have abort() function support on HIP/HCC path and the same has been tried on HIP/NVCC path by using __trap/ asm("trap;");

**Comment by gargrahul** [comment]
@theZiz I am closing this issue. Please let me know if you would like us to check it further.
