### ISSUE TITLE
CentOS 8 - Install Failure

### ISSUE THREAD

**Issue by kiritigowda** [ROCm-Developer-Tools/HIP#2330]
ROCm Installation fails on CentOS 8, attached is the docker file to reproduce the issue.

```
FROM centos:centos8

# install base dependencies
RUN yum -y update --nogpgcheck && yum -y install --nogpgcheck gcc gcc-c++ kernel-devel make cmake git
# install ROCm
RUN echo -e "[ROCm]\nname=ROCm\nbaseurl=https://repo.radeon.com/rocm/centos8/rpm\nenabled=1\ngpgcheck=1\ngpgkey=https://repo.radeon.com/rocm/rocm.gpg.key" > \
        /etc/yum.repos.d/rocm.repo && yum -y update --nogpgcheck && yum -y install --nogpgcheck rocm-dev
```

Failure
```
Error: 
 Problem: package rocm-dev-4.3.0.40300-52.el8.x86_64 requires hip-base, but none of the providers can be installed
  - conflicting requests
  - nothing provides perl-File-BaseDir needed by hip-base-4.3.21300.5994.40300-52.el8.x86_64
  - nothing provides perl-URI-Encode needed by hip-base-4.3.21300.5994.40300-52.el8.x86_64
```
DockerFile - [rocm-centOS8-dockerfile.txt](https://github.com/ROCm-Developer-Tools/HIP/files/7079787/rocm-centOS8-dockerfile.txt)

**Comment by PourroyJean** [comment]
perl-URI-Encode package is missing.
You can install it from the epel repository.

Run, for example, the following command to install it:
`dnf --nogpgcheck install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`

**Comment by lachlan2k** [comment]
For `perl-File-BaseDir` you also need to enable powertools with `sudo dnf config-manager --set-enabled powertools` after installing epel-release.

**Comment by ppanchad-amd** [comment]
@kiritigowda Are you still having this issue? If not, please close this ticket.  Thanks!
