### ISSUE TITLE
[hipBLAS] Is there any convenient command to realize the interchange of hipDoubleComplex and hipblasDoubleComplex？

### ISSUE THREAD

**Issue by HXTP** [ROCm-Developer-Tools/HIP#2332]
Is there any convenient command to realize the interchange of hipDoubleComplex and hipblasDoubleComplex？It has bothered me for a long time. Thank you!

**Comment by jinz2014** [comment]
Is it right that there is no cublasDoubleComplex in cuBLAS ?

**Comment by emankov** [comment]
`cuBLAS` uses the CUDA library type `cudaDataType`. Its analogue `hipDataType` is already in HIP. What is actually missing in `hipBLAS` is that `hipblasDatatype_t` should be mapped to HIP's `hipDataType` (https://github.com/ROCmSoftwarePlatform/hipBLAS/issues/366).

**Comment by jinz2014** [comment]
Could there be one type instead of three types (hipComplex, hipFloatComplex, hipblasComplex) ?

**Comment by emankov** [comment]
Oh, you asked about Complex types only.

You may use `hipFloatComplex` (`hipComplex`) and `hipDoubleComplex` in your hipBLAS applications already. And `hipblasComplex` equals to `hipFloatComplex`, equals to `hipComplex`, as you can see in the table below.

|**CUDA**|**HIP**|**hipBLAS**|
|:--|:-:|:-:|
|`cuFloatComplex`  | `hipFloatComplex` | typedef `hipFloatComplex` hipblasComplex; |
|`cuDoubleComplex` | `hipDoubleComplex` | typedef `hipDoubleComplex` hipblasDoubleComplex; |
| typedef `cuFloatComplex` `cuComplex`; | typedef `hipFloatComplex` `hipComplex`; | `hipblasComplex` |
