### ISSUE TITLE
Build failures with cmake 3.21.3

### ISSUE THREAD

**Issue by haampie** [ROCm-Developer-Tools/HIP#2377]
See https://github.com/spack/spack/issues/26459

```
CMake Error in CMakeLists.txt:
  HIP_ARCHITECTURES is empty for target
  "directed_tests.kernel.hipLaunchParm".
```

**Comment by haampie** [comment]
We apply a patch to disable the tests: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hip/0005-Disable-tests-4.1.0.patch

Can you make a proper fix for this here please?

**Comment by mangupta** [comment]
#2364 should resolve this.

**Comment by haampie** [comment]
Ah okay, thank you @mangupta / @cjatin! That's part of 4.4.0?

Is there a way to disable building tests generally?

**Comment by ppanchad-amd** [comment]
@haampie Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!
