### ISSUE TITLE
Kernel name not identifiable

### ISSUE THREAD

**Issue by psn9** [ROCm-Developer-Tools/HIP#240]
Hi ,

I am trying to run a HIP compiled binary but ending up with 
**HSADevice::CreateKernel(): Unable to create kernel** error.

In the error log , I can find the kernel name to be "unnamed" . I cant post the entire error log here.
Here's a sample,

CreateKernel_demangled=  void MS::CUD::Sort_of<2>::Dial<float>(unsigned long, unsigned long, unsigned long, bool, float const*, float const*, float*, float const*, float, float const*, float const*, float const*, float const*, ihipStream_t*)::HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_name_end_12::__cxxamp_trampoline(int, int, int, float const*, float const*, float*, float const*, float, float const*, float const*, float const*, float const*)

When I tried HIP_TRACE_API , I can see the kernel being launched , but then this error is being thrown.

A snippet of HIP_TRACE_API :

_hip-api tid:1.53 hipMemset                      ret= 0 (hipSuccess)>>
<<hip-api tid:1.53 1.53 hipLaunchKernel '(kSortBack<BlockDimX, BlockDimY, false, U>)' gridDim:{1,1,1} groupDim:{16,8,1} sharedMem:+0 stream:0.0_

kSortBack is the kernel

As u can see in the error log , the kernel name is "unnamed" - HIP_kernel_functor_name_begin_**unnamed**_HIP_kernel_functor_name_end_

Any general cause for this ? Am using the latest environment.

**Comment by psn9** [comment]
It seems the "unnamed" thing is normal in HIP. Even successful gpu programs had kernel name "unnamed" . But Can I get a solution for the **CreateKernel()** issue ?

What could possibly be the cause ?

**Comment by whchung** [comment]
@psn9 could you show the exact steps how you compile/link the program. one common error is that you didn't use `hipcc` or `hcc` as the linker.

**Comment by mangupta** [comment]
PR #246 addresses the unnamed kernel issue in addition to other changes. So closing this issue.
