### ISSUE TITLE
hipMemcpyToSymbol segfaults

### ISSUE THREAD

**Issue by Madu86** [ROCm-Developer-Tools/HIP#2406]
I am working on hipifying a large code that requires device code linking. I have to copy static structs into constant memory using hipMemcpyToSymbol in source files that are compiled with and without -fgpu-rdc flag. For some reason, this fails in source files compiled with -fgpu-rdc. I am attaching a simple test program that reproduces my problem. 
Specifically, If I turn fooStr into static on Line 4 of foo.cpp this results in a segfault. However, if I do the same on line 4 of bar.cpp, which is compiled without -fgpu-rdc, this doesn't happen. Can someone help me to figure out what is happening here? Thanks!

HIP version: 4.3.21331-94fc2572
ROCm driver version: 5.11.14
OS: ubuntu~18.04
[test.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/7498215/test.tar.gz)

**Comment by yxsamliu** [comment]
The issue has been fixed in rocm 4.4.2

**Comment by Madu86** [comment]
Great! Thanks @yxsamliu.

**Comment by Madu86** [comment]
@yxsamliu So I used rocm 4.5 and I was able to run my test program successfully. However, the problem in my original code remained the same. So I drilled down further and found that bundling the driver compiled with -fgpu-rdc into a second library was the culprit. In case it is useful for someone, I am changing the make file of my test program and demonstrate the problem. Specifically, If I build the test program using `nofault` target below, the executable wont segfault. However, if I use the `segfault` target, it will.    

```
nofault:
	hipcc -fgpu-rdc -fPIC -g -c dev.cu -o dev.o
	ar rcsD libHipDevice.a dev.o
	hipcc -fgpu-rdc -g -c foo.cu -o foo.o
	hipcc -g -c main.cu -o main.o
	hipcc -g -c bar.cu -o bar.o
	ar cr libtest.a bar.o
	hipcc -g libHipDevice.a -L./ -ltest foo.o main.o -fgpu-rdc -o a.out

segfault:
	hipcc -fgpu-rdc -fPIC -g -c dev.cu -o dev.o
	ar rcsD libHipDevice.a dev.o
	hipcc -fgpu-rdc -g -c foo.cu -o foo.o
	hipcc -g -c main.cu -o main.o
	hipcc -g -c bar.cu -o bar.o
	ar cr libtest.a foo.o bar.o
	hipcc -g libHipDevice.a -L./ -ltest main.o -fgpu-rdc -o a.out

clean:
	rm -f *.o *.a a.out
```

**Comment by yxsamliu** [comment]
.o file generated with -fgpu-rdc is actually bundled object file which needs special handling by clang. As such, if it is in an archive, that archive has to be passed to hipcc directly instead of by -l. This is a limitation of hipcc.

**Comment by Madu86** [comment]
I see. Thanks for the explanation.
