### ISSUE TITLE
When I install nvcc-hip,I get Error

### ISSUE THREAD

**Issue by wangzy0327** [ROCm-Developer-Tools/HIP#2412]
refer nvidia platform document installation:
https://rocmdocs.amd.com/en/latest/Installation_Guide/HIP-Installation.html
When I install hip-runtime-nvidia,I get error as below.
![image](https://user-images.githubusercontent.com/22990858/140888164-dcc54000-34f4-4b39-a418-b04f0f3561da.png)
my env is :
![image](https://user-images.githubusercontent.com/22990858/140888436-1dcf684c-e8dc-46f4-9037-69b33b1c9b3e.png)

What can I get help?

**Comment by emankov** [comment]
Transfer the issue to HIP.

**Comment by wangzy0327** [comment]
> Transfer the issue to HIP.
OK，I will transfer the issue to HIP

**Comment by ppanchad-amd** [comment]
@wangzy0327 Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!
