### ISSUE TITLE
HIP rocm-4.5.x install from source on NVIDIA platform

### ISSUE THREAD

**Issue by jakub-homola** [ROCm-Developer-Tools/HIP#2413]
If I understand correctly, with the new rocm-4.5.x branches, this HIP repository contains only several things common to both NVIDIA and AMD platforms. Then there is the [hipamd](https://github.com/ROCm-Developer-Tools/hipamd) repository, which "provides HIP implementation specifically for AMD platform", according to the readme. I did not find anything about hipnvidia or anything like that.

The [INSTALL.md](https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-4.5.x/INSTALL.md#building-hip-from-source) seems to be relevant only for the AMD platform, since it mentions ROC* requirements, which are required only on the AMD platform.

So, what is currently the correct way of installing HIP from source on the NVIDIA platform?

I tried using only HIP as in previous versions, but `hipcc` complains about `<hip/hip_version.h>` not found, which really isn't there. Also the `*_detail` include directories are missing.

hipamd does work on the NVIDIA platform, but it seems weird, since it is supposed to be designed specifically for AMD.

**Comment by ppanchad-amd** [comment]
@jakub-homola Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!
