### ISSUE TITLE
HIP language support in cmake lacking compile_commands.json support

### ISSUE THREAD

**Issue by dindon-sournois** [ROCm-Developer-Tools/HIP#2427]
Not sure if it's a cmake or hip-lang issue. Files compiled with HIP language enabled (`.hip` extensions) are not referrenced in the generated `compile_commands.json` when [CMAKE_EXPORT_COMPILE_COMMANDS ](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) is activated. I can provide additionnal details if needed.

As an unrelated note, the [HIP porting guide](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_porting_guide.md#choosing-hip-file-extensions) advise using `.hip.cpp` file extensions but the default extension used by the cmake HIP language is `.hip`. I think we can change the properties of a source file to adjust its language but doing it the other way around (changing `CMAKE_HIP_SOURCE_FILE_EXTENSIONS`) does not seem possible as cmake identifies the file as a C++ source file.

```
$ cat <...>/bin/.hipVersion
# Auto-generated by cmake
HIP_PACKAGING_VERSION_PATCH=0
CPACK_DEBIAN_PACKAGE_RELEASE=local
CPACK_RPM_PACKAGE_RELEASE=local%{?dist}
HIP_VERSION_MAJOR=4
HIP_VERSION_MINOR=3
HIP_VERSION_PATCH=0

$ cmake --version
cmake version 3.21.2
```

**Comment by pfultz2** [comment]
This is an issue with cmake. We dont generate any compile_commands.json files, its all done by cmake.

**Comment by dindon-sournois** [comment]
Fixed by [this commit](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6789)
