### ISSUE TITLE
compiling for use with nvcc & nvidia gpu on fedora 33

### ISSUE THREAD

**Issue by burlen** [ROCm-Developer-Tools/HIP#2431]
HI, I want to use HIP for platform portable development. My development environment is Fedora 33 linux and CUDA 11.0. I have a quadro rtx 4000 card. The instructions reference "apt-get" installs, which is Debian/Ubuntu method, so I assume that no binaries are available for Fedora and hence I should install from sources.

However, trying to install HIP (as described here: https://github.com/ROCm-Developer-Tools/HIP/blob/develop/INSTALL.md#building-hip-from-source). CMake errors out because it failed to find amd_comgr.  Apparently the instructions are incomplete.

What are the minimal steps do I need to take to install HIP for use with Nvidia on Fedora 33 linux and CUDA 11.0?

**Comment by Maxzor** [comment]
Maybe this can help?
https://gist.github.com/cgmb/7cd9a481c42ce132b5d6420380becef3

**Comment by burlen** [comment]
> Maybe this can help?

Thanks! It was helpful.
