### ISSUE TITLE
HIP tests leak processes

### ISSUE THREAD

**Issue by Maxzor** [ROCm-Developer-Tools/HIP#2457]
`make -j$(ncore) test`
The 40x tests finish.
There are dozens of processes from hipMultiProcIpcMem still eating the full CPU resources after that.
My test result is below, the test hipMultiProcIpcMem timed out.

```
99% tests passed, 3 tests failed out of 403

Total Test time (real) = 3933.38 sec

The following tests FAILED:
	103 - directed_tests/ipc/hipMultiProcIpcMem.tst (Timeout)
	132 - directed_tests/runtimeApi/cooperativeGrps/cooperative_streams_half_capacity.tst (Subprocess aborted)
	197 - directed_tests/runtimeApi/memory/hipIpcMemAccessTest.tst (Timeout)
```

**Comment by littlewu2508** [comment]
Observed that `directed_tests/ipc/hipMultiProcIpcMem--N4.tst` timeout, and still leaked process after test.

ROCm: 5.4.3, Gentoo Linux

**Comment by ppanchad-amd** [comment]
@Maxzor Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@littlewu2508 Is this still an issue with latest ROCm 6.1.2? Thanks!

**Comment by ppanchad-amd** [comment]
@Maxzor @littlewu2508 Closing ticket as there is no response.  Please re-open ticket if you still see the issue with the latest ROCm 6.1.2 Thanks!
