### ISSUE TITLE
Unable to locate package hip-runtime-nvidia,hip-dev ?

### ISSUE THREAD

**Issue by wangzy0327** [ROCm-Developer-Tools/HIP#2462]
When I install hip-runtime-nvidia,hip-dev, Unable to locate packages
![image](https://user-images.githubusercontent.com/22990858/149889374-abcead12-5361-403f-9b48-d00c7b6a4f08.png)

**Comment by ppanchad-amd** [comment]
@wangzy0327 Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!
