### ISSUE TITLE
Mark public API with "C" linkage as "noexcept"

### ISSUE THREAD

**Issue by averinevg** [ROCm-Developer-Tools/HIP#2470]
I suggest to mark all exported functions with `C` linkage as `noexcept` for better c++ support. Missing `noexcept` causes code analyzers to issue a warning.

**Comment by ppanchad-amd** [comment]
@averinevg Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!

**Comment by averinevg** [comment]
@ppanchad-amd Thanks for your answer!

This is not a defect. This is just a recommendation, the library is written in C++ and can throw exceptions. My suggestion is to have these exceptions handled internally by the library and have the interface return an error code. If the code using this library is written in C, then it simply will not be able to handle the exception. `noexcept` is not a guarantee, it is an agreement that the code will not throw exceptions.

**Comment by ppanchad-amd** [comment]
@averinevg Created internal ticket to get this resolved. Thanks!

**Comment by jamesxu2** [comment]
Hi @averinevg , your recommendation is valid, but the library is not written with and does not use exceptions even though it is written in C++ and could do so in theory. If possible, you can try to suppress those warnings in your code analyzer.
