### ISSUE TITLE
About HSA_AMD_AGENT_INFO_COOPERATIVE_COMPUTE_UNIT_COUNT in the building the source code of HIP

### ISSUE THREAD

**Issue by xwentian2020** [ROCm-Developer-Tools/HIP#2516]
Hi,
In building HIP from the source code, I encountered an error message as shown below

/ROCclr/device/rocm/rocdevice.cpp:1091:44: error: use of undeclared identifier 'HSA_AMD_AGENT_INFO_COOPERATIVE_COMPUTE_UNIT_COUNT'
                         (hsa_agent_info_t)HSA_AMD_AGENT_INFO_COOPERATIVE_COMPUTE_UNIT_COUNT,

It was found that HSA_AMD_AGENT_INFO_COOPERATIVE_COMPUTE_UNIT_COUNT was relate to a new environment variable HSA_COOP_CU_COUNT. I tried to add this environment variable, but the problem still has not been solved. 

Any suggestions for this problem?

**Comment by willcrozi** [comment]
@xwentian2020 I'm hitting this problem too building on current latest 'develop' branch, did you manage to resolve somehow?
