### ISSUE TITLE
__launch_bounds__ lowers to the wrong thing.

### ISSUE THREAD

**Issue by seanbaxter** [ROCm-Developer-Tools/HIP#2521]
https://gist.github.com/seanbaxter/bf60b073db4971bc8cccb89ffbcef424

The 2nd argument of `__launch_bounds__` indicates the minimum number of blocks to schedule per EU. hipcc is lowering that directly to "amdgpu-waves-per-eu", which is the wrong thing, as that indicates the number of waves per EU, not the number of blocks. Changing the wave size by selecting a different device doesn't change the term either.

**Comment by seanbaxter** [comment]
The problem is your macro in amd_hip_runtime.h is wrong
```cpp
#define launch_bounds_impl1(requiredMaxThreadsPerBlock, minBlocksPerMultiprocessor)                \
    __attribute__((amdgpu_flat_work_group_size(1, requiredMaxThreadsPerBlock),                     \
                   amdgpu_waves_per_eu(minBlocksPerMultiprocessor)))
```

**Comment by ppanchad-amd** [comment]
@seanbaxter Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!
