### ISSUE TITLE
`clock` function is redeclared with the wrong return type

### ISSUE THREAD

**Issue by seanbaxter** [ROCm-Developer-Tools/HIP#2524]
/opt/rocm/include/hip/amd_detail/amd_device_functions.h:995 declares`clock()` to have return type `long long`. ctime.h declares it to have return type `clock_t`, which is `long`. Please fix.

**Comment by ppanchad-amd** [comment]
@seanbaxter Can you please check with latest ROCm 6.0.2 (HIP 6.0.32831)? Thanks!

**Comment by harkgill-amd** [comment]
Hi @seanbaxter, this issue is no longer seen in ROCm 6.1.2 as there is only a single declaration of `clock_t clock()` at https://github.com/ROCm/HIP/blob/develop/docs/reference/kernel_language.rst#timer-functions.
