### ISSUE TITLE
[HIPIFY] hipify-perl produces warnings for threadfence and threadfence_block, which are supported

### ISSUE THREAD

**Issue by mattsinc** [ROCm-Developer-Tools/HIP#258]
I am currently porting a CUDA application that uses threadfence and threadfence_block to enforce ordering.  According to the HIP documentation (http://rocm-documentation.readthedocs.io/en/latest/Programming_Guides/Kernel_language.html#memory-fence-instructions), these instructions are supported in HIP.  However, while I run hipify-perl on this application, I get warnings like the following:

  warning: unsupported device function :      _threadfence();
  …
  warning: unsupported device function :               _threadfence_block();

If these instructions are supported, then shouldn't these warnings not be printed?  On the flip side, in hip/include/hip/hcc_detail/hip_runtime.h, there are __hip_hc_threadfence and __hip_hc_threadfence_block(). The comments suggest that these are currently empty stubs, but then there are implementations (in a single asm instructions) nevertheless. So I'm not sure if applications with threadfences are actually supported or not?  If not, then perhaps that's why these warnings are appearing?

Matt

**Comment by emankov** [comment]
Fixed by #1053: [HIPIFY][perl][fix][#258] Memory fence device functions are supported now.
