### ISSUE TITLE
[HIPIFY] hipify-perl produces incorrect output for kernels that have no input args

### ISSUE THREAD

**Issue by mattsinc** [ROCm-Developer-Tools/HIP#259]
I am porting an application that exclusively uses hipMemcpyToSymbol for its kernels.  When I run hipify-perl on this, it will happily convert it (except for the threadfence issue I noted in #258).  However, when I try to compile the kernel I get the following for each kernel:

hipLaunchKernelGGL((Kernel1), dim3(numTBs), dim3(numThreadsPerBlock), 0, 0, );

This is related to the issue I raised in #257 -- currently hipcc requires at least one input arg to correctly compile a kernel, when this is not necessary if MemcpyToSymbol is used.  But regardless, it doesn't seem like hipify should add a comma with nothing after it.

Matt

**Comment by emankov** [comment]
Fixed by #1387
