### ISSUE TITLE
Code disassembly from hiprtcGetCode

### ISSUE THREAD

**Issue by CaptnJackSparrow** [ROCm-Developer-Tools/HIP#2615]
Is it possible to get the kernel disassembly (e.g. compiled with gfx908) from the output of hiprtcGetCode?

**Comment by cjatin** [comment]
you can dump the output of `hiprtcGetCode` to a file and use  `llvm-objdump -d <file>` to get isa.

**Comment by ppanchad-amd** [comment]
@CaptnJackSparrow Is this ticket still relevant? If not, please close. Thanks!
