### ISSUE TITLE
ROCM 5.1 install fails

### ISSUE THREAD

**Issue by sampie** [ROCm-Developer-Tools/HIP#2654]
On ubuntu 20.04 installing ROCM 5.1 fails:

The following additional packages will be installed:
  hip-doc
The following NEW packages will be installed:
  hip-doc
0 upgraded, 1 newly installed, 0 to remove and 36 not upgraded.
149 not fully installed or removed.
Need to get 1077 kB of archives.
After this operation, 5536 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://repo.radeon.com/rocm/apt/debian ubuntu/main amd64 hip-doc amd64 5.1.20531.50100-36 [1077 kB]
Fetched 1077 kB in 1s (850 kB/s)  
(Reading database ... 45036 files and directories currently installed.)
Preparing to unpack .../hip-doc_5.1.20531.50100-36_amd64.deb ...
Unpacking hip-doc (5.1.20531.50100-36) ...
dpkg: error processing archive /var/cache/apt/archives/hip-doc_5.1.20531.50100-36_amd64.deb (--unpack):
 unable to create '/opt/rocm-5.1.0/hip/docs/RuntimeAPI/html/md__long_pathname_so_that_rpms_can_package_the_debug_info_src_external_hip-on-vdi_docs_markdown_c9f14333590e6676
8be7ae177b7ce60b.html.dpkg-new' (while processing './opt/rocm-5.1.0/hip/docs/RuntimeAPI/html/md__long_pathname_so_that_rpms_can_package_the_debug_info_src_external_hip-on-v
di_docs_markdown_c9f14333590e66768be7ae177b7ce60b.html'): File name too long
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/hip-doc_5.1.20531.50100-36_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ppanchad-amd** [comment]
@sampie Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!
