### ISSUE TITLE
question about gfxName in the unsafe atomic test

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#2655]
There are some questions about atomic operation. Could the gfxName include gfx906 and gfx908 ?  

```
TEST_CASE("Unit_unsafeAtomicAdd") {
  using namespace std;
  int device = 0;
  hipDeviceProp_t props;
  HIP_CHECK(hipGetDeviceProperties(&props, device));
  std::string gfxName(props.gcnArchName);

  if (gfxName == "gfx90a" || gfxName.find("gfx90a:") == 0) {
```

More generally, is there some device attribute that can help developers determine a device's support of atomic functions ?   Thank you for your answer.

The CUDA programming guide shows:
```
atomicAdd_system(addr, 10);       // **only available on devices with compute capability 6.x**

**#if __CUDA_ARCH__ < 600**
__device__ double atomicAdd(double* address, double val)
{
    unsigned long long int* address_as_ull =
                              (unsigned long long int*)address;
    unsigned long long int old = *address_as_ull, assumed;

    do {
        assumed = old;
        old = atomicCAS(address_as_ull, assumed,
                        __double_as_longlong(val +
                               __longlong_as_double(assumed)));

    // Note: uses integer comparison to avoid hang in case of NaN (since NaN != NaN)
    } while (assumed != old);

    return __longlong_as_double(old);
}
#endif
```

**Comment by yxsamliu** [comment]
You can check https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/AMDGPU/AMDGPU.td

FeatureAtomicFaddInsts

It is supported by gfx908, gfx90a, gfx940.

**Comment by zjin-lcf** [comment]
Thank you for showing me the table. I suppose that gfx906 includes atomic add instruction too.

def FeatureISAVersion9_0_6 : FeatureSet<
  [FeatureGFX9,
   HalfRate64Ops,
   FeatureFmaMixInsts,
   FeatureLDSBankCount32,
   FeatureDsSrc2Insts,
   FeatureExtendedImageInsts,
   FeatureImageInsts,
   FeatureMadMacF32Insts,
   FeatureDLInsts,
   FeatureDot1Insts,
   FeatureDot2Insts,
   FeatureDot7Insts,
   FeatureSupportsSRAMECC,
   FeatureImageGather4D16Bug]>;

**Comment by yxsamliu** [comment]
For atomic add operation, gfx906 only supports integer, not floating point.

Floating point atomic add is only supported by gfx908, gfx90a, and gfx940.
