### ISSUE TITLE
atomic increment and decrement functions

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#2656]
Could ROCm consider adding the two functions in HIP ?

Reference:
https://github.com/NVIDIA/cuda-samples/blob/master/Samples/0_Introduction/systemWideAtomics/systemWideAtomics.cu 

```
main.cu:45:5: error: use of undeclared identifier 'atomicInc_system'; did you mean 'atomicAnd_system'?
    atomicInc_system((unsigned int *)&atom_arr[4], 17);
    ^~~~~~~~~~~~~~~~
    atomicAnd_system
/opt/rocm-4.5.2/hip/include/hip/amd_detail/amd_hip_atomic.h:562:14: note: 'atomicAnd_system' declared here
unsigned int atomicAnd_system(unsigned int* address, unsigned int val) {
             ^
main.cu:48:5: error: use of undeclared identifier 'atomicDec_system'
    atomicDec_system((unsigned int *)&atom_arr[5], 137);
    ^
```

**Comment by harkgill-amd** [comment]
Hi @zjin-lcf, I will confirm whether adding atomicInc and atomicDec is planned in the future and let you know.

**Comment by harkgill-amd** [comment]
Hi @zjin-lcf, unfortunately, there are currently no plans to implement the atomicInc and atomicDec functions. In place of these functions, it is recommended to use atomicAdd to guarantee the highest possible performance. Thank you!
