### ISSUE TITLE
Multi-Device called by multi cpu thread

### ISSUE THREAD

**Issue by stabunkow** [ROCm-Developer-Tools/HIP#2657]
Could ROCm consider non-lock hipMemcpyAsync API when each thread control a device?

**Comment by stabunkow** [comment]
```
#pragma omp for
for (deviceId = 0; deviceId < deviceSiz; ++deviceId) 
{
   hipSetDevice(deviceId);
   hipMemcpyAsync(...);
}
```
I know there is spinlock inside hipMemcpyAsync API, but when set hipSetDevice, the spinlock will be removed?

**Comment by ppanchad-amd** [comment]
@stabunkow Apologies for the lack of response. Do you still need assistance with this ticket? Thanks!
