### ISSUE TITLE
no matching function for call to isnan

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#2663]
Thank you for your instruction for building the example

```
/* filename: test.cu */
#include <cstdio>
#include <cmath>       /* isnan, sqrt */
#include <hip/hip_runtime.h>

int main()
{
  printf ("isnan(0.0)       : %d\n",isnan(0.0));
  return 0;
}

```
test.cu:: error: no matching function for call to 'isnan'
  printf ("isnan(0.0)       : %d\n",isnan(0.0));
                                    ^~~~~
/opt/rocm-4.5.2/llvm/lib/clang/13.0.0/include/__clang_hip_cmath.h:469:23: note: candidate template ignored: substitution failure [with __T = double]: no type named 'type' in '__hip_enable_if<false, bool>'
__HIP_OVERLOAD1(bool, isnan)
~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/opt/rocm-4.5.2/llvm/lib/clang/13.0.0/include/__clang_hip_cmath.h:406:7: note: expanded from macro '__HIP_OVERLOAD1'
      __fn(__T __x) {                                                          \
      ^
/opt/rocm-4.5.2/llvm/lib/clang/13.0.0/include/__clang_hip_cmath.h:96:17: note: candidate function not viable: call to __device__ function from __host__ function
__DEVICE__ bool isnan(float __x) { return ::__isnanf(__x); }
 ```

**Comment by xianwujie** [comment]
Hello @zjin-lcf , I have encountered a similar problem, may I ask if you solved it?

**Comment by zjin-lcf** [comment]
HIP docs show that the function is supported on host and device. Did you compile your program with new releases of ROCm ?

**Comment by xianwujie** [comment]
Hi @zjin-lcf , thanks for your reply.
I compiled it on the specified rocm4.0 version,I'll look into the HIP documentation you said.

**Comment by zjin-lcf** [comment]
I tried "std::isnan" and the compile is fine for rocm 4.5.2 and up.

**Comment by xianwujie** [comment]
I got it, thank you very much。

**Comment by zjin-lcf** [comment]
You are welcome.
