### ISSUE TITLE
Macros to check for FLT64 ATOMICS 

### ISSUE THREAD

**Issue by abagusetty** [ROCm-Developer-Tools/HIP#2686]
Hi, 

Is there a way/work-around to check for the support of `fp64 atomics` similar to `__HIP_ARCH_HAS_*_INT32_ATOMICS__` and some its variants.

**Comment by ppanchad-amd** [comment]
@abagusetty Sorry for the lack of response.  Do you still need assistance with this ticket? Thanks!
