### ISSUE TITLE
The number of compute units reported by rocminfo and hip/ocl API are not equal; 

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#2687]
The number of compute units (CUs) reported by rocminfo matches the specs of a GPU, but the number of CUs is half of the expected number using the HIP API function "hipDeviceGetAttribute" with the attribute "hipDeviceAttributeMultiprocessorCount".

In addition, the number of CUs read from both the OpenCL function "clGetDeviceInfo" and clinfo is also half of the expected number.

I built the ROCm components from source. Do you have pointers to the cause of issues ?

Thanks

**Comment by mangupta** [comment]
@zjin-lcf : Could you share details of which GPU you are seeing this issue on, OS details, ROCm version used, etc.? Also do you see this issue if you use the ROCm pre-built packages instead of building them yourself from source?

**Comment by zjin-lcf** [comment]
There is no pre-built package for Ubuntu 22.04. The device family is Navi 10 and the version of ROCm is 5.1.2. I don't remember the source of the error or if it has something to do with dual compute unit in RDNA architecture. Thank you for your pointer.

**Comment by keryell** [comment]
@zjin-lcf, oh you have some recipe for Ubuntu 22.04?

**Comment by gandryey** [comment]
GFX10 has WGP mode, which combines 2 CU(s) into 1 WGP. rocminfo reports the number of actual CUs, because it  doesn't control WGP mode. HIP and OCL are language runtimes and they control WGP mode, which is enabled by default. That's why the reported number is a half of rocminfo.

**Comment by zjin-lcf** [comment]
HIP and OpenCL program may compute the global work size for a kernel with the number of compute units. Is it recommended that rocminfo and HIP/OCL show the same number ?  

Thanks 

> @zjin-lcf, oh you have some recipe for Ubuntu 22.04?
Sorry, I look forward to the installer recipe in future ROCm releases.

**Comment by gandryey** [comment]
The app uses the language runtimes and should rely on the information reported from those API(s). ROCr doesn't control any language (kernel compilation). Hence, it can't decided ahead what to select and considers the low level physical CU mode as the base.
The latest hip runtime has the new query - hipDeviceAttributePhysicalMultiProcessorCount, which should match the rocminfo value.

**Comment by zjin-lcf** [comment]
Thanks again for your suggestions.
