### ISSUE TITLE
Significant performance drops in generated batched matrix multiplication kernels

### ISSUE THREAD

**Issue by ravil-mobile** [ROCm-Developer-Tools/HIP#2804]
Hi everyone,

I was testing some batched matrix multiplication kernels using HIP from ROCm 4.5.2, 5.1.0 and 5.1.3 suites. My target hardware is Mi200 i.e., gfx90a. The kernels themselves were generated with a python script. The multiplications took the following form: $A^{56, k} \cdot B^{k, 9}$, where $k \in [56, 55, 54, 53, 52, 51, 50, 49, 48]$. I used the outer product sum approach and unroll all the loops. Here is my obtained results.

![performance-comparison](https://user-images.githubusercontent.com/19637079/179536627-bc57ff6b-5528-462d-987a-e5ef5405d847.png)

The performance significantly drops when $k \in [55, 53, 51, 49]$. In theory, $k$ is the contraction length which, in my case, determines the bounds of the outer-most loop and thus should not affect performance. However, it influences the total number of instructions.

Here is my source code: [kernels.tar.gz](https://github.com/ROCm-Developer-Tools/HIP/files/9132989/kernels.tar.gz)

I suspect that something is wrong with the instruction scheduling. Could I ask somebody to have a look? For convenience, I am attaching the intermediate code as well. 
[kernel-hip-amdgcn-amd-amdhsa-gfx90a.s.txt](https://github.com/ROCm-Developer-Tools/HIP/files/9133007/kernel-hip-amdgcn-amd-amdhsa-gfx90a.s.txt)

Thank you in advance!

**Comment by ppanchad-amd** [comment]
@ravil-mobile Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!

**Comment by ravil-mobile** [comment]
Hi @ppanchad-amd. I can report that the problem disappeared starting from ROCm 5.4. The updated results can be found in https://onlinelibrary.wiley.com/doi/pdf/10.1002/cpe.8037
