### ISSUE TITLE
hipGetDeviceProperties doesn't have model of GPU for MI100, MI200.   Also -- Perhaps HIP version minor/major unchanging.

### ISSUE THREAD

**Issue by bigtrak** [ROCm-Developer-Tools/HIP#2807]
Using the HIP-Examples vectorAdd example, if you run it on a MI25, it outputs 
agent prop name of: Radeon Instinct MI25.   Running this on a MI100 or MI200,
the agent prop name is the empty string.   That  occurs with the current release rocm-5.2.0
as well as older releases.   That comes from hipDeviceProp_t & hipGetDeviceProperties()

Tested on centos-8 and on SLES.

In addition, the hipDeviceProp_t  major and minor has not changed since rocm-4.5,
which is the earliest version I have on hand to test.

This occurs with multiple versions of rocm and the amdgpu driver.  Latest test was rocm-5.2.0
and amdgpu-dkms-5.16.9.22.20.50200-1438747 on el8.   

Replicate via 
git clone https://github.com/ROCm-Developer-Tools/HIP-Examples
cd HIP-Examples/vectorAdd
HIP_PATH=/opt/rocm-5.2.0/hip  ## or wherever you installed it
make
./vectoradd_hip.exe
re-run with ROCR_VISIBLE_DEVICES adjusted to the different GPUs
that you have access to, to select the different GPUs to see what
they output for 'agent prop name'.

It may be that some things have not been updates for newer GPUs, and perhaps
HIP versions as well -- GPU is an issue, I don't know what HIP versions should
be reported, same numbers for years at this point.

**Comment by bigtrak** [comment]
I found that this or a similar behavior also exists in ROCm itself.

I filed a ROCm issue on it, and refer to it here to link them together:

https://github.com/RadeonOpenCompute/ROCm/issues/1778

**Comment by abhimeda** [comment]
@bigtrak Hi, is your issue resolved on the latest HIP? If so can we close this ticket?

**Comment by bigtrak** [comment]
Yes, this is fixed definitely in rocm-6.0.   IIRC correctly it may have been fixed in a late rocm-5.x release; I no longer
have them available to test when it was fixed.
