### ISSUE TITLE
Feature request: rHIP (remote HIP)

### ISSUE THREAD

**Issue by erkinalp** [ROCm-Developer-Tools/HIP#2834]
To replicate a rCUDA-like remoting interface for HIP.

**Comment by b-sumner** [comment]
As  I understand it, rCUDA was developed by Technical University of Valencia.  Have you contacted them with this request?

**Comment by abhimeda** [comment]
@erkinalp Is your issue resolved? If so, can we please close this ticket?

**Comment by erkinalp** [comment]
Sadly no, this is still an issue.

**Comment by ppanchad-amd** [comment]
@erkinalp Can you please try contacting Technical University of Valencia with this feature request?

**Comment by erkinalp** [comment]
The developers sadly abandoned the project, and the website is parked.

**Comment by ppanchad-amd** [comment]
@erkinalp I will check with the internal team and will provide you an update. Thanks!

**Comment by ppanchad-amd** [comment]
@erkinalp Currently, there is no plan to implement or support this feature request. Thanks!
