### ISSUE TITLE
hipFuncGetAttribute is missing from HIP shared library.

### ISSUE THREAD

**Issue by pratik2542** [ROCm-Developer-Tools/HIP#2844]
I am having an issue with the file if which I have a hash.
#2197 #2124 #2564 #2807 #2807 #2807 #2348 #2729 
![image](https://user-images.githubusercontent.com/38732246/182824211-9bfb12e3-4417-423a-8ff5-7e35287f6560.png)

**Comment by zjin-lcf** [comment]
Is the name of the function 'hipFuncGetAttributes' ?

**Comment by abhimeda** [comment]
@pratik2542 Hi, is your issue resolved on the latest HIP? If so, can we please close this ticket?
