### ISSUE TITLE
dependencies problem when install hip-runtime-nvidia

### ISSUE THREAD

**Issue by ITCJ** [ROCm-Developer-Tools/HIP#2866]
after adding package server and `apt update` based on [Installation_Guide]

![image](https://user-images.githubusercontent.com/33901467/185734539-bf1f837e-67cc-425e-8304-94ce654e28fc.png)

**TRIED**
I have tried export `CUDA_PATH` manually, but it doesn't work either.

**Comment by JinlongLi2001** [comment]
have you solved this error，please？

**Comment by abhimeda** [comment]
@ITCJ Hi were you able to resolve your issue on the latest HIP? If so, can we please close this ticket?
