### ISSUE TITLE
HIP atomic is slower than Nvidia

### ISSUE THREAD

**Issue by yhlisnps** [ROCm-Developer-Tools/HIP#2914]
I used AMD MI100 and Nvidia V100, to test a very simple code. A value was added to the different memory using atomic. The test found that the V100 was three times faster than the MI100.Theoretically, V100 is worse than MI100 in all aspects such as memory frequency.Is there any way to solve this problem?

Sample code:
```c++
__global__ void kernel(
    const int* __restrict__ A,
    const int* __restrict__ D,
    volatile double* __restrict__ x,
    volatile int* d_graphInDegree)
{
    const int global_id = blockIdx.x * blockDim.x + threadIdx.x;
    int col = global_id / WARP_SIZE;
    const int local_warp_id = threadIdx.x / WARP_SIZE;
    
    //do something

    while (1 != d_graphInDegree[global_x_id]){};
    xi[local_warp_id] = x_dev[global_x_id];
    for (jj = D[global_id] + lane_id; jj < D[global_id+1]; jj += 64){
        double tmp=0.0;
         //do something
        atomicAdd((double*)&x[rowIdx], tmp);
        __threadfence();
        atomicSub((int*)&d_graphInDegree[rowIdx], 1);
    }
}
```

**Comment by b-sumner** [comment]
How many threads were adding values to how many atomics?  If the latter is 1, you may be benefiting from a cuda compiler optimization that HIP is not making.

**Comment by yhlisnps** [comment]
> How many threads were adding values to how many atomics? If the latter is 1, you may be benefiting from a cuda compiler optimization that HIP is not making.

Thx, There are multiple threads and multiple atomic in the code, does HIP have any plans to optimize it? Or is there any way to avoid it?

**Comment by b-sumner** [comment]
MI-100 must use compare-and-swap to implement double precision atomic add.  Double precision atomic add instructions were added in MI-200.  MI-100 does have a single precision atomic add instruction but it's a bit odd (it can't return the original value) so you must use `void atomicAddNoRet(float*, float)` to update it.

**Comment by yhlisnps** [comment]
> MI-100 must use compare-and-swap to implement double precision atomic add. Double precision atomic add instructions were added in MI-200. MI-100 does have a single precision atomic add instruction but it's a bit odd (it can't return the original value) so you must use `void atomicAddNoRet(float*, float)` to update it.

Thank you very much for your answer. My testing revealed just what you said.
