### ISSUE TITLE
[Question] How could get the version of processor?

### ISSUE THREAD

**Issue by galeselee** [ROCm-Developer-Tools/HIP#2918]
Hi, guys. I wonder how could I get the processor version such as `gfx1030` with HIP runtime api on AMDGPU. I could get the similar info(compute version) on NVIDIA GPU with `cuDeviceGetAttribute`
and  `CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR`. 
If it is not appropriate to ask questions here, could you point me to the HIP-related forum community?

**Comment by zjin-lcf** [comment]
https://gitlab.com/cscs-ci/ci-testing/ault-amdgpu/-/blob/master/helloworld.cpp
