### ISSUE TITLE
HIP compiler link error

### ISSUE THREAD

**Issue by olddrivertakemefly** [ROCm-Developer-Tools/HIP#292]
Recently i edit a program with hip ,and i find every time i compiler kernel（GPU） program with outside function,the compiler will  fail. But when i remove axi_host_time_inc  in kernel_function,it can compiler successfully. The detail information is as follow:

c language function:
axi_host_time_inc(axi_signal*) 
{

}
__global__ void kernel_function(hipLaunchParm lp,
                                axi_signal*axi_bus_out,
                                axi_signal*axi_bus_in,
                                int * men_addr,
                                const int width)
{
     
   ......
   axi_host_time_inc(axi_signal);
   ......
}

building information:
/opt/rocm/hip/bin/hipcc -g    -c -o axi.o axi.cpp
/opt/rocm/hip/bin/hipcc -g    -c -o 2dshfl.o 2dshfl.cpp
/opt/rocm/hip/bin/hipcc axi.o 2dshfl.o -o 2dshfl
/opt/rocm/hcc/bin/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_LO against symbol: axi_host_time_inc(axi_signal*) in readonly segment; recompile object files with -fPIC
>>> defined in /tmp/tmp.Uge2kgpYPI/kernel-gfx801.hsaco.isabin
>>> referenced by /tmp/tmp.Uge2kgpYPI/kernel-gfx801.hsaco.isabin:(main::HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_name_end_5::__cxxamp_trampoline(axi_signal*, axi_signal*, int*, int))

/opt/rocm/hcc/bin/ld.lld: error: can't create dynamic relocation R_AMDGPU_REL32_HI against symbol: axi_host_time_inc(axi_signal*) in readonly segment; recompile object files with -fPIC
>>> defined in /tmp/tmp.Uge2kgpYPI/kernel-gfx801.hsaco.isabin
>>> referenced by /tmp/tmp.Uge2kgpYPI/kernel-gfx801.hsaco.isabin:(main::HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_name_end_5::__cxxamp_trampoline(axi_signal*, axi_signal*, int*, int))
Generating AMD GCN kernel failed in ld.lld for target: gfx801
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Died at /opt/rocm/hip/bin/hipcc line 498.
Makefile:29: recipe for target '2dshfl' failed
make: *** [2dshfl] Error 1

Makefile:
HIP_PATH?= $(wildcard /opt/rocm/hip)
ifeq (,$(HIP_PATH))
        HIP_PATH=../../..
endif
ifeq (gfx701, $(findstring gfx701,$(HCC_AMDGPU_TARGET)))
        $(error gfx701 is not a supported device for this sample)
endif
HIPCC=$(HIP_PATH)/bin/hipcc
TARGET=hcc
SOURCES = axi.cpp 2dshfl.cpp
OBJECTS = $(SOURCES:.cpp=.o)
EXECUTABLE=./2dshfl
.PHONY: test
all: $(EXECUTABLE) test
CXXFLAGS =-g
CXX=$(HIPCC)
$(EXECUTABLE): $(OBJECTS)
        $(HIPCC) $(OBJECTS) -o $@
test: $(EXECUTABLE)
        $(EXECUTABLE)
clean:
        rm -f $(EXECUTABLE)
        rm -f $(OBJECTS)
        rm -f $(HIP_PATH)/src/*.o

Please tell me the problem~ Thank you all!

**Comment by RaymonSHan** [comment]
the global function running on GPU
the device function running on GPU

the normal function running on CPU
you can only call device function in global. not the normal C function.

**Comment by gargrahul** [comment]
Closing this issue since solution was provided.
