### ISSUE TITLE
HIP build on nvidia platform success but does find_package(hip) fails

### ISSUE THREAD

**Issue by Michael-Liao** [ROCm-Developer-Tools/HIP#2924]
using the instructions in `docs/markdown/hip_build.md` can successfully build on CUDA 11.7.
However, on invoking `find_package(hip)` it says I have unmet dependencies.
Perhaps update the documentation, so people understand which dependency is needed to build for the nvidia platform?

**Comment by abhimeda** [comment]
@Michael-Liao Hi, was your issue resolved? If so, can please close this ticket?
