### ISSUE TITLE
No CMakeLists.txt

### ISSUE THREAD

**Issue by xinlipn** [ROCm-Developer-Tools/HIP#2925]
Hello,
Try to build/install HIP on  Ubuntu 20.04.5 LTS with the steps below

https://rocmdocs.amd.com/en/latest/Programming_Guides/hip_install.html

1. cd HIP
2 .mkdir build
3. cd build
4. cmake ..
5. make
6. make install

Step 4 gives error below
does not appear to contain CMakeLists.txt.

Am I missing anything? Thanks

**Comment by abhimeda** [comment]
@xinlipn  Hi, were you able to resolve this issue on the latest HIP? If so can we close this ticket?
