### ISSUE TITLE
hipStreamPerThread - missing documentation, missing tests

### ISSUE THREAD

**Issue by pvelesko** [ROCm-Developer-Tools/HIP#2957]
The only mention of per-thread streams that I can find online is here:
https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-FAQ.html 

where it says it's still under development but it does seem that there is an implementation looking at HIPAMD. 

1. Is this feature complete yet? If so, where can I find the documentation for it?
2. Will there be a CUDA equivalent of `hipcc --default-stream per-thread/legacy`?

In terms of Catch2 testing I found 12 unit tests but it seems that none of them test for expected behavior when `HIP_API_PER_THREAD_DEFAULT_STREAM` macro is defined. 

One file seems to mention this vaguely - `hipStreamAPIEnable.cpp` where this define is commented out.

3. Clarification on testing the macro?

**Comment by gargrahul** [comment]
@pvelesko For stream per thread usage please check https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_faq.md#how-to-use-per-thread-default-stream-in-hip

**Comment by abhimeda** [comment]
@pvelesko  Hi, were you able to resolve this issue on the latest HIP? If so can we close this ticket?

**Comment by pvelesko** [comment]
@abhimeda I found the updated per-thread info here: https://github.com/ROCm/HIP/blob/develop/docs/user_guide/programming_manual.md

However, most of your website documentation still mentions it as under development - might want to update. @gargrahul


`HIP_API_PER_THREAD_DEFAULT_STREAM` is not supported like it is in CUDA. 

`hipcc --default-stream per-thread/legacy`  is actually `"-fgpu-default-stream=per-thread"`
