### ISSUE TITLE
[enhancement] cannot compile this non-scalar arg to printf yet

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#2963]
ROCm version: 4.5.2

```
main.cu:10:61: warning: format specifies type 'int' but the argument has type 'const __HIP_Coordinates<__HIP_ThreadIdx>::__X' [-Wformat]
    printf("thread %d", threadIdx.x);
                           ~~                               ^
main.cu:10:5: error: cannot compile this non-scalar arg to printf yet
    printf("thread %d", threadIdx.x);
```

**Comment by yxsamliu** [comment]
threadIdx etc are implemented in https://github.com/ROCm-Developer-Tools/hipamd/blob/develop/include/hip/amd_detail/amd_hip_runtime.h#L377

For performance reasons, they are not of integer type, therefore cannot be accepted by printf.

However, to fix this issue, we are going to lose performance.

A workaround is to explicitly cast threadIdx.x etc to int when passing to printf.

Considering performance is more important than printf, and workaround is easily available, we won’t fix this.

**Comment by zjin-lcf** [comment]
printf() is for debugging, and not for performance in the first place.  Thanks.

**Comment by abhimeda** [comment]
@zjin-lcf  Hi, were you able to resolve this issue on the latest HIP? If so can we close this ticket?
