### ISSUE TITLE
Does the compiler hipcc not support any optimization level higher than -O1 for inline assembly code?

### ISSUE THREAD

**Issue by terU3760** [ROCm-Developer-Tools/HIP#2983]
Successfully compiled some code on MI100 using hipcc with the following options:
`-O0 -U__HIP_NO_HALF_OPERATORS__ -U__HIP_NO_HALF_CONVERSIONS__ --amdgpu-target=gfx908 --no-offload-arch=gfx1030`
. But when change the option
`-O0`
to
`-O1` or `-O2` or `-O3`
, it fails to compile. The code has a lot of parts containing inline assemblies. Does the compiler hipcc not support any optimization level higher than -O1 for inline assembly code?

**Comment by yxsamliu** [comment]
hipcc supports inline assembly. If the inline assembly is GPU specific, it needs to be guarded by `#if __gfx908__` or `#if __gfx1030__`.

**Comment by terU3760** [comment]
Thanks. I found the problem change to both compiles OK but the program logic seems to be different.
