### ISSUE TITLE
hipcc optimization option "-O1" and above is not compatible with inline assembly code

### ISSUE THREAD

**Issue by terU3760** [ROCm-Developer-Tools/HIP#2993]
On MI100 gpu platform, say start from some environment configuration such as rocm4.2_ubuntu18.04_py3.6.
Firstly run the following command:
`git clone -b release/1.10 https://github.com/ROCmSoftwarePlatform/pytorch pytorch_ROCmSoftwarePlatform_release_v1.10 pytorch`
to clone the project and enter in into this project directory. Then (following the directions similar to [Frameworks 101 - Every Question a Successful Member Should be Able to Answer (Adrian Abeyta)](https://confluence.amd.com/pages/viewpage.action?pageId=383166939)) do the following:
`git submodule init`
`git submodule update --init --recursive`
`python3 tools/amd_build/build_amd.py`
`python setup.py develop --cmake-only`
`PYTORCH_ROCM_ARCH=gfx908 python setup.py develop`
The above commands successfully build the PyTorch for ROCm release 1.10.
Then run the following command:
`git clone --branch master https://github.com/terU3760/apex.git`
will the apex project for ROCm, the project is not public, the author can add you as a collaborator of it.
Within this apex project directory, run the following command to install it:
`pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" --global-option="--fmha" ./`
Factually only install the basic module and fmha module.
Will find it compiles OK. But if you modify the compiler option of module "--fmha" in setup.py from "-O0" to "-O1". Then it compiles with errors. The module is full of inline assemblies. Is hipcc optimization option "-O1" and above is not compatible with inline assembly code?
Thanks in advance.

The compiler version is:
`root@xxxxx:/var/lib/jenkins# hipcc --version`
`HIP version: 4.4.21432-f9dccde4`
`AMD clang version 13.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-4.5.2 21432 9bbd96fd1936641cd47defd8022edafd063019d5)`
`Target: x86_64-unknown-linux-gnu`
`Thread model: posix`
`InstalledDir: /opt/rocm/llvm/bin`

**Comment by searlmc1** [comment]
Hi,

Please provide a minimal reproducer. The minimal reproducer should provide
- a code snippet that fails to compile
- the compiler invocation to compile it
- the version of the compiler that is used
- the output of the failed compilation

Thanks

**Comment by terU3760** [comment]
Thanks. I found the problem change to both compiles OK but the program logic seems to be different.
