### ISSUE TITLE
[Question] How to handle runtime auto-detection if AMD GPU or Nvidia GPU is available?

### ISSUE THREAD

**Issue by madMAx43v3r** [ROCm-Developer-Tools/HIP#2994]
It seems we have to compile two binaries or shared libraries, one for AMD and one for Nvidia.

But then the question is still how to detect which GPUs are available at runtime (either in `C++` or `bash` or `python` for example) and then dynamically load the correct shared library?

**Comment by abhimeda** [comment]
@madMAx43v3r  Hi, were you able to resolve this issue on the latest HIP? If so can we close this ticket?
