### ISSUE TITLE
/opt/rocm/lib/cmake/hip/FindHIP.cmake does not find HIP by default

### ISSUE THREAD

**Issue by Snektron** [ROCm-Developer-Tools/HIP#3019]
When no environment variables are set, FindHIP.cmake attempts to find the HIP root directory from its installed path:
https://github.com/ROCm-Developer-Tools/HIP/blob/24c0cb92b38688b4db8cf80198752f2e8e03e248/cmake/FindHIP.cmake#L51
https://github.com/ROCm-Developer-Tools/HIP/blob/24c0cb92b38688b4db8cf80198752f2e8e03e248/cmake/FindHIP.cmake#L58-L68

There are two paths where FindHIP.cmake is installed: `/opt/rocm/lib/cmake/hip/FindHIP.cmake` and `/opt/rocm/hip/cmake/FindHIP.cmake`. In the latter case, `_IMPORT_PREFIX` gets resolved to `/opt/rocm/hip`, which indeed contains `bin/hipconfig`. In the former case though, it gets resolved to `/opt/rocm/lib/cmake`, which does not, and so `find_package(HIP)` fails when using this config file.

This is a regression from ROCm 5.2, though I believe that the line in question was always wrong. It broke after [this commit](https://github.com/ROCm-Developer-Tools/HIP/commit/357186bf9e6df79dbdd48570fc52ac892e2a1ec7). It can be worked around by using the other module by setting `-DCMAKE_MODULE_PATH=/opt/rocm/hip/cmake`.

**Comment by Madouura** [comment]
Likely related: https://github.com/ROCm-Developer-Tools/hipamd/issues/55

**Comment by abhimeda** [comment]
@Snektron  Hi, were you able to resolve this issue on the latest HIP? If so can we close this ticket?

**Comment by Snektron** [comment]
This particular part seems to be working now. There are still some issues remaining with an out-of-the-box experience, but that's a separate problem.
