### ISSUE TITLE
doc: Wrong documentation for `totalConstMem`

### ISSUE THREAD

**Issue by bertwesarg** [ROCm-Developer-Tools/HIP#3035]
See https://github.com/ROCm-Developer-Tools/HIP/blob/685390469af762268ab766245933033455f8c29d/include/hip/hip_runtime_api.h#L99

The `totalConstMem` member has the same documentation as `sharedMemPerBlock`:

```
size_t sharedMemPerBlock;  ///< Size of shared memory region (in bytes).
```

**Comment by abhimeda** [comment]
@bertwesarg  Hi, were you able to resolve this issue on the latest HIP? If so can we close this ticket?

**Comment by bertwesarg** [comment]
I'm not sure how I can resolve this. The code itself still looks the [same](https://github.com/ROCm/HIP/blob/310b089cbe21e29961797845dc5ddc30533a9d46/include/hip/hip_runtime_api.h#L114C1-L114C84):

```c
    size_t totalConstMem;             ///< Size of shared memory region (in bytes).
```

**Comment by ppanchad-amd** [comment]
@bertwesarg Internal ticket has been created to resolve this issue. Thanks!
