### ISSUE TITLE
Thread-safety of implicit `hipInit`

### ISSUE THREAD

**Issue by msimberg** [ROCm-Developer-Tools/HIP#3063]
I have the following minimal example which frequently segfaults with a stacktrace pointing inside `hipStreamCreate`:

```
#include <hip/hip_runtime.h>
#include <stdexcept>
#include <thread>

void check_hip(hipError_t error) {
  if (error != hipSuccess) {
    throw std::runtime_error(hipGetErrorString(error));
  }
}

int main() {
  // No segfault if hipInit is explicitly called before
  // check_hip(hipInit(0));

  hipEvent_t event;
  std::thread t2{[&]() {
          check_hip(hipEventCreate(&event));
  }};

  hipStream_t stream;
  std::thread t1{[&]() {
          // Segfault inside hipStreamCreate
          check_hip(hipStreamCreate(&stream));
  }};

  t1.join();
  t2.join();

  check_hip(hipStreamDestroy(stream));
  check_hip(hipEventDestroy(event));
}
```
With an explicit `hipInit` before the threads are created there is no segfault. If I swap the order of the two threads created it's instead `hipEventCreate` that segfaults. Presumably both `hipStreamCreate` and `hipEventCreate` are implicitly initializing HIP and it's not thread safe?

My question is then if this is:
1. A bug, and (implicit) initialization is supposed to be thread safe, or
2. Expected behaviour?

If the latter, is there any documentation explaining this? I could not find anything regarding thread safety (only this mentioning that most HIP API functions implicitly initialize the runtime: https://rocmdocs.amd.com/en/latest/ROCm_API_References/HIP_API/Initialization-and-Version.html?highlight=hipInit#hipinit).

I've tested this with HIP 5.2.3.

**Comment by abhimeda** [comment]
@msimberg Hi, is your issue resolved on the latest HIP? If so can we close this ticket?

**Comment by msimberg** [comment]
Hi, I don't know, but I can try it out. We've worked around this issue by having to initialize HIP as early as possible to avoid any potential concurrent initialization but I haven't tested the reproducer above with later versions.

Has anything been changed in HIP to make initialization thread-safe? Has it been documented somewhere whether or not it's supposed to be thread-safe?

**Comment by msimberg** [comment]
It does indeed look like the test above is no longer failing. I can still reproduce the failure with 5.2.3 and can't reproduce it with 5.7.1 and 6.0.0.
