### ISSUE TITLE
'omp.h' file not found

### ISSUE THREAD

**Issue by misos1** [ROCm-Developer-Tools/HIP#3069]
#2111

Seems this problem with `omp` reoccured (HIP version: 5.3.22061-e8e78f1a):
```
hipcc -fopenmp test.cpp
test.cpp:2:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
```

**Comment by klausbu** [comment]
I have the same problem when I try to compile rocBLAS with clients on RHEL 9.1 i.e. AlmaLinux 9.1. 

]$ hipcc --version

HIP version: 5.4.22801-aaa1e3d8
AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.0 22465 d6f0fe8b22e3d8ce0f2cbd657ea14b16043018a5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.4.0/llvm/bin

**Comment by misos1** [comment]
I think I resolved it by installing `rocm-openmp-sdk`. @klausbu Did this work for you?
