### ISSUE TITLE
How to get hsa_agent_t and hsa_queue_t from hip device and stream?

### ISSUE THREAD

**Issue by misos1** [ROCm-Developer-Tools/HIP#3087]
There was a simple way to do this with `hcc` thanks to functions like `accelerator_view::get_hsa_agent` and `accelerator_view::acquire_locked_hsa_queue`. Is this possible with `hip`?

**Comment by jatinx** [comment]
This is not possible anymore.

**Comment by abhimeda** [comment]
@misos1 Hi, is your issue resolved on the latest HIP? If so can we close this ticket?

**Comment by misos1** [comment]
@abhimeda I think this probably stayed in "not possible anymore" state (authors should know better than me).
