### ISSUE TITLE
hip-runtime-nvidia : Depends: cuda (>= 7.5) but it is not installable

### ISSUE THREAD

**Issue by JinlongLi2001** [ROCm-Developer-Tools/HIP#3096]
I need to install hip-runtime-nvidia on NVIDIA T600 GPU ,but it failed

$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

$ echo ${CUDA_PATH} 
/usr/local/cuda

$ echo ${PATH} 
/home/ljl/Apps/tecplot/360ex_2017r3/bin:/home/ljl/Apps/tecplot/chorus_2017r3/bin:/usr/local/cuda/bin:/home/ljl/Apps/anaconda3/bin:/usr/local/cmake/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

$ echo ${LD_LIBRARY_PATH} 
/home/ljl/Apps/sundials/lib:/home/ljl/Apps/tbb/lib64:/usr/local/cuda/lib64:/usr/lib:/usr/lib32:/usr/lib64

$ sudo apt install hip
hipblas                  hip-dev                  hipfft-dev               hipify-clang             hip-runtime-nvidia5.3.0  hipsolver-dev5.3.0
hipblas5.3.0             hip-dev5.3.0             hipfft-dev5.3.0          hipify-clang5.3.0        hip-samples              hipsparse
hipblas-dev              hip-doc                  hipfort                  hippomocks               hip-samples5.3.0         hipsparse5.3.0
hipblas-dev5.3.0         hip-doc5.3.0             hipfort5.3.0             hip-runtime-amd          hipsolver                hipsparse-dev
hipcub-dev               hipfft                   hipfort-dev              hip-runtime-amd5.3.0     hipsolver5.3.0           hipsparse-dev5.3.0
hipcub-dev5.3.0          hipfft5.3.0              hipfort-dev5.3.0         hip-runtime-nvidia       hipsolver-dev            

$ sudo apt install hip-runtime-nvidia
[sudo] password for ljl: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hip-runtime-nvidia : Depends: cuda (>= 7.5) but it is not installable
E: Unable to correct problems, you have held broken packages.

$ uname -a
Linux Ljl-TUF 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ more /etc/apt/sources.list.d/rocm.list
deb [arch=amd64] https://repo.radeon.com/rocm/apt/5.3 focal main
# deb [arch=amd64] https://repo.radeon.com/rocm/apt/5.0 focal main

**Comment by w-1x** [comment]
解决了吗？

**Comment by JinlongLi2001** [comment]
no

**Comment by yanrun000** [comment]
同问，解决了吗？

**Comment by abhimeda** [comment]
@jiuxiaocloud Hi, is your issue resolved on the latest HIP? If so can we close this ticket?
