### ISSUE TITLE
hipDeviceGetAttribute with hipDeviceAttributeWallClockRate returns error

### ISSUE THREAD

**Issue by misos1** [ROCm-Developer-Tools/HIP#3099]
While `hipDeviceAttributeClockRate` is working and returning correct frequency 1750 MHz, `hipDeviceAttributeWallClockRate` fails with error code `hipErrorInvalidValue` instead of correctly succeeding and returning 27000 kHz. Agent gfx900. Rocm 5.3.

``` c++
#include <hip/hip_runtime.h>

int main()
{
	int dev, rate;
	printf("%i\n", hipGetDevice(&dev));
	printf("%i\n", hipDeviceGetAttribute(&rate, hipDeviceAttributeClockRate, dev));
	printf("%i\n", rate);
	printf("%i\n", hipDeviceGetAttribute(&rate, hipDeviceAttributeWallClockRate, dev));
}
```
```
0
0
1750000
1
```

**Comment by zjin-lcf** [comment]
What is wall clock rate ?

**Comment by zjin-lcf** [comment]
I couldn't reproduce the result on an MI-series GPU

**Comment by misos1** [comment]
This was fixed in https://github.com/ROCm-Developer-Tools/hipamd/commit/4d6d791e1ef2fe28f74934a31b8097199cd77271 which got into rocm 5.4.
