### ISSUE TITLE
Question about wall clock

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#3110]
The wall clock frequency is about 20 - 30 MHz. Could you please explain its usage ? Thanks.  
 
```
long long int wall_clock64()
```
Returns wall clock count at a constant frequency on the device, which can be queried via HIP API with hipDeviceAttributeWallClockRate attribute of the device in HIP application code, for example,
```
int wallClkRate = 0; //in kilohertz
HIPCHECK(hipDeviceGetAttribute(&wallClkRate, hipDeviceAttributeWallClockRate, deviceId));
```
Where hipDeviceAttributeWallClockRate is a device attribute.
Note that, wall clock frequency is a per-device attribute.

**Comment by b-sumner** [comment]
The question is not clear to me.  To use it, you call wall_clock64() from device code.  To interpret its long long return value, you probably want to know the rate it increments, and that rate is provided as the device attribute.

**Comment by zjin-lcf** [comment]
Which function should a user choose in device code (kernel) for timing ? The GPU clock rate is about 1.6 GHz while the wall clock frequency is 20 - 30 MHz. I am confused that the wall clock frequency is much lower. Thanks.

long long int clock64()
long long int wall_clock64()

**Comment by b-sumner** [comment]
The choice is yours and depends on your needs..  Note that clock64() counts GPU cycles, which are variable rate.

The wall clock is driven by the board and is not entirely under AMD control.  There are boards that have a 100MHz wall clock.
