### ISSUE TITLE
Question about assembly instructions for query ID of a component

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#3123]
I assume that `smid` corresponds to a compute unit in the AMD GPU architecture. Could the ID of a compute unit be read with a single assembly instruction ?  Thanks. 

```
static __device__ __inline__ uint32_t __mysmid() {
    uint32_t smid;
    asm volatile("mov.u32 %0, %%smid;" : "=r"(smid));
    return smid;
}
```

**Comment by b-sumner** [comment]
You're programming in hip, so why not just use __smid()?

Also, are you aware that the result can change while the code is running?  This function just returns a snapshot.

**Comment by zjin-lcf** [comment]
I am not familiar with __smid(). Thank you for explaining the function.
