### ISSUE TITLE
How to use roc-obj with rocblas-bench

### ISSUE THREAD

**Issue by nishshah0** [ROCm-Developer-Tools/HIP#3152]
I am trying to benchmark MI250X with rocblas-bench and I see some discrepancy. I want to look at the assembly using roc-obj. How do I enable dumping the assembly for the kernel being launched by rocblas-bench. Here is my command
`./rocBLAS/build/release/clients/staging/rocblas-bench -m 8 -k 8 -n 8 -f gemm_ex -r bf16_r --compute_type f32_r -i 1 -j 1 --device 0`

I tried adding HIP env variable export GPU_DUMP_CODE_OBJECT=1 before launching rocblas-bench, and I see bunch of object files, 
![image](https://user-images.githubusercontent.com/122632692/216132567-15be901f-a217-4a93-a696-40a5f6b15461.png)
When I open them with command
`roc-obj -d _code_object0000.o`

I get following error

```
Error: No kernel section found
error: no executables specified
```

**Comment by jatinx** [comment]
This issue should be posted at https://github.com/ROCmSoftwarePlatform/rocBLAS

The team should be able to answer any rocblas related queries you have

**Comment by nishshah0** [comment]
Thanks, create issue in rocBLAS, https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/1295
