### ISSUE TITLE
[Question] Disabling L1 cache for specific variable

### ISSUE THREAD

**Issue by HardMax71** [ROCm-Developer-Tools/HIP#3159]
Hi, 

To test L2 cache, i would like to disable usage of L1 for specific variable in device functions. In CUDA, i can do it like [this](https://stackoverflow.com/questions/12553086/cuda-disable-l1-cache-only-for-one-variable):

```
__device__ __inline__ double ld_gbl_cg(const double *addr) {
  double return_value;
  asm("ld.global.cg.f64 %0, [%1];" : "=d"(return_value) : "l"(addr));
  return return_value;
}
```

What and how should i inline to acquire same result with HIP? Checked ISA GFX9, GFX10 docs, found only simple load instructions and 0 data whether L1 / L2 is used.

-- 
Specs: 
Rocm 4.5.0
GPU: RX 5500 XT 
Arch: gfx1012
OS: Ubuntu 20.04

**Comment by jatinx** [comment]
What exactly are you trying to do here? If you can give us some context we might be able to help you better with it.

**Comment by HardMax71** [comment]
Hi, @jatinx !

In general, i would like to measure L2 cache latency, and for that i would like to bypass L1 and load variable only to L2. More specifically, i would like to use an instruction like CUDA-specific [`ld.cg`](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#cache-operators) also on AMD GPUs.

What i have found out, is that for AMD GPU's `load_dword` with `dlc` = 1 is required, but i'm not sure, which `load_dword` instruction would suit best here.

**Comment by jatinx** [comment]
We advice against writing `asm` in HIP kernels.

What you might be looking for in non temporal loads: https://clang.llvm.org/docs/LanguageExtensions.html#non-temporal-load-store-builtins

**Comment by ppanchad-amd** [comment]
@HardMax71 Please advise if we can go ahead and close this ticket? Thanks!

**Comment by HardMax71** [comment]
@ppanchad-amd yes, you're free to close it. Thank you!
