### ISSUE TITLE
[Question] HipGraph & support for device graph launch

### ISSUE THREAD

**Issue by Kawaboongawa** [ROCm-Developer-Tools/HIP#3160]
Hello everyone,

I'm working on some implementations requiring an great level of determinism. A very interesting feature of cudaGraph since CUDA 12.0 allows to launch graph within the GPU. Is there an ambition to propose the same feature on HIP? I think it would be very interesting for professional applications.

Thank you.

**Comment by ppanchad-amd** [comment]
@Kawaboongawa Can you please check with latest ROCm 6.0.2 (HIP 6.0.32831)? Thanks!

**Comment by ppanchad-amd** [comment]
@Kawaboongawa Sorry for the lack of response.  Will check internally and let you know. Thanks!

**Comment by darren-amd** [comment]
Hi @Kawaboongawa,

Good question! We currently have support for launching graphs through hipGraphLaunch, which is similar to the cudaGraph feature cudaGraphLaunch: [Cuda Graph Launch](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__GRAPH.html#group__CUDART__GRAPH_1g1920584881db959c8c74130d79019b73). You can find the documentation for hipGraphLaunch, as well as other hipGraph features here: [HIP Graph Management](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___graph.html).

**Comment by RemiThales** [comment]
Hi @darren-amd,

I would be very interested in this feature on AMD devices: https://developer.nvidia.com/blog/enabling-dynamic-control-flow-in-cuda-graphs-with-device-graph-launch/
From what I have read, this does not exist yet with HIP. Are there any plans to add it?

Thanks!
