### ISSUE TITLE
question about HIP API for KERNEL_COMPILE_WORK_GROUP_SIZE

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#3166]
In OpenCL,  CL_KERNEL_COMPILE_WORK_GROUP_SIZE returns the work-group size specified in the kernel source. Is there a HIP API for querying the size at compile or run time?  Thanks.

Reference
https://registry.khronos.org/OpenCL/sdk/2.1/docs/man/xhtml/clGetKernelWorkGroupInfo.html

**Comment by jatinx** [comment]
I do not believe we have any way to query this sort of kernel meta data from HIP.

**Comment by zjin-lcf** [comment]
It may be helpful to query the sizes in the HIP plugin of the SYCL compiler. Thanks for considering it as a feature request.

https://github.com/intel/llvm/blob/sycl/sycl/plugins/hip/pi_hip.cpp

```
    case PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE: {
      // Returns the work-group size specified in the kernel source or IL.
      // If the work-group size is not specified in the kernel source or IL,
      // (0, 0, 0) is returned.
      // https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/clGetKernelWorkGroupInfo.html

      size_t group_size[3] = {0, 0, 0};
      return getInfoArray(3, param_value_size, param_value,
                          param_value_size_ret, group_size);
    }
```
