### ISSUE TITLE
Launch bounds

### ISSUE THREAD

**Issue by koparasy** [ROCm-Developer-Tools/HIP#3167]
When describing the launch bound conversion between cuda and hip [here](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_kernel_language.md#porting-from-cuda-__launch_bounds) you provide the following formula:

`MIN_WARPS_PER_EXECUTION_UNIT = (MIN_BLOCKS_PER_MULTIPROCESSOR * MAX_THREADS_PER_BLOCK) / 32`

I would expect something among the following lines:

`MIN_WARPS_PER_EXECUTION_UNIT = ((MIN_BLOCKS_PER_MULTIPROCESSOR * MAX_THREADS_PER_BLOCK) / 64) * NUMBER_OF_EU_PER_CU`

The Warp Size is equal to 64 and where `NUMBER_OF_EU_PER_CU` is equal to the number of simd-units (eu) on every compute unit.

**Comment by ppanchad-amd** [comment]
@koparasy Apologies for the lack of response. Can you please test with latest ROCm 6.0.2 (HIP 6.0.32831)? If resolved, please close ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@koparasy Closing ticket. Please re-open if you still need assistance with this ticket. Thanks!
