### ISSUE TITLE
`-fallow-half-arguments-and-returns` is not recognized using clang-16

### ISSUE THREAD

**Issue by littlewu2508** [ROCm-Developer-Tools/HIP#3178]
hipcc add an option `-Xclang -fallow-half-arguments-and-returns` when HIP_CLANG_HCC_COMPAT_MODE is true, and some tests use this option: https://github.com/ROCm-Developer-Tools/HIP/blob/369afc8bae6306f8a019e9d17a23a0427eae05ee/tests/catch/unit/deviceLib/CMakeLists.txt#L81

But clang-16 drop this argument: https://github.com/llvm/llvm-project/issues/61143, https://reviews.llvm.org/D133885

**Comment by yxsamliu** [comment]
I have a fix for this: https://reviews.llvm.org/D145345

**Comment by littlewu2508** [comment]
Hello, I see the patch is already accepted for  months. When is it going to be merged to llvm-project?

**Comment by yxsamliu** [comment]
> Hello, I see the patch is already accepted for months. When is it going to be merged to llvm-project?

sorry for the delay. it is now committed to trunk https://reviews.llvm.org/rG7f12dcac79f3d2653ae77cd1be0768e64ff7a518
