### ISSUE TITLE
[HIP] Segment fault when attemp to dynamically load libamdhip64.so and run hipInit(0)

### ISSUE THREAD

**Issue by galeselee** [ROCm-Developer-Tools/HIP#3180]
Hi, all
When i attempt to use some functions in `dlfcn.h`(e.g. dlopen, dlsym) to dynamically load `libamdhip64.so` and run `hipInit` function(ignore the dlclose for now). There will be a segment fault when `hipInit` is running.  

Env: 
1. ROCm - 5.4.3
2. clang++(version 14.0.0)
3. RX 6900XT(gfx1030)

How to compile
```
clang++ load.cpp(below) -ldl
```

Code
```
#include <dlfcn.h>
#include <iostream>
#include <string>
#include <unistd.h>
using namespace std;

void *load_dll(string name) {
    void* dll_ = nullptr;
    dll_ = dlopen(name.c_str(), RTLD_LAZY);
    if (dll_ == nullptr) {
        std::cout << "unable open the lib" << std::endl;
        exit(0);
    }
    return dll_;
}

void *load_function(void *dll_, string func_name) {
    if (dll_ == nullptr) {
        std::cout << "dll_ is nullptr" << std::endl;
        exit(0);
    }
    void * func = nullptr;
    func = dlsym(dll_, func_name.c_str());
    const char *dlsym_error = dlerror();
    if (dlsym_error) {
        std::cout << "load error in load_function" << std::endl;
        exit(0);
    }
    if (func == nullptr) {
        std::cout << "func is nullptr" << std::endl;
        exit(0);
    }
    return func;
}

void close_dll(void *dll) {
    dlclose(dll);
}

template <typename T>
void load_func(void *func, T &f) {
    f = T(func);
}

int main() {
    auto dll = load_dll("libamdhip64.so");
    auto init = load_function(dll, "hipInit");
    unsigned int(*initfunc)(unsigned int);

    load_func(init, initfunc);
    auto err = initfunc(0);
    if (err != 0) {
        std::cout << "init error " << err << std::endl;
    }
    std::cout << "finish to init" << std::endl;
    close_dll(dll);
}

```

**Comment by galeselee** [comment]
Note, when i use hipcc to compile the code, it works. :-)
Maybe `dlsym` and `libamdhip64.so` are in confilct, but i want to know why. And what behavior is allowed to finish the work.

**Comment by jatinx** [comment]
Seems to be working fine.
The difference is my clang version (17) and rocm version. I have same GPU as yours
clang++ --version
clang version 17.0.0 (https://github.com/llvm/llvm-project.git 63178c36354881c3e3f3e3bbd716d8e4b3f38b07)
Target: x86_64-unknown-linux-gnu
Thread model: posix
clang++ load.cc
./a.out
finish to init

**Comment by galeselee** [comment]
> Seems to be working fine.
> The difference is my clang version (17) and rocm version. I have same GPU as yours
> clang++ --version
> clang version 17.0.0 (https://github.com/llvm/llvm-project.git 63178c36354881c3e3f3e3bbd716d8e4b3f38b07)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> clang++ load.cc
> ./a.out
> finish to init

Thanks for your reply! Could you tell me the version of your rocm?

**Comment by jatinx** [comment]
I am on development branch of ROCm. i.e. latest sources from hip, hipamd and rocclr.

**Comment by galeselee** [comment]
Thanks! I'll be waiting for the next version
