### ISSUE TITLE
Question about the implementation of ihipModule_t

### ISSUE THREAD

**Issue by Jackwin** [ROCm-Developer-Tools/HIP#3185]
Hi folks,

Right now, I'm reading the code of HIP runtime, and find that _ihipModule_t_ is used in the hip_runtime_api.h, but cannot get its implementation. So I'm curious that whether the detail of  ihipModule_t is opened or not? Thanks.
`typedef struct ihipModule_t* hipModule_t;`

**Comment by yxsamliu** [comment]
It is implemented as amd::Program.
https://github.com/ROCm-Developer-Tools/hipamd/blob/05e3016405bdaec0b8acfe8378df968dd02136d5/src/hip_fatbin.hpp#L62
ihipModule_t is an opaque struct which has no implementation. It just makes hipModule_t like a pointer to the compiler.

**Comment by Jackwin** [comment]
@yxsamliu  Cool, thanks. It's clear now. Are there any docs or codes about amd::program? Thanks again.
