### ISSUE TITLE
Failure to get device count with multiple GPUs

### ISSUE THREAD

**Issue by jordan44665** [ROCm-Developer-Tools/HIP#3191]
I have an application that runs fine with one AMD W6800 (using HIP API). But when I add another GPU into the same machine, it doesn't work. 

When I run rocm-smi, before running the application, I am able to see two devices:

```
GPU  Temp (DieEdge)  AvgPwr  SCLK    MCLK   Fan     Perf  PwrCap  VRAM%  GPU%  
0    50.0c           46.0W   500Mhz  96Mhz  40.78%  auto  213.0W    0%   2%    
1    47.0c           48.0W   500Mhz  96Mhz  40.78%  auto  213.0W    0%   1%    
```

Then, I load my application in gdb and set a break point in main() and as soon as I hit the breakpoint, rocm-smi give this output and hipGetDeviceCount() returns 100.

```
======================= ROCm System Management Interface =======================
================================= Concise Info =================================
Expected integer value from monitor, but got ""
Expected integer value from monitor, but got ""
================================================================================
================================================================================
Expected integer value from monitor, but got ""
Expected integer value from monitor, but got ""
Expected integer value from monitor, but got ""
Expected integer value from monitor, but got ""
================================================================================
================================================================================
Expected integer value from monitor, but got ""
Expected integer value from monitor, but got ""
GPU  Temp (DieEdge)  AvgPwr  SCLK  MCLK  Fan  Perf     PwrCap       VRAM%  GPU%  
0    N/A             N/A     None  None  0%   unknown  Unsupported    0%   0%    
1    N/A             N/A     None  None  0%   unknown  Unsupported    0%   0%    
```

Any idea what's going on here?

I am running:

HIP version: 5.4.22802-aaa1e3d8
AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.1 22465 d6f0fe8b22e3d8ce0f2cbd657ea14b16043018a5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.4.1/llvm/bin

**Comment by jatinx** [comment]
Can you run the application with `AMD_LOG_LEVEL=7 ./a.out` and share the log

**Comment by jordan44665** [comment]
I figured out (actually one of my colleagues) that I had to disable power management. The GPU cards were being powered down.
