### ISSUE TITLE
function hipInit(unsigned int flags) does not provide any documentation for the flags parameter

### ISSUE THREAD

**Issue by Noerr** [ROCm-Developer-Tools/HIP#3195]
Function `hipInit` is declared in hip_runtime_api.h
HIP API documentation for hipInit autogenerates for this function.  The resulting documentation provides no description for the purpose of the `unsigned int flags` input parameter.

Please update the documentation. I do not know how to use `hipInit`
https://sep5.readthedocs.io/en/latest/ROCm_API_References/HIP_API/Initialization-and-Version.html

**Comment by jatinx** [comment]
Thanks for pointing it out. Will add documentation to hipInit API

**Comment by ppanchad-amd** [comment]
@Noerr Internal ticket has been created to resolve this issue. Thanks!

**Comment by harkgill-amd** [comment]
Hi @Noerr, the documentation for hipInit was updated to describe the `flags` input parameter with commit https://github.com/ROCm/HIP/commit/8a6491289feb44965e1e67b3f583640ea01240b4.
```
@param [in] flags  Initialization flag, should be zero.
```
The updated documentation can also be found [here](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___driver.html#ga01baa652dda5815c594d047060496caa).
