### ISSUE TITLE
Documentation inconsistent about preprocessor macros identifying AMD or NVIDIA platform

### ISSUE THREAD

**Issue by Noerr** [ROCm-Developer-Tools/HIP#3199]
`HIP_PLATFORM_AMD` or `__HIP_PLATFORM_AMD__` ?
`HIP_PLATFORM_NVIDIA` or `__HIP_PLATFORM_NVIDIA__` ?

The paragraph [Identifying HIP Target Platform](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/markdown/hip_porting_guide.md#identifying-hip-target-platform) should be more explicit in use of "is defined".  

If talking about a preprocessor macro definition, then these names without double underscore are inconsistent with the following paragraph.

If talking about an environment variable set, then say "is defined in the environment".  ( I suspect this is not the case, what would define such a variable )

This [HIP FAQ by AMD](https://docs.amd.com/bundle/HIP-FAQ/page/Introduction_to_HIP-FAQ.html#d2e1018) suggests the right macro is no double underscores.

**Comment by jatinx** [comment]
Hello,
Thanks for pointing it out. The macro is definitely an issue and will fix it. The correct macro has underscores
The FAQ's env variable are used for config/compiling HIP or running hipcc. That does not have underscores.

**Comment by ppanchad-amd** [comment]
@Noerr Internal ticket has been created to resolve this issue? Thanks!

**Comment by harkgill-amd** [comment]
Not sure how https://github.com/rocm-ci/HIP/commit/918214ecabd2608058d615471249150b0a549fc4 was overwritten but the macros have once again been updated in https://github.com/ROCm/HIP/pull/3636. As @jatinx mentioned, the correct macros **have** underscores. Thanks again for bringing this up!
