### ISSUE TITLE
What is the .cui file in the hipcc compiling?

### ISSUE THREAD

**Issue by Jackwin** [ROCm-Developer-Tools/HIP#3200]
Hi folks,

when running the command `hipcc ../vectoradd_hip.cpp -o vector_add -save-temps -v 1&> log` to check out the temporary outputs in the [vector_add example design](https://github.com/ROCm-Developer-Tools/HIP-Examples/tree/master/vectorAdd), a .cui file is generated. But, I'm curious about the `.cui `file but there are no files to explain it. So, any hints/documentation about the cui file?

Moreover, when checking the log of  hipcc compilation flow, it can be summarized as two parts:
1. Device: Cpp -> .cui -> .bc ->.s -> .o -> .out->hipfb
2. Host: (hipfb+host.cui) ->host.bc -> host.s -> host.o ->(ld.lld )

I have two questions about the flow:
1. why there is a cui file, could we replace cui file with ll file(LLVM IR)?
2. I would like to write a Makefile to control the device and the host compilation flow step by step, any reference script? 

Thanks

**Comment by yxsamliu** [comment]
It is preprocessor expansion output. In newer clang versions it has been renamed as .hipi file.

.bc file is LLVM IR in binary format. You can disassemble it with llvm-dis.

If you want to duplicate the device and host compilations done by clang,  you have to check the output of clang with -v -save-temps and follow them. clang detects standard C++ include and lib path and HIP include and lib path and add them. It also detects HIP device library path and add them. It also translates options to clang -cc1 options. You may be able to do that for simple cases but it is error-prone for general cases, therefore it is not recommended.

**Comment by Jackwin** [comment]
Hi @yxsamliu Thank you for your prompt reply. Any newer version you recommend, as I use Rocm 4.5.3 and clang 15.0.0, which I think is not quite old?

Yes, I have used -v -save-temps to record the compiling steps, and the whole compilation is controlled by the Perl script `/opt/rocm-5.4.3/bin/hipcc.pl`, right? The detection of C++ include &lib/HIP include & lib is conducted by the same Perl ? Please correct me if I'm wrong. I'm wondering how the complicated compilation flow is conducted.

Thanks

**Comment by yxsamliu** [comment]
I recommend the latest ROCm release 5.4.

hipcc.pl is a wrapper for clang. hipcc.pl detects HIP includes and libs but it is unnecessary and will be removed in future. clang itself detects HIP include and lib path and C++ include and lib path. The compilation stages you saw with '-v' is determined by clang driver https://clang.llvm.org/docs/DriverInternals.html . For HIP, it involves offloading, therefore it is more complicated. There is no documentation for HIP offloading toolchain but there is one for OpenMP (https://clang.llvm.org/docs/OffloadingDesign.html), which is similar to HIP offloading.

**Comment by Jackwin** [comment]
Correct my ROCm version. Right now I'm using `/opt/rocm-5.4.3, version 5.4.22804`, sorry for the mistake. But I did not see the .hipi file when invoking `hipcc -v` . Could you show the log or the command/script? Or .cui is still used in 5.4.3 ?

Many thanks for the information on the clang driver and OpenMP offloading, quite helpful.
