### ISSUE TITLE
ld.lld: error: undefined symbol: main

### ISSUE THREAD

**Issue by Looong01** [ROCm-Developer-Tools/HIP#3202]
At first, I installed rocm-5.4.2, and everything is OK.

Then I upgraded it to version 5.4.3. After that it returns errors when I use ```hipcc -v```.

```
(PyTorch) loong@home:~$ hipcc -v
AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.3 23045 a29fe425c7b0e5aba97ed2f95f61fd5ecba68aed)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.4.3/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found HIP installation: /opt/rocm-5.4.3, version 5.4.22804
 "/opt/rocm-5.4.3/llvm/bin/ld.lld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /lib/x86_64-linux-gnu/crt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/12/crtbegin.o -L/opt/rocm-5.4.3/lib -L/opt/rocm-5.4.3/llvm/bin/../lib/clang/15.0.0/lib/linux -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib -L/usr/lib/llvm-14/lib -L. -lgcc_s -lgcc -lpthread -lm -lrt -rpath=/opt/rocm-5.4.3/lib:/opt/rocm-5.4.3/lib -lamdhip64 -lclang_rt.builtins-x86_64 -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/12/crtend.o /lib/x86_64-linux-gnu/crtn.o
ld.lld: error: undefined symbol: main
>>> referenced by /lib/x86_64-linux-gnu/crt1.o:(_start)
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jatinx** [comment]
Can you share the output with `HIPCC_VERBOSE=1`

So something like `HIPCC_VERBOSE=1 hipcc -v`

**Comment by Looong01** [comment]
> Can you share the output with `HIPCC_VERBOSE=1`
> 
> So something like `HIPCC_VERBOSE=1 hipcc -v`

(base) loong@home:~$ HIPCC_VERBOSE=1 hipcc -v
hipcc-cmd: /opt/rocm-5.4.3/llvm/bin/clang++  -L"/opt/rocm-5.4.3/lib" -O3 -lgcc_s -lgcc -lpthread -lm -lrt  -v -Wl,-rpath=/opt/rocm-5.4.3/lib:/opt/rocm-5.4.3/lib -lamdhip64  -L/opt/rocm-5.4.3/llvm/bin/../lib/clang/15.0.0/lib/linux -lclang_rt.builtins-x86_64
AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.3 23045 a29fe425c7b0e5aba97ed2f95f61fd5ecba68aed)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.4.3/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found HIP installation: /opt/rocm-5.4.3, version 5.4.22804
 "/opt/rocm-5.4.3/llvm/bin/ld.lld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /lib/x86_64-linux-gnu/crt1.o /lib/x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/12/crtbegin.o -L/opt/rocm-5.4.3/lib -L/opt/rocm-5.4.3/llvm/bin/../lib/clang/15.0.0/lib/linux -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib -L/usr/lib/llvm-14/lib -L. -lgcc_s -lgcc -lpthread -lm -lrt -rpath=/opt/rocm-5.4.3/lib:/opt/rocm-5.4.3/lib -lamdhip64 -lclang_rt.builtins-x86_64 -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/12/crtend.o /lib/x86_64-linux-gnu/crtn.o
ld.lld: error: undefined symbol: main
">>>" referenced by /lib/x86_64-linux-gnu/crt1.o:(_start)
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jatinx** [comment]
The issue was due to hipcc script adding a certain flags to clang call.

hipcc is being moved to https://github.com/ROCm-Developer-Tools/hipcc

the new hipcc should not have this issue.

**Comment by TNTran92** [comment]
I have the same issue. Using HIP 6.0.24015

```
ld.lld: error: undefined symbol: main
>>> referenced by /lib/x86_64-linux-gnu/crt1.o:(_start)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ppanchad-amd** [comment]
@jatinx Can you please confirm if this is resolved with latest ROCm 6.0.2 (HIP 6.0.32831)? Thanks!

**Comment by chengl-amd** [comment]
Hi, I met the same issue when run 'hipcc -v' in ROCm 6.0.2 docker:

![image](https://github.com/ROCm/HIP/assets/144640849/535868a2-d471-423c-a374-633edbf81887)

**Comment by Looong01** [comment]
~$ hipcc -v
AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-6.0.2 24012 af27734ed982b52a9f1be0f035ac91726fc697e4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-6.0.2/llvm/bin
Configuration file: /opt/rocm-6.0.2/lib/llvm/bin/clang++.cfg
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found HIP installation: /opt/rocm-6.0.2/lib/llvm/bin/../../.., version 6.0.32831
 "/opt/rocm-6.0.2/llvm/bin/ld.lld" -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /lib/x86_64-linux-gnu/crt1.o /lib/x86_64-linux-gnu/crti.o /opt/rocm-6.0.2/lib/llvm/lib/clang/17.0.0/lib/linux/clang_rt.crtbegin-x86_64.o -L/usr/lib/gcc/x86_64-linux-gnu/12 -L/usr/lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/lib -L/usr/lib --enable-new-dtags -L/opt/rocm-6.0.2/lib/llvm/bin/../../../lib -rpath /opt/rocm-6.0.2/lib/llvm/bin/../../../lib -lamdhip64 -lstdc++ -lm /opt/rocm-6.0.2/lib/llvm/lib/clang/17.0.0/lib/linux/libclang_rt.builtins-x86_64.a -lgcc_s -lc /opt/rocm-6.0.2/lib/llvm/lib/clang/17.0.0/lib/linux/libclang_rt.builtins-x86_64.a -lgcc_s /opt/rocm-6.0.2/lib/llvm/lib/clang/17.0.0/lib/linux/clang_rt.crtend-x86_64.o /lib/x86_64-linux-gnu/crtn.o
ld.lld: error: undefined symbol: main
>>> referenced by /lib/x86_64-linux-gnu/crt1.o:(_start)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yxsamliu** [comment]
seems to be hipcc issue. it should not add options for libraries or libraries as input files when -v is specified.

**Comment by shiltian** [comment]
If the intention of using `-v` is to check version, then `--version` needs to be used. For clang, `-v` means "Show commands to run and use verbose output". ROCm sets up a clang config file that appends more arguments to the clang driver, specifically linker related arguments. That is the reason the linker was invoked.

```
➜  cat /opt/rocm/lib/llvm/bin/rocm.cfg
-Wl,--enable-new-dtags
--rocm-path='<CFGDIR>/../../..'
-frtlib-add-rpath
```

FWIW, even for GCC, `-v` doesn't mean to check version. I don't think the convention in command line applications that using `-v` to check version applies here.

With that being said, I don't think there is anything wrong.

**Comment by anusha-bylla** [comment]
hello sir, I'm getting this which i don't understand. can you please help me to solve this error.

FAILED: libQGroundControl_x86_64.so 
C:\Windows\system32\cmd.exe /C "cd . && D:\SDK\ndk\26.1.10909125\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=x86_64-none-linux-android23 --sysroot=D:/SDK/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -DQT_QML_DEBUG   -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -g  -fno-limit-debug-info  -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--gc-sections -Qunused-arguments -Wl,--no-undefined   -Wl,-Bsymbolic -shared  -o libQGroundControl_x86_64.so @CMakeFiles\QGroundControl.rsp && cd ."
ld.lld: error: undefined symbol: jpeg_CreateDecompress
>>> referenced by gstgloverlay.c:682 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:682)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: jpeg_std_error
>>> referenced by gstgloverlay.c:683 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:683)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: jpeg_stdio_src
>>> referenced by gstgloverlay.c:684 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:684)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: jpeg_read_header
>>> referenced by gstgloverlay.c:685 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:685)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: jpeg_start_decompress
>>> referenced by gstgloverlay.c:686 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:686)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: jpeg_read_scanlines
>>> referenced by gstgloverlay.c:722 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:722)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: jpeg_finish_decompress
>>> referenced by gstgloverlay.c:724 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:724)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: jpeg_destroy_decompress
>>> referenced by gstgloverlay.c:725 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:725)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: png_sig_cmp
>>> referenced by gstgloverlay.c:764 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:764)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: graphene_matrix_get_type
>>> referenced by gstgltransformation.c:242 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgltransformation.c:242)
>>>               gstgltransformation.c.o:(gst_gl_transformation_class_intern_init) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a
>>> referenced by gstglfiltershader.c:384 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstglfiltershader.c:384)
>>>               gstglfiltershader.c.o:(_set_uniform) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a
>>> referenced by gstglfiltershader.c:384 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstglfiltershader.c:384)
>>>               gstglfiltershader.c.o:(_set_uniform) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: graphene_matrix_alloc
>>> referenced by gstgltransformation.c:271 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgltransformation.c:271)
>>>               gstgltransformation.c.o:(gst_gl_transformation_init) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a
>>> referenced by gstgltransformation.c:272 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgltransformation.c:272)
>>>               gstgltransformation.c.o:(gst_gl_transformation_init) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a
>>> referenced by gstgltransformation.c:273 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgltransformation.c:273)
>>>               gstgltransformation.c.o:(gst_gl_transformation_init) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a
>>> referenced 4 more times

ld.lld: error: undefined symbol: png_create_read_struct
>>> referenced by gstgloverlay.c:770 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:770)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: png_set_error_fn
>>> referenced by gstgloverlay.c:779 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:779)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: png_create_info_struct
>>> referenced by gstgloverlay.c:781 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:781)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: png_init_io
>>> referenced by gstgloverlay.c:790 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:790)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: png_set_sig_bytes
>>> referenced by gstgloverlay.c:792 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:792)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: graphene_vec3_alloc
>>> referenced by gstgltransformation.c:279 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgltransformation.c:279)
>>>               gstgltransformation.c.o:(gst_gl_transformation_init) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: png_read_info
>>> referenced by gstgloverlay.c:794 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:794)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: png_get_IHDR
>>> referenced by gstgloverlay.c:796 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:796)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: undefined symbol: png_set_filler
>>> referenced by gstgloverlay.c:801 (/home/nirbheek/projects/repos/cerbero.git/1.22/build/sources/android_universal/x86_64/gst-plugins-base-1.0-1.22.12/_builddir/../ext/gl/gstgloverlay.c:801)
>>>               gstgloverlay.c.o:(gst_gl_overlay_filter_texture) in archive _deps/gstreamer/install/gstreamer/x86_64/lib/gstreamer-1.0/libgstopengl.a

ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
09:43:23: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 1.
09:43:23: Error while building/deploying project QGroundControl (kit: Android Qt 6.8.1 Clang x86_64)
09:43:23: When executing step "Build"
09:43:23: Elapsed time: 18:47.
