### ISSUE TITLE
clarify behavior of hipLaunchHostFunc

### ISSUE THREAD

**Issue by Noerr** [ROCm-Developer-Tools/HIP#3204]
`hipLaunchHostFunc` does not appear in the [HIP API documentation](https://rocm-developer-tools.github.io/HIP/index.html) .   After reviewing the header `HIP/include/hip_runtime_api.h` description,  I request a clarification be added.

`hipError_t hipLaunchHostFunc(hipStream_t stream, hipHostFn_t fn, void* userData);`

**Does the stream block until after hipHostFn_t fn returns?**

In other words, would an event added to in-order stream *after* the hipLaunchHostFunc call not execute until *after* for hipHostFn_t fn completes?

**Comment by jatinx** [comment]
Regarding the documentation missing, I have raised a query. There seems to be doxygen documentation present but not being populate.

Regarding hipLaunchHostFunc behavior, it should block subsequent enqueued commands. So the event should not execute till host function returns.

**Comment by ppanchad-amd** [comment]
@Noerr Internal ticket has been created to update documentation? Thanks!

**Comment by harkgill-amd** [comment]
Hi @Noerr, the documentation for `hipLaunchHostFunc` is available [here](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___clang.html#ga154cd475c8e1b9e623981fc165c543a9). The header in [`hip_runtime_api.h`](https://github.com/ROCm/HIP/blob/develop/include/hip/hip_runtime_api.h#L5942) has also been updated to clarify the blocking behaviour of the function.

**Comment by Noerr** [comment]
Thank You!
