### ISSUE TITLE
Link to `INSTALL.md` from `README.md` no longer works 

### ISSUE THREAD

**Issue by ajahraus** [ROCm-Developer-Tools/HIP#3214]
The link to the "Install Note" in the `README.md` file points to the old location. The `INSTALL.md` file has been moved from the top level directory to `docs\install.md` as of #3192. 

`README.md` should be updated to point to the new file locations.

**Comment by ppanchad-amd** [comment]
@ajahraus Please confirm if we can go ahead and close this ticket? Thanks!

**Comment by harkgill-amd** [comment]
Hi @ajahraus, the `README.md` has changed significantly and now contains updated links under the "More Info" and "How do I get set up?" sections. If you still see any issues with the links in `README.md`, please re-open this ticket. Thanks!
