### ISSUE TITLE
[QA] hip vs opencl

### ISSUE THREAD

**Issue by muzhailong** [ROCm-Developer-Tools/HIP#3218]
ROCm support hip and opencl runtime, but I have some follow questions:

1. AMD will drop opencl?
2. the difference between hip and opencl except c++ language.
3. hip code will be converted to opencl code when the code is compiled?
4. if I want to use low-level api(instruct)，I should choose which one?

Thanks!

**Comment by b-sumner** [comment]
1. No.
2.  hip is a single source heterogeneous programming language and runtime.  OpenCL is dual (accelerator, host) source.
3. No, both are compiled directly to ISA via clang/LLVM.
4. Either one.  I strongly recommend against using inline ASM.

**Comment by muzhailong** [comment]
> 1. No.
> 2. hip is a single source heterogeneous programming language and runtime.  OpenCL is dual (accelerator, host) source.
> 3. No, both are compiled directly to ISA via clang/LLVM.
> 4. Either one.  I strongly recommend against using inline ASM.

in fact，I need to debug in asm level,in this way for me, which one is more friendly for coding and debug？

**Comment by ppanchad-amd** [comment]
@muzhailong Sorry for the delay in response. Do you still need assistance with this ticket? Thanks!
