### ISSUE TITLE
way to check if function exists in the module and unload the function from the module

### ISSUE THREAD

**Issue by miniskar** [ROCm-Developer-Tools/HIP#3220]
1. Is there a way to check if function name exists in the hipModule_t object or not? 
2.  I am getting a weird error when I call "hipModuleGetFunction(hipkernel_obj, module_obj, name)" again on the same function "name". 
     Error: "Device mismatch from where this module is loaded"
     I am wondering if there is a way to unload the function from the module

**Comment by jatinx** [comment]
1. hipModuleGetFunction will return hipErrorNotFound if function is not present
2. Can you share a minimal code sample which reproduces this error, along side compile options and your system config(ROCm version, AMD GPU name)

**Comment by miniskar** [comment]
Here is the piece of code. 
<img width="493" alt="image" src="https://user-images.githubusercontent.com/33693516/235736980-808bfcd6-0c05-412b-ba57-87e6ff36c9e4.png">

Context: 
We are working on a heterogeneous runtime system. 
We are having 4 MI100 GPUs and creating a thread for each GPU where each thread checks whether the function is available in it's module or not. All threads may try to check the same function name available in their respective modules. The thread object is holding its private module created by using hipModuleLoad(&module_, "kernels.hip"), where "kernels.hip" is common across all threads. Here is the timing sequence. 
T1: thread-1 calls hipModuleGetFunction for function name "saxpy" to check whether "saxpy" available or not. 
      It returns hipSuccess 
T2: thread-2 calls hipModuleGetFunction for function name "saxpy" to check whether "saxpy" available or not. 
     It returns Error: "Device mismatch from where this module is loaded"

I am having similar code for CUDA GPUs, where it doesn't return error. 

ROCM: 5.2.3. 
GPU: MI100

With Regards,
Narasinga.

**Comment by miniskar** [comment]
I found the problem. The context has been changed. When I set back the context to thread, it worked.
