### ISSUE TITLE
[Ubuntu][6.3.1 kernel][ROCm 5.5.0] Tensorflow Throwing a Segfault on a 7900 XTX (gfx1100)

### ISSUE THREAD

**Issue by Mushoz** [ROCm-Developer-Tools/HIP#3229]
I am trying to get Tensorflow to work on my 7900 XTX. This doesn't even attempt to run by default, so I had to compile HIP myself to enable GFX1100 support, as well as Tensorflow. It does correctly attempt to use my 7900 XTX now, but unfortunately it is still failing. 

I am running it inside a Ubuntu docker container, on an Archlinux host.

I have ran it with `AMD_LOG_LEVEL=7` set, and this is the full log:

[log.txt](https://github.com/ROCm-Developer-Tools/HIP/files/11445043/log.txt)

Any help would be much appreciated! Let me know if I can provide any more details.

**Comment by jatinx** [comment]
gfx1100 is not supported in ROCm 5.5

You need to recompile all of tensorflow and its dependencies with --offload-arch=gfx1100

**Comment by Mushoz** [comment]
Managed to get it to work by compiling Tensorflow myself, this time from the correct repo/branch. Build instructions can be found here for anyone running into the same issue: https://github.com/RadeonOpenCompute/ROCm/issues/1880#issuecomment-1547838227
