### ISSUE TITLE
Rename make_Complex() to make_hipComplex() in hip/nvidia_detail/nvidia_hip_complex.h 

### ISSUE THREAD

**Issue by torrance** [ROCm-Developer-Tools/HIP#3230]
In `hip/nvidia_detail/nvidia_hip_complex.h`, the function `make_Complex()` is incorrectly named.

It should be `make_hipComplex()` to be consistent with `hip/amd_detail/nvidia_amd_complex.h` as well as with HIPIFY.

**Comment by jatinx** [comment]
Thanks for pointing it out. Will fix it and should be available in future releases

**Comment by ppanchad-amd** [comment]
@jatinx Please advise if this has been fixed with latest ROCm 6.1.0 (HIP 6.1)? Thanks!

**Comment by torrance** [comment]
In 6.1.0, it looks like `make_Complex()` has been renamed to `make_hipFloatComplex()`, alongside `make_hipDoubleComplex()`.
