### ISSUE TITLE
How to use inline asm to store the value of array?

### ISSUE THREAD

**Issue by Tianlukr** [ROCm-Developer-Tools/HIP#3233]
How to use inline asm to store the value of array?
I did the following try:
```
__global__ void axpy(int4 *x, int4 *y) {
  int tid = threadIdx.x;
//   y[threadIdx.x] = x[threadIdx.x];

  int r2[4];
  asm("flat_load_dwordx4 %0, %1": "=v"(r2): "v"(x[threadIdx.x]));
  asm("flat_store_dwordx4 %0, %1" : "=v"(y[threadIdx.x]) : "v"(r2));
}

```
Error:
Operand for indirect constraint must have elementtype attribute
  %2 = tail call i128 asm "flat_load_dwordx4 $0, $1", "=v,\*v"(%struct.HIP_vector_type\* %arrayidx) #4, !srcloc !5

**Comment by ppanchad-amd** [comment]
@Tianlukr Apologies for the lack of response.  Do you still assistance with your question? Thanks!

**Comment by ppanchad-amd** [comment]
@Tianlukr Closing ticket for now.  Please feel free to re-open ticket if you still require assistance. Thanks!
