### ISSUE TITLE
question about atomicAdd_system()

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#3244]
A flag is needed to determine whether atomicAdd_system() is supported in HIP.  The value of hipDeviceAttributeComputeCapabilityMajor seems to be 9. It is not clear which values may indicate the support of concurrent atomic access in HIP. Thanks for your comments. 

```
      if (getAttribute(device, hipDeviceAttributeComputeCapabilityMajor) >= 6) {
        // compute capability 6.x introduces operations that are atomic with
        // respect to other CPUs and GPUs in the system
        value |= PI_USM_CONCURRENT_ATOMIC_ACCESS;
```

**Comment by yxsamliu** [comment]
the closest query we have is `hipDeviceGetAttribute(&pcieAtomic, hipDeviceAttributeHostNativeAtomicSupported, 0)` e.g.

https://github.com/ROCm/hip-tests/blob/5d21315df45762d31082a0c8ea3d73285612c4a5/catch/unit/memory/hipSVMTestFineGrainSyncBuffers.cpp#L80C13-L80C95
