### ISSUE TITLE
Installation notes link is broken

### ISSUE THREAD

**Issue by gonidelis** [ROCm-Developer-Tools/HIP#3247]
Installation notes link is broken in README.

https://github.com/ROCm-Developer-Tools/HIP/blame/d4762f69efd0d35f2ccfa4ecf14bcbf898bf1fc4/README.md#L65

**Comment by jatinx** [comment]
please use clr to build hip on amd now.

https://github.com/ROCm-Developer-Tools/clr/

the link should have build steps

**Comment by ppanchad-amd** [comment]
@gonidelis Has this issue been resolved? If so, please close ticket. Thanks!
