### ISSUE TITLE
question about register usage by a HIP kernel 

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#3248]
Is it right the HIP runtime will never report an out-of-resource (launch) error for registers because the number of registers used by a GPU kernel will never exceed the maximum ? Thanks.

**Comment by yxsamliu** [comment]
That's right. The compiler calculates number of registers available based on launch bounds (if not specified, the default launch bounds) and only uses registers that are available. If a kernel launch fails due to insufficient registers, that is a compiler bug.
