### ISSUE TITLE
Allow querying LUID from device for better interoperability

### ISSUE THREAD

**Issue by Nielsbishere** [ROCm-Developer-Tools/HIP#3255]
Intel's open image denoiser (oidn) has a layer to better interface between HIP, CUDA and SYCL. This layer has a feature to query a device's LUID which is in turn used to create a device for interoperability between for example DirectX12 (since that only has the ability to get the adapter's LUID). 
Unfortunately due to HIP's limitation for querying a LUID (according to intel: https://github.com/OpenImageDenoise/oidn/issues/163) this doesn't seem possible right now. This would make implementing OIDN "hardware support" (gpu acceleration) in our engine to be quite bothersome (if it's even possible). Is it possible to get this feature natively in HIP?

**Comment by scarsty** [comment]
I have check the hipDeviceProp_t, it seems that only pci bus can be used to locate a physical video card. Here is a function to get luid from it:

https://github.com/scarsty/mlcc/blob/master/vramusage.h

**Comment by Nielsbishere** [comment]
@scarsty Thank you for your help, I'll forward this to oidn as well so it could be used if they desire.

**Comment by mangupta** [comment]
@Nielsbishere : Did you try [hipDeviceGetUuid](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/include/hip/hip_runtime_api.h#L1466)?

**Comment by scarsty** [comment]
> @Nielsbishere : Did you try [hipDeviceGetUuid](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/include/hip/hip_runtime_api.h#L1466)?

I have tried it. The result is "XX", and I thought it is of no use.

**Comment by ppanchad-amd** [comment]
@Nielsbishere Has your issue been resolved? If so, please close ticket. Thanks!

**Comment by Nielsbishere** [comment]
Adding @atafra here to see if there's any change here.

**Comment by salipourto** [comment]
ROCm 6+ supports LUID query. [Windows HIP SDK 6.1](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) just got released. OIDN now needs to enable LUID support on HIP devices: https://github.com/RenderKit/oidn/issues/230.
