### ISSUE TITLE
Problem when using half2 kernel

### ISSUE THREAD

**Issue by ardfork** [ROCm-Developer-Tools/HIP#3280]
I'm not sure if this is the right place to post that issue, please redirect me to the correct channel if it's the wrong one.

I recently added support for ROCm HIP on [ExLlama](https://github.com/turboderp/exllama), a standalone implementation of Llama. I had a bunch of problem with the hipified project outputting gibberish, it was found that this was an issue with kernels using half2.

Would it be possible to have someone with more knowledge than me look at where the problem is? Using `python test_benchmark_inference.py -d GPTQ-model-dir -p -v`  with and without `-fh2` (force half2) should expose the problem.

**Comment by cjatin** [comment]
The task of debugging this will be easier if you could share the code which PyTorch actually generates and tries to compile.

Also share your system information. GPU, ROCm version, OS etc

**Comment by ardfork** [comment]
I do not know how to make a smaller reproducible version.

As for my system information, I do not believe that it's relevant, the two others people that contributed to my HIP patch also had that issue and a more popular project that used ExLlama didn't disable half2 kernels and got at least 4 people reporting issues and none reported it working.

If you really want to know, I'm using Arch Linux on kernel 6.3.8 with ROCm 5.4.3, my GPU is an RX 6700 XT overridden to gfx1030, I also tried with the latest rocm/dev-ubuntu-22.04 docker image.

**Comment by ardfork** [comment]
Someone found the problem and fixed it. It was two different one.

First, HIP half2 struct is not the same as CUDA. On CUDA, half2 have two half type public variables x and y. Meanwhile, on HIP, x and y are unsigned short. I'm not sure if difference between CUDA and HIP are issues worth tracking.

The second issue was h2rcp producing incorrect result. The contributor that found the problem opened an issue on hipamd repo for that.
