### ISSUE TITLE
Segmentation fault in libamdhip64.so.5.4.22804

### ISSUE THREAD

**Issue by joerg-mank** [ROCm-Developer-Tools/HIP#3282]
When trying to run the example in https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html
I get following message: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
Running the python script with gdb I see that the segmentation fault appears here:
#0  0x00007fffa6ed9cd8 in  () at /opt/rocm/hip/lib/libamdhip64.so.5
I use pytorch-opt-rocm with 2.0.1-3
  rocm-hip-libraries 5.4.3-2
 
 My iGPU is an: VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo (rev c1) (prog-if 00 [VGA controller])
 My CPU is an AMD Ryzen 5825U

Any help is appreciated

**Comment by cjatin** [comment]
iGPUs are not supported.

Please refer to https://rocm.docs.amd.com/en/latest/release/gpu_os_support.html for supported GPUs

**Comment by mealejan** [comment]
Thank you for your help. For people stumbling over the same problem, there is a workaround, setting an env variable:
HSA_OVERRIDE_GFX_VERSION=9.0.0
allowed me to train on my iGPU.

**Comment by joerg-mank** [comment]
Thank you for your help. For people stumbling over the same problem, there is a workaround, setting an env variable:
HSA_OVERRIDE_GFX_VERSION=9.0.0
allowed me to train on my iGPU.
