### ISSUE TITLE
Test failures from distro package (Gentoo)

### ISSUE THREAD

**Issue by littlewu2508** [ROCm-Developer-Tools/HIP#3292]
This is some test results from Gentoo [`dev-util/hip-5.6.0`](https://github.com/littlewu2508/gentoo/blob/2e250ad8fcedabb0adc88e5ad749d2f8855dc07d/dev-util/hip/hip-5.6.0.ebuild) package on several GPUs. There are some test failures:

Radeon RX 6700XT has most failures:

Driver is Linux 6.4 upstream kernel
```
          6 - directed_tests/Functional/host/hipFloat161.22.3.tst (Subprocess aborted)
        108 - directed_tests/kernel/hipShflTests.tst (Subprocess aborted)
        109 - directed_tests/kernel/hipShflUpDownTest.tst (Subprocess aborted)
        121 - directed_tests/printf/hipPrintfManyWaves.tst (Bus error)
        185 - directed_tests/runtimeApi/memory/hipHostRegister.tst (Subprocess aborted)
        186 - directed_tests/runtimeApi/memory/hipIpcMemAccessTest.tst (Subprocess aborted)
        469 - Unit_hmax_hmin_Tsts (Failed)
        470 - Unit_hmax_hmin_Tsts_Negative (Failed)
        933 - Unit_hipHostRegister_Memcpy - int (Failed)
        934 - Unit_hipHostRegister_Memcpy - float (Failed)
        935 - Unit_hipHostRegister_Memcpy - double (Failed)
        1424 - Unit_HMM_OverSubscriptionTst (Failed)
        1664 - Unit_hipIpcOpenMemHandle_Negative_Open_In_Two_Contexts_Same_Device (Failed)
        1666 - Unit_hipIpcGetMemHandle_Positive_Unique_Handles_Reused_Memory (Failed)
        1669 - Unit_hipIpcCloseMemHandle_Positive_Reference_Counting (Failed)
        1771 - Unit_hipWaitExternalSemaphoresAsync_Vulkan_Positive_Binary_Semaphore (Subprocess aborted)
        1772 - Unit_hipWaitExternalSemaphoresAsync_Vulkan_Positive_Multiple_Semaphores (Subprocess aborted)
        1773 - Unit_hipWaitExternalSemaphoresAsync_Vulkan_Negative_Parameters (Subprocess aborted)
        1774 - Unit_hipSignalExternalSemaphoresAsync_Vulkan_Positive_Binary_Semaphore (Subprocess aborted)
        1775 - Unit_hipSignalExternalSemaphoresAsync_Vulkan_Positive_Multiple_Semaphores (Subprocess aborted)
        1776 - Unit_hipSignalExternalSemaphoresAsync_Vulkan_Negative_Parameters (Subprocess aborted)
        1777 - Unit_hipImportExternalSemaphore_Vulkan_Negative_Parameters (Subprocess aborted)
        1778 - Unit_hipDestroyExternalSemaphore_Vulkan_Negative_Parameters (Subprocess aborted)
        1793 - Unit_hipMemPrefetchAsyncOneToAll (Failed)
        1795 - Stress_printf_ComplexKernelMultStream (Subprocess aborted)
        1797 - Stress_printf_ConstStr (Bus error)
        1798 - Stress_printf_IfElseConditionalStr (Bus error)
        1799 - Stress_printf_IfConditionalStr (Bus error)
        1800 - Stress_printf_VariableStr (Bus error)
        1801 - Stress_printf_DependentCalc (Bus error)
        1802 - Stress_printf_DecimalStr (Bus error)
        1803 - Stress_printf_SharedMem (Bus error)
        1805 - Stress_printf_AtomicCalc (Bus error)
        1811 - Stress_deviceAllocation_malloc_loop_singlekernel (Bus error)
        1831 - Unit_hipIpcMemAccess_Semaphores (Timeout)
        1832 - Unit_hipIpcMemAccess_ParameterValidation (Failed)
```

Followed by Radeon VII and MI210, which is listed as officially supported GPU:

Radeon VII, Driver is Linux 6.3 upstream kernel:
```
        6 - directed_tests/Functional/host/hipFloat161.22.3.tst (Subprocess aborted)
        108 - directed_tests/kernel/hipShflTests.tst (Subprocess aborted)
        109 - directed_tests/kernel/hipShflUpDownTest.tst (Subprocess aborted)
        186 - directed_tests/runtimeApi/memory/hipIpcMemAccessTest.tst (Subprocess aborted)
        469 - Unit_hmax_hmin_Tsts (Failed)
        470 - Unit_hmax_hmin_Tsts_Negative (Failed)
        1664 - Unit_hipIpcOpenMemHandle_Negative_Open_In_Two_Contexts_Same_Device (Failed)
        1666 - Unit_hipIpcGetMemHandle_Positive_Unique_Handles_Reused_Memory (Failed)
        1669 - Unit_hipIpcCloseMemHandle_Positive_Reference_Counting (Failed)
        1781 - Unit_hipMemPrefetchAsyncOneToAll (Failed)
        1819 - Unit_hipIpcMemAccess_Semaphores (Timeout)
        1820 - Unit_hipIpcMemAccess_ParameterValidation (Failed)
```

MI210
Driver is amdgpu-dkms version rocm-5.6.0, installed on `Linux 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1`.
```
          6 - directed_tests/Functional/host/hipFloat161.22.3.tst (Subprocess aborted)
        108 - directed_tests/kernel/hipShflTests.tst (Subprocess aborted)
        109 - directed_tests/kernel/hipShflUpDownTest.tst (Subprocess aborted)
        201 - directed_tests/runtimeApi/memory/hipMemcpy-size.tst (Subprocess aborted)
        469 - Unit_hmax_hmin_Tsts (Failed)
        470 - Unit_hmax_hmin_Tsts_Negative (Failed)
        1644 - Unit_hipDeviceSetCacheConfig_Positive_Basic (Failed)
        1645 - Unit_hipDeviceSetCacheConfig_Negative_Parameters (Failed)
        1693 - Unit_hipDeviceSetSharedMemConfig_Positive_Basic (Failed)
        1769 - Unit_hipShflTests (Failed)
        1770 - Unit_runTestShfl_up (Failed)
        1771 - Unit_runTestShfl_Down (Failed)
        1772 - Unit_runTestShfl_Xor (Failed)
        1840 - Unit_malloc_CoherentTst (Failed)
        1841 - Unit_malloc_CoherentTstWthAdvise (Failed)
        1842 - Unit_mmap_CoherentTst (Failed)
        1843 - Unit_mmap_CoherentTstWthAdvise (Failed)
```

Both are using upstream llvm/clang 16.0.6 and ROCm-5.6.0 user-space packages delivered by Gentoo.

There are some common failures across GPUs. For examples:

- `hipFloat161.22.3.tst` all failed with the same error `diff=0.641602`.
- `hipShflTests.tst` and `hipShflUpDownTest.tst` all failed, and it passed in older version of ROCm/HIP
- Upstream kernel will omit `invalid device pointer` in `hipIpcMemAccessTest.tst`. `Unit_hipIpcOpenMemHandle_Negative_Open_In_Two_Contexts_Same_Device` `Unit_hipIpcGetMemHandle_Positive_Unique_Handles_Reused_Memory` `Unit_hipIpcCloseMemHandle_Positive_Reference_Counting` also emits error, probably related to memory management.
- `Unit_hmax_hmin_Tsts` and `Unit_hmax_hmin_Tsts_Negative` all failed -- maybe it's related with half precision not fully supported by upstream llvm/clang (such as https://github.com/ROCm-Developer-Tools/HIP/issues/3178)
- Radeon RX 6700XT fails many Stress test, probably due to non-ECC memory
- The Radeon RX 6700XT installed vulkan sdk, so some vulkan related error comes out
There are many other failures in common or specific to device/kernel driver ...... Please analyze them, and consider fixing them.

Here are the gzip compressed logs: build.log for compilation and testing, and test.log for details of tests. For upstream kernel, there are also lots of amdgpu driver issues during the test, logged in dmesg.log.

[6700XT_linux-6.4_build.log.gz](https://github.com/ROCm-Developer-Tools/HIP/files/12206780/6700XT_linux-6.4_build.log.gz)
[6700XT_linux-6.4_test.log.gz](https://github.com/ROCm-Developer-Tools/HIP/files/12206781/6700XT_linux-6.4_test.log.gz)
[6700XT_linux-6.4_dmesg.log.gz](https://github.com/ROCm-Developer-Tools/HIP/files/12207015/6700XT_linux-6.4_dmesg.log.gz)
[MI210_amdgpu-dkms-5.6_build.log.gz](https://github.com/ROCm-Developer-Tools/HIP/files/12206782/MI210_amdgpu-dkms-5.6_build.log.gz)
[MI210_amdgpu-dkms-5.6_test.log.gz](https://github.com/ROCm-Developer-Tools/HIP/files/12206783/MI210_amdgpu-dkms-5.6_test.log.gz)
[RadeonVII_linux-6.3_build.log.gz](https://github.com/ROCm-Developer-Tools/HIP/files/12206784/RadeonVII_linux-6.3_build.log.gz)
[RadeonVII_linux-6.3_test.log.gz](https://github.com/ROCm-Developer-Tools/HIP/files/12206785/RadeonVII_linux-6.3_test.log.gz)
[RadeonVII_linux-6.3_dmesg.log.gz](https://github.com/ROCm-Developer-Tools/HIP/files/12207016/RadeonVII_linux-6.3_dmesg.log.gz)

**Comment by littlewu2508** [comment]
CCing Debian and Fedora hip maintainers who may be interested in these test results.

@cgmb @emollier @Maxzor @Mystro256

**Comment by cjatin** [comment]
Kernel 6.0+ is not supported yet.

Please refer to https://rocm.docs.amd.com/en/latest/release/gpu_os_support.html#supported-distributions

**Comment by littlewu2508** [comment]
> Kernel 6.0+ is not supported yet.
> 
> Please refer to https://rocm.docs.amd.com/en/latest/release/gpu_os_support.html#supported-distributions

I do not think that support matrix is relevent. The kernel listed there are just validated to work on; upstream kernels are known to work for ROCm.

And the value of this issue is indeed test HIP on upstream kernels to see potential bugs

**Comment by cjatin** [comment]
The kernel support matrix contains the list of kernels which are actively being tested/worked on. That list helps differentiate between known to work vs something we actively support, test and fix.

Regarding:
> And the value of this issue is indeed test HIP on upstream kernels to see potential bugs

I can put this to the team to see what can be done regarding testing for **LTS-only** kernels. Get their thoughts on it.

**Comment by littlewu2508** [comment]
I see. I will try to switch to a supported kernel and run these tests.

I think there are two main sources of test failures: not using well-supported kernel and using upstream LLVM instead of ROCm forked LLVM

**Comment by littlewu2508** [comment]
Now it seems that HIT tests are deprecated. The catch tests all passed except those related to vulkan, and [one stress test failure observed on Radeon VII](https://github.com/ROCm/clr/issues/41)

Reference: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=5297819d6d04e8608d329a12afa05dd68ea4f10f

**Comment by cjatin** [comment]
Hey @littlewu2508 
I think we sorted the printf test out.
Can we close this?

**Comment by littlewu2508** [comment]
> I think we sorted the printf test out.

Thanks for noticing! May I ask which commit the printf test is sorted out? I will try testing again.

**Comment by cjatin** [comment]
The comment of https://github.com/ROCm/clr/issues/41 said that you had low disk space issue which was causing the failure

**Comment by littlewu2508** [comment]
> The comment of [ROCm/clr#41](https://github.com/ROCm/clr/issues/41) said that you had low disk space issue which was causing the failure

Ah, thank you for the reminder. Sorry I forgot this!
