### ISSUE TITLE
[Question] gfx1032 support

### ISSUE THREAD

**Issue by dc-dc-dc** [ROCm-Developer-Tools/HIP#3295]
gfx1032 on windows supports hip runtime but not sdk, was just wondering what the timeframe is for sdk support to be added

OS: Windows 
[Support Chart](https://rocm.docs.amd.com/en/latest/release/windows_support.html#windows-supported-gpus)

**Comment by bdenhollander** [comment]
I've been experimenting with the SDK on an RX 6600 (gfx1032) since it was released. Give it a try and see if it works.

There's no mention of GCN4 but the SDK was also able to compile and run HIP code on an RX 460 (gfx803).

**Comment by ppanchad-amd** [comment]
@dc-dc-dc gfx 1032 is not supported on HIP SDK with the latest version 5.7.1. Please see (https://rocm.docs.amd.com/projects/install-on-windows/en/latest/reference/system-requirements.html). Thanks!
