### ISSUE TITLE
atomicMax for signed long long is missing

### ISSUE THREAD

**Issue by athas** [ROCm-Developer-Tools/HIP#3297]
This is strictly speaking not a bug as [the HIP documentation](https://docs.amd.com/projects/HIP/en/latest/reference/kernel_language.html#atomic-functions) correctly lists what is supported, but if the goal is to match the CUDA API, then I am missing a function with this prototype:

    long long int atomicMax(long long int* address, long long int val);

That is, a 64-bit signed atomic maximum.  HIP currently defines only the `unsigned long long int` version.

**Comment by b-sumner** [comment]
I'm not sure which version of ROCm you're running, but the support for signed long long is checked in.  It should be present in the next release if not already in the latest.

**Comment by athas** [comment]
I think I am running the latest release, or at least close to it. Looking forward to the next one now!

**Comment by athas** [comment]
I don't know if the implementation is supposed to reside in this repository (I cannot find it), but [the documentation](https://github.com/ROCm-Developer-Tools/HIP/blob/3d5ab7689661ade927e19858cc0a743f873645d1/docs/reference/kernel_language.md?plain=1#L493-L497) should probably be updated with the signed long long atomicMax.
