### ISSUE TITLE
[Question] Does HIP provide dynamic libraries for use with nvidia gpus?

### ISSUE THREAD

**Issue by SzymonOzog** [ROCm-Developer-Tools/HIP#3300]
After following [download instructions](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/docs/how_to_guides/install.md) for CUDA I have .so files for AMD cards located at `/opt/rocm/hip/lib` but I cannot see the equivalent for nvidia

**Comment by cjatin** [comment]
At the moment for nvidia platforms, HIP has inline functions and no library. The functions forward the call of equivalent CUDA functions. This might change in the future.

Ideally you should not have AMD platform libraries installed since you can not use them.

**Comment by cjatin** [comment]
closing the issue.
