### ISSUE TITLE
[QA] CUDA features in HIP

### ISSUE THREAD

**Issue by Smit703** [ROCm-Developer-Tools/HIP#3301]
Does HIP support following CUDA features:
1) __ballot_sync
2) __shfl_sync

If not are there any alternatives or similar feature support in HIP?

**Comment by b-sumner** [comment]
Hello @Smit703.  You can use either the non-_sync suffixed functions, or you can move to cooperative groups.  I'd suggest the latter.

Also, if you are porting from Cuda, note that HIP does not support independent thread scheduling.

Finally a comment: That mask argument and type was a huge mistake on Cuda's part, which they quickly corrected with cooperative groups.

**Comment by Smit703** [comment]
Thankyou @b-sumner  for the answers.

Could you just help me with one more question : 
While running on NVIDIA GPU with CUDA enabled the hipcc compiler will "un-hipify" HIP kernels and compile with nvcc, is this true? I could not find any documentation referring to running process of HIP on NVIDIA from AM, if any please could you point it out. 
Thankyou

**Comment by b-sumner** [comment]
I think the clang/hipcc compiler is used to generate PTX and then the nvidia compiler is invoked from there.  There is no un-hipify, but the hip device headers wrap the nvidia headers.

**Comment by yxsamliu** [comment]
hipcc calls nvcc to compile CUDA source code to ISA. clang is not used.

**Comment by b-sumner** [comment]
Ugh.  Thanks for correcting me.

**Comment by Smit703** [comment]
Thankyou @yxsamliu and @b-sumner for the answers
