### ISSUE TITLE
Running Hip on NVIDIA gpu

### ISSUE THREAD

**Issue by Smit703** [ROCm-Developer-Tools/HIP#3310]
Following the guide https://docs.amd.com/projects/HIP/en/docs-5.3.0/how_to_guides/install.html, I have installed HIP on NVIDIA V100 GPU
/opt/rocm/bin/hipconfig --full - This command gives :
HIP version  : 5.5.30202-23639ff0

== hipconfig
HIP_PATH     : /opt/rocm-5.5.3
ROCM_PATH    : /opt/rocm
HIP_COMPILER : nvcc
HIP_PLATFORM : nvidia
HIP_RUNTIME  : cuda
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__= -D__HIP_PLATFORM_NVIDIA__= -I/opt/rocm-5.5.3/include -I/usr/local/cuda/include

== nvcc
CUDA_PATH   : /usr/local/cuda
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jul_11_02:20:44_PDT_2023
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0

But I cannot run HIP code using either hipcc or nvcc. What can be the problem?

hip/hip_runtime.h: No such file or directory -> Error while running NVCC
Command 'hipcc' not found, -> Error while running hipcc

**Comment by cjatin** [comment]
can you confirm if hipcc is being installed in /opt/rocm/bin.

**Comment by Smit703** [comment]
Yes @cjatin , I can see hipcc in /opt/rocm/bin

**Comment by cjatin** [comment]
in that case can try by adding hipcc path to your env `$PATH`.

Something like `export PATH=$PATH:/opt/rocm/bin`
Also set `export HIP_PLATFORM=nvidia`
and then run hipcc.

**Comment by Smit703** [comment]
Yep it worked. Thanks @cjatin

**Comment by galenyu** [comment]
@Smit703 Hi Smit! I am a beginner in HIP. I recently received a code for HIP  and I want to run it on NVIDIA GPU. But it is difficult to find relevant tutorials or examples. Do you know how to port HIP  to CUDA  for compilation and use ?

Any suggestion will be appreciated!

**Comment by jamesxu2** [comment]
Hi @galenyu , you do not need to port HIP code to CUDA, you can compile HIP code directly with NVCC by setting the HIP_PLATFORM=nvidia. You can see the discussion on this issue for more information: https://github.com/ROCm/HIP/issues/3582
