### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for HIP

### ISSUE THREAD

**Issue by wangyuliu** [ROCm-Developer-Tools/HIP#3327]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting. In fact, it can be estimated on average across various architectures.As part of my dataset, I have collected the HIP project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be simple, with a small amount of code related to the CPU architecture in the project. (referring to the overall workload from adapting the project to a specific architecture to achieving full functionality on that architecture). Is this assessment accurate? I look forward to your help and response.

**Comment by yxsamliu** [comment]
HIP runtime depends on https://github.com/ROCm-Developer-Tools/clr, which in turn depends on https://github.com/RadeonOpenCompute/ROCR-Runtime, which in turn depends on https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver . Probably those dependencies need more effort for porting.

**Comment by cjatin** [comment]
https://github.com/ROCm-Developer-Tools/HIP-CPU might be worth looking at

**Comment by wangyuliu** [comment]
I'm very grateful for this and look forward to your further guidance.Can you have a more detailed or specific assessment? For example, our tool believes that there is very little architecture-related code in HIP. We think the porting work is very simple. Do you agree?

**Comment by wangyuliu** [comment]
> https://github.com/ROCm-Developer-Tools/HIP-CPU might be worth looking at

HIP-CPU mentioned--It is generic and does not assume a particular CPU vendor or architecture---, I would like to continue to ask for your opinion, when building the HIP-CPU project, whether a lot of work was done on cpu architecture portability, or whether it took very little effort to make it possible Ignore the difference in CPU architecture?

**Comment by sohaibnd** [comment]
> I'm very grateful for this and look forward to your further guidance.Can you have a more detailed or specific assessment? For example, our tool believes that there is very little architecture-related code in HIP. We think the porting work is very simple. Do you agree?

Hi @wangyuliu, sorry for the delay. As @yxsamliu mentioned, HIP is not a standalone project. It is a runtime that is part of a much larger software stack called [ROCm](https://rocm.docs.amd.com/en/latest/). To be able to run HIP on a system with a RISC-V cpu, you would also need to port other projects in the ROCm stack that HIP is dependent on. This includes [clr](https://github.com/ROCm/clr) (which includes the actual implementation of the HIP runtime under the `hipamd` directory, the HIP repo is just the interface for the HIP API), [ROCR-Runtime](https://github.com/ROCm/ROCR-Runtime), the drivers, the [compiler](https://github.com/ROCm/llvm-project) (amdclang/hipcc), and the tools (debugger, profiler, etc) at the very least.

![image](https://github.com/user-attachments/assets/d973fe29-4161-435e-97c2-482121d119e8)

Let me know if you need further details!

**Comment by sohaibnd** [comment]
@wangyuliu I'm going to close this issue due to inactivity but feel free to re-open it if you need more information.
