### ISSUE TITLE
not all "pi" functions present  in ROCm math library are available through hipcc

### ISSUE THREAD

**Issue by VinInn** [ROCm-Developer-Tools/HIP#3335]
ROCm math library implements all "pi" functions: sinpi, cospi, tanpi and their inverse (including atan2pi)
hip seems to provide access only to  sinpi and cospi.

see
https://github.com/RadeonOpenCompute/ROCm-Device-Libs/issues/99

**Comment by cjatin** [comment]
Will raise it internally. Open it up to broader discussion since if we add it, it will be supported for a long time.

**Comment by yxsamliu** [comment]
It seems we should not document that tanpi is supported.

tanpi is not declared by CUDA SDK https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#mathematical-functions-appendix .

**Comment by ppanchad-amd** [comment]
@VinInn Is this ticket still relevant? Thanks!

**Comment by VinInn** [comment]
It would be useful to have all math functions implemented in the device library available through hipcc.
I do understand that at the moment strict compatibility with the CUDA SDK is instead preferred.

**Comment by darren-amd** [comment]
Hi @VinInn,

Thanks for the suggestion! I spoke to the internal team and unfortunately we do not have plans to support this currently, as we do not have plans to add non-CUDA functions as of now.
