### ISSUE TITLE
Add documentation for intrinsic functions

### ISSUE THREAD

**Issue by benrichard-amd** [ROCm-Developer-Tools/HIP#3337]
There is no HIP documentation for intrinsic functions, for example `__builtin_amdgcn_ds_swizzle`.

Each intrinsic function should be documented so that developers can use them.

**Comment by b-sumner** [comment]
Builtins are not documented for a reason.  They are subject to change and their availability depends on the architecture.  They are only meant to be used by those ready to take on that risk and already understand why and how to use them.
