### ISSUE TITLE
Failed compilation for floating point template parameters

### ISSUE THREAD

**Issue by Sephirothbahamut** [ROCm-Developer-Tools/HIP#3338]
Hi,
I've reported the same bug on nvcc one year ago, and now that I'm trying HIP the bug is following me. Floating point template parameters are supported as of C++20.

I'm on a Windows machine, compiling via Visual Studio. If I compile the HIP code through nvcc it works properly (Project settings > General > Platform Toolset > AMD HIP for nvcc Compiler), while if I compile the same code with HIP-clang (AMD HIP for clang Compiler) the code fails to compile.

Minimal example:

```c++
template <float f>
__global__ void func_template()
    {
    printf("\nValue: %f\n", f);
    }

int main()
    {
    func_template<1.f><<<1, 1, 0>>>();
    HIP_CHECK(hipDeviceSynchronize());
    }
```

```
1>main.hip(134,5): error : no matching function for call to 'func_template'
1>main.hip(127,17): note: candidate template ignored: invalid explicitly-specified argument for template parameter 'f'
```

**Comment by yxsamliu** [comment]
clang by default uses the same C++ standard for C++ and HIP programs. To use C++20 standard you need to add option -std=c++20.

**Comment by Sephirothbahamut** [comment]
@yxsamliu where do I add command line options for Clang in the Visual Studio example solutions? All the specific options I see are labelled as [AMD HIP for nvcc].
I was assuming that using the "AMD HIP for clang Compiler" toolset it would follow the language standard selected in general properties... (which was already set to C++20)

**Comment by yxsamliu** [comment]
you may switch toolset:

![image](https://github.com/ROCm-Developer-Tools/HIP/assets/6145511/3f21f0f1-34e8-4eb0-b5c5-c1409c6e29b2)

normally if  you have env var HIP_PATH set, this should be auto. https://rocm.docs.amd.com/projects/hip-vs/en/latest/usage.html

**Comment by emankov** [comment]
Additionally, be aware of `Configuration` (`Debug` and `Release` by default). You may change the `Platform Toolset` only for a single `Configuration`, or for `All configurations`, or for `Multiple Configurations...`.

**Comment by Sephirothbahamut** [comment]
Sorry for the late reply; that's not a fix to the issue, I'm already switching toolsets. Maybe my explanation was poor.
Compiling the example code I wrote in the previous post with a pure CUDA project, i can make it work.
Compiling it from a HIP project (I modified ROCm-Example's hello world) with the "AMD HIP for nvcc Compiler" toolset and the "ISO C++20 Standard (std=c++20)" standard in General settings it compiles and it works without issues.
It's only when compiling it from a HIP project with the "AMD HIP for clang Compiler" toolset (same language standard as before) that it doesn't compile. 
And my only hypothesis is that it's not compiling because of the compiler not following the standard chosen C++20 standard for some reason, as the error doesn't occur when using non-floating template parameters, it only occurs with floating ones that weren't supported before C++20

**Comment by yxsamliu** [comment]
It seems -std=c++20 is correctly passed to clang if you set it in MSVC project settings. However, currently clang does not support floating point as non-type template argument https://godbolt.org/z/hv9K35oPK

**Comment by zichguan-amd** [comment]
Hi @Sephirothbahamut, your hypothesis is right, the clang version used by ROCm 6.2.2 is 18.0.0git, see the docs [here](https://rocm.docs.amd.com/projects/llvm-project/en/docs-6.2.2/LLVM/clang/html/index.html). And it does not support the feature that you are looking for. 
[Clang 18.1.0rc](https://releases.llvm.org/18.1.0/tools/clang/docs/ReleaseNotes.html#c-language-changes) adds the c++20 features as documented by:
> Implemented [P1907R1](https://wg21.link/P1907R1) which extends allowed non-type template argument kinds with e.g. floating point values and pointers and references to subobjects. This feature is still experimental. Accordingly, __cpp_nontype_template_args was not updated. However, its support can be tested with __has_extension(cxx_generalized_nttp).

Testing `__has_extension(cxx_generalized_nttp)` with `hipcc` shows that clang 18.0.0git does not support this feature.
```
$ cat test.cpp 
#include <hip/hip_runtime.h>

int main()
{
printf("%s\n", __clang_version__);
printf("%d\n", __has_extension(cxx_generalized_nttp));
}
$ hipcc test.cpp -std=c++20
$ ./a.out
18.0.0git (https://github.com/RadeonOpenCompute/llvm-project roc-6.2.1 24355 77cf9ad00e298ed06e06aec0f81009510f545714)
0
```
