### ISSUE TITLE
HIP doesn't support `atomicMax` or `atomicMin` with `long long int`

### ISSUE THREAD

**Issue by stonea** [ROCm-Developer-Tools/HIP#3340]
CUDA supports `atomicMax` and `atomicMin` with `long long int`: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomicmax but this doesn't appear to be the case for HIP: https://sep5.readthedocs.io/en/latest/Programming_Guides/Kernel_language.html?highlight=atomicAdd#atomic-functions

Any particular reason for this difference? Is it a hardware limitation or just an oversight in the API?

Hipify, will gladly process these calls without warning but linker time you'll get an error.

**Comment by cjatin** [comment]
https://github.com/ROCm-Developer-Tools/clr/blob/5914ac3c6e9b3848023a7fa25e19e560b1c38541/hipamd/include/hip/amd_detail/amd_hip_atomic.h#L825

It got added

**Comment by stonea** [comment]
Perfect, thanks!
