### ISSUE TITLE
__match functions

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#3345]
It seems that __match_any is not available in HIP.  Thanks.  

__match_any_sync
Returns mask of threads that have same value of value in mask

**Comment by yxsamliu** [comment]
it is added recently https://github.com/ROCm/clr/blob/develop/hipamd/include/hip/amd_detail/amd_warp_sync_functions.h#L171

**Comment by kjayapra-amd** [comment]
Please re-open the issue, if you have more questions.

**Comment by jinz2014** [comment]
rocm-6.2.0 
error: use of undeclared identifier '__match_any'
