### ISSUE TITLE
hipHostMalloc: hipHostMallocNumaUser flag is ignored

### ISSUE THREAD

**Issue by jyvet** [ROCm-Developer-Tools/HIP#3351]
You'll find below a short reproducer. The `hipHostMallocNumaUser` flag is used, but HIP continues to force the NUMA affinity of GCD 0 (which is NUMA 3):

```
grep "MemUsed"  /sys/devices/system/node/node*/meminfo; numactl -N 1 ./numa & sleep 2 && grep "MemUsed"  /sys/devices/system/node/node*/meminfo 
/sys/devices/system/node/node0/meminfo:Node 0 MemUsed:        11489500 kB
/sys/devices/system/node/node1/meminfo:Node 1 MemUsed:        11453372 kB
/sys/devices/system/node/node2/meminfo:Node 2 MemUsed:        11506444 kB
/sys/devices/system/node/node3/meminfo:Node 3 MemUsed:        13204208 kB
[2] 7814
/sys/devices/system/node/node0/meminfo:Node 0 MemUsed:        11490004 kB
/sys/devices/system/node/node1/meminfo:Node 1 MemUsed:        11480932 kB
/sys/devices/system/node/node2/meminfo:Node 2 MemUsed:        11506444 kB
/sys/devices/system/node/node3/meminfo:Node 3 MemUsed:        14253288 kB
[1]  - 7539 done       numactl -N 1 ./numa
```

As a temporary workaround, is there a way to avoid double buffering without using hipHostMalloc? (like mmap then tell HIP  the pages are locked)?

Here is the reproducer code:
```
// hipcc -g  -D__HIP_PLATFORM_AMD__ numa.c -o numa
#include <unistd.h>
#include <hip/hip_runtime.h>

#define N_SIZE_DEFAULT  1073741824
#define DEVICE_ID 0

#define checkHip(ret) { assertHip((ret), __FILE__, __LINE__); }
inline void assertHip(hipError_t code, const char *file, int line)
{
   if (code != hipSuccess)
   {
      fprintf(stderr,"CheckHip: %s %s %d\n", hipGetErrorString(code), file, line);
      exit(code);
   }
}

int main(int argc, char *argv[])
{
    float *buf;

    checkHip( hipSetDevice(DEVICE_ID) );
    checkHip( hipHostMalloc(((void **)&buf), N_SIZE_DEFAULT, hipHostMallocDefault | hipHostMallocNumaUser) );

    sleep(10);

    checkHip( hipHostFree(buf) );
    return 0;
}
```

```
HIP version: 5.7.31921-d1770ee1b
AMD clang version 17.0.0
InstalledDir: /opt/rocm-5.7.0/llvm/bin
```

**Comment by iassiour** [comment]
Hi @jyvet, the following works:

grep "MemUsed"  /sys/devices/system/node/node*/meminfo; numactl **--membind** 1 ./numa & sleep 2 && grep "MemUsed"  /sys/devices/system/node/node*/meminfo

and also this:

grep "MemUsed"  /sys/devices/system/node/node*/meminfo; numactl **--preferred** 1 ./numa & sleep 2 && grep "MemUsed"  /sys/devices/system/node/node*/meminfo

Based on the code here:
https://github.com/ROCm-Developer-Tools/clr/blob/76e3ffeb8178c6e32e2ee9a61b9fb0ec7ca39414/rocclr/device/rocm/rocdevice.cpp#L2195

it looks like the cpunodebind option still falls back to the default case where the numa node is selected based only on the closest distance to the current GPU device. In this case, it looks like you might have a single device and equal distance pools so it falls back to always select the last one. 

To confirm, if you run the test after setting environment variable AMD_LOG_LEVEL=4 you can see what node is selected for which gpu:
_Numa selects cpu agent[0]=0x2639590(fine=0x26397b0,coarse=0x263a4d0) for gpu agent=0x263b1b0 CPU<->GPU XGMI=0_

**Comment by jyvet** [comment]
Hi @iassiour,

Many thanks for your detailed reply!
Indeed, those mods are working properly.

The only drawback is that interleaved pages won't work (`numactl -i 0,1` for instance). That could be neat to mimic NPS1 or NPS2 behaviors with NPS4.

**Comment by jyvet** [comment]
The following seems to be enough to get user defined affinity (interleaved pages is also working) without the double buffering penalty:

```
posix_memalign((void**) &buf, sysconf(_SC_PAGESIZE), N_SIZE_DEFAULT);
hipHostRegister(buf, N_SIZE_DEFAULT, hipHostRegisterMapped);
```

I guess this case can be closed then.

Thanks
