### ISSUE TITLE
How to estimate the accuracy of converting HIP to CUDA or converting CUDA to HIP?

### ISSUE THREAD

**Issue by NiuKeke** [ROCm-Developer-Tools/HIP#3355]
How to estimate the accuracy of converting HIP to CUDA or converting CUDA to HIP? As we all know, HIP could support CUDA definitely.But how to estimate its support accuracy,which is important to using HIP.Is there some tool which could fix this problem?

**Comment by yxsamliu** [comment]
This could be done by some test suites about fp operations. Unfortunately, I am not aware of one for CUDA/HIP.

There is a research paper about math function accuracy of various math libraries, including CUDA and HIP (ROCm) 

https://members.loria.fr/PZimmermann/papers/accuracy.pdf

**Comment by b-sumner** [comment]
@NiuKeke I'm not sure we're clear on what kind of accuracy you mean.  Could you elaborate?

**Comment by NiuKeke** [comment]
> research paper about math function accuracy of various math libraries, including CUDA and HIP (ROCm)
I mean if there were some test suites about CUDA/HIP just like opencl-cts, which could be a criterion of Opencl.

**Comment by NiuKeke** [comment]
> @NiuKeke I'm not sure we're clear on what kind of accuracy you mean. Could you elaborate?

I mean if there were some test suites about CUDA/HIP just like opencl-cts, which could be a criterion of Opencl.

**Comment by NiuKeke** [comment]
> This could be done by some test suites about fp operations. Unfortunately, I am not aware of one for CUDA/HIP.
> 
> There is a research paper about math function accuracy of various math libraries, including CUDA and HIP (ROCm)
> 
> https://members.loria.fr/PZimmermann/papers/accuracy.pdf

thank you!I mean if there were some test suites about CUDA/HIP just like opencl-cts, which could be a criterion of Opencl.

**Comment by ppanchad-amd** [comment]
@NiuKeke Please advise if we can go ahead and close this ticket? Thanks!

**Comment by ppanchad-amd** [comment]
@NiuKeke Closing ticket for now.  Please feel free to re-open if you still require assistance with this ticket. Thanks!
