### ISSUE TITLE
Number of VGPRs and SGPRs vs. hipDeviceProp_t::regsPerBlock

### ISSUE THREAD

**Issue by maartenarnst** [ROCm-Developer-Tools/HIP#3356]
I have a question about the member variable `regsPerBlock` of the `struct` `hipDeviceProp_t`. The documentation indicates that this variable provides the "number of registers per block". My question is how to relate this number to the VGPRs and SGPRs? Is there a way to deduce these numbers separately? Thank you very much in advance.

**Comment by yxsamliu** [comment]
These are number of VGPR's per CU.

It is eventually from:

https://github.com/ROCm-Developer-Tools/clr/blob/1338ff37e89b4d1fb36d23d48ccdf55998e15df5/rocclr/device/rocm/rocdevice.cpp#L1706

https://github.com/ROCm-Developer-Tools/clr/blob/1338ff37e89b4d1fb36d23d48ccdf55998e15df5/rocclr/device/rocm/rocdevice.cpp#L1702

https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/blob/8276083301409001ec7643e68f5ad58b057c21fd/lib/comgr/src/comgr-isa-metadata.def#L49

**Comment by maartenarnst** [comment]
Hi @yxsamliu. Thanks a lot for your help! That's indeed exactly what I was looking for.

In my code, I'm now retrieving the number of VGPRs and SGPRs from the comgr, by proceeding similarly as in the code in `rocdevice.cpp` that you had referred me to. 

I found that most of the functions used in `rocdevice.cpp` are available from the api in `amd_comgr/amd_comgr.h`. However, the function `getValueFromIsaMeta` is in `rocdevice.cpp` but it appears it's not in `amd_comgr/amd_comgr.h`. So it might be a suggestion to try to include this function in `amd_comgr/amd_comgr.h`.  I'd be happy to post it as a suggestion on a GitHub repository, but it seems `RadeonOpenCompute/llvm-project/tree/amd-stg-open/amd/comgr` doesn't accept issues.

**Comment by yxsamliu** [comment]
comgr was migrated from https://github.com/RadeonOpenCompute/ROCm-CompilerSupport

You may open an issue there

**Comment by kjayapra-amd** [comment]
Closing the issue, since this is not related to HIP. 
Please open a ticket https://github.com/RadeonOpenCompute/ROCm-CompilerSupport here as @yxsamliu suggested.
