### ISSUE TITLE
error: 'hipErrorInvalidDevice'(1010), when testing HIP applications

### ISSUE THREAD

**Issue by yige-hu** [ROCm-Developer-Tools/HIP#337]
When I was testing my HIP installation with HIP/samples/0_Intro/square, I got the followed error at runtime:
      error: 'hipErrorInvalidDevice'(1010) at square.cpp:60

My configurations:
      GPU: AMD Radeon RX 580
      Kernel: 4.4.0-109-generic
      Distribution: Ubuntu 16.04.3 LTS

Any idea on what could be wrong? Is my GPU model not supported by HIP?

I really appreciate your help!

**Comment by whchung** [comment]
@yige-hu RX580 is supported. HIP depends on a functional ROCm stack to dispatch GPU kernels. Please check if you have `/opt/rocm` directory, and if `vector_copy` under `/opt/rocm/hsa/sample` can be built and run correctly.

You may want to check: https://github.com/RadeonOpenCompute/ROCm for installation procedure of ROCm stack.

**Comment by yige-hu** [comment]
@whchung Thanks! I think I found the reason -- both the square example and vector_copy example work with sudo.

Do applications on ROCm all need sudo? Is there a configuration (e.g. privileged group) that I can set to allow non-privileged users to run GPU programs on ROCm?

**Comment by whchung** [comment]
@yige-hu iy shouldn't be. please check if adding your account to `video` group solves the issue: https://github.com/RadeonOpenCompute/ROCm#next-set-your-permsions

**Comment by yige-hu** [comment]
@whchung Yea, it works. I followed the hiptensorflow installation tutorial, which doesn't mention that. Thanks a lot!

**Comment by whchung** [comment]
@sunway513 for awareness. ROCm 1.7 is indeed behaving differently than earlier versions of ROCm stack.
