### ISSUE TITLE
graph conditional handles

### ISSUE THREAD

**Issue by alessblaze** [ROCm-Developer-Tools/HIP#3372]
Is there any information if graph conditional handles will be available in hip . A lot of Cuda 12.2 features aren't yet available in hip. But on hipblas there's lots of progress in mainline . Is there any info on this

**Comment by ppanchad-amd** [comment]
@anishsheikh Do you still need assistance with this ticket? Thanks!

**Comment by alessblaze** [comment]
Unfortunately no, when i needed to know, i was working, now the female pm whom i was gonna suggest, have 2 children already,
and happily married left the job. has been an eternity. but thanks
