### ISSUE TITLE
Kernels produced by `hipcc` vs `hiprtc` run the GPU in different compute modes (gfx1100).

### ISSUE THREAD

**Issue by loostrum** [ROCm-Developer-Tools/HIP#3374]
My GPU kernel ran 3 times faster when compiled with `hipcc` when compared to `hiprtc`. It turns out that `hipcc` compiles kernels with the GPU in WGP mode, while `hiprtc` defaults to CU mode. I would expect both to have the same default setting for the compute mode, it is very confusing to a new user that this isn't the case. Could these defaults be made the same?

System details:
GPU: 7900 XT
CPU: 7900X3D (iGPU hidden with `HIP_VISIBLE_DEVICES=0`)
ROCM version: 5.7.1
OS: Rocky Linux 9.3
Kernel version: 5.14

Steps to reproduce:
1. Create `kernel.cpp` file with the following contents:
```c++
#include <hip/hip_runtime.h>

extern "C"
__global__ void kernel(int* a, const int n) {
    int idx = threadIdx.x + blockIdx.x * blockDim.x;
    if (idx < n) {
        a[idx] = 10;
    }
}
```
2. Compile with `hipcc`:
```
/opt/rocm/bin/hipcc --offload-arch=gfx1100 kernel.cpp -emit-llvm 
/opt/rocm/llvm/bin/llc -mcpu=gfx1100 kernel-hip-amdgcn-amd-amdhsa-gfx1100.bc
```
3. Observe that output .s file contains `.workgroup_processor_mode: 1`

4. Compile the same kernel with `hiprtc`, e.g. with something like [this](https://gist.github.com/loostrum/f32c5fad41401f468f36e4f678e444a9) followed by 
```
/opt/rocm/llvm/bin/llc -mcpu=gfx1100 hiprtc-kernel-hip-amdgcn-amd-amdhsa-gfx1100.bc
```

5. Observe that the output .s file contains `.workgroup_processor_mode: 0`

As a workaround, one can give the `-mno-cumode` argument to `hiprtc`, in which case it will run the GPU in WGP mode and the bitcode produced by `hipcc` and `hiprtc` is identical as expected.

**Comment by cjatin** [comment]
Thanks for sharing this. Will look into this

**Comment by cjatin** [comment]
I think this is a bug.
Will raise a PR internally to fix it.

**Comment by cjatin** [comment]
https://github.com/ROCm/HIP/commit/838e587a2497b7307aad6c3849319378f8178027

https://github.com/ROCm/clr/commit/49369f08519be2c8643736c5611c9cd77ce47b93
