### ISSUE TITLE
`operator*` overloads for complex types are broken in 5.7

### ISSUE THREAD

**Issue by msimberg** [ROCm-Developer-Tools/HIP#3377]
`operator*` overloads for complex types are ambiguous if `hip/hip_vector_types.h` and `hip/hip_complex.h` are included in the same translation unit. See https://godbolt.org/z/KPhqr91Ec for an example that triggers the compilation failure with 5.7 but compiles fine with 5.3.

Error message:
```
<source>:8:16: error: use of overloaded operator '*' is ambiguous (with operand types 'hipFloatComplex' (aka 'HIP_vector_type<float, 2>') and 'hipFloatComplex')
    auto c = a * b;
             ~ ^ ~
/opt/compiler-explorer/libs/rocm/5.7.0/include/hip/amd_detail/amd_hip_vector_types.h:548:65: note: candidate function
        friend __HOST_DEVICE__ inline constexpr HIP_vector_type operator*(
                                                                ^
/opt/compiler-explorer/libs/rocm/5.7.0/include/hip/amd_detail/amd_hip_complex.h:237:1: note: candidate function
COMPLEX_MUL_OP_OVERLOAD(hipFloatComplex)
^
/opt/compiler-explorer/libs/rocm/5.7.0/include/hip/amd_detail/amd_hip_complex.h:78:40: note: expanded from macro 'COMPLEX_MUL_OP_OVERLOAD'
    __HOST_DEVICE__ static inline type operator*(const type& lhs, const type& rhs) {           \
                                       ^
1 error generated when compiling for gfx90a.
Compiler returned: 1
```

**Comment by cjatin** [comment]
Operator in hipComplex have been source of contention and controversy for quite some time now.

I highly recommend you to use `hipCmulf` etc to do operations on complex numbers.

These operators will be removed in future releases to fix this ambiguous operators.

**Comment by msimberg** [comment]
Thanks @cjatin for the quick response. That sounds reasonable. The `operator*` overloads should presumably be marked `[[deprecated]]` so that users know to move away from them?
