### ISSUE TITLE
Memleak when using ROCm 5.7 with Pytorch 2.2.0-dev

### ISSUE THREAD

**Issue by DistantThunder** [ROCm-Developer-Tools/HIP#3379]
When using SD WebUI 1.7.0 with Pytorch built with ROCm 5.7 , a memleak on system RAM is observable as one switches from one model to another:

* https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/14329

All system details available on linked issue.

**Comment by kjayapra-amd** [comment]
Based on the latest comments on the attached ticket, this does not seem to be ROCm specific issue. Issue is at the App level.

**Comment by gargrahul** [comment]
Closing based on above comment.
