### ISSUE TITLE
hipcofig report HIP_PLATFORM:nvcc for RX580

### ISSUE THREAD

**Issue by RaymonSHan** [ROCm-Developer-Tools/HIP#338]
I am in hip for month, and everything is on it's way, until last week, maybe after i run rga for disassmbly .cl file.

and now i found the error is origin from hipconfig, in my R7 + RX580(the only gpu) ub16.04.3,  

**hipconfig report** 
raymon@raymonR7:/opt/rocm/hip/bin$ ./hipconfig
HIP version  : 1.4.0

== hipconfig
HIP_PATH     : /opt/rocm/hip/bin
HIP_PLATFORM : nvcc
CPP_CONFIG   :  -D__HIP_PLATFORM_NVCC__=  -I/opt/rocm/hip/bin/include -I/usr/local/cuda/include

== nvcc
Can't exec "nvcc": No such file or directory at ./hipconfig line 143.

=== Environment Variables
PATH=/home/raymon/bin:/home/raymon/.local/bin:/home/raymon/Qt5.6.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/home/raymon/Qt5.6.3/lib:/opt/AMDAPPSDK-3.0/lib/x86_64/sdk/

== Linux Kernel
Hostname     : raymonR7
Linux raymonR7 4.13.0-31-generic #34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**hipconfig is wrong, the real platform is rx580 as clinfo say:**

raymon@raymonR7:/opt/rocm/hip/bin$ clinfo
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP (2482.3)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     Ellesmere
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 AMD-APP (2482.3)
  Driver Version                                  2482.3
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Board Name (AMD)                         Radeon RX 580 Series
  Device Topology (AMD)                           PCI-E, 28:00.0
  Max compute units                               36
  SIMD per compute unit (AMD)                     4
......

i have uninstall and reinstall following
 http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Install.aspx
&
https://github.com/RadeonOpenCompute/ROCm
which i have done month before. but error still here.

any suggest except reinstall all linux?

**Comment by bensander** [comment]
This error indicates the AMD graphics driver was not successfully detected.  Looks like you are trying to use AMDGPU driver – this is intended for graphics/workstation.  For compute start with the ROCm kernel driver following the instructions from : rocm.github.io.

**Comment by RaymonSHan** [comment]
YES!!
following https://rocm.github.io/install.html

uninstall & reinstall it is ok

raymon@raymonR7:/opt/rocm/hip/bin$ ./hipconfig
HIP version  : 1.4.0

== hipconfig
HIP_PATH     : /opt/rocm/hip/bin
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/hip/bin/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 6.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 42ceed861a212d9bd0aef883ee7981144f3ecc02) (ssh://gerritgit/compute/ec/hcc-tot/llvm 23e086be6f627e6e983c6789d2e77da6bf85ebb6) (based on HCC 1.1.17493-2f85d8a-42ceed8-23e086b )
