### ISSUE TITLE
The documentation of `hipEventQuery` is incorrect

### ISSUE THREAD

**Issue by fwyzard** [ROCm-Developer-Tools/HIP#3383]
The [documentation](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___event.html#ga5d12d7b798b5ceb5932d1ac21f5ac776) of `hipEventQuery()` says that

> Query the status of the specified event. This function will return [hipSuccess](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/hip__runtime__api_8h.html#ae4a28dbad173b548a3ac2a2092994d6b) if all commands in the appropriate stream (specified to [hipEventRecord()](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___event.html#ga553b6f7a8e7b7dd9536d8a64c24d7e29)) have completed. If that work has not completed, or if [hipEventRecord()](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___event.html#ga553b6f7a8e7b7dd9536d8a64c24d7e29) was not called on the event, then [hipErrorNotReady](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/hip__runtime__api_8h.html#a8e981181b750f34a4c9532cbba73ba76) is returned.

However, calling `hipEventQuery(event)` immediately after `hipEventCreate(&event)`, before calling `hipEventRecord(event, stream)`, actually returns `hipSuccess`.

This is consistent with the documented behaviour of [hipEventSynchronize()](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___event.html#ga1f72d98ba5d6f7dc3da54e0c41fe38b1):
>If [hipEventRecord()](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___event.html#ga553b6f7a8e7b7dd9536d8a64c24d7e29) has not been called on event, this function returns immediately.
that implies that a newly created event is in "ready" or "recorded" state.

**Comment by fwyzard** [comment]
Here is a sample code showing the actual behaviour:
```c++
__global__
void sleep(uint64_t delta) {
  if (blockIdx.x == 0 and threadIdx.x == 0) {
    uint64_t start = clock64();
    while (clock64() - start < delta);
  }
}

void test_hip(void) {
  // initialise the HIP runtime
  HIP_CHECK(hipFree(nullptr));

  // create a HIP stream
  hipStream_t stream;
  HIP_CHECK(hipStreamCreate(&stream));

  // create a HIP event
  hipEvent_t event;
  HIP_CHECK(hipEventCreate(&event));

  // check the event
  auto status = hipEventQuery(event);
  std::cout << "HIP event status: " << status << " (" << hipGetErrorName(status) << ")\n";

  // submit asynchronous work and record the event
  uint64_t rate_kHz = 1'700'000;  // 1700 MHz
  uint64_t time_ms = 10'000;      // 10 s
  sleep<<<1, 1, 0, stream>>>(time_ms * rate_kHz);
  HIP_CHECK(hipEventRecord(event, stream));

  // check the event
  status = hipEventQuery(event);
  std::cout << "HIP event status: " << status << " (" << hipGetErrorName(status) << ")\n";

  // wait for all asynchronous work to complete
  HIP_CHECK(hipEventSynchronize(event));
  std::cout << "asynchronous work complete\n";

  // check the event
  status = hipEventQuery(event);
  std::cout << "HIP event status: " << status << " (" << hipGetErrorName(status) << ")\n";

  // clean up
  HIP_CHECK(hipEventDestroy(event));
  HIP_CHECK(hipStreamDestroy(stream));
}
```

Running it prints
```
HIP event status: 0 (hipSuccess)
HIP event status: 600 (hipErrorNotReady)
asynchronous work complete
HIP event status: 0 (hipSuccess)
```

The first message (`HIP event status: 0 (hipSuccess)`) confirms that a newly created event is in "ready" or "recorded" status.

**Comment by kjayapra-amd** [comment]
I see the inconsistency. Investigating this internally, will update here once I have more info.

**Comment by kjayapra-amd** [comment]
Discussed this with the team internally. The documentation needs to be fixed. 

HIP runtime behavior is correct. If hipEventRecord was not called on a newly created event, we will return hipSuccess, since there are no pending events.

(We have initiated the process to fix the documentation).

**Comment by kjayapra-amd** [comment]
This is fixed in our latest documentation.
Thanks @jujiang-del for updating.
