### ISSUE TITLE
What are the supported APIs in HIP Graph Management? 

### ISSUE THREAD

**Issue by jaykolla** [ROCm-Developer-Tools/HIP#3397]
https://docs.amd.com/projects/HIP/en/docs-5.0.0/doxygen/html/group___graph.html#:~:text=Reference%3A%20Graph%20Management-,Graph%20Management,-%23

Some Math Libraries have Graph Support, but I cannot identify supported APIs on the above-linked documentation page. Please have a section for all supported APIs which are graph safe!

**Comment by kjayapra-amd** [comment]
Our new features are marked as beta. Feel free to use them and report any issues you might encounter.
The document you listed has all the Graph APIs we support.

**Comment by jaykolla** [comment]
I don't see any math library support listed in there, if you can point me to the right doc where I see all supported Math libraries APIs that has graph support perhaps that helps.

**Comment by nartmada** [comment]
@jaykolla and @kjayapra-amd:

![image](https://github.com/ROCm/HIP/assets/144284448/52d6c148-6a99-4328-b6fe-b68377e09f09)

Please check HIP 6.1.0 Documentation
https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/index.html

Is this what you are looking for?
https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___graph.html

![image](https://github.com/ROCm/HIP/assets/144284448/fd081555-cf3e-456c-960d-e122a9b9d46b)

**Comment by jaykolla** [comment]
If you look at this picture, there is Graph Support enabled for rocBLAS, I would like to know what other Math Library Components are supported with HIP Graph. Is there a consolidated view of all Supported Math Library components with HIP Graph? 

<img width="790" alt="image" src="https://github.com/ROCm/HIP/assets/149093828/6c71915b-ff65-4161-b0be-5fcc60093b46">

**Comment by zichguan-amd** [comment]
Hi @jaykolla, thanks for reaching out. Unfortunately, we currently do not have a clear documentation page on the supported libraries. I'll escalate this issue to the docs team. In the meantime, I was able to find some information about graph support in a few libraries.
- rocBLAS: [partial support](https://github.com/ROCm/rocBLAS/blob/develop/docs/reference/beta-features.rst#graph-support-for-rocblas)
- rocThrust: [not supported](https://github.com/ROCm/rocThrust/blob/develop/docs/hipgraph-support.rst)
- rocRAND: [supported](https://github.com/ROCm/rocRAND/blob/develop/docs/conceptual/programmers-guide.rst#using-rocrand-in-hip-graphs)
- rocSPARSE: [partial support](https://github.com/search?q=repo%3AROCm%2FrocSPARSE+hipgraph&type=code)
- hipCUB: [partial support](https://github.com/ROCm/hipCUB/blob/develop/CHANGELOG.md#added-1)
- rocPRIM: [supported](https://github.com/ROCm/rocPRIM/blob/rocm-6.2.2/test/hipgraph/test_hipgraph_basic.cpp)

Please let me know if you are looking for graph support for a particular library not mentioned above.

**Comment by zichguan-amd** [comment]
Documentation for HIP graph-safe libraries is available since ROCm 6.3.1 at https://rocm.docs.amd.com/en/latest/reference/graph-safe-support.html
