### ISSUE TITLE
[Issue]: Multiple definition error caused by using <hip/hip_bf16.h>

### ISSUE THREAD

**Issue by lhcalibur** [ROCm-Developer-Tools/HIP#3403]
### Problem Description

The function in <hip/hip_bf16.h> is defined without **inline** , which will cause multi definition error when using this header file in multi .cu/.hip files.

For example the code:
```
 /**
  * \ingroup HIP_INTRINSIC_BFLOAT162_CONV
  * \brief Returns low 16 bits of __hip_bfloat162
  */
 __device__ __hip_bfloat16 __low2bfloat16(const __hip_bfloat162 a) { return a.x; }

```

### Operating System

Ubuntu 22.04

### CPU

AMD EPYC

### GPU

AMD Instinct MI250

### ROCm Version

ROCm 6.0.0

### ROCm Component

HIP

**Comment by mangupta** [comment]
@lhcalibur : This is already resolved via https://github.com/ROCm/clr/commit/86bd518981b364c138f9901b28a529899d8654f3 and https://github.com/ROCm/clr/commit/77c581a3ebd47b5e2908973b70adea66891159ee
