### ISSUE TITLE
[Issue]:  Unable to find header file cmath.h

### ISSUE THREAD

**Issue by rerrabolu** [ROCm-Developer-Tools/HIP#3406]
### Problem Description

master@hpe-sjc2-03:memory_allocation_test-main$ 
master@hpe-sjc2-03:memory_allocation_test-main$ echo "OS:" && cat /etc/os-release | grep -E "^(NAME=|VERSION=)";
OS:
NAME="Ubuntu"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
master@hpe-sjc2-03:memory_allocation_test-main$ 

master@hpe-sjc2-03:memory_allocation_test-main$ 
master@hpe-sjc2-03:memory_allocation_test-main$ echo "CPU: " && cat /proc/cpuinfo | grep "model name" | sort --unique; 
CPU: 
model name	: AMD EPYC 7542 32-Core Processor
master@hpe-sjc2-03:memory_allocation_test-main$

master@hpe-sjc2-03:memory_allocation_test-main$ hipcc -std=c++17 test.cpp -DUSE_SYSTEM_MEMORY_ALLOC -DMEM_INIT_CPU 
In file included from <built-in>:1:
In file included from /opt/rocm-6.1.0-13349/lib/llvm/lib/clang/17/include/__clang_hip_runtime_wrapper.h:50:
/opt/rocm-6.1.0-13349/lib/llvm/lib/clang/17/include/cuda_wrappers/cmath:27:15: fatal error: 'cmath' file not found
   27 | #include_next <cmath>
      |               ^~~~~~~
1 error generated when compiling for gfx908.
master@hpe-sjc2-03:memory_allocation_test-main$

### Operating System

Ubuntu 22.04.3 LTS (Jammy Jellyfish)

### CPU

AMD EPYC 7542 32-Core Processor

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 6.0.0

### Steps to Reproduce

Try to compile a Hip test/workload that includes cmath.h file

#include_next <cmath>

**Comment by kjayapra-amd** [comment]
Ubuntu 22.04 has g++ 11.3.0 as its default version. We need g++-12, please use the below command to install.

sudo apt install g++-12

**Comment by kjayapra-amd** [comment]
That should resolve the issue. 
Please re-open if you still see this issue.
