### ISSUE TITLE
Is there any lossless compression available on AMD GPUs in ROCm or HIP?

### ISSUE THREAD

**Issue by yulingao** [ROCm-Developer-Tools/HIP#3419]
I am exploring options for data compression and decompression on AMD GPUs within the ROCm or HIP. Specifically, I am interested in finding a lossless compression algorithm that can efficiently compress and decompress data directly on the GPU. This would allow for reduced data transfer overhead when transmitting data between GPUs or between the GPU and the host system. 

Any responses would be greatly appreciated.

**Comment by huanglang123** [comment]
I'm also very interested in this topic. Does anyone have an answer?

**Comment by schung-amd** [comment]
Hi @yulingao @huanglang123, https://github.com/ROCm/hipCOMP-core/ is based on `nvCOMP` and should provide what you're looking for. Let me know if this is insufficient or if you'd like guidance on using it.

**Comment by schung-amd** [comment]
Closing this for now, feel free to comment if you still need guidance and we can reopen this.
