### ISSUE TITLE
[Issue]: Unable to install HIP extension for Visual Studio 2022

### ISSUE THREAD

**Issue by TomClabault** [ROCm-Developer-Tools/HIP#3420]
### Problem Description

Trying to install the Visual Studio HIP extension with the HIP SDK reports a 215 error every time I try. I also tried following [this](https://rocm.docs.amd.com/projects/hip-vs/en/latest/building.html) tutorial but all the links to the Github are dead links and I am unable to download the necessary files to build the extension myself.

[This](https://github.com/ROCm/ROCm/issues/2363) issue mentions the error 215 but the only solution to this error seems to be installing the SDK without the VS extension but the extension is exactly what I'm trying to install...

### Operating System

Windows 11 10.0.22631

### CPU

13th Gen Intel(R) Core(TM) i5-13600KF

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 5.7.1

### ROCm Component

HIP

### Additional Information

SDK Installer: Windows 10 & 11 5.7.1: https://www.amd.com/fr/developer/resources/rocm-hub/hip-sdk.html
Visual Studio Version: Visual Studio Community 2022 17.9.0

**Comment by cjatin** [comment]
@emankov can you please help

**Comment by flipflopsen** [comment]
same here, the repos referenced in https://rocm.docs.amd.com/projects/hip-vs/en/latest/building.html aren't existing anymore as well and there was some sort of information that they should've been migrated to https://github.com/ROCm somewhere, but this isn't the case.
So what we need is either a fixed installer which installs the VS extension, or a comeback of the ROCm-Developer-Tools/HIP-VS Repo, which was located at: https://github.com/ROCm-Developer-Tools/HIP-VS/blob/master/extension/HIPExtension2022.sln (referenced in the rocm docs).

**Comment by emankov** [comment]
AFAIK, the 215 error is most likely related to the HIP SDK installer itself. I'll inform the installer team about it once again.
As for installing HIP-VS separately, there are two options I can see here.
1. Look into the HIP SDK installer archive and extract the needed vsix files (for VS 2022, 2019, and/or 2017) and run them. The targeting VS shouldn't be running at that moment.
2. Build vsix files from scratch: https://github.com/ROCm/HIP-VS/blob/master/extension/HIPExtension2022.sln. The HIP-VS 5.7 release will be uploaded there as well soon (in a couple of days).

**Comment by TomClabault** [comment]
@emankov 

I tried extracting (I just opened the .exe file with 7zip) the .vsix files from the installer under the Packages/Apps/ROCmSDKPackages/VisualStudioPlugin2022 folder. I could only find an MSI installer there, no .vsix file. Extracting the MSI setup and running it manually throws the follwing error:

<img width="284" alt="error" src="https://github.com/ROCm/HIP/assets/61839853/0f2aaebb-75cc-4e7c-8f5e-7371b0d50324">

The HIP-VS repository ([https://github.com/ROCm/HIP-VS](https://github.com/ROCm/HIP-VS)) doesn't seem to exist anymore. Do you mean that it will be back online in a couple of days with the release of HIP-VS 5.7?

**Comment by emankov** [comment]
Hello @TomClabault, 

Oh, they put the vsix into the msi. Could you please rename that msi to zip and extract the file `VisualStudio2022Installer`? After adding a `.vsix` extension to the extracted file, you will finally be able to run the HIP-VS installer separately. Sorry for that... 

The HIP-VS repository still exists, but it's private. I thought you already had access to https://github.com/ROCm-Developer-Tools/HIP-VS, which was always private, too. https://github.com/ROCm/HIP-VS is the same repo; only the GitHub organization ROCm-Developer-Tools migrated to the ROCm organization.

As for the 215 error, I've already informed the Installer team.

Thanks!

**Comment by TomClabault** [comment]
@emankov 

Extracting the file from the .msi and running it as a .vsix did work and I could install the extension to my Visual Studio 2022.
This is a viable solution while waiting for the installer team to work on a fix.

Thanks for your help!

**Comment by flipflopsen** [comment]
From the download page (https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) there is only the option to get the installer in PE (.exe) format and not in .msi format.
Did some research on that, didn't able to find any msi installers, even tried to extract resources from the exe.

I would appreciate if someone could provide a link to the .msi installers so I can extract the VS2022 vsix. :)

Greetings

EDIT: I am aware that I could use my Linux Distro or WSL to utilize the HIP. Nevertheless I would love to stay on my Windows Enviroment and have the appropiate VS2022 Extension installed. ^^

**Comment by TomClabault** [comment]
@flipflopsen Hey there,

Dowload the .exe installer (~1.2GB) and open it as an archive. You should have access to a folder hierarchy that looks like:

![image](https://github.com/ROCm/HIP/assets/61839853/92864d07-f065-409c-babe-fbbcd12e5882)

The .msi file is then located in Packages/Apps/ROCmSDKPackages/VisualStudioPlugin2022

Open that .msi file as archive and add the .vsix extension to the file found within the .msi file and you should be good to go.
