### ISSUE TITLE
[Documentation]: build guide does not handle dependency CppHeaderParser

### ISSUE THREAD

**Issue by sogartar** [ROCm-Developer-Tools/HIP#3431]
### Description of errors

The [build guide](https://github.com/ROCm/HIP/blob/d62ffdd9c55a11b16538675156f3a7c0191e9b66/docs/developer_guide/build.md#build-hip-runtime) does not mention that you need the Python module`CppHeaderParser`. Which results in an error.
```
ModuleNotFoundError: No module named 'CppHeaderParser'
CMake Error at hipamd/src/CMakeLists.txt:228 (message):
      The "CppHeaderParser" Python3 package is not installed.     Please install it using the following command: "pip3 install CppHeaderParser".  
```

**Comment by ppanchad-amd** [comment]
@sogartar Internal ticket has been created to fix documentation. Thanks!

**Comment by ppanchad-amd** [comment]
@sogartar Fixed. Please see (https://rocm.docs.amd.com/projects/HIP/en/latest/install/build.html )
