### ISSUE TITLE
The One Billion Row Challenge

### ISSUE THREAD

**Issue by sviscapi** [ROCm-Developer-Tools/HIP#3448]
Dear ROCm team,

I just stumbled upon that article about "The One Billion Row Challenge":

https://tspeterkim.github.io/posts/cuda-1brc

> The challenge is simple, but implementing it in CUDA was not. Here I will share [my solution](https://github.com/tspeterkim/cuda-1brc/blob/main/fast.cu) that runs in 16.8 seconds on a [V100](https://aws.amazon.com/ec2/instance-types/p3/). It’s certainly not the fastest solution, but it is the first one of its kind (no [cudf](https://github.com/rapidsai/cudf), hand-written kernels only). **I challenge other CUDA enthusiasts** to make it faster.

I hope AMD will accept that challenge and offer an HIP-based solution to this problem :)

https://1brc.dev/

Best regards,

Samuel

**Comment by tcgu-amd** [comment]
Hi @sviscapi, thanks for the invitation! We would love to rise to the challenge; in the mean time, we would also like send a gentle reminder that the issues section is a place for reporting bugs and problems with ROCm. We would appreciated it if we continue the thread to somewhere such as https://github.com/ROCm/ROCm/discussions. Please understand that this issue will be closed for now. Thanks! :D
