### ISSUE TITLE
[Documentation]: No actual guide for properly getting started working with this

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [ROCm-Developer-Tools/HIP#3453]
### Description of errors

Steps I've taken so far:
1. So far I managed to install HIP using the installer found from [here](https://rocm.docs.amd.com/projects/install-on-windows/en/latest/index.html#hip-install-quick)
2. Created a new empty C++ project in VS2022
3. Attempt to find a gist.github.com example for using ROCm/HIP/What ever it is that lets me just use an LLM on a GPU
4. Gave up searching gist, searched documentation for some kind of actual working example(Found none, not even a hello world that runs on a GPU with this thing)
5. Search youtube, find nothing that actually showed how to do this either. just a few AMD vids that explained concepts but didn't go through writing an actual program with it.
6. Loaded up LM Studio and used LLama 3 to try and generate an example in hopes that I could use an AI to teach me how to use this thing so that I can use an AI. AI failed to produce a working example, forced me to hunt down what headers were missing from being included. Still didn't work after finding the right headers to include from standard library and GLM

It would be really nice to just get a working example or tutorial that properly explains how to get started.

**Comment by kjayapra-amd** [comment]
Hi,
Thanks for the feedback. We have HIP samples - https://github.com/ROCm/hip-tests/tree/develop/samples, which provides some examples on how to compile and run. Please let me know if this works.

Your feedback on lack of examples on other mediums are noted.

**Comment by kjayapra-amd** [comment]
Please re-open if you have more concerns.
