### ISSUE TITLE
Any suggestions for porting HIP to CUDA? 

### ISSUE THREAD

**Issue by galenyu** [ROCm-Developer-Tools/HIP#3462]
Hello everyone! I am a beginner in `HIP`. I recently received a code for `HIP ` and I want to run it on NVIDIA GPU. But it is difficult to find relevant tutorials or examples. Does anyone know how to port `HIP ` to `CUDA ` for compilation and use ?

Any suggestion will be appreciated!

**Comment by kjayapra-amd** [comment]
Please take a look at hipify tools we provide - https://github.com/ROCm/HIPIFY/blob/amd-staging/README.md
