### ISSUE TITLE
[Documentation]: Fix NVIDIA build instructions

### ISSUE THREAD

**Issue by torrance** [ROCm-Developer-Tools/HIP#3472]
### Description of errors

Since at least `v6.0`, the build process for NVIDIA has required cloning https://github.com/ROCm/hipother.git, however this is not mentioned anywhere in the documentation here: https://rocm.docs.amd.com/projects/HIP/en/latest/developer_guide/build.html

Please add this repository as a requisite for building for NVIDIA.

**Comment by ppanchad-amd** [comment]
@torrance Internal ticket has been created to fix this. Thanks!

**Comment by harkgill-amd** [comment]
Hi @torrance, the ROCm 6.2.0 documentation address the hipother repo in it's build instructions at [Build HIP from source](https://rocm.docs.amd.com/projects/HIP/en/latest/install/build.html#building-the-hip-runtime). The below excerpt is taken directly from the documentation under the `NVIDIA` tab.
```
1. Get the HIP source code.

git clone -b "$ROCM_BRANCH" https://github.com/ROCm/clr.git
git clone -b "$ROCM_BRANCH" https://github.com/ROCm/hip.git
git clone -b "$ROCM_BRANCH" https://github.com/ROCm/hipother.git

2. Set the environment variables.

export CLR_DIR="$(readlink -f clr)"
export HIP_DIR="$(readlink -f hip)"
export HIP_OTHER="$(readlink -f hipother)"

3. Build HIP.

cd "$CLR_DIR"
mkdir -p build; cd build
cmake -DHIP_COMMON_DIR=$HIP_DIR -DHIP_PLATFORM=nvidia -DCMAKE_INSTALL_PREFIX=$PWD/install -DHIP_CATCH_TEST=0 -DCLR_BUILD_HIP=ON -DCLR_BUILD_OCL=OFF -DHIPNV_DIR=$HIP_OTHER/hipnv ..
make -j$(nproc)
sudo make install
```
