### ISSUE TITLE
cudaMemGetInfo and hipMemGetInfo are Functionally Different

### ISSUE THREAD

**Issue by mathewhall** [ROCm-Developer-Tools/HIP#348]
cudaMemGetInfo provides the available device memory and the total device memory, whereas hipMemGetInfo provides the total device memory and the total device memory minus the memory consumed by the calling process.  Maybe GPU programs will all be able to think they have access to the full amount of memory at some point, but that is not currently the case.  While this is not the case, the CUDA API is significantly more useful.

**Comment by satyanveshd** [comment]
hipMemGetInfo has been reimplemented (#1447) to address this. Now the device memory consumed is accounted from kfd and the available memory is reported accordingly.
