### ISSUE TITLE
HIP SDK 5.7 installer installs HIP runtime 5.2

### ISSUE THREAD

**Issue by wenqingli** [ROCm-Developer-Tools/HIP#3482]
### Problem Description

Download ROCm 5.7.1 (actually it is AMD Software PRO Edition 23.Q4) for win10/11 from https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html, then install, after finish, you can see the HIP runtime dll version is actually **5.2** in C:\Windows\System32\amdhip64.dll, why the version is not **5.7.1**?
![image](https://github.com/ROCm/HIP/assets/24380807/89aa3ed1-d4d3-4dec-9342-664687e76f19)

### Operating System

Windows 10

### CPU

5950x

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 5.7.1

### ROCm Component

HIP

**Comment by bdenhollander** [comment]
I believe that file is installed by the graphics driver rather than the HIP SDK. Are you using a 23.x version of AMD Adrenaline Edition driver package?

**Comment by wenqingli** [comment]
Yes, it is installed by graphics driver(the pro edition not adrenaline edition), but the graphics driver is packed together with HIP SDK 5.7, when I select full install(including hip sdk + graphics driver), the HIP runtime and HIP SDK looks unmatched.

**Comment by harkgill-amd** [comment]
Hi @wenqingli, could you please advise if you are still seeing this issue. If so, what version of the HIP SDK do you see under "Installed apps"? Thanks!

**Comment by wenqingli** [comment]
No, the HIP version turns to 5.7 with latest amd software, hence close this issue, thank you guys.
