### ISSUE TITLE
[Issue]: how to close or bypass L1 cache

### ISSUE THREAD

**Issue by JNYXR** [ROCm-Developer-Tools/HIP#3506]
### Problem Description

MI100 how to close or bypass L1 cache

### Operating System

ubuntu 18.04

### CPU

AMD EPYC 7452 32-Core Processor

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 5.5.0

**Comment by b-sumner** [comment]
@JNYXR your situation is not clear to me.  But if you are writing HIP source code, then I would recommend using `__builtin_nontemporal_{load, store}`.  This will work on all targets.

**Comment by JNYXR** [comment]
@b-sumner Thank you for your reply，CUDA can set the -Xptxas-dlcm = cg-Xptxas-dscm =wt compiler option to bypass L1 CACHE. Does HIP have compiler options or environment variables? I want to verify whether L1 CACHE affects my kernel, so I want to try bypass L1 CACHE.

**Comment by tcgu-amd** [comment]
Hi @JNYXR , sorry for the lack of response. Unfortunately, HIP doesn't have compiler flags or environment variables that allow for disabling/bypassing L1 cache directly. To achieve this, you will have to modify your kernel code. This means manually replacing every load and store operation in your kernel code with `__builtin_nontemporal_load(ptr)`/`__builtin_nontemporal_store(value, ptr)` . Hope this helps!
