### ISSUE TITLE
return value of the device property

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#3516]
The return value of the following device property is zero.  Thanks for your comments/suggestions.
 
  hipDeviceProp_t deviceProp;
  hipGetDeviceProperties(&deviceProp, 0);
  size = deviceProp.sharedMemPerBlockOptin;
  printf("%zu\n", size);

HIP version is 6.0.3

**Comment by harkgill-amd** [comment]
Hi @jinz2014, an internal ticket has been created to investigate this issue. Thanks!

**Comment by harkgill-amd** [comment]
Hi @jinz2014 , this issue is addressed in https://github.com/ROCm/clr/commit/4b95e7bc87f6a5d704c78a3bd2173e29a0aef8f6. Thanks for pointing this out!
