### ISSUE TITLE
[Issue]: I want to use rocgdb to trace the calling situation of the hip runtime functions。such as hipMalloc

### ISSUE THREAD

**Issue by fortunerains** [ROCm-Developer-Tools/HIP#3528]
### Problem Description

I want to use rocgdb to trace the calling situation of the hip runtime functions, but found that the hipMalloc function cannot be traced and directly skipped in the gdb debugging process.

how can I trace hipMalloc   running process？

The gdb process is as follows:
![image](https://github.com/ROCm/HIP/assets/24492495/ea5900d9-57ea-4a1b-95d3-3d265cf28615)

### Operating System

Linux td50 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### CPU

Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.1.0

### ROCm Component

HIP

**Comment by kjayapra-amd** [comment]
You need to have debug build for that. Please see the instructions below.
https://github.com/ROCm/clr/blob/develop/README.md
https://rocm.docs.amd.com/projects/HIP/en/latest/install/build.html
