### ISSUE TITLE
[Documentation]: hipMemGetAdressRange unexpectedly returns hipErrorNotFound

### ISSUE THREAD

**Issue by BKitor** [ROCm-Developer-Tools/HIP#3531]
### Description of errors

Minor Docs typo, looks like hipErrorInvalidDevicePointer got swapped to hipErrorNotFound at some point. Makes debugging a bit confusing...

Link to function in CLR:
https://github.com/ROCm/clr/blob/6b9e89fe0cf9a08ce5e3b81a240977a89587dd03/hipamd/src/hip_memory.cpp#L783C15-L783C17

doc line in header file:
https://github.com/ROCm/HIP/blob/91db702b8c214d0fbd10acf39169237be394c668/include/hip/hip_runtime_api.h#L4998

**Comment by harkgill-amd** [comment]
Hi @BKitor, an internal ticket has been created to fix this issue. Thanks!

**Comment by harkgill-amd** [comment]
Fixed with this change https://github.com/ROCm/HIP/commit/9e407373f4cfa2289b0f04dd80eb0e9254222037. Closing out issue, thanks again @BKitor!
