### ISSUE TITLE
[Issue]: Visual Studio 2022 HIP-VS extension - missing General [AMD HIP for Clang] option in project property.

### ISSUE THREAD

**Issue by pibesk** [ROCm-Developer-Tools/HIP#3546]
### Problem Description

As in title. In project property General [AMD HIP for Clang] is missing

In documentation its present 
![obraz](https://github.com/user-attachments/assets/990de81a-3a3e-4a11-8035-30f5051331be)
but in my VS 2022 (c++, c#, HIP-VS works except this option, jetbrains for c#, lang of interface - Polish) its missing.
![obraz](https://github.com/user-attachments/assets/3be5b41e-07ed-4dec-a2a7-40672bf72bd2)

Ogólne - Generic 
Generic for HIP is missing

Rocm sample projects are building fine. Both with Visual Studio 2022 & with cmake.

Im using sdk 6.1.2 for windows.

My GPU is actually 6700xt (cannot select in dropdown in report, should not matter)

### Operating System

Windows 11

### CPU

AMD Ryzen 5950x

### GPU

AMD Radeon RX 6700XT

### ROCm Version

ROCm 6.1.0

### ROCm Component

HIP, ROCm

### Additional Information

Visual Studio 2022 was installed early as RC version and then updated up to this day.

**Comment by harkgill-amd** [comment]
Hi @pibesk, this property is present in AMD HIP Runtime projects. You can create one by selecting the project template in the "Create a new project" drop down menu below.

![image](https://github.com/user-attachments/assets/6c9080d2-da02-4766-8ec6-b63c55feacbe)

**Comment by pibesk** [comment]
@harkgill-amd HI, well sad news is i took my screenshot from exactly that project youre suggesting 
"AMD HIP 6.1 Runtime - Matrix Transpose sample", ive also checked new empty HIP runtime project + ROCM samle repo. Same issue. I had this problem since i first installed sdk 5.5, then 5.7 and now 6.1.

**Comment by pibesk** [comment]
@harkgill-amd ok. i found issue at least on my Visual Studio 2022.
I've added English language pack with VS installer (next to my Polish language pack), switched to English and this property is visible now.
But when i switch back to Polish prop disappears.

**Comment by harkgill-amd** [comment]
@pibesk, Looks like the issue isn't specific to just Polish as the option is missing for both French and German as well. 

I will create an internal ticket to investigate the missing property when changing language packs, thanks!

**Comment by harkgill-amd** [comment]
Hi @pibesk, spoke with the internal team and unfortunately there are no plans to implement localization support for HIP-VS. We appreciate your feedback and will keep it in mind for future updates to the plugin.
