### ISSUE TITLE
Fail to compile: ld.lld: error: unable to find library -lstdc++

### ISSUE THREAD

**Issue by CanYing0913** [ROCm-Developer-Tools/HIP#3557]
Hello HIP community. I have a simple Makefile with my HIP program converted by using hifipy-clang tool:
```Makefile
# Define compiler and compiler flags
CXX = g++
HIPCC = hipcc
SRCS = src
HIPCCFLAGS = -O3 -I /usr/include/x86_64-linux-gnu/c++/11 -I /usr/include/c++/11 -L /usr/lib/x86_64-linux-gnu -v
HIPOBJS = main_hip.o fdtd3d_gpu_hip.o fdtd3d_texture_hip.o

all: hip

hip: hip_gpu.o hip_main.o hip_texture.o
	$(HIPCC) -o hip_gpu $(HIPOBJS) $(HIPCCFLAGS)

hip_main.o: ${SRCS}/main_hip.cpp
	$(HIPCC) -c ${SRCS}/main_hip.cpp $(HIPCCFLAGS)

hip_gpu.o: ${SRCS}/fdtd3d_gpu_hip.cpp ${SRCS}/fdtd3d_gpu_hip.h
	$(HIPCC) -c ${SRCS}/fdtd3d_gpu_hip.cpp $(HIPCCFLAGS)

hip_texture.o: ${SRCS}/fdtd3d_texture_hip.cpp ${SRCS}/fdtd3d_texture_hip.h
	$(HIPCC) -c ${SRCS}/fdtd3d_texture_hip.cpp $(HIPCCFLAGS)

clean:
	rm hip_gpu *.o 
```
The output messages can be viewed here:
[hip_out.txt](https://github.com/user-attachments/files/16450936/hip_out.txt)
It can be seen that it complains: `ld.lld: error: unable to find library -lstdc++`
Take a deeper look at the output, it seems that it skips a lot of directories. How can I fix this issue? I'm pretty sure I have required libraries (I installed ROCm following official docs and my build-essentials is up-to-date with `sudo apt-get update`). Any help is appreciated.

**Comment by mangupta** [comment]
@CanYing0913 : I think you are missing the libstdc++-11-dev or libstdc++-12-dev package on your system for some reason. Could you try installing it depending on which g++ version you have installed?

**Comment by CanYing0913** [comment]
@mangupta Passing the correct library path successfully compiles it. After running it, it said no ROCm compatible device detected. However, I do have a NVIDIA gpu, which I think is also supported by HIP?

**Comment by harkgill-amd** [comment]
Hi @CanYing0913, have you added your user to the video and render groups? This can be done with the following command
```
sudo usermod -a -G render,video $LOGNAME
```

**Comment by taylding-amd** [comment]
Hi @CanYing0913, by default, access to GPU devices and certain system resources is restricted to the root user or specific groups. The command ```sudo usermod -a -G render,video $LOGNAME``` is used to add the current user to the render and video groups on a Linux system. The render group is typically used to grant access to the GPU for rendering tasks. Members of this group can access the GPU devices directly, which is essential for applications that require GPU acceleration, such as those using ROCm for compute tasks. The video group is used to manage access to video devices. This is important for applications that may need to perform video processing or utilize video hardware acceleration.

After adding the current user to the groups, you need to reboot the system to make it work. Here is a link to the [Rocm quick installation guide](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html), please let me know if you have more questions.
