### ISSUE TITLE
[Issue]: Hipify tool generates the following: fatal error: 'device_launch_parameters.h' file not found.

### ISSUE THREAD

**Issue by crinard** [ROCm-Developer-Tools/HIP#3568]
### Problem Description

Attempting to compile this code:
```
#include <cuda_runtime.h>
#include <device_launch_parameters.h>
#include <cuda_fp16.h>
#include <stdint.h>
#include <torch/extension.h>
#include <ATen/cuda/CUDAContext.h>

// SHA256 Constants
__constant__ uint32_t k[64] = {
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
};

// SHA256 functions
#define ROTRIGHT(word, bits) (((word) >> (bits)) | ((word) << (32 - (bits))))
#define CH(x, y, z) (((x) & (y)) ^ (~(x) & (z)))
#define MAJ(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define EP0(x) (ROTRIGHT(x, 2) ^ ROTRIGHT(x, 13) ^ ROTRIGHT(x, 22))
#define EP1(x) (ROTRIGHT(x, 6) ^ ROTRIGHT(x, 11) ^ ROTRIGHT(x, 25))
#define SIG0(x) (ROTRIGHT(x, 7) ^ ROTRIGHT(x, 18) ^ ((x) >> 3))
#define SIG1(x) (ROTRIGHT(x, 17) ^ ROTRIGHT(x, 19) ^ ((x) >> 10))

__device__ void sha256_transform(uint32_t state[8], const uint32_t data[16]) {
    uint32_t a, b, c, d, e, f, g, h, i, j, t1, t2;
    uint32_t m[64];

    for (i = 0; i < 16; ++i)
        m[i] = data[i];
    for (; i < 64; ++i)
        m[i] = SIG1(m[i - 2]) + m[i - 7] + SIG0(m[i - 15]) + m[i - 16];

    a = state[0];
    b = state[1];
    c = state[2];
    d = state[3];
    e = state[4];
    f = state[5];
    g = state[6];
    h = state[7];

    for (i = 0; i < 64; ++i) {
        t1 = h + EP1(e) + CH(e, f, g) + k[i] + m[i];
        t2 = EP0(a) + MAJ(a, b, c);
        h = g;
        g = f;
        f = e;
        e = d + t1;
        d = c;
        c = b;
        b = a;
        a = t1 + t2;
    }

    state[0] += a;
    state[1] += b;
    state[2] += c;
    state[3] += d;
    state[4] += e;
    state[5] += f;
    state[6] += g;
    state[7] += h;
}

__global__ void hash_gradients_kernel(const half2* __restrict__ gradients, size_t total_elements, uint32_t* __restrict__ final_hash) {
    __shared__ uint32_t shared_state[8];
    
    if (threadIdx.x < 8) {
        shared_state[threadIdx.x] = final_hash[threadIdx.x];
    }
    __syncthreads();

    uint32_t local_data[16];
    size_t idx = blockIdx.x * blockDim.x + threadIdx.x;
    size_t stride = blockDim.x * gridDim.x;

    while (idx * 2 < total_elements) {
        for (int i = 0; i < 16; i += 2) {
            if ((idx + i / 2) * 2 < total_elements) {
                half2 grad_half2 = gradients[idx + i / 2];
                float2 grad_float2 = __half22float2(grad_half2);
                local_data[i] = __float_as_uint(grad_float2.x);
                local_data[i+1] = __float_as_uint(grad_float2.y);
            } else {
                local_data[i] = local_data[i+1] = 0;
            }
        }

        sha256_transform(shared_state, local_data);
        idx += stride;
    }

    __syncthreads();
    if (threadIdx.x < 8) {
        atomicXor(&final_hash[threadIdx.x], shared_state[threadIdx.x]);
    }
}

void compute_gradient_hash(const half* gradients, size_t num_elements, uint32_t* hash_result, cudaStream_t stream) {
    uint32_t initial_hash[8] = {
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
        0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19
    };
    cudaMemcpyAsync(hash_result, initial_hash, 32, cudaMemcpyHostToDevice, stream);
    int block_size = 1024;
    int num_blocks = (num_elements + block_size - 1) / block_size;
    num_blocks = min(num_blocks, 108);
    hash_gradients_kernel<<<num_blocks, block_size, 0, stream>>>(
        reinterpret_cast<const half2*>(gradients),
        num_elements,
        hash_result
    );
}

// Python binding
torch::Tensor gradient_hash_cuda(torch::Tensor gradients) {
    TORCH_CHECK(gradients.is_cuda(), "Gradients must be a CUDA tensor");
    TORCH_CHECK(gradients.scalar_type() == torch::kHalf, "Gradients must be in half precision");
    
    auto num_elements = gradients.numel();
    auto options = torch::TensorOptions().dtype(torch::kInt32).device(torch::kCUDA);
    auto hash_result = torch::zeros({8}, options);
    
    uint32_t initial_hash[8] = {
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
        0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19
    };
    
    cudaMemcpyAsync(hash_result.data_ptr(), initial_hash, 32, cudaMemcpyHostToDevice, at::cuda::getCurrentCUDAStream());

    int block_size = 1024;
    int num_blocks = (num_elements / 2 + block_size - 1) / block_size;
    num_blocks = min(num_blocks, 108);

    hash_gradients_kernel<<<num_blocks, block_size, 0, at::cuda::getCurrentCUDAStream()>>>(
        reinterpret_cast<const half2*>(gradients.data_ptr()),
        num_elements,
        reinterpret_cast<uint32_t*>(hash_result.data_ptr())
    );
    
    C10_CUDA_KERNEL_LAUNCH_CHECK();
    
    return hash_result;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("gradient_hash_cuda", &gradient_hash_cuda, "Compute SHA256 hash for gradients on CUDA");
}
```

Included through this python file:
```
import torch
import ctypes
from torch.utils.cpp_extension import load

# Compile the CUDA code
cuda_module = load(name="gradient_hash_kernel",
                   sources=["gradient_hash_kernel.cu"],
                   extra_cuda_cflags=["-O3"])  # sm_80 is for A100

def hash_optimizer_state(optimizer):
    # assert torch.cuda.get_device_capability() >= (8, 0), "This code is optimized for A100 or newer GPUs"
    
    all_params = []
    for group in optimizer.param_groups:
        for p in group['params']:
            if p.grad is not None:
                all_params.append(p.grad.data)
    
    # Concatenate all gradients into a single tensor
    all_grads = torch.cat([p.view(-1) for p in all_params])
    
    # Ensure the tensor is in half precision
    if all_grads.dtype != torch.float16:
        all_grads = all_grads.half()
    
    num_elements = all_grads.numel()
    hash_result = torch.zeros(8, dtype=torch.int32, device='cuda')
    
    cuda_module.gradient_hash_cuda(
        all_grads
    )
    return hash_result.cpu().numpy()

def adam_step_with_gradient_hash(optimizer):
    grad_hash = hash_optimizer_state(optimizer)
    # print(f"Gradient hash for entire optimizer state: {grad_hash}")
    return grad_hash
```

Into a pytorch training script fails with the following output:
```
Traceback (most recent call last):
  File "/home/USER/zg/training/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2104, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/DIRNAME/torch_ft_commit.py", line 20, in <module>
    from gradient_hash_wrapper import adam_step_with_gradient_hash
  File "/home/DIRNAME/gradient_hash_wrapper.py", line 6, in <module>
    cuda_module = load(name="gradient_hash_kernel",
  File "/home/DIRNAME/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1314, in load
    return _jit_compile(
  File "/home/DIRNAME/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1721, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/DIRNAME/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1833, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/DIRNAME/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2120, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gradient_hash_kernel': [1/2] /opt/rocm-6.1.2/bin/hipcc  -DWITH_HIP -DTORCH_EXTENSION_NAME=gradient_hash_kernel -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include/TH -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include/THC -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include/THH -isystem /opt/rocm-6.1.2/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -fPIC -D__HIP_PLATFORM_AMD__=1 -DUSE_ROCM=1 -DHIPBLAS_V2 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -O3 --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908 --offload-arch=gfx90a --offload-arch=gfx1030 --offload-arch=gfx1100 --offload-arch=gfx942 -fno-gpu-rdc -c /home/DIRNAME/gradient_hash_kernel.hip -o gradient_hash_kernel.cuda.o 
FAILED: gradient_hash_kernel.cuda.o 
/opt/rocm-6.1.2/bin/hipcc  -DWITH_HIP -DTORCH_EXTENSION_NAME=gradient_hash_kernel -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include/TH -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include/THC -isystem /home/DIRNAME/venv/lib/python3.10/site-packages/torch/include/THH -isystem /opt/rocm-6.1.2/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -fPIC -D__HIP_PLATFORM_AMD__=1 -DUSE_ROCM=1 -DHIPBLAS_V2 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -O3 --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908 --offload-arch=gfx90a --offload-arch=gfx1030 --offload-arch=gfx1100 --offload-arch=gfx942 -fno-gpu-rdc -c /home/DIRNAME/gradient_hash_kernel.hip -o gradient_hash_kernel.cuda.o 
/home/DIRNAME/gradient_hash_kernel.hip:3:10: fatal error: 'device_launch_parameters.h' file not found
    3 | #include <device_launch_parameters.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx1030.
ninja: build stopped: subcommand failed.
```

### Operating System

Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### CPU

Intel(R) Core(TM) i9-14900KF

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.1.0

### ROCm Component

HIPCC, HIPIFY

### Steps to Reproduce

See code above. Calling through a python include.

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

ROCk module version 6.7.0 is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.13
Runtime Ext Version:     1.4
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Core(TM) i9-14900KF       
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Core(TM) i9-14900KF       
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   5700                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    65544884(0x3e822b4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    65544884(0x3e822b4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65544884(0x3e822b4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1100                            
  Uuid:                    GPU-f0ab61106df2dd5c               
  Marketing Name:          Radeon RX 7900 XTX                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      6144(0x1800) KB                    
    L3:                      98304(0x18000) KB                  
  Chip ID:                 29772(0x744c)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2304                               
  BDFID:                   768                                
  Internal Node ID:        1                                  
  Compute Unit:            96                                 
  SIMDs per CU:            2                                  
  Shader Engines:          6                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 202                                
  SDMA engine uCode::      20                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    25149440(0x17fc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1100         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***

**Comment by cjatin** [comment]
Can you remove the file <device_launch_parameters> and try again?

I think hip_runtime.h (which hipify should generate) should contain all required HIP apis.

**Comment by crinard** [comment]
Yep, that did the trick. Are you guys going to fix this in future versions?
