### ISSUE TITLE
[Issue]: Invalid argument from hipCreateTextureObject

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIP#3583]
### Problem Description

After the migration of the HSOpticalFlow example from CUDA to HIP, running the program shows the following issue:

./main
HSOpticalFlow Starting...

Loading "frame10.ppm" ...
Loading "frame11.ppm" ...
Computing optical flow on CPU...
Processing time on CPU: 3856.753418 (ms)
Computing optical flow on GPU...
HIP Error = 1: invalid argument from file ./downscaleKernel.cuh, line 94
HIP Error = 1: invalid argument from file ./downscaleKernel.cuh, line 94
HIP Error = 1: invalid argument from file ./downscaleKernel.cuh, line 94
HIP Error = 1: invalid argument from file ./downscaleKernel.cuh, line 94
HIP Error = 1: invalid argument from file ./warpingKernel.cuh, line 97
HIP Error = 1: invalid argument from file ./derivativesKernel.cuh, line 131
HIP Error = 1: invalid argument from file ./derivativesKernel.cuh, line 140
HIP Error = 1: invalid argument from file ./warpingKernel.cuh, line 97
HIP Error = 1: invalid argument from file ./derivativesKernel.cuh, line 131
HIP Error = 1: invalid argument from file ./derivativesKernel.cuh, line 140
HIP Error = 1: invalid argument from file ./warpingKernel.cuh, line 97
HIP Error = 1: invalid argument from file ./derivativesKernel.cuh, line 131
HIP Error = 1: invalid argument from file ./derivativesKernel.cuh, line 140

### Operating System

Ubuntu 22.04

### CPU

Intel Xeon

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.1.0

### ROCm Component

HIP

### Steps to Reproduce

The example is https://github.com/zjin-lcf/HeCBench/tree/master/src/opticalFlow-hip

Type make

./main

**Comment by TomSang** [comment]
Reason: 
The hardcode is wrong,
const int StrideAlignment = 32;
You should query hipDeviceAttributeTexturePitchAlignment.
It is  256 on gfx1100 in my test.

**Comment by jinz2014** [comment]
I hope 256 is a constant.  Thanks.

**Comment by zjin-lcf** [comment]
Thank you for explaining the issue.
