### ISSUE TITLE
[Feature]: atomicAdd() to support half and bfloat16

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#3589]
### Suggestion Description

It is similar to the "atomicAdd() to support half2 and bfloat162.

Could bf16.h and bfloat16.h be combined into a single file ? 

### Operating System

Ubuntu

### GPU

MI200

### ROCm Component

HIP

**Comment by ppanchad-amd** [comment]
Hi @jinz2014, internal ticket has been created to assist with your question. Thanks!

**Comment by cjatin** [comment]
I think we can close this one: https://github.com/ROCm/clr/commit/bb52d9ed62e8953dc9673b7e4d0fd13608a4dbf6

**Comment by ppanchad-amd** [comment]
Hi @jinz2014. This is fixed in ROCm 6.3. Closing ticket. Thanks!

**Comment by jinz2014** [comment]
I didn't see the function in /opt/rocm-6.3.0/lib/llvm/bin/../../../include/hip/amd_detail/amd_hip_atomic.h
