### ISSUE TITLE
[Issue]: cooperativeLaunch is unavailable on Windows?

### ISSUE THREAD

**Issue by nazar-pc** [ROCm-Developer-Tools/HIP#3640]
### Problem Description

The software I'm trying to run requires cooperative launch support. When tested with HIP SDK 6.2.1 and 6.2.2 GPUs like RX 6600 and RX 6800 were confirmed as working on Linux by users, while on Windows one user reports that RX 6700 XT (which is similar to those mentioned before) doesn't work and the only reason I see is `cooperativeLaunch: 0` in `hipinfo`'s output.

I tried Azure VM with Radeon Pro V620 MxGPU and Windows Server 2022 and got similar output and software not working:
<details>

```
device#                           0
Name:                             AMD Radeon Pro V620 MxGPU
pciBusID:                         0
pciDeviceID:                      0
pciDomainID:                      0
multiProcessorCount:              36
maxThreadsPerMultiProcessor:      2048
isMultiGpuBoard:                  0
clockRate:                        555 Mhz
memoryClockRate:                  555 Mhz
memoryBusWidth:                   0
totalGlobalMem:                   7.39 GB
totalConstMem:                    2147483647
sharedMemPerBlock:                64.00 KB
canMapHostMemory:                 1
regsPerBlock:                     0
warpSize:                         32
l2CacheSize:                      4194304
computeMode:                      0
maxThreadsPerBlock:               1024
maxThreadsDim.x:                  1024
maxThreadsDim.y:                  1024
maxThreadsDim.z:                  1024
maxGridSize.x:                    2147483647
maxGridSize.y:                    65536
maxGridSize.z:                    65536
major:                            10
minor:                            3
concurrentKernels:                1
cooperativeLaunch:                0
cooperativeMultiDeviceLaunch:     0
isIntegrated:                     0
maxTexture1D:                     16384
maxTexture2D.width:               16384
maxTexture2D.height:              16384
maxTexture3D.width:               2048
maxTexture3D.height:              2048
maxTexture3D.depth:               2048
hostNativeAtomicSupported:        1
isLargeBar:                       0
asicRevision:                     0
maxSharedMemoryPerMultiProcessor: 64.00 KB
clockInstructionRate:             1000.00 Mhz
arch.hasGlobalInt32Atomics:       1
arch.hasGlobalFloatAtomicExch:    1
arch.hasSharedInt32Atomics:       1
arch.hasSharedFloatAtomicExch:    1
arch.hasFloatAtomicAdd:           1
arch.hasGlobalInt64Atomics:       1
arch.hasSharedInt64Atomics:       1
arch.hasDoubles:                  1
arch.hasWarpVote:                 1
arch.hasWarpBallot:               1
arch.hasWarpShuffle:              1
arch.hasFunnelShift:              0
arch.hasThreadFenceSystem:        1
arch.hasSyncThreadsExt:           0
arch.hasSurfaceFuncs:             0
arch.has3dGrid:                   1
arch.hasDynamicParallelism:       0
gcnArchName:                      gfx1030
peers:
non-peers:                        device#0

memInfo.total:                    7.39 GB
memInfo.free:                     7.25 GB (98%)
```

</details>

One difference is that HIP SDK 6.1.2 is the latest available for Windows, but I see nothing in release notes of 6.2.0/6.2.1/6.2.2 that would indicate changes relevant to this issue.

### Operating System

Windows Server 2022 Datacenter Azure Edition 10.0.20348

### CPU

AMD EPYC 7763

### GPU

AMD Radeon Pro V620

### ROCm Version

ROCm 6.1.0

**Comment by ppanchad-amd** [comment]
Hi @nazar-pc. Internal ticket has been created to assist with your issue. Thanks!

**Comment by schung-amd** [comment]
Hi @nazar-pc, `hipInfo` also does not report cooperative launch support on Windows with a 7900XTX, so it seems the issue does lie with HIP SDK as you suggest. I'll check in with the internal team to see what the status of this is. 

As a side note, is this an NGads Azure VM? ROCm isn't currently enabled on Azure NGads instances as of ROCm 6.2, so this probably won't work regardless; there are plans to introduce support on cloud platforms in an upcoming release.

**Comment by nazar-pc** [comment]
> Hi @nazar-pc, hipInfo also does not report cooperative launch support on Windows with a 7900XTX, so it seems the issue does lie with HIP SDK as you suggest. I'll check in with the internal team to see what the status of this is.

Great, thanks!

> As a side note, is this an NGads Azure VM? ROCm isn't currently enabled on Azure NGads instances as of ROCm 6.2, so this probably won't work regardless; there are plans to introduce support on cloud platforms in an upcoming release.

Yes, that was the only one I was able to rent easily, needed to get my hands on something because other reports are from end users and I don't have much control there to do experiments. Thanks for letting me know about this, I'll monitor release notes.

**Comment by nazar-pc** [comment]
BTW while we're at it, is there a fundamental reason cooperative launch support is missing on cards like RX 5700 on Linux? We have some users with those and they were a bit disappointed with those not super old RX 5xxx cards not working.

**Comment by schung-amd** [comment]
Unfortunately there is no reason I can provide for this, but we do not plan to support cooperative groups on those cards.

**Comment by schung-amd** [comment]
Closing this for now, as far as I can see there is no timeline for when cooperative groups might be supported on Windows. If I find more information regarding this I'll update you here, but unfortunately support shouldn't be expected on Windows in the near future.

**Comment by nazar-pc** [comment]
Very sad for end users :disappointed:
