### ISSUE TITLE
The default value of the third argument of the shfl 

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#3643]
### Suggestion Description

In the "shfl" function, could the default value of the third argument be warpSize instead of 32 ? It seems that the default value is 32 though the warpSize is 64 on the target platform.

### ROCm Component

hipcc

**Comment by harkgill-amd** [comment]
Hi @jinz2014, per the documentation at [Warp shuffle functions](https://rocm.docs.amd.com/projects/HIP/en/latest/reference/cpp_language_extensions.html#warp-shuffle-functions), the third argument, `width`, is defaulted to `warpSize`. This is also consistent with the definition of these functions over at [amd_warp_functions.h](https://github.com/ROCm/clr/blob/amd-staging/hipamd/include/hip/amd_detail/amd_warp_functions.h) and [amd_warp_sync_function.h](https://github.com/ROCm/clr/blob/amd-staging/hipamd/include/hip/amd_detail/amd_warp_sync_functions.h).

Please note that the default warp size for NVIDIA devices is 32. For AMD, gfx9 will return a warpSize of 64 whereas devices that are gfx10 and above will return 32.

**Comment by jinz2014** [comment]
Thanks.
