### ISSUE TITLE
Will a Radeon 7600S work with Windows HIP SDK?

### ISSUE THREAD

**Issue by ET3D-ET3D** [ROCm-Developer-Tools/HIP#3654]
I want to convert a CUDA application to HIP, and a laptop would be convenient. Would a Radeon 7600S work with the Windows HIP SDK. (The desktop 7600 is officially supported.)

**Comment by darren-amd** [comment]
Hi @ET3D-ET3D,

Running on a RX 7600S is not officially supported so it hasn't been tested before for compatibility. However, seeing as we do support 7600's which are also based on Navi33 architecture, it might work. Please give it a try by following the instructions here: [HIP SDK Installer for Windows](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html), while making sure to upgrade to the latest version of the Adrenaline display drivers. Thanks!

**Comment by ET3D-ET3D** [comment]
So far (just running the Hello World sample) it seems to work.

**Comment by darren-amd** [comment]
Glad to hear that, I'm going to close this issue off but please feel free to create another one if you run into any issues, thanks!

**Comment by jgardona** [comment]
Yep, it works today as expected.
