### ISSUE TITLE
Which library corresponding to cusolver

### ISSUE THREAD

**Issue by kazulittlefox** [ROCm-Developer-Tools/HIP#366]
Now I am trying to translate CuPy(known as Numpy-like array API which uses Cuda library)
 to hip compatible code. 
So I first used hipify-perl for converting the original code, then I got to replacing 
modules which was unchanged at hipify script.

But I have had no Idea which library is corresponding to CuSolver, nor  had enough time to
implement the modules corresponding to CuSolver.

Would you mind tell me which library is corresponding to cusolver, 
or show me some advice for implementing  API which corresponds to CuSolver?

Thanks in advance.

**Comment by kazulittlefox** [comment]
I am closing this issue, while I have stopped converting CuPy for myself and examine
another branch which has already implemented for HIP environment.

Thanks.

**Comment by oscarbg** [comment]
Still interesting to know cusolver hip equivalent
