### ISSUE TITLE
Question about install HIP to run on nvidia gpu

### ISSUE THREAD

**Issue by huccpp** [ROCm-Developer-Tools/HIP#3665]
I try to install HIP to run on nvidia gpu.
I looked at the instruction here:
https://rocm.docs.amd.com/projects/HIP/en/latest/install/install.html
I am on ubuntu 20.04. Earlier I have installed nvidia hpc sdk, 
but the path of cuda it contains is not at /usr/local/cuda as written  (it is at /opt/nvidia/.../cuda).
How to specify the path for the apt install?
And in this case, do I need to do the step
sudo apt-get install ubuntu-drivers-common && sudo ubuntu-drivers autoinstall
sudo reboot
?
Thanks a lot.

**Comment by harkgill-amd** [comment]
Hi @huccpp, I believe your current installation at `/opt/nvidia` is due to cuda being installed from the Ubuntu repositories. If you install the toolkit from the [official website](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_local), the installation should be done under `/usr/local`.

**Comment by huccpp** [comment]
Hello @harkgill-amd,
Thanks for your reply. Earlier  I installed the nvidia hpc sdk from 
https://developer.nvidia.com/hpc-sdk-downloads 
which includes things in cuda toolkits, but inside /opt/nvidia/ .
The problem is that I wonder whether it is possible to install HIP without installing cuda toolkits as its contents are already in my nvidia hpc sdk installation (also to avoid possible conflicts). 
Thanks.
huccpp

**Comment by harkgill-amd** [comment]
I know of users working around the official cuda toolkit dependency by adding a `| nvidia-cuda-toolkit (>= 7.5)` in the `hip-runtime-nvidia` .deb file, see https://github.com/ROCm/HIP/issues/820#issuecomment-910063554. Please note that this is not officially supported and may cause errors for dependencies that look for the cuda installation at `/usr/local/cuda`. 

Not sure if the installation from the HPC SDK link satisfies either of these package requirements but it would be worth giving a try. If you could also share any errors encountered during the installation, that would be helpful in further investigating.

EDIT: You can also set the default CUDA installation path with the `CUDA_PATH` environment variable ([ref](https://rocm.docs.amd.com/projects/HIPCC/en/docs-6.2.4/env.html)).

**Comment by huccpp** [comment]
Thanks a lot, @harkgill-amd.  I eventually installed it successfully.
huccpp

**Comment by harkgill-amd** [comment]
No problem, happy to hear it's working on your end. Will close out this issue.
