### ISSUE TITLE
support of GPUs with a warpsize of 32  (The mask must be a 64-bit integer.)

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#3667]
Please suggest the workaround for devices with a warpsize of 32.  Thanks.

/opt/rocm-6.2.4/lib/llvm/bin/../../../include/hip/amd_detail/amd_warp_sync_functions.h:276:52: error: static assertion failed due to requirement 'sizeof(unsigned int) == 8': The mask must be a 64-bit integer. Implicitly promoting a smaller integer is almost always an error.

__shfl_xor_sync(warpMask, ...)

**Comment by harkgill-amd** [comment]
Hi @jinz2014, from what I see in the definition of `_shfl_xor_sync(` ([ref](https://github.com/ROCm/clr/blob/amd-staging/hipamd/include/hip/amd_detail/amd_warp_sync_functions.h#L273-L278)), the warpMask has to be a 64-bit integer regardless of the warpsize. When using a warpsize of 32, the upper half of the 64-bit mask is simply ignored ([ref](https://github.com/ROCm/clr/blob/amd-staging/hipamd/include/hip/amd_detail/amd_warp_sync_functions.h#L57-L61)). Please let me know if you have any further questions.

**Comment by jinz2014** [comment]
Thanks.
