### ISSUE TITLE
[Issue]: Why float pointer and double pointer in AMD MI 942 assembly take size of 8 ?

### ISSUE THREAD

**Issue by yiakwy-xpu-ml-framework-team** [ROCm-Developer-Tools/HIP#3686]
### Problem Description

I checked the assembly ABI and code object specification, and surprisely found that our float, double pointer takes size of 8. While int still take size of 4. I am wondering why we are using a 8 byte to represent a memory address ?

Also I want fully understand offset computing logics for MI300X : 

> I checked source code, the following instruction means kernel argument pointer address stored in s[0:1], and s[0:1]+0x1cd should point to blockDim.x

```
.loc	21 275 58 prologue_end          ; /opt/rocm-6.2.0/lib/llvm/bin/../../../include/hip/amd_detail/amd_hip_runtime.h:275:58
s_load_dword s6, s[0:1], 0x1c
s_waitcnt lgkmcnt(0)
s_and_b32 s1, s6, 0xffff
```

It is obvious the blockDim.x and blockDim.y are fetched in a 32-bit register (dword), and we extract it with 0xffff mask, but how should we determine the offset **0x1c**? 

I checked HSA specification, but it is all for RDNA. Do have document about how this kernel initialized ?

I also want to know where I can ensure that s[0:1] point to a kernel dispatch patchet and kernel arguments, while for GCN arhictecture, usually s[4:5] point to kernel dispatch packet and s[6:7] point to kernel argument region. 

### Operating System

Ubuntu 22.04

### CPU

EPYC, latest

### GPU

MI300X

### ROCm Version

ROCm 6.2.3

### ROCm Component

HIP, HIPCC

**Comment by ppanchad-amd** [comment]
Hi @yiakwy-xpu-ml-framework-team. Internal ticket has been created to assist with your issue. Thanks!

**Comment by searlmc1** [comment]
+ @arsenm

**Comment by zichguan-amd** [comment]
Hi @yiakwy-xpu-ml-framework-team, please refer to the llvm doc (https://llvm.org/docs/AMDGPUUsage.html) and ISA (https://gpuopen.com/amd-gpu-architecture-programming-documentation/ ISA relevant to your question can be found here: https://www.amd.com/content/dam/amd/en/documents/instinct-tech-docs/instruction-set-architectures/amd-instinct-mi300-cdna3-instruction-set-architecture.pdf page 25 and 67) for any similar/future questions.

> I am wondering why we are using a 8 byte to represent a memory address ?

Global address is 64-bit (https://llvm.org/docs/AMDGPUUsage.html#amdgpu-address-spaces).

> but how should we determine the offset 0x1c?

See GPR initialization and https://llvm.org/docs/AMDGPUUsage.html#amdgpu-amdhsa-code-object-kernel-argument-metadata-map-table-v3.

> I also want to know where I can ensure that s[0:1] point to a kernel dispatch patchet and kernel arguments, while for GCN arhictecture, usually s[4:5] point to kernel dispatch packet and s[6:7] point to kernel argument region.

gfx942 does not have Private Segment Buffer, therefore the first 4 SGPRs are not used. See https://llvm.org/docs/AMDGPUUsage.html#initial-kernel-execution-state and https://llvm.org/docs/AMDGPUUsage.html#amdgpu-amdhsa-kernel-prolog-private-segment-buffer.

You can find additional resources here https://llvm.org/docs/AMDGPUUsage.html#additional-documentation

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@zichguan-amd Thanks for pointing out the usage of Private Segment Buffer. That explains why s[0:1] in MI300X instead of s[4:5].

> If the Target Properties column of [AMDGPU Processors](https://llvm.org/docs/AMDGPUUsage.html#amdgpu-processor-table) specifies Architected flat scratch then a Private Segment Buffer is not supported. Instead the flat SCRATCH instructions are used.

Otherwise, Private Segment Buffer SGPR register is used to initialize 4 SGPRs that are used as a V# to access scratch.

<img width="910" alt="截屏2024-11-30 20 46 23" src="https://github.com/user-attachments/assets/3d8b116c-991a-4233-9f60-39396dcb02d6">
