### ISSUE TITLE
Why HIP_VERSION_PATCH does not match official release and can be the same on different releases ?

### ISSUE THREAD

**Issue by syl20bnr** [ROCm-Developer-Tools/HIP#3703]
Most of `6.2` releases have their patch number in VERSION set to `41134`. Is that expected ?

I maintain some Rust bindings for HIP and it would be great to have a way to identify unambiguously the official release number from the installed headers.

**Comment by mangupta** [comment]
HIP_VERSION_PATCH is only incremented if there is a change in the HIP runtime in any release. There is no change to HIP runtime code in any of the ROCm 6.2.x releases. Hence the patch version was not incremented.

Also please note that HIP is just a component of the ROCm release. Relying on the HIP version to detect ROCM version is incorrect. Instead you should look at rocm_version.h.

**Comment by syl20bnr** [comment]
Make sense, thank you for the clarification.
