### ISSUE TITLE
BF16 atomic add question

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIP#3711]
I observe that the bf16 atomic add will reach the value of 256 and then will not be incremented further.  This is not observed for fp16 atomic add. 

To reproduce the issue, the example is https://github.com/zjin-lcf/HeCBench/tree/master/src/f16atomic-hip

Thanks.

**Comment by b-sumner** [comment]
@jinz2014 it is true for all floating point types that at some point adding 1.0 to a floating point value v will result in v.  That value v is defined by the number of bits in the significand of the floating point type.   And I will note that bf16 has only 7 bits in the significand.
