### ISSUE TITLE
HIPCC heavily dependent on HCC

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#427]
Hello. After peering into the code base, it appears that there isn't a straightforward way to teach HIPCC to use GCC for host code. Are there any future plans on the road map for decoupling the dependency between hipcc & hcc?

**Comment by mangupta** [comment]
hipcc is only a convenience wrapper that allows simple HIP applications to be compiled on both AMD as well as nVidia platform using hcc or nvcc respectively. It is suitable for applications that don't care which compiler is used for host.
However using another compiler (such as gcc) for the host-only source files a specific HIP application is not difficult. All you need to do is to add rules to compile them to object files using gcc to your makefile. The only thing to be remember is to use hipcc for linking.

**Comment by pfultz2** [comment]
According to PR #418, hip can't be compiled with gcc when using the AMD backend.

**Comment by pfultz2** [comment]
> @pfultz2 - We have no desire to compile hip with gcc.

> there isn't a straightforward way to teach HIPCC to use GCC for host code.

These seem contradictory.

**Comment by Jorghi12** [comment]
@pfultz2 - The statement holds. There are translation units that do not necessarily require any HIP headers whatsoever. We've designed the code such that CUDA headers exist only in specified files ending in the .cu / .cuh extension (which should be compiled using hcc). The rest of the code should be compiled with gcc.
