### ISSUE TITLE
Request to expose __to_local() to HIP kernels

### ISSUE THREAD

**Issue by jlgreathouse** [ROCm-Developer-Tools/HIP#430]
This is a follow-on to [this HCC bug report](https://github.com/RadeonOpenCompute/hcc/issues/693). A quick summary: when a customer attempted to use inline assembly to write a `ds_read_b32` instruction in a HIP program, the compilation would fail because the pointer to shared memory region is 64-bits, but the input to the `ds_read_b32` instruction is 32-bits.

@scchan recommended using the __to_local() operator around the input pointer, and this worked. However, this requires defining the __to_local() operator somewhere in the program.

Would it be possible to make this operator available to HIP kernels in the general case, so that users don't need to know the magic `__attribute__((address_space(3))` definition? e.g. if the local address space changes from address_space(3) in a future compiler revision, user programs would break if they have to define it themselves to use the __to_local() fix mentioned in that bug report.

Thanks!

**Comment by mangupta** [comment]
Closing the ticket since _to_local() is not part of master branch.
