### ISSUE TITLE
No support for __shfl_xor or __shfl_down for type double.

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#434]
I could not find a signature for the functions __shfl_xor or __shfl_down with type double. These should be added.

**Comment by aaronenyeshi** [comment]
Hi @Jorghi12 double implementation was added in https://github.com/ROCm-Developer-Tools/HIP/pull/515

**Comment by mangupta** [comment]
Marking as duplicate of #442. Closing it.
