### ISSUE TITLE
Add support for cudaOccupancyMaxActiveBlocksPerMultiprocessor

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#439]
This is a pretty important instruction when designing kernels that are highly performant for the selected GPU architecture.

**Comment by emankov** [comment]
Hah, it's only implemented in fallback nvcc path.

**Comment by Jorghi12** [comment]
Can we have it implemented for hcc path :)

**Comment by mangupta** [comment]
Marking this as a duplicate of the newer #567 which is the same request.
