### ISSUE TITLE
HIPCC does not provide primitives for .cu / .cuh files.

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#441]
Generally when building files using the NVCC compiler, when the only dependency is the primatives (e.g. __host__ and __device__), the files will still build successfully **without** inclusion of cuda headers.
Here's an example: https://github.com/wsttiger/pytorch/blob/sending_pr/aten/src/ATen/cuda/detail/TensorInfo.cuh 

(FYI: The translation unit ATen.h does not contain any cuda header definitions.)

When parsing through this code using HIPCC we receive this error below:
`/home/rocm-user/pytorch_amd/aten/src/ATen/native/cuda/RoiPooling.cu:7:1: error: unknown type name '__host__'
__host__ __device__ __forceinline__ float fmin(float a, float b) {`

Would allowing for this change be fine for the design philosophy of HIP/ROCm?

**Comment by bensander** [comment]
HIP follows a minimal design philosophy and aims to be a (mostly) standard C++ compiler - so no headers are secretly included by default.  Similar to how even hello world in C++ requires including <stdio.h> or <iostream>.      To get the behavior you describe here - could you use something like passing '--include hip_runtime.h' option?  This could be added in the make infrastructure and would not require changes to any source files.

**Comment by Jorghi12** [comment]
Hi @bensander! Yes this definitely makes sense. I forgot the design philosophy is an intentional feature of the ROCm stack. Thanks again!
