### ISSUE TITLE
HIP vector types: implicit default ctor, dtor

### ISSUE THREAD

**Issue by jszuppe** [ROCm-Developer-Tools/HIP#453]
Is it possible to replace implemented (empty) default ctors and dtors for HIP's vector types (see https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/hcc_detail/hip_vector_types.h) with implicit default constructors/destructors (`= default`)? Implicit ctors/dtors are sometime useful.

**Comment by Sarbojit2019** [comment]
Looks like PR#1180 has requested change hence no action needed now.
