### ISSUE TITLE
#define for hipPitchedPtr not defined

### ISSUE THREAD

**Issue by pradeepisro** [ROCm-Developer-Tools/HIP#461]
The #define is not present in **nvcc_detail/hip_runtime_api.h**. This is causing error while building the example code from the driver api porting guide. After changing the header manually it is building.

**Comment by mangupta** [comment]
Thank you for reporting the issue. The issue was fixed a couple of hours ago via merging of the PR #456.

**Comment by pradeepisro** [comment]
Thank you
