### ISSUE TITLE
Error while building HIP using ninja

### ISSUE THREAD

**Issue by pradeepisro** [ROCm-Developer-Tools/HIP#467]
Error:
`ninja: error: build.ninja:2433: bad $-escape (literal $ must be written as $$)`

Build Command:
`ccmake -G Ninja ..`

But there were no errors while using `make`
I tried fixing manually by turning $(VERBOSE) to $$(VERBOSE)
It worked.

Fix:
It can be fixed by changing `add_custom_target(build_tests DEPENDS directed_tests)` to `add_custom_target(build_tests DEPENDS ${directed_tests})` in the CMakeLists.txt

**Comment by mangupta** [comment]
@pradeepisro #522 has been merged. so this issue should be fixed now I guess. Can you confirm and close the ticket?
