### ISSUE TITLE
hipEventDestroy(NULL) crashes

### ISSUE THREAD

**Issue by ArchaeaSoftware** [ROCm-Developer-Tools/HIP#47]
The CUDA runtime returns invalid-resource-handle. (It does not crash.)

(In retrospect, as Tommy Thorn pointed out back in the day, we screwed up the interfaces for the CUDA runtime. free() returns void and free(NULL) is valid and has no side effects. Really we should have echoed those API semantics in the CUDA runtime.)

**Comment by adityaatluri** [comment]
Hi,
Thanks you! Getting settled from SC this week. Will fix it.
