### ISSUE TITLE
hipSolver support

### ISSUE THREAD

**Issue by chentianran** [ROCm-Developer-Tools/HIP#498]
There does not appear to be a hipSolver library that could replace cuSolver in a portable way (I hope I'm not missing anything obvious). Is there any plan to implement that?

**Comment by mangupta** [comment]
@chentianran You can check out [rocSOLVER](https://github.com/ROCmSoftwarePlatform/rocSOLVER). Keep in mind that this effort has just started.

**Comment by oscarbg** [comment]
There is support for hip automatic translation?

**Comment by cgmb** [comment]
Hello everyone. I just wanted to mention that [hipSOLVER](https://github.com/ROCmSoftwarePlatform/hipSOLVER) was released in ROCm 4.5.
