### ISSUE TITLE
No device code available for function

### ISSUE THREAD

**Issue by pradeepisro** [ROCm-Developer-Tools/HIP#499]
I am getting the above error while trying to launch a kernel from a shared library. When I tried nm on the shared library I could find the symbol. It is defined as a global Text symbol.

**Comment by jszuppe** [comment]
It might have been complied for different GPU arch and it's missing code for GPU you want to run it on. See https://github.com/RadeonOpenCompute/hcc/wiki#compiling-for-different-gpu-architectures.

**Comment by pradeepisro** [comment]
Thanks @jszuppe, It worked. Shouldn't compiler detect the architecture automatically? Also the error was not very trivial to debug, Is there any documentation available for that?

**Comment by mangupta** [comment]
Closing this since the issue seems to have been resolved.
