### ISSUE TITLE
Strange function prototype for atomicAdd in hip_atomic.h

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#540]
I'm looking through the HIP source and noticed a strange function prototype.

`static double atomicAdd(double* address, double val)`

Why is the return type for this function double instead of void? Since it's performing an addition to the value stored at the provided address, there's no need to return anything.

**Comment by ekondis** [comment]
Returns the old value. Same as below:

[https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomicadd](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomicadd)
