### ISSUE TITLE
Allow hc::parallel_for_each to support priority.

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#547]
We want to implement hipCreateStreamWithPriority. However, since all kernel launches must go through the hc:parallel_for_each syntax, this will require modification to the HC API. 

Specifically, preemption capabilities at the block level for kernels with higher priority that are being executed on the GPU.

**Comment by mangupta** [comment]
```hipLaunchKernel``` and ```hipLaunchKernelGGL``` internally call ```hipModuleLaunchKernel```. See https://github.com/ROCm-Developer-Tools/HIP/blob/master/src/functional_grid_launch.inl#L128. And ```hipModuleLaunchKernel``` directly constructs an aql packet and dispatches it. See https://github.com/ROCm-Developer-Tools/HIP/blob/master/src/hip_module.cpp#L203.

So HIP kernels do not use hc:parallel_for_each. So all that is required in HIP is to create a hsa queue with higher priority. In case you still need enhancements in HC API so as to enable a similar feature in HC-mode applications, please file a separate issue in the HCC repo.

**Comment by Jorghi12** [comment]
Hi @mangupta, great that clears a few things. Though, I'm not sure if this approach will allow us to obtain fine grained prioritization. With the priority queue, we'd be able to prioritize the scheduling of one kernel over another, but once a kernel is dispatched, there needs to be a mechanism in place to pre-empty a lower priority kernel mid-computation (save its state) and let a higher priority kernel execute.
