### ISSUE TITLE
this line is returning zero for me and setting HIP_PLATFORM to nvcc.

### ISSUE THREAD

**Issue by odellus** [ROCm-Developer-Tools/HIP#552]
https://github.com/ROCm-Developer-Tools/HIP/blob/66f12daaa495b2715662dc160aa2537b56a40342/bin/hipconfig#L70

**Comment by mangupta** [comment]
@odellus That implies that the driver has not been loaded correctly. Most likely the ROCm stack has not been installed correctly.

Please ensure that you have followed all the steps listed in https://github.com/RadeonOpenCompute/ROCm#installing-from-amd-rocm-repositories. Executing rocminfo as specified in the instructions should show you the AMD GPU that it has identified.
Additionally can you verify that you are able to run the hsa sample under /opt/rocm/hsa/sample correctly? The sample is also available @ https://github.com/RadeonOpenCompute/ROCR-Runtime/tree/master/sample.

**Comment by odellus** [comment]
I've been using rocm-tensorflow and it's been working swimmingly. But just tested my rocminfo, the sample, and the tensorflow code I've been using and yeah something has gone wrong since I installed. Might have been a kernel upgrade from Ubuntu. Not sure.

Closing.

**Comment by odellus** [comment]
This is what happened. Ubuntu pushed me up to 4.15 and broke my ROCm installation.
https://github.com/RadeonOpenCompute/ROCm/issues/449

**Comment by odellus** [comment]
this is crap, AMD. :-1:
