### ISSUE TITLE
roc-1.8.x missing include

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#571]
Per our discussion here: https://github.com/ROCm-Developer-Tools/HIP/pull/523

You sent the fix for the missing include into the master branch, but when will it propagate to the roc-1.8.x branch? Without it, roc-1.8.x fails to build.

@mangupta

**Comment by mangupta** [comment]
Whoops. I missed out on pushing this. Done @ https://github.com/ROCm-Developer-Tools/HIP/commit/505a12754c6258b192941d91db0916da96a2b051.
