### ISSUE TITLE
__forceinline__ doesn't imply inline

### ISSUE THREAD

**Issue by jithunnair-amd** [ROCm-Developer-Tools/HIP#572]
HIP needs to handle `__forceinline__` like CUDA does. Currently, based on the comment here: https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_faq.md#what-if-hip-generates-error-of-symbol-multiply-defined-only-on-amd-machine
`__forceinline__` doesn't imply `inline`.

**Comment by AlexVlx** [comment]
#362 should be taken into account as well

**Comment by mangupta** [comment]
This was fixed via e7352a1f4aed1be98bcde4efe9201c66704ac621. Closing the issue.
