### ISSUE TITLE
Build error on latest master trunk  code tree on ARM64 Ubuntu 16.04

### ISSUE THREAD

**Issue by wormwang** [ROCm-Developer-Tools/HIP#577]
-- HIP Platform: hcc
-- Looking for HCC in: /opt/rocm/hcc. Found version: 1.2.18262-a743e2b-05eee4e-b25febc
-- Looking for HSA runtime in: /opt/hsa-rocr-dev/hsa
-- HIP will be installed in: /opt/rocm/hip
-- Found HIP: /opt/rocm/hip (found version "1.5.18283") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/HIP/build

 "/opt/rocm/hcc/bin/hc-kernel-assemble" /tmp/code_object_bundle-5ea64b.s CMakeFiles/hip_hcc_static.dir/src/code_object_bundle.cpp.o
[  7%] Building CXX object CMakeFiles/hip_hcc_static.dir/src/hip_clang.cpp.o
HCC clang version 7.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 05eee4ea8aedc4a168d11fbbf5095646702f83f2) (https://github.com/RadeonOpenCompute/llvm.git b25febceadb1ffabf9cd9bc0fd41e3cb8d4e9b80) (based on HCC 1.2.18262-a743e2b-05eee4e-b25febc )
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/aarch64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found HCC installation: /opt/rocm/hcc/bin/..
 "/opt/rocm/hcc/bin/clang-7" -cc1 -D__KALMAR_HC__=1 -D__HCC_HC__=1 -triple aarch64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -main-file-name hip_clang.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file /root/HIP/build/CMakeFiles/hip_hcc_static.dir/src/hip_clang.cpp.gcno -resource-dir /opt/rocm/hcc/lib/clang/7.0.0 -I/opt/rocm/hcc/bin/../include -I/opt/rocm/hcc/bin/../hcc/include -I /root/HIP/include -I /root/HIP/tests/src -D HIP_VERSION_MAJOR=1 -D HIP_VERSION_MINOR=5 -D HIP_VERSION_PATCH=18283 -I /opt/rocm/hcc/include -I /opt/rocm/include -I /opt/hsa-rocr-dev/hsa/include -D NDEBUG -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/rocm/hcc/lib/clang/7.0.0/include -internal-externc-isystem /usr/include/aarch64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++amp -fdeprecated-macro -fdebug-compilation-dir /root/HIP/build -ferror-limit 19 -fmessage-length 201 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -famp -fhsa-ext -o /tmp/hip_clang-11c6f4.s -x hc-host /root/HIP/src/hip_clang.cpp -emit-llvm-bc
clang -cc1 version 7.0.0 based upon HCC 1.2.18262-a743e2b-05eee4e-b25febc  default target aarch64-unknown-linux-gnu
ignoring nonexistent directory "/opt/rocm/hcc/bin/../hcc/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/opt/rocm/hcc/bin/../include"
ignoring duplicate directory "/usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rocm/hcc/bin/../include
 /root/HIP/include
 /root/HIP/tests/src
 /opt/rocm/include
 /opt/hsa-rocr-dev/hsa/include
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward
 /usr/local/include
 /opt/rocm/hcc/lib/clang/7.0.0/include
 /usr/include/aarch64-linux-gnu
 /usr/include
End of search list.
In file included from /root/HIP/src/hip_clang.cpp:26:
In file included from /root/HIP/include/hip/hip_runtime.h:56:
In file included from /root/HIP/include/hip/hcc_detail/hip_runtime.h:64:
In file included from /root/HIP/include/hip/hip_runtime_api.h:308:
In file included from /root/HIP/include/hip/hcc_detail/hip_runtime_api.h:41:
In file included from /root/HIP/include/hip/hcc_detail/hip_texture_types.h:38:
In file included from /root/HIP/include/hip/hcc_detail/channel_descriptor.h:27:
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:719:1: note: in instantiation of function template specialization 'HIP_vector_type<char, 2>::HIP_vector_type<signed char, signed char, nullptr>'
      requested here
DECLOP_MAKE_TWO_COMPONENT(signed char, char2);
^
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:696:49: note: expanded from macro 'DECLOP_MAKE_TWO_COMPONENT'
    type make_##type(comp x, comp y) { type r = {x, y}; return r; }
                                                ^
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: note: insert an explicit cast to silence this issue
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
                                                                static_cast<char>( )
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: note: insert an explicit cast to silence this issue
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
                                                                static_cast<char>( )
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:720:1: note: in instantiation of function template specialization 'HIP_vector_type<char, 3>::HIP_vector_type<signed char, signed char, signed char,
      nullptr>' requested here
DECLOP_MAKE_THREE_COMPONENT(signed char, char3);
^
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:702:57: note: expanded from macro 'DECLOP_MAKE_THREE_COMPONENT'
    type make_##type(comp x, comp y, comp z) { type r = {x, y, z}; return r; }
                                                        ^
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: note: insert an explicit cast to silence this issue
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
                                                                static_cast<char>( )
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: note: insert an explicit cast to silence this issue
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
                                                                static_cast<char>( )
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: note: insert an explicit cast to silence this issue
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
                                                                static_cast<char>( )
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:721:1: note: in instantiation of function template specialization 'HIP_vector_type<char, 4>::HIP_vector_type<signed char, signed char, signed char,
      signed char, nullptr>' requested here
DECLOP_MAKE_FOUR_COMPONENT(signed char, char4);
^
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:709:18: note: expanded from macro 'DECLOP_MAKE_FOUR_COMPONENT'
        type r = {x, y, z, w}; \
                 ^
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: note: insert an explicit cast to silence this issue
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
                                                                static_cast<char>( )
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: note: insert an explicit cast to silence this issue
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
                                                                static_cast<char>( )
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: note: insert an explicit cast to silence this issue
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
                                                                static_cast<char>( )
/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: error: non-constant-expression cannot be narrowed from type 'signed char' to 'char' in initializer list [-Wc++11-narrowing]
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
**/root/HIP/include/hip/hcc_detail/hip_vector_types.h:126:65: note: insert an explicit cast to silence this issue
        HIP_vector_type(Us... xs) noexcept { data = Native_vec_{xs...}; }
                                                                ^~
                                                                static_cast<char>( )
9 errors generated.**
 "/opt/rocm/hcc/bin/clang-7" -cc1 -D__KALMAR_HC__=1 -D__HCC_HC__=1 -famp-is-device -fno-builtin -fno-common -O2 -triple amdgcn--amdhsa-hcc -aux-triple aarch64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -main-file-name hip_clang.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -no-integrated-as -mconstructor-aliases -fuse-init-array -v -coverage-notes-file /root/HIP/build/CMakeFiles/hip_hcc_static.dir/src/hip_clang.cpp.gcno -resource-dir /opt/rocm/hcc/lib/clang/7.0.0 -I/opt/rocm/hcc/bin/../include -I/opt/rocm/hcc/bin/../hcc/include -I /root/HIP/include -I /root/HIP/tests/src -D HIP_VERSION_MAJOR=1 -D HIP_VERSION_MINOR=5 -D HIP_VERSION_PATCH=18283 -I /opt/rocm/hcc/include -I /opt/rocm/include -I /opt/hsa-rocr-dev/hsa/include -D NDEBUG -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/rocm/hcc/lib/clang/7.0.0/include -internal-externc-isystem /usr/include/aarch64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++amp -fdeprecated-macro -fno-dwarf-directory-asm -fdebug-compilation-dir /root/HIP/build -ferror-limit 19 -fmessage-length 201 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -famp -fhsa-ext -o /tmp/hip_clang-caf899.s -x hc-kernel /root/HIP/src/hip_clang.cpp -emit-llvm-bc
clang -cc1 version 7.0.0 based upon HCC 1.2.18262-a743e2b-05eee4e-b25febc  default target aarch64-unknown-linux-gnu
ignoring nonexistent directory "/opt/rocm/hcc/bin/../hcc/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/opt/rocm/hcc/bin/../include"
ignoring duplicate directory "/usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/opt/rocm/hcc/lib/clang/7.0.0/include"
ignoring duplicate directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rocm/hcc/bin/../include
 /root/HIP/include
 /root/HIP/tests/src
 /opt/rocm/include
 /opt/hsa-rocr-dev/hsa/include
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward
 /usr/local/include
 /opt/rocm/hcc/lib/clang/7.0.0/include
 /usr/include/aarch64-linux-gnu
 /usr/include
End of search list.
 "/opt/rocm/hcc/bin/hc-kernel-assemble" /tmp/hip_clang-caf899.s CMakeFiles/hip_hcc_static.dir/src/hip_clang.cpp.o
CMakeFiles/hip_hcc_static.dir/build.make:86: recipe for target 'CMakeFiles/hip_hcc_static.dir/src/hip_clang.cpp.o' failed
make[2]: *** [CMakeFiles/hip_hcc_static.dir/src/hip_clang.cpp.o] Error 1
make[2]: *** Deleting file 'CMakeFiles/hip_hcc_static.dir/src/hip_clang.cpp.o'
CMakeFiles/Makefile2:3354: recipe for target 'CMakeFiles/hip_hcc_static.dir/all' failed
make[1]: *** [CMakeFiles/hip_hcc_static.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

another error

"/opt/rocm/hcc/bin/hc-host-assemble" /tmp/hip_memory-c47ff2.s CMakeFiles/hip_hcc_static.dir/src/hip_memory.cpp.o -v -DHIP_VERSION_MAJOR=1 -DHIP_VERSION_MINOR=5 -DHIP_VERSION_PATCH=18231 -fPIC -O3 -DNDEBUG -famp
HCC clang version 7.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 05eee4ea8aedc4a168d11fbbf5095646702f83f2) (https://github.com/RadeonOpenCompute/llvm.git b25febceadb1ffabf9cd9bc0fd41e3cb8d4e9b80) (based on HCC 1.2.18262-a743e2b-05eee4e-b25febc )
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/aarch64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/aarch64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found HCC installation: /opt/rocm/hcc/bin/..
 "/opt/rocm/hcc/bin/clang-7" -cc1 -D__KALMAR_AMP__=1 -D__HCC_AMP__=1 -triple aarch64-unknown-linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hip_memory-c47ff2.s.bc -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file /root/ROCm/HIP/build/CMakeFiles/hip_hcc_static.dir/src/hip_memory.cpp.gcno -resource-dir /opt/rocm/hcc/lib/clang/7.0.0 -O3 -fdebug-compilation-dir /root/ROCm/HIP/build -ferror-limit 19 -fmessage-length 201 -fno-signed-char -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -famp -o CMakeFiles/hip_hcc_static.dir/src/hip_memory.cpp.o -x ir /tmp/hip_memory-c47ff2.s.bc
clang -cc1 version 7.0.0 based upon HCC 1.2.18262-a743e2b-05eee4e-b25febc  default target aarch64-unknown-linux-gnu
**fatal error: error in backend: Unsupported calling convention.
clang-7: error: clang frontend command failed with exit code 70 (use -v to see invocation)**
HCC clang version 7.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 05eee4ea8aedc4a168d11fbbf5095646702f83f2) (https://github.com/RadeonOpenCompute/llvm.git b25febceadb1ffabf9cd9bc0fd41e3cb8d4e9b80) (based on HCC 1.2.18262-a743e2b-05eee4e-b25febc )
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
clang-7: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-7: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs.
 "/opt/rocm/hcc/bin/clang-7" -cc1 -D__KALMAR_HC__=1 -D__HCC_HC__=1 -famp-is-device -fno-builtin -fno-common -O2 -triple amdgcn--amdhsa-hcc -aux-triple aarch64-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -main-file-name hip_memory.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fmath-errno -no-integrated-as -mconstructor-aliases -fuse-init-array -v -coverage-notes-file /root/ROCm/HIP/build/CMakeFiles/hip_hcc_static.dir/src/hip_memory.cpp.gcno -resource-dir /opt/rocm/hcc/lib/clang/7.0.0 -I/opt/rocm/hcc/bin/../include -I/opt/rocm/hcc/bin/../hcc/include -I /root/ROCm/HIP/include -I /root/ROCm/HIP/tests/src -D HIP_VERSION_MAJOR=1 -D HIP_VERSION_MINOR=5 -D HIP_VERSION_PATCH=18231 -I /opt/rocm/hcc/include -I /opt/rocm/include -I /opt/hsa-rocr-dev/hsa/include -D NDEBUG -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0 -internal-isystem /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward -internal-isystem /usr/local/include -internal-isystem /opt/rocm/hcc/lib/clang/7.0.0/include -internal-externc-isystem /usr/include/aarch64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -std=c++amp -fdeprecated-macro -fno-dwarf-directory-asm -fdebug-compilation-dir /root/ROCm/HIP/build -ferror-limit 19 -fmessage-length 201 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -famp -fhsa-ext -o /tmp/hip_memory-63c386.s -x hc-kernel /root/ROCm/HIP/src/hip_memory.cpp -emit-llvm-bc
clang -cc1 version 7.0.0 based upon HCC 1.2.18262-a743e2b-05eee4e-b25febc  default target aarch64-unknown-linux-gnu
ignoring nonexistent directory "/opt/rocm/hcc/bin/../hcc/include"
ignoring nonexistent directory "/include"
ignoring duplicate directory "/opt/rocm/hcc/bin/../include"
ignoring duplicate directory "/usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0"
ignoring duplicate directory "/usr/local/include"
ignoring duplicate directory "/opt/rocm/hcc/lib/clang/7.0.0/include"
ignoring duplicate directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/rocm/hcc/bin/../include
 /root/ROCm/HIP/include
 /root/ROCm/HIP/tests/src
 /opt/rocm/include
 /opt/hsa-rocr-dev/hsa/include
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/aarch64-linux-gnu/c++/5.4.0
 /usr/lib/gcc/aarch64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/backward
 /usr/local/include
 /opt/rocm/hcc/lib/clang/7.0.0/include
 /usr/include/aarch64-linux-gnu
 /usr/include
End of search list.
 "/opt/rocm/hcc/bin/hc-kernel-assemble" /tmp/hip_memory-63c386.s CMakeFiles/hip_hcc_static.dir/src/hip_memory.cpp.o
clang-7: error: HC host assembler command failed with exit code 70 (use -v to see invocation)
HCC clang version 7.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 05eee4ea8aedc4a168d11fbbf5095646702f83f2) (https://github.com/RadeonOpenCompute/llvm.git b25febceadb1ffabf9cd9bc0fd41e3cb8d4e9b80) (based on HCC 1.2.18262-a743e2b-05eee4e-b25febc )
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
clang-7: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-7: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-7: note: diagnostic msg: /tmp/hip_memory-e63b3d.cpp
clang-7: note: diagnostic msg: /tmp/hip_memory-89a395.cpp
clang-7: note: diagnostic msg: /tmp/hip_memory-e63b3d.sh
clang-7: note: diagnostic msg: 

********************
CMakeFiles/hip_hcc_static.dir/build.make:230: recipe for target 'CMakeFiles/hip_hcc_static.dir/src/hip_memory.cpp.o' failed
make[2]: *** [CMakeFiles/hip_hcc_static.dir/src/hip_memory.cpp.o] Error 70
CMakeFiles/Makefile2:3354: recipe for target 'CMakeFiles/hip_hcc_static.dir/all' failed
make[1]: *** [CMakeFiles/hip_hcc_static.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mangupta** [comment]
@wormwang Thanks for the bug report. I have noted down the logs. However as mentioned earlier, the ROCm stack does not support ARM/ARM64 as of today. Also I am not aware of any plans to support this architecture in the short term. Keep an eye on https://github.com/RadeonOpenCompute/ROCm for any updates on supported platforms.
