### ISSUE TITLE
The hc::accelerate_view hangs when using device #0.

### ISSUE THREAD

**Issue by Jorghi12** [ROCm-Developer-Tools/HIP#602]
I've noticed hangs on these calls [hc::accelerator_view::wait](https://github.com/ROCm-Developer-Tools/HIP/blob/7311b602200438d90c9c9ab30f19a57b756f02f0/src/hip_hcc.cpp#L421) and [hc::accelerator_view::copy_ext](https://github.com/ROCm-Developer-Tools/HIP/blob/7311b602200438d90c9c9ab30f19a57b756f02f0/src/hip_hcc.cpp#L2273).

**Trace showing hang on the hc::accelerator_view::copy_ext:**
![image](https://user-images.githubusercontent.com/8586039/43301779-2a8f41cc-9135-11e8-9a91-6119c1aed13b.png)

The hangs **only** occur when I execute kernel launches and memory copies using GPU device 0. If I use a GPU with any other number (1, 2, 3), then the hang disappears. I've eliminated the possibility of this being a hardware issue since this occurs for whichever device has position 0.

After reading the source code for the hc::accelerator class, the hangs occur due to blocking, which implies that there are other commands that have been submitted to the accelerator that haven't yet finished. 

Perhaps this is a deadlock?

Docker Image:
https://hub.docker.com/r/jorgdoku123/pytorch_hang_repro/

**Reproduction steps:**
```
import torch
src = torch.FloatTensor([1,2,3,4]).cuda(0)
dst = torch.LongTensor([[0]]).cuda(0)
torch.take(src,dst)
```

**Comment by gargrahul** [comment]
@Jorghi12 Could you please try with #601 ?

**Comment by Jorghi12** [comment]
@gargrahul Hi, I'll give it a try right now.

**Comment by Jorghi12** [comment]
@gargrahul Hi, this doesn't appear to solve the issue at hand. hipMemcpyAsync is still waiting an indefinite amount of time to acquire the lock.

**Comment by gargrahul** [comment]
@Jorghi12 Thanks for testing. Could you please help me understand the test in details? Is it possible to have simpler HIP sample for this? What are the steps? Does your test use hipHostMalloc?

**Comment by Jorghi12** [comment]
@gargrahul Hi, I'll respond with the sequence of HIP calls that resulted in this error in a moment. I'm extracting them from the framework.
