### ISSUE TITLE
TensorFlow public benchmark fails to run with HIP July 13, 2018 and onward commit

### ISSUE THREAD

**Issue by perflab1** [ROCm-Developer-Tools/HIP#604]
TensorFlow CNN public benchmarks fail to run with HIP July 13, 2018 commit and onwards. @sunway513 has been able to reproduce the issue on his system and currently looking into it. 

**Comments from Bill's investigation**
HIP July 17 update causes tensorflow public benchmark failed:
 
 
 
root@970669213a54:~/benchmarks/scripts/tf_cnn_benchmarks# python tf_cnn_benchmarks.py --model=resnet50
TensorFlow:  1.9
Model:       resnet50
Dataset:     imagenet (synthetic)
Mode:        training
SingleSess:  False
Batch size:  64 global
             64 per device
Num batches: 100
Num epochs:  0.00
Devices:     ['/gpu:0']
Data format: NCHW
Layout optimizer: False
Optimizer:   sgd
Variables:   parameter_server
==========
Generating model
W0723 22:16:52.685952 140437112125184 tf_logging.py:125] From /root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:1608: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-07-23 22:16:53.173561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1500] Found device 0 with properties: 
name: Device 6863
AMDGPU ISA: gfx900
memoryClockRate (GHz) 1.6
pciBusID 0000:03:00.0
Total memory: 15.98GiB
Free memory: 15.73GiB
2018-07-23 22:16:53.173599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1611] Adding visible gpu devices: 0
2018-07-23 22:16:53.173625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1031] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-23 22:16:53.173640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1037]      0 
2018-07-23 22:16:53.173652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1050] 0:   N 
2018-07-23 22:16:53.173693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1168] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15306 MB memory) -> physical GPU (device: 0, name: Device 6863, pci bus id: 0000:03:00.0)
2018-07-23 22:16:53.192168: E tensorflow/core/common_runtime/gpu/gpu_device.cc:264] Illegal GPUOptions.experimental.num_dev_to_dev_copy_streams=0 set to 1 instead.
terminate called after throwing an instance of 'std::runtime_error'
  what():  No device code available for function: _ZN10tensorflow7functor28FillPhiloxRandomKernelLaunchINS_6random19UniformDistributionINS2_12PhiloxRandomEfEEEEvS4_PNT_17ResultElementTypeExS6_
Aborted (core dumped)
 
 
 
 
 
Last successfully run is on the following HIP version (July 12):
HIP version is:
Package Name: HIP
commit hash: 06f4579c3a9c252c0bf9c874b3bd0a7816edda36
Author: Maneesh Gupta <maneesh.gupta@amd.com>
Full Time: Thu Jul 12 07:49:41 2018 +0530
Date: Jul 12, 2018
Epoch time: 1531361981
 
 
 
The failed HIP packages is after 7/17/2018 including (7/17 and 7/19)
HIP version is:
Package Name: HIP
commit hash: 502ce06dda9f949c4fc3efb0323b42a5820fa058
Author: Maneesh Gupta <maneesh.gupta@amd.com>
Full Time: Tue Jul 17 13:20:24 2018 +0530
Date: Jul 17, 2018
Epoch time: 1531813824
 
 
The rest of packages versions are kept same, no change:
 
Package Name: hcc
commit hash: ea039a8a500b506d738b112b74028b61a7a895a5
-Subproject e2bf492f56c5b41acfe836f4686fa4291b449145
+Subproject e80a5a861041225bd14933fdf0b61120466c9319
Author: David Salinas <dsalinas@amd.com>
Full Time: Fri Jul 13 16:37:38 2018 -0400
Date: Jul 13, 2018
Epoch time: 1531514258
 
Package Name: rocm-cmake
commit hash: ec7313aa43de72729c8f66b2e53155e03aa74e20
Author: Paul <pfultz2@yahoo.com>
Full Time: Mon Apr 23 17:13:10 2018 -0500
Date: Apr 23, 2018
Epoch time: 1524521590
 
 
Package Name: MIOpenGEMM
commit hash: 9547fb9e8499a5a9f16da83b1e6b749de82dd9fb
Author: Mayank Daga <mayank.daga@amd.com>
Full Time: Tue Apr 3 18:55:27 2018 -0500
Date: Apr 3, 2018
Epoch time: 1522799727
 
 
Package Name: MLOpen
commit hash: be15592ccfe911423eba30d4a08a30de4b09f898
Author: Daniel Lowell <daniel.lowell@amd.com>
Full Time: Wed May 23 09:53:21 2018 -0500
Date: May 23, 2018
Epoch time: 1527087201
 
 
Package Name: rocRAND
commit hash: 1890bb31675a6cbaa7766e947c8e35c4d1010ad6
Author: bragadeesh <bragadeesh@users.noreply.github.com>
Full Time: Tue Feb 13 09:42:27 2018 -0800
Date: Feb 13, 2018
Epoch time: 1518543747
 
 
Package Name: rocBLAS
commit hash: 227d37330e8dc65ca9eb20e95d5ca8aa3fdc06af
Author: zaliu <35415350+zaliu@users.noreply.github.com>
Full Time: Tue May 22 15:37:14 2018 -0700
Date: May 22, 2018
Epoch time: 1527028634
 
 
Package Name: hipBLAS
commit hash: ac512bf8483362d78d0d20e51acc1f378e484e1c
Author: zaliu <35415350+zaliu@users.noreply.github.com>
Full Time: Tue May 22 18:37:28 2018 -0700
Date: May 22, 2018
Epoch time: 1527039448
 
 
Package Name: rocFFT
commit hash: 002be49e6e31e7e08e867f1c0f02662716f1884d
Author: bragadeesh <bragadeesh@users.noreply.github.com>
Full Time: Wed May 23 11:19:04 2018 -0700
Date: May 23, 2018
Epoch time: 1527099544
 
 
Package Name: tensorflow
commit hash: b820d65c35a70a4d187ef158b9b7659e79f73b06
Author: Deven Desai <36858332+deven-amd@users.noreply.github.com>
Full Time: Mon Jul 9 12:02:45 2018 -0400
Date: Jul 9, 2018
Epoch time: 1531152165

**Comment by sunway513** [comment]
Verified the issue was caused by PR#515, I'll create a JIRA ticket and let's move there for solutions.
