### ISSUE TITLE
Support for unified CUDA/ROCM support in same executable/binary..

### ISSUE THREAD

**Issue by oscarbg** [ROCm-Developer-Tools/HIP#627]
Hi,
HIP compiler is great but could be better if had some invocation flags that generate both compiled CUDA kernels/CUDA runtime calls and also ROCM kernels/ROCM/HSA runtime calls and that executable at runtime selects platform (CUDA or ROCM) upon platform avaiability.. this will be better for Windows assuming HIP for Windows is coming soon. (this year)..
would love to have CUDA code compiled with HIP to a Windows exe file that runs on CUDA or AMD GPUs on Windows depending on user GPU..
thanks..

**Comment by mangupta** [comment]
HIP selects between CUDA or ROCM path at compile time. It is not possible to have a single binary that contains both CUDA runtime+kernels as well as ROCM runtime+kernels. There would be other non-technical implications in doing that. So it would probably never happen.
