### ISSUE TITLE
hipInfo showed L2cache size equal to zero

### ISSUE THREAD

**Issue by J0hnn4J1ang** [ROCm-Developer-Tools/HIP#628]
Not only /opt/rocm/hip/bin/hipInfo showed L2 cache size is 0, but also below hip code. My amd card is Radeon RX 570
`int l2cachesize = -1;
hipDeviceGetAttribute(&l2cachesize, hipDeviceAttibuteL2CacheSize, 0);`

//below is hipinfo output.
--------------------------------------------------------------------------------
device#                           1
Name:                             Ellesmere [Radeon RX 470/480]
pciBusID:                         2
pciDeviceID:                      0
multiProcessorCount:              32
maxThreadsPerMultiProcessor:      2560
isMultiGpuBoard:                  1
clockRate:                        1130 Mhz
memoryClockRate:                  2000 Mhz
memoryBusWidth:                   256
clockInstructionRate:             1000 Mhz
totalGlobalMem:                   4.00 GB
maxSharedMemoryPerMultiProcessor: 4.00 GB
totalConstMem:                    16384
sharedMemPerBlock:                64.00 KB
regsPerBlock:                     0
warpSize:                         64
l2CacheSize:                      0

**Comment by SarbojitAMD** [comment]
HIP runtime queries L2Cach information from Rocr which is not generating the information hence hip is helpless :). Closing this as 'Will not fix'
