### ISSUE TITLE
Warning that "__HIPCC__" has been redefined.

### ISSUE THREAD

**Issue by tdd11235813** [ROCm-Developer-Tools/HIP#632]
During compilation process on travis/CI (HIP platform=nvcc 8.0), redefine warning occurs.
```
/home/travis/hip/include/hip/hip_common.h:37:0: warning: "__HIPCC__" redefined
 #define __HIPCC__
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from /home/travis/hip/include/hip/hip_runtime.h:53:0,
```
This could be resolved in `hip_common.h` by an ifdef guard:
```C
#ifndef __HIPCC__
  #define __HIPCC__
#endif
```

**Comment by mangupta** [comment]
That is strange. The only place HIP defines __HIPCC__ is in ```include/hip/hip_common.h```. So you should not see a redefinition unless you are manually defining it someplace. Do you see this issue when building some application that uses HIP or when building HIP itself?

**Comment by tdd11235813** [comment]
It was my fault, sorry. I thought I already had checked my sources, where I did not find any such definition, but obviously I did not right :( Sorry for that issue.

**Comment by tdd11235813** [comment]
PS: cmake adds a definition of `__CUDACC__` and `NVCC` to nvcc (=> `nvcc -M -D__CUDACC__ -DNVCC ...`), so the host compiler called by nvcc also sees `__CUDACC__`. 
This cmake behavior could be mentioned in [the porting guide](https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/hip_porting_guide.md) about `__CUDACC__`.

CMake source: See [cmake's run_nvcc.cmake here](https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA/run_nvcc.cmake#L192) and [here](https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA/run_nvcc.cmake#L206):

```cmake
# nvcc doesn't define __CUDACC__ for some reason when generating dependency files.  This
# can cause incorrect dependencies when #including files based on this macro which is
# defined in the generating passes of nvcc invokation.  We will go ahead and manually
# define this for now until a future version fixes this bug.
set(CUDACC_DEFINE -D__CUDACC__)
```

To get the same behavior, I had defined `__HIPCC__` in cmake manually as well, so I could distinguish between host compiler called by HIP(nvcc) and host compiler which is not called by HIP(nvcc).
That's where I got the redefine errors with HIP. However, I can use any different name for such a macro, so no need to use `__HIPCC__`.
