### ISSUE TITLE
Is it possible to use clang has the HIP_COMPILER without hcc?

### ISSUE THREAD

**Issue by tstellar** [ROCm-Developer-Tools/HIP#643]
I'm trying to configure hip to use clang as the HIP_COMPILER, but cmake is still requiring that I have hcc installed.  Is it possible to use hip without hcc?  Below is my cmake invocation:

cmake .. \
        -DHSA_PATH=/usr/ \
        -DHIP_COMPILER=clang \
        -DCMAKE_INSTALL_PREFIX=/usr

**Comment by tstellar** [comment]
I'm using the hip-clang branch.

**Comment by yxsamliu** [comment]
usign cmake with -DHIP_COMPILER=clang will build a HIP runtime which can be used by hip-clang to build other HIP package. However the HIP runtime itself still needs to be built by HCC since the HIP runtime source code uses HCC runtime API's.

**Comment by SarbojitAMD** [comment]
@tstellar, you can refer the link https://github.com/ROCm-Developer-Tools/HIP/blob/master/INSTALL.md#hip-clang in order to configure hip-clang as the default compiler for hip code.

Feel free to open a ticket in case you have any further queries.
