### ISSUE TITLE
hipResourceDesc.res.linear.sizeInBytes is passed to HSA incorreclty

### ISSUE THREAD

**Issue by ex-rzr** [ROCm-Developer-Tools/HIP#671]
https://github.com/ROCm-Developer-Tools/HIP/blob/master/src/hip_texture.cpp#L266

According to HSA specification, width is "Width of the image, in components", not in bytes:
http://www.hsafoundation.com/html/Content/Runtime/Topics/03_Extensions/hsa_ext_image_descriptor_t.htm

**Comment by gargrahul** [comment]
@ex-rzr Thanks for reporting this issue. I will fix and update the PR here.
