### ISSUE TITLE
Directed tests fail in Nvidia

### ISSUE THREAD

**Issue by pradeepisro** [ROCm-Developer-Tools/HIP#673]
This is the error log that I get while building HIP in nvidia.	

    [  3%] Building HIPCC object CMakeFiles/directed_tests.deviceLib.hipTestIncludeMath.dir/tests/src/deviceLib/directed_tests.deviceLib.hipTestIncludeMath_generated_hipTestIncludeMath.cpp.o
	[HIP Source]/tests/src/deviceLib/hipTestIncludeMath.cpp:52:2: error: #error "__HIP_ARCH_HAS_WARP_FUNNEL_SHIFT__ or __HIP_ARCH_HAS_DYNAMIC_PARALLEL__ not defined"
	 #error                                                                         \
	  ^
	CMake Error at /opt/rocm/hip/cmake/FindHIP/run_make2cmake.cmake:18 (file):
	  file failed to open for reading (No such file or directory):

	    [HIP Source]/build/CMakeFiles/directed_tests.deviceLib.hipTestIncludeMath.dir/tests/src/deviceLib/directed_tests.deviceLib.hipTestIncludeMath_generated_hipTestIncludeMath.cpp.o.depend.pre

	CMake Error at directed_tests.deviceLib.hipTestIncludeMath_generated_hipTestIncludeMath.cpp.o.cmake:134 (message):
	  Error generating
	  [HIP Source]/build/CMakeFiles/directed_tests.deviceLib.hipTestIncludeMath.dir/tests/src/deviceLib/./directed_tests.deviceLib.hipTestIncludeMath_generated_hipTestIncludeMath.cpp.o

	CMakeFiles/directed_tests.deviceLib.hipTestIncludeMath.dir/build.make:63: recipe for target 'CMakeFiles/directed_tests.deviceLib.hipTestIncludeMath.dir/tests/src/deviceLib/directed_tests.deviceLib.hipTestIncludeMath_generated_hipTestIncludeMath.cpp.o' failed
	make[3]: *** [CMakeFiles/directed_tests.deviceLib.hipTestIncludeMath.dir/tests/src/deviceLib/directed_tests.deviceLib.hipTestIncludeMath_generated_hipTestIncludeMath.cpp.o] Error 1
	CMakeFiles/Makefile2:1118: recipe for target 'CMakeFiles/directed_tests.deviceLib.hipTestIncludeMath.dir/all' failed
	make[2]: *** [CMakeFiles/directed_tests.deviceLib.hipTestIncludeMath.dir/all] Error 2
	CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/build_tests.dir/rule' failed
	make[1]: *** [CMakeFiles/build_tests.dir/rule] Error 2
	Makefile:173: recipe for target 'build_tests' failed
	make: *** [build_tests] Error 2

**Comment by mangupta** [comment]
Known issue. There are about 4 tests that are broken. Fix was incoming in another half hour.

**Comment by pradeepisro** [comment]
is the issue due to `__KALMAR_ACCELERATOR__` being not defined?
