### ISSUE TITLE
install.sh: 'rename' is not installed by default on ubuntu

### ISSUE THREAD

**Issue by VincentSC** [ROCm-Developer-Tools/HIP#675]
So a small change is needed in install.sh, line 28:

-    sudo apt-get install dpkg-dev rpm doxygen libelf-dev
+   sudo apt-get install dpkg-dev rpm doxygen libelf-dev rename

**Comment by mangupta** [comment]
Thanks for submitting the patch. Closing this since the PR has been merged.
