### ISSUE TITLE
Should ihipMemset return hipSuccess if sizeBytes=0x0?

### ISSUE THREAD

**Issue by jithunnair-amd** [ROCm-Developer-Tools/HIP#680]
Similar to how it's handled in hipMemCpy: https://github.com/ROCm-Developer-Tools/HIP/blob/7ae8a997ca40fc697d1d206836130cd52f4660d1/src/hip_memory.cpp#L1139

**Comment by jithunnair-amd** [comment]
@mangupta @gargrahul

**Comment by gargrahul** [comment]
@jithunnair-amd yes possible. Need to check if cudaMemset returns success when sizeBytes=0x0.

**Comment by jithunnair-amd** [comment]
Checking if there's any plan to fix this. This will help us with some pytorch unit tests.

**Comment by gargrahul** [comment]
@jithunnair-amd What return value are you getting when calling hipMemset with sizeBytes =0? I see it returns hipSuccess already and this behavior is similar to cudaMemset.

**Comment by jithunnair-amd** [comment]
Thanks!

**Comment by jithunnair-amd** [comment]
I'll close it once I can verify with my failing unit test.

**Comment by mangupta** [comment]
This has been fixed for a long time. Assuming that the issue is resolved. @jithunnair-amd In case that isn't so, please reopen the issue.
