### ISSUE TITLE
hipify-clang doc out of data

### ISSUE THREAD

**Issue by yuq** [ROCm-Developer-Tools/HIP#693]
Seems I can't get hipify-clang work by referencing the doc here:
https://github.com/ROCm-Developer-Tools/HIP/blob/master/hipify-clang/README.md

> opt/rocm/hip/bin/hipify-clang memory.cu -x cuda --cuda-path=/usr/local/cuda
> LLVM ERROR: CommonOptionsParser: failed to parse command-line arguments. [CommonOptionsParser]: hipify-clang: Unknown command line argument '-x'.  Try: '/opt/rocm/hip/bin/hipify-clang -help'
> hipify-clang: Did you mean '-o'?
> hipify-clang: Unknown command line argument '--cuda-path=/usr/local/cuda'.  Try: '/opt/rocm/hip/bin/hipify-clang -help'
> hipify-clang: Did you mean '-extra-arg=/usr/local/cuda'?

> /opt/rocm/hip/bin/hipify-clang memory.cu
> Error while trying to load a compilation database:
> Could not auto-detect compilation database for file "memory.cu"
> No compilation database found in /rocm/nwchem/src/tce/ccsd_t or any parent directory
> fixed-compilation-database: Error while opening fixed database: No such file or directory
> json-compilation-database: Error while opening JSON database: No such file or directory
> Running without flags.
> warning: /rocm/nwchem/src/tce/ccsd_t/memory.cu.hipify-tmp: 'linker' input unused [-Wunused-command-line-argument]
> warning: argument unused during compilation: '-std=c++11' [-Wunused-command-line-argument]
> error: unable to handle compilation, expected exactly one compiler job in ''
> Error while processing /rocm/nwchem/src/tce/ccsd_t/memory.cu.hipify-tmp.

Do we use hipify-perl or hipify-clang nowadays?

**Comment by MichaelLettrich** [comment]
In case you were wondering: You're using the wrong string. 
`opt/rocm/hip/bin/hipify-clang memory.cu -- -x cuda --cuda-path=/usr/local/cuda` instead of 
`opt/rocm/hip/bin/hipify-clang memory.cu -x cuda --cuda-path=/usr/local/cuda` should do the trick.

**Comment by yuq** [comment]
Thanks, my mistake didn't see the "--" separator.
