### ISSUE TITLE
Non-const value for const args of templated kernel needs explicit templating

### ISSUE THREAD

**Issue by jithunnair-amd** [ROCm-Developer-Tools/HIP#718]
The following code:

```
#include "hip/hip_runtime.h"

template <typename scalar_t>
__global__ void constKernel(const scalar_t* i) {
  // Nothing
}

int main() {
  int* i;
  hipMalloc(&i, sizeof(int));
  hipLaunchKernelGGL(constKernel, 1, 1, 0, 0, i);

  return 0;
}
```

gives the error:
```
super_simple_const_bug.cu:11:3: error: no matching function for call to 'hipLaunchKernelGGL'
  hipLaunchKernelGGL(constKernel, 1, 1, 0, 0, i);
  ^~~~~~~~~~~~~~~~~~
/opt/rocm/include/hip/hcc_detail/functional_grid_launch.hpp:111:13: note: candidate function [with Args = <int *>, F = void (*)(int *)] not viable: no
      overload of 'constKernel' matching 'void (*)(int *)' for 1st argument
inline void hipLaunchKernelGGL(F kernel, const dim3& numBlocks, const dim3& dimBlocks,
            ^
1 error generated.
```

But if I explicitly specify the templating type as int ie. `constKernel<int>`, it compiles fine.

**Comment by ex-rzr** [comment]
Another way is to pass the parameter with `const` explicitly:

```cpp
hipLaunchKernelGGL(constKernel, 1, 1, 0, 0, const_cast<const int *>(i));
```

(I'm not sure this will work in this case, but works in similar cases).

But I agree, it's annoying sometimes. It'd be great if `hipLaunchKernelGGL` accepted such parameters without additional work.

**Comment by mangupta** [comment]
Implicit typecasting is not supported by the underlying compiler i.e. hcc. So you need to explicitly specify template types or explicitly typecast as necessary. This is not something that can be fixed in hip. Hence closing this issue.
