### ISSUE TITLE
[HIPIFY] Segfault while hipifying any CUDA source, when hipify-clang is linked with LLVM+Clang libs starting from 7.0.0

### ISSUE THREAD

**Issue by kneternal** [ROCm-Developer-Tools/HIP#725]
This snippet of axpy.cu code is from [Compiling CUDA with clang](https://llvm.org/docs/CompileCudaWithLLVM.html) This code is verified that it can be successfully compiled by clang using:

`clang++ axpy.cu -o axpy --cuda-gpu-arch=<GPU arch> -L<CUDA install path>/<lib64 or lib> -lcudart_static -ldl -lrt -pthread`

I have tried to do:

`hipify-clang square.cu --
  -x cuda
  --cuda-path=/opt/cuda
  --cuda-gpu-arch=sm_30
  -isystem /opt/cuda/samples/common/inc
  -I /opt/cuda/cuDNN` and get a **segfault** from there

Then I tried to do the conversion by using the clang command I used in clang standalone compilation but stil got an error of: 
> Error while processing /home/kneternal/Work/test/clang_test/axpy.cu.hipify-tmp.

My version of LLVM+Clang is 7.0.0 and they are built and installed from source. Could I get some help about this?

**Comment by emankov** [comment]
Please provide Linux, its version and CUDA version installed.

**Comment by emankov** [comment]
Verified on Ubuntu 16.04 with LLVM 7.0.0 release built from sources and CUDA 8.0:

```
emankov@spb-hlc-fiji1h:~/git/HIP/hipify-clang/build$ ./hipify-clang ../../tests/hipify-clang/square.cu -- -x cuda --cuda-path=/usr/local/cuda-8.0 --cuda-gpu-arch=sm_30 -isystem /usr/local/cuda-8.0/samples/common/inc
#0 0x000000000140375a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x140375a)
#1 0x0000000001401c4c llvm::sys::RunSignalHandlers() (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x1401c4c)
#2 0x0000000001401db7 SignalHandler(int) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x1401db7)
#3 0x00007f5cad788390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#4 0x0000000000656118 clang::ast_matchers::MatchFinder::MatchFinder(clang::ast_matchers::MatchFinder::MatchFinderOptions) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x656118)
#5 0x000000000064c355 HipifyAction::CreateASTConsumer(clang::CompilerInstance&, llvm::StringRef) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x64c355)
#6 0x000000000067b4e6 clang::FrontendAction::CreateWrappedASTConsumer(clang::CompilerInstance&, llvm::StringRef) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x67b4e6)
#7 0x00000000006822b3 clang::FrontendAction::BeginSourceFile(clang::CompilerInstance&, clang::FrontendInputFile const&) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x6822b3)
#8 0x00000000006a85b6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x6a85b6)
#9 0x00000000007687e4 clang::tooling::FrontendActionFactory::runInvocation(std::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x7687e4)
#10 0x000000000076326f clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::shared_ptr<clang::CompilerInvocation>, std::shared_ptr<clang::PCHContainerOperations>) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x76326f)
#11 0x000000000076558b clang::tooling::ToolInvocation::run() (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x76558b)
#12 0x000000000076737e clang::tooling::ClangTool::run(clang::tooling::ToolAction*) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x76737e)
#13 0x0000000000761b4c clang::tooling::RefactoringTool::runAndSave(clang::tooling::FrontendActionFactory*) (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x761b4c)
#14 0x00000000006450d8 main (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x6450d8)
#15 0x00007f5cac2dd830 __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:325:0
#16 0x0000000000644329 _start (/home/emankov/git/HIP/hipify-clang/build/hipify-clang+0x644329)
Segmentation fault (core dumped)

```

**Comment by emankov** [comment]
Verified on Ubuntu 16.04 with LLVM 6.0.1 release built from sources and CUDA 8.0:

No segfault. Hipification is correct.

Conclusion: Bug appeared with LLVM+Clang 7.0.0.

**Comment by emankov** [comment]
This is a six months old clang bug: [https://bugs.llvm.org/show_bug.cgi?id=36384](https://bugs.llvm.org/show_bug.cgi?id=36384).
It is not related to hipify-clang internals. Please use the previous (6.0.x) releases of LLVM+Clang for hipification, they work fine.

**Comment by kneternal** [comment]
> This is a six months old clang bug: https://bugs.llvm.org/show_bug.cgi?id=36384 "MatchFinder constructor causes segfault".
> It is not related to hipify-clang internals. Please use the previous (6.0.x) releases of LLVM+Clang for hipification, they work fine.

Thank you so much for help. It is working now using LLVM6.0.1

**Comment by kneternal** [comment]
Maybe it is good to give a note in the installation guide to tell people not to use 7.0.0 for now

**Comment by emankov** [comment]
Readme is updated: https://github.com/ROCm-Developer-Tools/HIP/pull/729

**Comment by emankov** [comment]
Is still reproduced on LLVM trunk (8.0). Going to fix or workaround as the bug is a serious showstopper for hipify-clang.

**Comment by emankov** [comment]
The segfault is not observable on the trunk [3d28a4490ff9cefedd3597c6ac3e14e523e6e13].
The segfault is not observable on clang 8.0.0 release.

Clang bug [36384](https://bugs.llvm.org/show_bug.cgi?id=36384) is closed.

Readme is updated: #1011: latest stable release for Linux is clang 8.0.0, which supports CUDA up to 10.0.
