### ISSUE TITLE
hipify-clang introducing non-ASCII characters

### ISSUE THREAD

**Issue by MichaelLettrich** [ROCm-Developer-Tools/HIP#739]
- OS Ubuntu 18.04
- `clang version 6.0.1-svn334776-1~exp1~20181018152737.116 (branches/release_60)` from official llvm repos
- CUDA 9.0 Patch 4
- HIP: hip_nvcc from repos 
- since HIP does not come with hipify clang, grabed and compiled
hipify-clang built from commit 25aae88fd5029a5952524d617934e71194702b9c

reproduce by compiling square sample:
`hipify-clang square.cu -- -x cuda --cuda-gpu-arch=sm_50 -L/usr/local/cuda/lib64 -lcudart_static -ldl -lrt -pthread -I/opt/rocm/include`
will terminate without problems. Looking inside, I get
`#include <hip/hipn^D^@^@^P^@^@^@¸p¥`
[square.cu.hip.txt](https://github.com/ROCm-Developer-Tools/HIP/files/2529306/square.cu.hip.txt)

Using  `hipconvertinplace.sh` for a multifile project a couple of files were transformed OK while some 
resulted in 
```
/home/milettri/Projects/gemmCUDA/gemmHIP/matmul/../helpers/cudaHelpers.hpp:5:21: warning: null character ignored [-Wnull-character]
#include <hip/hip+<U+0000><U+0000><U+0000><U+0008><U+0000><U+0000><U+0000><A8>U<U+000B>
                                  ^
```

reproduced on two different ubuntu 18.04 machines, one with ubuntu packaged clang, the other with official llvm packages. Building `hipify-clang` from release tag 1.9.1 resulted in the same issues.

**Comment by MichaelLettrich** [comment]
> Update:
> 
> change the target_link_libraries in CMakelist from private to public will solve the non-ascii issue and the conflict.

Cannot confirm this works on my system. Which CMakelist did you modify - the one of hipify-clang?

**Comment by kneternal** [comment]
> @kneternal I ran hipconvertinplace.sh (which uses hipify-clang) with removed includes for
> `#include <cuda_runtime.h>` and ran into the very same problems again. Only after removing `#include <cuda.h>` as well, conversion went smoothly. As of now, this can be seen as a workaround.

Yeap, I am assuming that, all the cuda-related includes will affect hipify-clang.

Sorry for the spam that PUBLIC can be a workaround, I just messed up the run files.

**Comment by MichaelLettrich** [comment]
Can confirm that the fix resolves the bug. Thank you for the quick intervention.
