### ISSUE TITLE
Compilation error for oceanFFT + HIP

### ISSUE THREAD

**Issue by BeamOfLight** [ROCm-Developer-Tools/HIP#75]
Hello! I have compilation error after code hiplification for the sample oceanFFT ( /usr/local/cuda/samples/5_Simulations/oceanFFT ):

../../common/inc/helper_cuda.h:990:81: error: no matching function for call to ‘_cudaGetErrorEnum(hipError_t&)’
                 file, line, static_cast<unsigned int>(result), _cudaGetErrorEnum(result), func);

What am i doing wrong or how fix it manually?

**Comment by whchung** [comment]
@BeamOfLight I assume you use `hipify` tool to convert the sample to HIP. As a first step, could you check if `_cudaGetErrorEnum` with the specified function signature does exist in the HIPified project?

**Comment by BeamOfLight** [comment]
There are some problems in last message - i forgot to convert some headers from ../../common/inc/ directory.
After convertation i have this error:

> ../../common/inc/helper_cuda.h: In instantiation of ‘void check(T, const char*, const char*, int) [with T = cudaError]’:
> ../../common/inc/helper_cuda_gl.h:92:5:   required from here
> ../../common/inc/helper_cuda.h:990:81: error: no matching function for call to ‘_cudaGetErrorEnum(cudaError&)’
>                  file, line, static_cast<unsigned int>(result), _cudaGetErrorEnum(result), func);
>                                                                                  ^
> ../../common/inc/helper_cuda.h:36:21: note: candidate: const char* _cudaGetErrorEnum(hipError_t)
>  static const char * _cudaGetErrorEnum(hipError_t error)
>                      ^
> ../../common/inc/helper_cuda.h:36:21: note:   no known conversion for argument 1 from ‘cudaError’ to ‘hipError_t’
> ../../common/inc/helper_cuda.h:295:20: note: candidate: const char* _cudaGetErrorEnum(CUresult)
>  static const char *_cudaGetErrorEnum(CUresult error)
>                     ^
> ../../common/inc/helper_cuda.h:295:20: note:   no known conversion for argument 1 from ‘cudaError’ to ‘CUresult {aka cudaError_enum}’
> ../../common/inc/helper_cuda.h:524:20: note: candidate: const char* _cudaGetErrorEnum(cufftResult)
>  static const char *_cudaGetErrorEnum(cufftResult error)
>                     ^
> ../../common/inc/helper_cuda.h:524:20: note:   no known conversion for argument 1 from ‘cudaError’ to ‘cufftResult {aka cufftResult_t}’
> Makefile:266: recipe for target 'oceanFFT.o' failed

In header file we have:
```
static const char * _cudaGetErrorEnum(hipError_t error)
static const char *_cudaGetErrorEnum(CUresult error)
static const char *_cudaGetErrorEnum(cublasStatus_t error)
static const char *_cudaGetErrorEnum(cufftResult error)
static const char *_cudaGetErrorEnum(cusparseStatus_t error)
static const char *_cudaGetErrorEnum(cusolverStatus_t error)
static const char *_cudaGetErrorEnum(curandStatus_t error)
static const char *_cudaGetErrorEnum(NppStatus error)
```

P.S. Full header file attached.
[helper_cuda_h.txt](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/files/976571/helper_cuda_h.txt)

**Comment by 7SK** [comment]
Hi @BeamOfLight 
The error is due to cudaGLSetGLDevice() func. We haven’t included it in our Hipify tool because this function is deprecated with CUDA 5.0 and should no longer be used.

For OpenGL Interoperability, HIP doesn't supports the following functions yet:
    cuda2hipRename["cudaGLGetDevices"]                                        = {"hipGLGetDevices", CONV_GL, API_RUNTIME, HIP_UNSUPPORTED};
    cuda2hipRename["cudaGraphicsGLRegisterBuffer"]                 = {"hipGraphicsGLRegisterBuffer", CONV_GL, API_RUNTIME, HIP_UNSUPPORTED};
    cuda2hipRename["cudaGraphicsGLRegisterImage"]                 = {"hipGraphicsGLRegisterImage", CONV_GL, API_RUNTIME, HIP_UNSUPPORTED};
    cuda2hipRename["cudaWGLGetDevice"]                                      = {"hipWGLGetDevice", CONV_GL, API_RUNTIME, HIP_UNSUPPORTED};

Thanks
