### ISSUE TITLE
struct alignment

### ISSUE THREAD

**Issue by leimingyu** [ROCm-Developer-Tools/HIP#768]
Hello,

   I have a data structure in my header files, which looks like below.
```cpp
typedef struct __align__(16) MCXDir {
float x;
float y;
float z;
float w;
} MCXdir;
```
   When I used hipcc to convert the source code, it reported an error shown below.
```bash
...
error: expected unqualified-id
...
```
   Is memory alignment with struct  supported in HIP?

**Comment by yxsamliu** [comment]
can you try alignas https://en.cppreference.com/w/cpp/language/alignas

**Comment by fangq** [comment]
my student @3upperm2n and I are trying to convert an open source cuda code (mcx) to run on rocm.

the source code of mcx is available https://github.com/fangq/mcx. I just tried the below commands and hipexamine.sh gave me tons of errors, for many of them I don't see any issue with my source code, so I suspect we probably did not use hipify correctly (or the toolchain is still not mature enough to handle regular C/CUDA codes). here are the commands to reproduce

```
git clone https://github.com/fangq/mcx.git
cd mcx
git checkout etherdome
hipexamine.sh  src
```
there are many errors printed, such as

```
mcx_core.cu.hipify-tmp:2106:105: error: no matching function for call to 'max'
mcx_core.cu.hipify-tmp:1928:29: error: no matching function for call to 'min'
mcx_core.cu.hipify-tmp:1754:15: error: use of undeclared identifier 'time'
xoroshiro128p_rand.cu.hipify-tmp:127:36: error: use of undeclared identifier 'EPS'

```
however, EPS macro is defined in mcx_utils.h, I don't understand why hipify can not handle this.

can someone take a look and let me know if I used these tools correctly? or I missed some setup steps?

thanks

**Comment by mangupta** [comment]
@fanq Did you build hipify-clang? hipexamine.sh makes use of [hipify-clang](https://github.com/ROCm-Developer-Tools/HIP/tree/master/hipify-clang). In case you haven't try using hipexamine-perl.sh instead which makes use of hipify-perl.

**Comment by 3upperm2n** [comment]
@yxsamliu thanks.

**Comment by 3upperm2n** [comment]
@mangupta Thanks for the reply. We build HIP from source. 
I tested hipexamine-perl.sh, which genereats a short summary log compared to the hipexamine.sh which generetes a detailed log with specific files and line numbers of the errors.

```bash
info: converted 10 CUDA->HIP refs( dev:2 mem:0 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:8 err:0 def:0 tex:0 extern_shared:0 other:0 ) warn:0 LOC:216 in 'src/tictoc.c'
  warning: src/br2cu.h:#39 : #define streamRead(a,b)  {size_t sy;cudaGetSymbolSize(&sy,b);printf("ss %d\n",sy);hipMemcpy(a, b[0], sy, \
  warning: src/br2cu.h:#41 : #define streamWrite(a,b) {size_t sy;cudaGetSymbolSize(&sy,a);printf("ss %d\n",sy);hipMemcpy(b[0], a, sy, \
info: converted 4 CUDA->HIP refs( dev:0 mem:4 kern:0 coord_func:0 math_func:0 special_func:0 stream:0 event:0 err:0 def:0 tex:0 extern_shared:0 other:0 ) warn:2 LOC:54 in 'src/br2cu.h'
  warning: src/mcx_core.cu:#1917 : 	       CUDA_ASSERT(cudaMemcpyFromSymbol(&debugrec, gjumpdebug,sizeof(uint),0,hipMemcpyDeviceToHost));
info: converted 145 CUDA->HIP refs( dev:7 mem:108 kern:17 coord_func:0 math_func:0 special_func:0 stream:0 event:4 err:6 def:0 tex:2 extern_shared:1 other:0 ) warn:1 LOC:2147 in 'src/mcx_core.cu'

info: TOTAL-converted 159 CUDA->HIP refs( dev:9 mem:112 kern:17 coord_func:0 math_func:0 special_func:0 stream:0 event:12 err:6 def:0 tex:2 extern_shared:1 other:0 ) warn:3 LOC:9817
  warning: unconverted cudaGetSymbolSize : 2
  warning: unconverted cudaMemcpyFromSymbol : 1
  kernels (1 total) :   mcx_test_rng(1)
```

**Comment by SarbojitAMD** [comment]
leimingyu, do you still face the issue with struct alignment? If not can we close the issue?

**Comment by SarbojitAMD** [comment]
Closing the issue as no response from the submitter.
