### ISSUE TITLE
How can I dump the GPU assembly code generated with hip?

### ISSUE THREAD

**Issue by x3ccd4828** [ROCm-Developer-Tools/HIP#799]
I am looking for a way to dump the assembly code similar to CodeXL offline compliler for OpenCL, is there such an application?

**Comment by whchung** [comment]
use `KMDUMPISA=1` when you compile your application with `hip`. ISA would be generated at link time.

**Comment by x3ccd4828** [comment]
That worked well. 

Is there a plan in the future to get similar features, as will codexl, where the assembly instructions are highlighted when hovering over the hip code?

**Comment by jlgreathouse** [comment]
We are working to expand the capabilities of the ROCm profiling and analysis tools, but I can't give you a roadmap for when such a feature would be added.

**Comment by mangupta** [comment]
Closing this since the original request has been resolved. Please keep a watch on the [ROCm github page](https://github.com/RadeonOpenCompute/ROCm) where any ROCm platform feature updates would be posted.
