### ISSUE TITLE
can not build hip from source

### ISSUE THREAD

**Issue by tingxingdong** [ROCm-Developer-Tools/HIP#82]
it is rocm-1.5 master branch

/home/tim/HIP/src/device_util.cpp:1219:10: error: call to 'sqrt' is ambiguous
  return hc::fast_math::sqrt(x);
         ^~~~~~~~~~~~~~~~~~~
/opt/rocm/include/kalmar_math.h:654:16: note: candidate function
        __fp16 sqrt(__fp16 x) { return __hc_sqrt_native_half(x); }
               ^
/opt/rocm/include/kalmar_math.h:657:15: note: candidate function
        float sqrt(float x) { return fast_math::sqrtf(x); }
              ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:156:13: note: candidate function
__MATHCALL (sqrt,, (_Mdouble_ __x));
            ^
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/cmath:482:3: note: candidate function
  sqrt(float __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/cmath:486:3: note: candidate function
  sqrt(long double __x)

**Comment by bensander** [comment]
Hip is closely tied to the hcc version.

On May 30, 2017, at 5:16 PM, tingxingdong <notifications@github.com<mailto:notifications@github.com>> wrote:


it is rocm-1.5 master branch

/home/tim/HIP/src/device_util.cpp:1219:10: error: call to 'sqrt' is ambiguous
return hc::fast_math::sqrt(x);
^~~~~~~~~~~~~~~~~~~
/opt/rocm/include/kalmar_math.h:654:16: note: candidate function
__fp16 sqrt(__fp16 x) { return __hc_sqrt_native_half(x); }
^
/opt/rocm/include/kalmar_math.h:657:15: note: candidate function
float sqrt(float x) { return fast_math::sqrtf(x); }
^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:156:13: note: candidate function
__MATHCALL (sqrt,, (Mdouble __x));
^
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/cmath:482:3: note: candidate function
sqrt(float __x)
^
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/cmath:486:3: note: candidate function
sqrt(long double __x)

**Comment by tingxingdong** [comment]
The HCC version 1.0.17230-3c6b5e3-867ee62-d59c075 and 1.0.17215-a2e894b-349ec4f-b684991 both see such problems for both HIP develop-review and master branch.

**Comment by gargrahul** [comment]
Can you change the src/device_util.cpp as follows for quick fix?

__device__ double __hip_fast_dsqrt_rd(double x) {
  //return hc::fast_math::sqrt(x);
  return hc::precise_math::sqrt(x);
}

__device__ double __hip_fast_dsqrt_rn(double x) {
  //return hc::fast_math::sqrt(x);
  return hc::precise_math::sqrt(x);
}

__device__ double __hip_fast_dsqrt_ru(double x) {
  //return hc::fast_math::sqrt(x);
  return hc::precise_math::sqrt(x);
}

__device__ double __hip_fast_dsqrt_rz(double x) {
  //return hc::fast_math::sqrt(x);
  return hc::precise_math::sqrt(x);
}

**Comment by tingxingdong** [comment]
Thank you. I am able to build HIP.  Building HIP (with the new compiler) is just the requirement of building rocBLAS. My main purpose is to test HCC compiler on rocBLAS not HIP functionalities. So the change of src/device_util is sufficient for me. 

Yet, the above hcc does not pass cmake configurations which, I guess, is out of this issue's scope.
