### ISSUE TITLE
Can not find hipify-clang

### ISSUE THREAD

**Issue by holyprince** [ROCm-Developer-Tools/HIP#828]
Recently I try to use the Rocm and HIP on Vega20. I want to port my old cuda project to hip, but when I use $HIP_DIR/bin/hipexamine.sh or hipify --inplace , there is the same error : 
/opt/rocm/hip/bin/hipify-clang: No such file or directory

I check the content in the /opt/rocm/hip/bin/:
ca           finduncodep.sh  hipcc_cmake_linker_helper  hipconvertinplace-perl.sh  hipdemangleatp      hipexamine.sh     hipify-perl
findcode.sh  hipcc           hipconfig                  hipconvertinplace.sh       hipexamine-perl.sh  hipify-cmakefile  lpl

I can not find the hipify-clang and in the github project ,I also can not find the hipify-clang. 
How can I get it ? Thanks !

**Comment by emankov** [comment]
hipify-clang is not shipped as a binary with HIP package yet. We are working on it. You may build it from sources: https://github.com/ROCm-Developer-Tools/HIP/blob/master/hipify-clang/README.md

**Comment by holyprince** [comment]
Thank you very much, I will try and sorry to disturb you.

**Comment by emankov** [comment]
It's ok, no any disturbing. We'll let you know when hipify-clang becomes available in HIP package.
