### ISSUE TITLE
The ability to print inside a kernel similar to cuprintf

### ISSUE THREAD

**Issue by x3ccd4828** [ROCm-Developer-Tools/HIP#830]
Is the printf functionality available in hip?

**Comment by gargrahul** [comment]
You can check simple example @ https://github.com/ROCm-Developer-Tools/HIP/blob/master/tests/src/kernel/hipPrintfKernel.cpp , better support is still under development.

**Comment by gargrahul** [comment]
@x3ccd4828 Can you try again after setting HCC_ENABLE_PRINTF ?

**Comment by x3ccd4828** [comment]
Perfect that worked.
Is it possible to add these two steps to the documentation for using printf? 
Do you want me to create a pull request in the ROCm documentation repo?

**Comment by doody1986** [comment]
@gargrahul 
May I ask how to set  HCC_ENABLE_PRINTF if I use cmake for a project? Thank you very much!

**Comment by holyprince** [comment]
I also want to use printf to debug the program and in my code, but the hipPrintfKernel.cpp didn't work.
I add  HCC_ENABLE_PRINTF in the same way as in hipPrintfKernel.cpp, the code is showed as below:

`#define HIP_ENABLE_PRINTF
#define HCC_ENABLE_PRINTF
#include "test_common.h"

__global__ void run_printf() { printf("Hello World\n"); }

int main() {
    hipLaunchKernelGGL(HIP_KERNEL_NAME(run_printf), dim3(1), dim3(1), 0, 0);
    hipDeviceSynchronize();
    passed();
}
`
but it also didn't print anything to screen, just "PASSED!" at the end.
What should I do if I want to use print?  Thank you very much!

**Comment by gargrahul** [comment]
@holyprince can you try **export HCC_ENABLE_PRINTF=1** before running your code?

**Comment by holyprince** [comment]
@gargrahul , thank you very much. It working for me.

**Comment by ghostplant** [comment]
@gargrahul 
I set this environment but it doesn't take effect but makes the kernel stuck:
```sh
/root $  HCC_ENABLE_PRINTF=1 ./a.out
Hello World from CPU!
(Hang ..)
```

**Comment by gargrahul** [comment]
@ghostplant Printf inside kernel should work with correct env variable as discussed above. Closing this issue.
