### ISSUE TITLE
uint2 addition does not use carry over

### ISSUE THREAD

**Issue by x3ccd4828** [ROCm-Developer-Tools/HIP#832]
The code found below should generate a = 0x400000000 however it generates a = 0x300000000.
It doesn't seem to use the v_addc instruction.

Is this expected behaviour? 

uint2 a, b;
a = make_uint2(1, 1);
b = make_uint2(0xFFFFFFFF,2);
a += b;

**Comment by b-sumner** [comment]
Yes.  Addition of vectors is component-wise.  The result of the addition is (uint2)(0, 3)

**Comment by mangupta** [comment]
Closing this since the query has been answered.
