### ISSUE TITLE
Port to windows

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#84]

**Comment by VincentSC** [comment]
Nope

**Comment by bensander** [comment]
Correct.  Popular request but not currently supported.

**Comment by boxerab** [comment]
Is there a plan to port to windows? I have an opencl project that I want to run on nvidia hardware, but don't trust the nvidia opencl drivers :) So, would like to port to HIP. But, I really really need to be able to run this on windows.

**Comment by boxerab** [comment]
Unless I can cross-compile to windows

**Comment by boxerab** [comment]
Also, given that nvidia no longer supports profiling opencl kernels :)

**Comment by bensander** [comment]
Right – we are looking at this but have not announced a committed plan.

**Comment by boxerab** [comment]
Thanks, Ben.  It would clearly help a lot with HIP adoption, but of course you guys have a lot on your plates at the moment.

**Comment by boxerab** [comment]
Just want to re-iterate : there are a lot of CUDA developers using Windows! So, porting to windows will really speed up adoption, and create a large pool of HIP developers.

**Comment by dtmoodie** [comment]
I'll add that I will port my entire computer vision platform to hip if Windows support is added.

**Comment by boxerab** [comment]
By the way, I have some time to work on this port to windows.

**Comment by emankov** [comment]
clang-hipfy can be built on Windows by MS VS 15, 17, so hipification (porting CUDA->HIP) might be performed on Windows, but not the running of the hipified code.

**Comment by dtmoodie** [comment]
What would be required to run it? I've heard mention that it is an OS level issue. Which strikes me as odd if we can launch opencl and cuda kernels with current facilities on Windows.

**Comment by bensander** [comment]
The HIP runtime uses the HSA Runtime and HCC runtime for event and code management, and HCC uses the HSA Runtime to communicate with the kernel driver.   To run HIP applications on Windows, we need a HSA runtime implementation for Windows.  Also we need HCC compiler to run on windows.  This is fair amount of work, but we hear the requests and have some internal efforts in this direction.

**Comment by boxerab** [comment]
Thanks, Ben. As I said earlier, we realize you guys are busy! Very glad to see the company realizing how important software ecosystem, especially open one.

In the meantime, I guess a simple interim solution would be to allow HIP code on windows to run on Green team only i.e. disable Radeon backend and only use NVCC etc. for windows. Would that work ?
Not ideal, of course.

**Comment by boxerab** [comment]
Personally, I already have an OpenCL solution for AMD cards on windows, so I guess the simplest
approach for supporting nVidia on windows is to use a wrapper that redirects hip calls to cuda calls, and re-write some of the host code.

**Comment by boxerab** [comment]
Hi Ben, 
Does closing this issue mean that there is no windows port planned ?

Kind Regards,
Aaron

**Comment by bensander** [comment]
Hi Aaron - we are aware of the interest in this from several people  and we will have it eventually. We will share more concrete roadmap when possible.

**Comment by boxerab** [comment]
Thanks.

**Comment by oscarbg** [comment]
Hope after 1.9 release this month, ROCM 2.0 beta at SC18 comes with some Windows HIP support (rocblas,fft,prim,solver libs)

**Comment by ghostplant** [comment]
@bensander To begin with, can we just make compiler `hcc` work on Windows? I think it is based on clang, and doesn't even require HSA runtime (maybe just some HSA headers would be OK). I need something like a HSACO cross-compiler that is able to build Windows.

If not, how about open-source LLVM-9, since it can generate different target codes and it also has Windows release version.

**Comment by bensander** [comment]
Upstream clang has support for hip language - we polishing this solution and release soon.   But remind me which problem you are trying to solve ?

**Comment by ghostplant** [comment]
@bensander I want an HIP cross-compiler compiled at Windows platform, thus allowing Windows supporting partial HIP stack.

**Comment by bensander** [comment]
Us too ! I anticipate you will see this from AMD in the next few months. Both compiler and runtime.

**Comment by ghostplant** [comment]
@bensander Great news! Eager to see this awesome progress soon.

**Comment by JessubKim** [comment]
Just found out why HCC compiler support on windows could be so useful. This would enable compilation of SyCL code in Nvidia GPU's in Windows using HipSyCL which uses AMD HIP to map SyCL codes.

**Comment by Degerz** [comment]
@bensander Have both the compiler and the runtime released yet and if not is it possible to get an ETA for them ?

**Comment by stefan-gavranovic** [comment]
@bensander Any update on this would be much appreciated.
I see that `hipify-clang` is working on Windows, but what good is that if HCC is not supported?

**Comment by Hendiadyoin1** [comment]
Even on a subsystem it refuses to install prompting me with not finding the package:

> # apt-get install hip-hcc
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package hip-hcc

**Comment by Hendiadyoin1** [comment]
So you are able to install all libraries on wsl2 see [the wsl repo](https://github.com/microsoft/WSL/issues/829)
though mainly supporting cuda
is there any move from the amd guys to enable it via the wsl

**Comment by IIIBlueberry** [comment]
> 
> 
> @bensander Any update on this would be much appreciated.
> I see that `hipify-clang` is working on Windows, but what good is that if HCC is not supported?

Someone found out amd has been shipping "amdhip.dll" on their driver, and able to run some HIP apps
https://github.com/illuhad/hipSYCL/issues/78#issuecomment-582810780

**Comment by ghostplant** [comment]
@IIIBlueberry Currently https://github.com/microsoft/antares is able to enable and evaluate ROCm Kernel execution workload on Windows 10. The evaluation branch is activated by `BACKEND=c-rocm_win64`, as long as the driver file "amdhip.dll" works on your system.

**Comment by IIIBlueberry** [comment]
@ghostplant wow this great, will this mean we can have ROCm on windows soon?

**Comment by ghostplant** [comment]
You can just use it at the level of driver API calls, which is enough to accelerate what Linux ROCm can accelerate.
But AMD officially doesn't support much more other than that.

**Comment by xuhuisheng** [comment]
@ghostplant 
Thank you for showing that microsoft had plan to support ROCm on windows.
I had a question how can I get `C:\Windows\System32\amdhip64.dll`, is there any redistribution packages? Or should I compile hip on windows by myself?
Is there any guides for this?

**Comment by ghostplant** [comment]
C:\Windows\System32\amdhip64.dll is provided by latest AMDGPU driver that can work on Windows.

**Comment by Sephirothbahamut** [comment]
Are there any news on the topic? Having access to HIP on Windows would still be huge...

**Comment by EzeAGB** [comment]
Please add support for Windows.

**Comment by Sp3ci3s8472** [comment]
With stable diffusion getting all the hype at the moment I would assume this issue would get more focus, or that WSL in combination with Docker would allow users to use ROCm on Windows. Sadly I have to use a Nvidia gpu with not a lot of VRAM while my 6900 XT sits idle.

**Comment by Enferlain** [comment]
Same. I've been following these topics and hoping for an update. I love my 6800xt but I can't do anything on windows
