### ISSUE TITLE
[ROCm 2.0] [C] failed to build C code including hip_runtime_api.h

### ISSUE THREAD

**Issue by zjunweihit** [ROCm-Developer-Tools/HIP#846]
# Environment
* Ubuntu 18.04( or Ubuntu16.04)
* ROCm: 2.0.89
* gcc 7.3.0
* g++ 7.3.0

# Issue
* It was found by NWChem HIP support. Also could be reproduced by simple main.c as below:
```C
#define __HIP_PLATFORM_HCC__
#include <stdio.h>
#include <hip/hip_runtime_api.h>
int main()
{
        printf("hello world\n");
        return 0;
}
```
* Building error
```bash
$ gcc -I/opt/rocm/hip/include main.c
In file included from /opt/rocm/hip/include/hip/hcc_detail/hip_runtime_api.h:2613:0,
                 from /opt/rocm/hip/include/hip/hip_runtime_api.h:308,
                 from main.c:3:
/opt/rocm/hip/include/hip/hcc_detail/hip_prof_api.h:5:10: fatal error: atomic: No such file or directory
 #include <atomic>
          ^~~~~~~~
compilation terminated.
```

# More info
* Workaround to build as c++ source, which doesn't make sense. We may exclude hip_prof_api.h for C compiling.
```
$ g++ -I/opt/rocm/hip/include -std=c++11 main.c
```
* ROCm 1.9.307 is fine as there is no hip_prof_api.h in rocm header path

**Comment by yuq** [comment]
There's another place which is not C compatible:
> /opt/rocm/hip/include/hip/hcc_detail/hip_runtime_api.h:2627:52: error: expected ‘;’, ‘,’ or ‘)’ before ‘&’ token
 static inline const char* hipApiName(const uint32_t& id) { return hip_api_name(id); }

**Comment by dereklstinson** [comment]
So, I am running into this issue with rocm 2.4.x, gcc 7.4, too.  I want to make some go bindings for HIP and MIOpen.  Is there plans to get this to work with gcc? I mean it is in the documentation that this will work with gcc.

**Comment by SarbojitAMD** [comment]
We have enabled in PR#1214 (already merged)
