### ISSUE TITLE
Missing update documentation

### ISSUE THREAD

**Issue by VincentSC** [ROCm-Developer-Tools/HIP#86]
There is `build_hcc_and_hip.sh` and good installation notes, but for updating there is a lack of documentation. Just read https://github.com/ROCm-Developer-Tools/HIP/releases/tag/preview_1.0.17241 and you see all is oriented towards new users for installation.

We don't want to get to a situation where we should had done something different. And while you're on it, please also explain how to test a new version - switching between multiple versions is really required.

**Comment by mangupta** [comment]
Thanks. We'll add some documentation that makes is clearer how to upgrade to a newer version of HIP.

**Comment by VincentSC** [comment]
Thanks!

**Comment by gargrahul** [comment]
@VincentSC I am closing this issue. developer preview support was stopped long back and HIP releases are better streamlined now. Please reopen it in case you feel we may still need to address it.
