### ISSUE TITLE
libunwind.h file not found build error

### ISSUE THREAD

**Issue by acyeh** [ROCm-Developer-Tools/HIP#88]
Hello, I'm attempting to update to the most recent developer HIP release because of the parameter upper bound in https://github.com/ROCm-Developer-Tools/HIP/issues/87 using the script on the release page at 
https://github.com/ROCm-Developer-Tools/HIP/releases

However, the build_hcc_and_hip.sh fails due to missing:

```
Generating opencl.amdgcn.bc
[ 98%] Built target opencl_lib
[ 99%] Built target test_workitem_code
[100%] Built target test_common_code
[100%] Built target test_math_code
[  8%] Built target rocdl
[ 12%] Building CXX object lib/CMakeFiles/mcwamp.dir/mcwamp.cpp.o
In file included from /server-home1/acyeh/relion/src/hcc/lib/mcwamp.cpp:18:
/server-home1/acyeh/relion/build/hcc-lc/include/hc_rt_debug.h:6:10: fatal error: 'libunwind.h' file not found
#include <libunwind.h>
         ^~~~~~~~~~~~~
1 error generated.
lib/CMakeFiles/mcwamp.dir/build.make:62: recipe for target 'lib/CMakeFiles/mcwamp.dir/mcwamp.cpp.o' failed
make[2]: *** [lib/CMakeFiles/mcwamp.dir/mcwamp.cpp.o] Error 1
CMakeFiles/Makefile2:276: recipe for target 'lib/CMakeFiles/mcwamp.dir/all' failed
make[1]: *** [lib/CMakeFiles/mcwamp.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

```

I've ran
`apt-get install rocm-device-libs`

because I suspected it might have been a device library issue, but this hasn't resolved the issue.

**Comment by adityaatluri** [comment]
Try `apt-get install libunwind`

**Comment by mangupta** [comment]
This is a requirement for building HCC. See the documentation [here](https://github.com/RadeonOpenCompute/hcc/wiki#building-hcc-from-source).
Essentially you are need to install libunwind-dev using ```apt-get install libunwind-dev``` or ```dnf install libunwind-devel``` depending upon the platform you are on.
