### ISSUE TITLE
atomicExch for unsigned long long returns unsigned int

### ISSUE THREAD

**Issue by ex-rzr** [ROCm-Developer-Tools/HIP#888]
https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/hcc_detail/hip_atomic.h#L115

**Comment by saadrahim** [comment]
@ex-rzr Could you add some more details for me to report the issue internally. Command line out put and reproduction instructions would be nice.

**Comment by ex-rzr** [comment]
`atomicExch` for `unsigned long long` must return `unsigned long long`, not `unsigned int`. That's all.

Compare with https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomicexch

**Comment by saadrahim** [comment]
The issue has been identified and will be fixed in a future release of rocm.
