### ISSUE TITLE
Compilation failure for __global__kernel as variadic template with variable number of arguments

### ISSUE THREAD

**Issue by davidrohr** [ROCm-Developer-Tools/HIP#893]
hipcc fails the compilation if the kernel is a variadic template taking variable number of arguments.
Attached are the sources of two different reproduces, giving 2 different error messages, although I assume it is the same problem.
[fail2.hip.cpp.txt](https://github.com/ROCm-Developer-Tools/HIP/files/2827745/fail2.hip.cpp.txt)
[fail3.hip.cpp.txt](https://github.com/ROCm-Developer-Tools/HIP/files/2827746/fail3.hip.cpp.txt)

Compiled with version roc-2.0.0 via hipcc --amdgpu-target=gfx900 -o test -std=c++17 -c fail2.hip.cpp

**Comment by AlexVlx** [comment]
Please see below:
    - fail2: remove const from Args; we do not support automated overload resolution for variadic `__global__`s yet;
    - fail3: krnl is ill-formed, we do not allow reference arguments for `__global__` functions; furthermore, partial specialisation of function templates is not allowed so the construct `krnl<foo>` actually selects a fully specialised overload of `krnl` that takes no variadic pack, which is not quite what you want; for the sake of demonstration, using `krnl<foo, std::nullptr_t>` will work.
Thank you.

**Comment by davidrohr** [comment]
Thanks for the fast answer, getting rid of the const and reference is not a problem.
The other part is a bit unfortunate, the krnl<foo> came out from the hipify_perl tool from CUDA code
`krnl<foo><<<256, 256>>>(nullptr)`
Apparently CUDA can resolve this automatically, while you are right that HIP cannot since partial specialization is not supported. I guess I can find a way to work around that and I also do not see a better way. So thanks again for the quick help.
