### ISSUE TITLE
More examples Please

### ISSUE THREAD

**Issue by boxerab** [ROCm-Developer-Tools/HIP#92]
It would be awesome if the APP SDK OpenCL samples were ported to HIP.
This would provide a lot more guidance than the current handful of samples in the repo.

**Comment by adityaatluri** [comment]
Hi,
We have some [here](https://github.com/ROCm-Developer-Tools/HIP/tree/master/samples/2_Cookbook). Do you have something specific in mind?

**Comment by boxerab** [comment]
Thanks. So, in a nutshell here is how my OpenCL app is currently designed:
(I make heavy use of OpenCL events, and OpenCL images)

1. chunk of data is read from disk and copied asynchronously to a device buffer using map/unmap functions
1. once on the card, a cl_event triggers a series of kernels to process the data
1. the last kernel triggers a map of the data buffer back to the host space
1. once mapped, data is processed on host

So, I am looking for an example that shows how to do this in HIP:

1. asynch copy from host to device and device to host
1. use of HIP events
1. use of HIP equivalent of OpenCL buffer and image

**Comment by VincentSC** [comment]
Did you also check out https://github.com/ROCm-Developer-Tools/HIP-Examples ?

**Comment by boxerab** [comment]
Thanks.  Didn't see anything that matches my requirements. I suppose I could re-implement in CUDA,
then port to HIP ?  :)

**Comment by boxerab** [comment]
But then, what's the point ?

**Comment by VincentSC** [comment]
HIP targets existing CUDA-software, so indeed no point. Except when there are CUDA-features that would improve performance, and have no equivalent in OpenCL - see discussion #19

**Comment by boxerab** [comment]
I think the best way to approach this is to simply find CUDA samples, and then convert to HIP.
But, of course, if AMD maintained an up to date repository of samples in HIP that showed which features are supported, that would be nice.
