### ISSUE TITLE
[Question] The way to choose GPU card for HIP apps

### ISSUE THREAD

**Issue by ghostplant** [ROCm-Developer-Tools/HIP#920]
I have a metal equipped with multiple AMD GPU cards with different gcnArch.
If I'd like to choose the secondary card as the default accelerator for many single-GPU applications to do whatever compiling or execution, how to do that to mask/hide the primary card?

**Comment by bensander** [comment]
HIP_VISIBLE_DEVICES=1

**Comment by ghostplant** [comment]
Thanks!
