### ISSUE TITLE
Enforce hcc when no AMD GPU is installed

### ISSUE THREAD

**Issue by VincentSC** [ROCm-Developer-Tools/HIP#926]
When using findHIP of cmake. 
Is it correct that `export HIP_PLATFORM="hcc"` enforces the installed hcc compiler to be used, so errors on not finding CUDA can be prevented?

**Comment by mangupta** [comment]
Yes you are right. ```export HIP_PLATFORM=hcc``` would enforce hcc as the compiler. However if you cmake also includes ```find_package(CUDA)``` you can still see errors related to not finding CUDA.
