### ISSUE TITLE
 The dependency target "lit" of target "test-hipify" does not exist.

### ISSUE THREAD

**Issue by BeamOfLight** [ROCm-Developer-Tools/HIP#94]
Hello!
I can't build hipify-clang. I have this error "The dependency target "lit" of target "test-hipify" does not exist."  Instruction: https://github.com/ROCm-Developer-Tools/HIP/blob/master/hipify-clang/README.md#build-and-install

Can you help me? Can i install hipify-clang from deb-package?

hipconfig:
> HIP version  : 1.2.17263
> 
> == hipconfig
> HIP_PATH     : /opt/rocm
> HIP_PLATFORM : hcc
> CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/include -I/opt/rocm/hcc/include
> 
> == hcc
> HSA_PATH     : /opt/rocm/hsa
> HCC_HOME     : /opt/rocm/hcc
> HCC clang version 5.0.0  (based on HCC 1.0.17262-7871d33-3953233-56b5abe )
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /opt/rocm/hcc/bin
> LLVM (http://llvm.org/):
>   LLVM version 5.0.0svn
>   Optimized build.
>   Default target: x86_64-unknown-linux-gnu
>   Host CPU: haswell
> 
>   Registered Targets:
>     amdgcn - AMD GCN GPUs
>     r600   - AMD GPUs HD2XXX-HD6XXX
>     x86    - 32-bit X86: Pentium-Pro and above
>     x86-64 - 64-bit X86: EM64T and AMD64
> HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc-1.0/include -I/opt/rocm/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc-1.0/lib -Wl,--rpath=/opt/rocm/hcc-1.0/lib -ldl -lm -lpthread -lunwind -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive
> 
> === Environment Variables
> ...
> 
> == Linux Kernel
> Hostname     : beamoflight-All-Series
> Linux beamoflight-All-Series 4.9.0-kfd-compute-rocm-rel-1.6-77 #1 SMP Wed Jun 28 07:30:27 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.2 LTS
> Release:	16.04
> Codename:	xenial
>

**Comment by sunway513** [comment]
Hi, I would first suggest you check if you have downloaded and installed the correct LLVM+Clang package. It seems you are on Ubuntu16.04, please use the following package as listed in the document:
<wget http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
tar xvfJ clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz>

**Comment by BeamOfLight** [comment]
My commands:

cd ~
git clone https://github.com/ROCm-Developer-Tools/HIP.git && cd HIP
git co remotes/origin/roc-1.6.x

wget http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
tar xvfJ clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
mv clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04 clang+llvm-3.8.0/

mkdir build && cd build
cmake -DHIPIFY_CLANG_LLVM_DIR=~/HIP/clang+llvm-3.8.0/ -DCMAKE_BUILD_TYPE=Release ..

Result:

> CMAKE_BUILD_TYPE=Release ..
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- HIP Platform: hcc
> -- Looking for HCC in: /opt/rocm/hcc. Found version: 1.0.17262-7871d33-3953233-56b5abe
> -- Looking for HSA runtime in: /opt/rocm/hsa
> -- HIP will be installed in: /opt/rocm/hip
> -- Found LLVM 3.8.0
> -- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.12") 
> -- Testing targets will not be available. To enable them please ensure that the HIP installation directory is writeable. Use -DCMAKE_INSTALL_PREFIX to specify a suitable location
> -- Configuring done
> CMake Warning (dev) at clang+llvm-3.8.0/share/llvm/cmake/AddLLVM.cmake:1020 (add_dependencies):
>   Policy CMP0046 is not set: Error on non-existent dependency in
>   add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
>   Use the cmake_policy command to set the policy and suppress this warning.
> 
>   The dependency target "lit" of target "test-hipify" does not exist.
> Call Stack (most recent call first):
>   clang+llvm-3.8.0/share/llvm/cmake/AddLLVM.cmake:1041 (add_lit_target)
>   hipify-clang/CMakeLists.txt:77 (add_lit_testsuite)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Generating done

**Comment by BeamOfLight** [comment]
Alternatively i can remove tests from CMakeLists.txt -it's work but this is a temporary solution.

**Comment by mangupta** [comment]
The message is just a warning. It does not prevent you from building and using hipify-clang.
LLVM releases do not ship with lit binary. Hence you will see this warning. When lit is not found, you cannot run the hipify-clang tests. Unless you intend to modify hipify-clang, you can ignore the warning for now.

**Comment by BeamOfLight** [comment]
Thank you
