### ISSUE TITLE
Rocm 1.6 can not find hipify, how to install old version HIP on NVIDIA platform

### ISSUE THREAD

**Issue by merlinzone** [ROCm-Developer-Tools/HIP#95]
I have apt-get install ROCm 1.6 HIP on NVIDIA GPU platform, but it does not include hipify(only have hipify-perl and hipify-cmakefile), old version include hipify, How can I install old version HIP?
https://github.com/ROCmSoftwarePlatform/rocBLAS/wiki/Setting-up-enviroment-on-NVIDIA-platform

**Comment by mangupta** [comment]
As mentioned in the [HIP release notes](https://github.com/ROCm-Developer-Tools/HIP/blob/master/RELEASE.md), hipify has been renamed to hipify-perl.
To install older HIP releases, you can get the source for older ROCm releases or binaries+source for developer preview releases from [releases page](https://github.com/ROCm-Developer-Tools/HIP/releases).
