### ISSUE TITLE
[HIPIFY] Is hipify-clang working for source codes that includes CUDA-related local headers?

### ISSUE THREAD

**Issue by ghostplant** [ROCm-Developer-Tools/HIP#989]
Is hipify-clang working for source codes that includes CUDA-related local headers?

**Comment by ghostplant** [comment]
e.g.
```sh
..
#include "cuda-kernel-collection.cuh"
..
```
while the file `cuda-kernel-collection.cuh` also contains codes that requires to be hipified.

**Comment by emankov** [comment]
You may specify them both in command line, as hipify-clang supports multiple input files.

**Comment by ghostplant** [comment]
@emankov Thanks! I build the latest hipify-clang using llvm-8 and clang-8, but got the following error:
```sh
[  3%] Building CXX object CMakeFiles/hipify-clang.dir/src/ArgParse.cpp.o
In file included from /home/weicu/HIP/hipify-clang/src/ArgParse.cpp:23:
/home/HIP/hipify-clang/src/ArgParse.h:25:10: fatal error: 'clang/Tooling/CommonOptionsParser.h' file not found
#include "clang/Tooling/CommonOptionsParser.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
CMakeFiles/hipify-clang.dir/build.make:62: recipe for target 'CMakeFiles/hipify-clang.dir/src/ArgParse.cpp.o' failed
make[2]: *** [CMakeFiles/hipify-clang.dir/src/ArgParse.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/hipify-clang.dir/all' failed
make[1]: *** [CMakeFiles/hipify-clang.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
w
```

**Comment by ghostplant** [comment]
@emankov Which llvm and clang version should I use to make it successfully?

**Comment by emankov** [comment]
Well, actually the info reported is incomplete. Nonetheless, please use the latest clang stable release: https://github.com/ROCm-Developer-Tools/HIP/blob/master/hipify-clang/README.md

Btw,
Why did you rebuild your (working) hipify-clang? Correct me if I wrong, but the point was in hipifying yet one another cuda source (cuda header to be hipified as well)?

P.S.
LLVM/Clang 8.0.0 is just released and is being tested in HIP infrastructure. Please, use the latest stable and tested release 6.0. according to the [documentation](https://github.com/ROCm-Developer-Tools/HIP/blob/master/hipify-clang/README.md).

Thanks.

**Comment by ghostplant** [comment]
@emankov I mean I have one local header file `common.cuh` and local source file `test.cu`:

The content of file `common.cuh` is:
```c
#include <cuda_runtime.h>

__device__ add(float *a, float *b) {
  ..
}

int common_add(void *d_a, void *d_b) {
  add<<<1, 1>>>(d_a, d_b);
  return 0;
}
```

The content of file `test.cu` is:
```c
#include <stdio.h>
#include "common.cuh"

int main() {
  float *d_a, *d_b;
  cudaMalloc(&d_a, sizeof(float));
  cudaMalloc(&d_b, sizeof(float));
  return common_add(d_a, d_b);
}
``

If I use `hipify-clang ./test.cu`, it generates a `./test.cu.hip` while the content of `common.cuh` is not hipified.

**Comment by emankov** [comment]
If you need to hipify a header file as well, you may specify it in command line along with your source file:

`./hipify-clang test.cu common.cuh`

Included header files are intentionally not being hipified; you should specify them explicitly in command line.
