### ISSUE TITLE
Initialization Error for hip-clang

### ISSUE THREAD

**Issue by louishp** [ROCm-Developer-Tools/HIP#993]
I try to use hip-clang to compile MatrixTranspose sample (/opt/rocm/hip/samples/2_Cookbook/0_MatrixTranspose), it's ok. But when I set HIP_DB = 1, some problem comes out:

`  hip-api pid:18720 tid:1:HIP initialized short_tid#1 (maps to full_tid: 0x7f1cdb322840)`
`<<hip-api pid:18720 tid:1.1 __hipRegisterFunction (0x18b6030, 0x400d30, _Z15matrixTransposePfS_i, _Z15matrixTransposePfS_i) @764398508689503`
`<<hip-api pid:18720 tid:1.2 hipModuleGetFunction (0x7ffd0584b6a0, 0x17dd660, _Z15matrixTransposePfS_i) @764398508747290`
`  hip-api pid:18720 tid:1.2 hipModuleGetFunction           ret= 0 (hipSuccess)>> +72321 ns`
`<<hip-api pid:18720 tid:1.3 hipModuleGetFunction (0x7ffd0584b6a0, 0x17fbd90, _Z15matrixTransposePfS_i) @764398508837668`
`  hip-api pid:18720 tid:1.3 hipModuleGetFunction           ret=500 (hipErrorNotFound)>> +15678 ns`
`<<hip-api pid:18720 tid:1.4 hipModuleGetFunction (0x7ffd0584b6a0, 0x17fbd90, _Z15matrixTransposePfS_i.kd) @764398508864531`
`  hip-api pid:18720 tid:1.4 hipModuleGetFunction           ret=500 (hipErrorNotFound)>> +13350 ns`
`<<hip-api pid:18720 tid:1.5 hipModuleGetFunction (0x7ffd0584b6a0, 0x1916840, _Z15matrixTransposePfS_i) @764398508889310`
`  hip-api pid:18720 tid:1.5 hipModuleGetFunction           ret=500 (hipErrorNotFound)>> +13712 ns`
`<<hip-api pid:18720 tid:1.6 hipModuleGetFunction (0x7ffd0584b6a0, 0x1916840, _Z15matrixTransposePfS_i.kd) @764398508913053`
`  hip-api pid:18720 tid:1.6 hipModuleGetFunction           ret=500 (hipErrorNotFound)>> +13160 ns`
`<<hip-api pid:18720 tid:1.7 hipGetDeviceProperties (0x7ffd0584b9c0, 0) @764398508949039`
`  hip-api pid:18720 tid:1.7 hipGetDeviceProperties         ret= 0 (hipSuccess)>> +6560 ns`

We have 3 dGPU on the server, the address can be found from DB output message: 0x17dd660, 0x17fbd90, 0x1916840. 

This DB message reveal a critical problem, ONLY DEVICE 0 have register function  '_Z15matrixTransposePfS_i'.

In order to verify this problem, I use hipSetDevice(2) to change device context to device 2. The DB message is :

`<<hip-api pid:18720 tid:1.8 hipSetDevice (2) @764398515748949`
`  hip-api pid:18720 tid:1.8 hipSetDevice                   ret= 0 (hipSuccess)>> +6922 ns`
`<<hip-api pid:18720 tid:1.9 hipMalloc (0x7ffd0584bb58, 4194304) @764398515777307`
`  hip-api pid:18720 tid:1.9 hipMalloc                      ret= 0 (hipSuccess)>> +1310978 ns`
`<<hip-api pid:18720 tid:1.10 hipMalloc (0x7ffd0584bb50, 4194304) @764398517110930`
`  hip-api pid:18720 tid:1.10 hipMalloc                      ret= 0 (hipSuccess)>> +588277 ns`
`<<hip-api pid:18720 tid:1.11 hipMemcpy (0x7f19bec00000, 0x7f19bf9ff010, 4194304, hipMemcpyHostToDevice) @764398517762157`
`  hip-api pid:18720 tid:1.11 hipMemcpy                      ret= 0 (hipSuccess)>> +4137123 ns`
`<<hip-api pid:18720 tid:1.12 hipSetupArgument (0x7ffd0584b898, 8, 0) @764398521932446`
`<<hip-api pid:18720 tid:1.13 hipSetupArgument (0x7ffd0584b890, 8, 8) @764398521943502`
`<<hip-api pid:18720 tid:1.14 hipSetupArgument (0x7ffd0584b88c, 4, 16) @764398521957215`
`<<hip-api pid:18720 tid:1.15 hipLaunchByPtr (0x400d30) @764398521969875`
`hipLaunchByPtr cannot find kernel with stub address 0x400d30 for device 2!`

With my analyzing, this problem comes from __hipRegisterFunction on hip_clang.cpp. __hipRegisterFunction try to call hipModuleGetFunction at the beginning of the program execution. __hipRegisterFunction pass modules->at(deviceId) to hipModuleGetFunction for each device.  Then the module with deviceID will pass to  hipModuleGetFunction -> ihipModuleGetFunction -> find_kernel_by_name on hip_module.cpp.  But  find_kernel_by_name use this_agent() to get the device of default context and hsa_executable_iterate_agent_symbols to get the symbol of function. That's why only device 0 have register function  '_Z15matrixTransposePfS_i'.

**Comment by louishp** [comment]
The rocm version is 2.2.

find_kernel_by_name use this_agent() to get device and pass to  hsa_executable_iterate_agent_symbols()

hsa_executable_symbol_t find_kernel_by_name(hsa_executable_t executable, const char* kname) {
    pair<const char*, hsa_executable_symbol_t> r{kname, {}};

    hsa_executable_iterate_agent_symbols(
        executable, this_agent(),
        [](hsa_executable_t, hsa_agent_t, hsa_executable_symbol_t x, void* s) {
            auto p = static_cast<pair<const char*, hsa_executable_symbol_t>*>(s);

            if (type(x) != HSA_SYMBOL_KIND_KERNEL) {
                return HSA_STATUS_SUCCESS;
            }
            if (name(x) != p->first) return HSA_STATUS_SUCCESS;

            p->second = x;

            return HSA_STATUS_INFO_BREAK;
        },
        &r);

    return r.second;
}

this_agent() only return the device on default ctx.  Please note that this function is called at program beginning.

inline hsa_agent_t this_agent() {
    auto ctx = ihipGetTlsDefaultCtx();

    if (!ctx) throw runtime_error{"No active HIP context."};

    auto device = ctx->getDevice();

    if (!device) throw runtime_error{"No device available for HIP."};

    ihipDevice_t* currentDevice = ihipGetDevice(device->_deviceId);

    if (!currentDevice) throw runtime_error{"No active device for HIP."};

    return currentDevice->_hsaAgent;
}

**Comment by yxsamliu** [comment]
Thanks for your analysis. It is very helpful.

https://github.com/ROCm-Developer-Tools/HIP/pull/997 should fix this. Could you please give it a try? Thanks.

**Comment by louishp** [comment]
> Thanks for your analysis. It is very helpful.
> 
> #997 should fix this. Could you please give it a try? Thanks.

The function initialization problem has solved. All devices have return hipSuccess throw ihipModuleGetFunction. But there is an other issue.  If __hipRegisterFunction call ihipModuleGetFunction directly, error log for ihipModuleGetFunction will not be collected. 

HIP_DB=0x1 [api]
  hip-api pid:17085 tid:1:HIP initialized short_tid#1 (maps to full_tid: 0x7f47f078e840)
<<hip-api pid:17085 tid:1.1 __hipRegisterFunction (0x20c9030, 0x400d30, _Z15matrixTransposePfS_i, _Z15matrixTransposePfS_i) @90973132154194
<<hip-api pid:17085 tid:1.2 hipGetDeviceProperties (0x7ffd5437bb30, 0) @90973132203105
  hip-api pid:17085 tid:1.2 hipGetDeviceProperties         ret= 0 (hipSuccess)>> +17364 ns

**Comment by yxsamliu** [comment]
I updated PR#997 for the log issue.

**Comment by louishp** [comment]
It works for me. The log issue has solved.

**Comment by gargrahul** [comment]
Closing this since reported issue got resolved.
