### ISSUE TITLE
Debian packaging for hip_nvcc is missing files

### ISSUE THREAD

**Issue by acowley** [ROCm-Developer-Tools/HIP#996]
On an Ubuntu 18.04 (Linux 4.15) machine with a Nvidia GPU, I installed `hip_nvcc` and got it working, but then started receiving warnings from `apt` saying that I could remove `hip_nvcc` because it had no files, and then the same for `hip_base`. After a reboot, I still have all the files in `/opt/rocm`, but `dpkg -L hip_nvcc` says `dpkg-query: package 'hip_nvcc' is not installed`. If I then again run `sudo apt install hip_nvcc`, it installs version 1.5.19055, but then I see,

```
$ dpkg -L hip_nvcc
/opt
/opt/rocm
/opt/rocm/hip
```

No files are reported! So everything seems to be working, but `apt` is confused and gives me the aforementioned warnings.

EDIT: The exact warning is,
```
The following package disappeared from your system as
all files have been overwritten by other packages:
  hip_nvcc
Note: This is done automatically and on purpose by dpkg.
```

**Comment by mangupta** [comment]
hip_nvcc is just a metapackage to ensure that both hip_base and cuda get installed. See https://github.com/ROCm-Developer-Tools/HIP/blob/master/packaging/hip_nvcc.txt#L21. The actual package that provides the HIP header files (for Nvidia GPU) is hip_base. As long as hip_base and cuda packages are installed properly on your system you should be fine. I haven't seen the above warning on my Ubuntu 18.04 setup, but I will continue to try and see if I can reproduce as well as avoid throwing the above warning.
