### ISSUE TITLE
Current commit build failing due to hip_prof_str.h

### ISSUE THREAD

**Issue by auyer** [ROCm-Developer-Tools/HIP#999]
The current commit on the master branch 4b7177ac4225c32ed0b02096a83b78fab0b9347a fails in the making procedure. I am running on a Arch Linux Base, and can confirm that relese 2.0 builds fine. System info after the build logs.

```
$ make
[  2%] Building CXX object CMakeFiles/hip_hcc.dir/src/hip_clang.cpp.o
In file included from /home/auyer/tensorflow/HIP/src/hip_clang.cpp:27:
In file included from /home/auyer/tensorflow/HIP/include/hip/hip_runtime.h:56:
In file included from /home/auyer/tensorflow/HIP/include/hip/hcc_detail/hip_runtime.h:62:
In file included from /home/auyer/tensorflow/HIP/include/hip/hip_runtime_api.h:308:
In file included from /home/auyer/tensorflow/HIP/include/hip/hcc_detail/hip_runtime_api.h:2969:
/home/auyer/tensorflow/HIP/include/hip/hcc_detail/hip_prof_api.h:9:10: fatal error: 'hip/hcc_detail/hip_prof_str.h' file not found
#include "hip/hcc_detail/hip_prof_str.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from /home/auyer/tensorflow/HIP/src/hip_clang.cpp:27:
In file included from /home/auyer/tensorflow/HIP/include/hip/hip_runtime.h:56:
In file included from /home/auyer/tensorflow/HIP/include/hip/hcc_detail/hip_runtime.h:62:
In file included from /home/auyer/tensorflow/HIP/include/hip/hip_runtime_api.h:308:
In file included from /home/auyer/tensorflow/HIP/include/hip/hcc_detail/hip_runtime_api.h:2969:
/home/auyer/tensorflow/HIP/include/hip/hcc_detail/hip_prof_api.h:9:10: fatal error: 'hip/hcc_detail/hip_prof_str.h' file not found
#include "hip/hcc_detail/hip_prof_str.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/hip_hcc.dir/build.make:76: CMakeFiles/hip_hcc.dir/src/hip_clang.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/hip_hcc.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
OS: Manjaro Linux x86_64
Kernel: 5.0.5-1-MANJARO
CPU: AMD Ryzen 7 2700X (16) @ 3.700GHz
GPU: AMD ATI Radeon RX Vega 64

**Comment by mangupta** [comment]
hip_prof_str.h is a generated file. It is generated using [hip_prof_gen.py](https://github.com/ROCm-Developer-Tools/HIP/blob/master/hip_prof_gen.py) and the cmake steps for generating hip_prof_str.h are defined @ https://github.com/ROCm-Developer-Tools/HIP/blob/master/CMakeLists.txt#L166-L175. Maybe your CMakeLists.txt is outdated while the rest of the code got updated?

**Comment by vladtcvs** [comment]
I still have the same problem on current master. If i comment line `if(USE_PROF_API EQUAL 1)` then this file is generated

**Comment by c0d3st0rm** [comment]
I am also experiencing the same issue. It seems `hip_prof_str.h` is only generated when `USE_PROF_API=1` and `HIP_PLATFORM=hcc` are defined in the cmake call (e.g. `cmake -DUSE_PROF_API=1 -DHIP_PLATFORM=hcc ...`).
